authgear/authgear-server

portal/src/graphql/portal/Web3ConfigurationAddCollectionSection.tsx

Press enter to add a collection

---

portal/src/formbinding.tsx
portal/src/graphql/portal/Web3ConfigurationAddCollectionSection.tsx
portal/src/graphql/portal/Web3ConfigurationContactUsDialog.tsx
portal/src/locale-data/en.json

Show error in dialog

---

pkg/auth/webapp/result.go

Preserve the query only if it doesn't exist in the new query

---

portal/src/graphql/portal/SubscriptionScreen.tsx
portal/src/locale-data/en.json

Show contact us button on the processing payment screen

---

pkg/lib/oauth/oidc/handler/handler_end_session.go
pkg/lib/oauth/response_mode.go
pkg/lib/oauth/response_mode_test.go

Add missing nonce in OAuth response mode script tag

---

cmd/authgear/background/wire_gen.go
pkg/admin/wire_gen.go
pkg/auth/wire_gen.go
pkg/lib/config/config.go
pkg/lib/config/configsource/resources.go
pkg/lib/config/rate_limit.go
pkg/lib/config/testdata/default_config.yaml
pkg/lib/deps/deps_config.go
pkg/lib/ratelimit/limiter.go
pkg/lib/ratelimit/limiter_test.go
pkg/resolver/wire_gen.go

Opt out rate limit

---

pkg/lib/oauth/grant_offline.go
pkg/lib/session/idpsession/session.go
pkg/lib/session/manager.go
pkg/lib/session/session.go
pkg/lib/session/test/context.go

ref #2640 
The PR based on #2663

Revoke sessions in the same SSO group

---

pkg/auth/handler/webapp/forgot_password.go
pkg/auth/handler/webapp/interaction.go
pkg/lib/interaction/intents/forgot_password.go
pkg/lib/interaction/nodes/forgot_password.go

Change to not using input login_id to search for indentity in forgot_password page

---

pkg/lib/elasticsearch/service.go
pkg/util/graphqlutil/api_error.go

Improve error logs related to Elasticsearch connectivity problem

---

docs/specs/event.md
pkg/admin/graphql/audit_log.go
pkg/api/event/nonblocking/identity_biometric_enabled.go
pkg/auth/wire_gen.go
pkg/lib/config/hook.go
pkg/lib/config/testdata/config_tests.yaml
pkg/lib/config/testdata/hook_tests.yaml
pkg/lib/deps/deps_common.go
pkg/lib/interaction/nodes/do_create_identity.go
pkg/lib/interaction/nodes/do_ensure_session.go
pkg/lib/oauth/handler/handler_token.go
portal/src/graphql/adminapi/globalTypes.generated.ts
portal/src/graphql/adminapi/schema.graphql
portal/src/locale-data/en.json

Add missing biometric events

---

docs/specs/event.md
pkg/admin/graphql/audit_log.go
pkg/api/event/nonblocking/identity_biometric_disabled.go
pkg/api/event/nonblocking/identity_biometric_enabled.go
pkg/auth/wire_gen.go
pkg/lib/config/hook.go
pkg/lib/config/testdata/config_tests.yaml
pkg/lib/config/testdata/hook_tests.yaml
pkg/lib/deps/deps_common.go
pkg/lib/interaction/nodes/do_create_identity.go
pkg/lib/interaction/nodes/do_ensure_session.go
pkg/lib/interaction/nodes/do_remove_identity.go
pkg/lib/oauth/handler/handler_token.go
portal/src/graphql/adminapi/globalTypes.generated.ts
portal/src/graphql/adminapi/schema.graphql
portal/src/locale-data/en.json

[Backport] Add missing biometric events

---

pkg/lib/elasticsearch/service.go
pkg/util/graphqlutil/api_error.go

[Backport] mprove error logs related to Elasticsearch connectivity problem

---

pkg/lib/elasticsearch/index.go
pkg/lib/elasticsearch/index_test.go
pkg/lib/elasticsearch/pagination.go
pkg/lib/elasticsearch/pagination_test.go
pkg/lib/elasticsearch/service.go
pkg/util/graphqlutil/connection.go

[Backport] Omit null node from search result

---

cmd/authgear/cmd/cmdinternal/internal.go
cmd/authgear/elasticsearch/reindex.go

ref #2688
---
To test deleted user,
1. Shutdown elasticsearch
2. Delete the user immediately
3. Restart elasticsearch
4. Reindex. We will see `1 deleted` in the command output.

Improve reindex command

---

pkg/lib/elasticsearch/index.go
pkg/lib/elasticsearch/index_test.go
pkg/lib/elasticsearch/pagination.go
pkg/lib/elasticsearch/pagination_test.go
pkg/lib/elasticsearch/service.go
pkg/util/graphqlutil/connection.go

Omit null node from search result

---

pkg/lib/session/middleware.go

Access token/App session token takes priority over IDP session

---

pkg/lib/config/oauth.go
pkg/lib/config/testdata/config_tests.yaml
portal/src/graphql/portal/EditOAuthClientForm.tsx
portal/src/locale-data/en.json

Makes post_logout_redirect_uris optional for spa oauth client

---

pkg/lib/oauth/protocol/authz.go

ref #2638 
x_suppress_idp_session_cookie is for backward compatibility only

Read x_sso_enabled first if it is provided in the request

---

pkg/api/event/nonblocking/user_session_terminated.go
pkg/lib/session/manager.go

Rename termination type of audit log `user.session.terminated`

---

resources/authgear/templates/en/web/__alternatives.html

ref: #2671
<table>
<tr>
<td>Desktop
<td>
<tr>
<td>Mobile
<td>
</table>

Enforce left text alignment for additional login method buttons

---

pkg/portal/service/collaborator.go
resources/portal/templates/en/messages/collaborator_invitation_email.html
resources/portal/templates/en/messages/collaborator_invitation_email.mjml
resources/portal/templates/en/messages/collaborator_invitation_email.txt

ref: #2672
**Preview**
> The project name is "accounts"
**Subject**
`"You are invited to collaborate on "accounts" in Authgear"`
**Text body**
```
Join \"accounts\" as a collaborator\n\nYou have been invited to join as a collaborator to manage the project \"accounts\" in Authgear. Please click the link below to view the invitation.\n\nhttp://portal.localhost:8000/collaborators/invitation?code=RMW389CRP5N7WHKPJF5860EB166JJ71H\n\nAuthgear is a user identity and authentication software that helps you manage users and log them in securely.\n\nIf you want to reject the invitation please ignore this email.\n
```
**HTML preview**

Update wordings for collaborator invitation email

---

pkg/admin/deps.go
pkg/admin/graphql/context.go
pkg/admin/graphql/user_mutation.go
pkg/admin/wire_gen.go
portal/src/graphql/adminapi/globalTypes.generated.ts
portal/src/graphql/adminapi/schema.graphql

implements #2762
after #2753 
ref #2740

Add mutation for generating OOB OTP code

---

docs/specs/event.md
docs/specs/user-model.md

List the implementation details in #2731

Specify account anonymization

---

cmd/authgear/background/wire_gen.go
pkg/admin/wire_gen.go
pkg/auth/handler/webapp/enter_oob_otp.go
pkg/auth/handler/webapp/verify_identity.go
pkg/auth/handler/webapp/whatsapp_wati_callback.go
pkg/auth/wire_gen.go
pkg/lib/authn/otp/sender.go
pkg/lib/authn/otp/service.go
pkg/lib/config/config.go
pkg/lib/config/otp.go
pkg/lib/config/testdata/default_config.yaml
pkg/lib/config/testdata/ratelimit_tests.yaml
pkg/lib/config/time.go
pkg/lib/deps/deps_config.go
pkg/lib/ratelimit/limiter.go
pkg/resolver/wire_gen.go
pkg/util/validation/formats.go
pkg/util/validation/formats_test.go
resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/enter_oob_otp.html
resources/authgear/templates/en/web/verify_identity.html
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

Add OTP retry rate limit

---

cmd/authgear/background/wire_gen.go
pkg/admin/wire_gen.go
pkg/auth/wire_gen.go
pkg/lib/authn/otp/service.go
pkg/resolver/wire_gen.go

Use verification config for OTP expiry

---

go.mod
go.sum
pkg/lib/config/secret_data.go
pkg/lib/infra/sms/twilio.go

ref #1854 
Tested with Canada number, it works

Support using Twilio message service

---

resources/authgear/templates/en/web/magic_link_otp.html

Fix extra spacing in sent magic link screen

---

pkg/auth/handler/webapp/alternatives.go
pkg/auth/handler/webapp/interaction.go
pkg/auth/webapp/interaction.go
pkg/auth/webapp/service2.go
pkg/lib/authn/authenticator/spec.go
pkg/lib/authn/otp/sender.go
pkg/lib/authn/otp/template.go
pkg/lib/config/authenticator.go
pkg/lib/config/testdata/default_config.yaml
pkg/lib/interaction/nodes/authn_begin.go
pkg/lib/interaction/nodes/create_authenticator_begin.go
pkg/lib/interaction/nodes/create_authenticator_magic_link_otp_setup.go
portal/src/graphql/portal/LoginMethodConfigurationScreen.tsx
portal/src/locale-data/en.json
portal/src/types.ts
resources/authgear/templates/en/messages/authenticate_primary_magic_link.html
resources/authgear/templates/en/messages/authenticate_primary_magic_link.mjml
resources/authgear/templates/en/messages/authenticate_primary_magic_link.txt
resources/authgear/templates/en/messages/setup_primary_magic_link.html
resources/authgear/templates/en/messages/setup_primary_magic_link.mjml
resources/authgear/templates/en/messages/setup_primary_magic_link.txt
resources/authgear/templates/en/translation.json
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

ref: #2748 #2856
based on: #2812

Allow magic link as primary authenticator

---

pkg/auth/deps.go
pkg/auth/handler/webapp/reset_password.go
pkg/auth/wire_gen.go
pkg/lib/authn/mfa/ratelimit.go
pkg/lib/authn/mfa/service.go
pkg/lib/feature/forgotpassword/provider.go
pkg/lib/ratelimit/limiter.go
resources/authgear/templates/en/web/reset_password.html

Display error early for invalid reset code

---

pkg/lib/interaction/nodes/utils_authn.go
pkg/lib/interaction/nodes/verify_identity.go
pkg/lib/ratelimit/error.go

Rate limit bucket returns same error instance

---

pkg/auth/webapp/session_middleware.go
pkg/lib/oauth/oidc/ui.go

fix #2879 
Fix redirecting to wrong page when promoting anonymous user

Fix missing login hint when creating web session in middleware

---

docs/specs/workflow.md
pkg/latte/input_take_login_id.go
pkg/latte/intent_login.go
pkg/latte/node_take_login_id.go
pkg/lib/workflow/cookie.go
pkg/lib/workflow/effect.go
pkg/lib/workflow/errors.go
pkg/lib/workflow/input.go
pkg/lib/workflow/intent.go
pkg/lib/workflow/node.go
pkg/lib/workflow/service_test.go
pkg/lib/workflow/testdata_dummy_test.go
pkg/lib/workflow/testdata_simplified_test.go
pkg/lib/workflow/traverse_test.go
pkg/lib/workflow/workflow.go

Make input reflective in the future

---

resources/authgear/templates/en/messages/setup_primary_login_link.html
resources/authgear/templates/en/messages/setup_primary_login_link.mjml
resources/authgear/templates/en/messages/setup_primary_login_link.txt

Fix setup primary login link copywriting

---

cmd/authgear/background/wire_gen.go
pkg/admin/wire_gen.go
pkg/auth/wire_gen.go
pkg/lib/authn/authenticator/service/deps.go
pkg/lib/authn/authenticator/service/ratelimit.go
pkg/lib/authn/authenticator/service/service.go
pkg/lib/config/authenticator.go
pkg/lib/config/testdata/default_config.yaml
pkg/resolver/wire_gen.go

Add ratelimit config for password authenticator

---

docs/workflows/.env.example
docs/workflows/verify-identity.http
pkg/api/errors.go
pkg/auth/wire_gen.go
pkg/latte/input_otp_verification.go
pkg/latte/input_otp_verification_resend.go
pkg/latte/input_trigger_verification.go
pkg/latte/intent_verify_identity.go
pkg/latte/intent_verify_user.go
pkg/latte/node_verified_identity.go
pkg/latte/node_verify_email.go
pkg/latte/node_verify_phone_sms.go
pkg/latte/ratelimit.go
pkg/lib/deps/deps_common.go
pkg/lib/facade/coordinator.go
pkg/lib/facade/deps.go
pkg/lib/facade/verification.go
pkg/lib/workflow/dependencies.go
pkg/lib/workflow/workflow.go

Add verify identity workflow

---

pkg/lib/translation/service.go

Include client id in email and sms template data

---

pkg/auth/handler/webapp/deps.go
pkg/auth/handler/webapp/error_feature_disabled.go
pkg/auth/routes.go
pkg/auth/webapp/deps.go
pkg/auth/webapp/require_authentication_enabled_middleware.go
pkg/auth/webapp/require_settings_enabled_middleware.go
pkg/auth/wire_gen.go
pkg/auth/wire_handler.go
pkg/auth/wire_middleware.go
pkg/lib/config/ui.go
resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/error_feature_disabled.html
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

Support disable authentication and settings page

---

pkg/lib/feature/forgotpassword/provider.go

Add flag to reset password email's context

---

docs/specs/workflow.md
docs/workflows/.env.example
docs/workflows/verify-identity.http
docs/workflows/websocket.http
pkg/auth/deps.go
pkg/auth/handler/api/deps.go
pkg/auth/handler/api/workflow_get.go
pkg/auth/handler/api/workflow_input.go
pkg/auth/handler/api/workflow_new.go
pkg/auth/handler/api/workflow_websocket.go
pkg/auth/routes.go
pkg/auth/wire_gen.go
pkg/auth/wire_handler.go
pkg/lib/workflow/deps.go
pkg/lib/workflow/event.go
pkg/lib/workflow/event_store.go
pkg/lib/workflow/service.go
pkg/lib/workflow/service_test.go

Add WebSocket endpoint for workflow

---

pkg/auth/deps.go
pkg/auth/handler/api/workflow_websocket.go
pkg/auth/handler/webapp/websocket.go
pkg/auth/wire_gen.go
pkg/images/wire_gen.go
pkg/lib/infra/middleware/cors.go
pkg/lib/infra/middleware/cors_matcher.go
pkg/lib/infra/middleware/cors_test.go
pkg/lib/infra/middleware/deps.go
pkg/util/pubsub/http_handler.go

Fix CORS checking in workflow websocket endpoint

---

pkg/auth/handler/api/workflow_websocket.go
pkg/lib/infra/middleware/cors.go
pkg/lib/infra/middleware/cors_matcher.go
pkg/lib/infra/middleware/cors_test.go

Fix origin matcher does not always allow host

---

pkg/latte/intent_authenticate_email_login_link.go
pkg/latte/intent_authenticate_oob_otp_phone.go
pkg/latte/intent_authenticate_password.go
pkg/latte/intent_login.go
pkg/latte/node_authenticate_password.go
pkg/latte/node_verified_authenticator.go

Allow user to select password authenticator even they don't have it

---

pkg/auth/handler/api/workflow_input.go

Include the workflow payload in the api response when there is error

---

pkg/auth/handler/webapp/enter_oob_otp.go
pkg/auth/handler/webapp/verify_identity.go
pkg/auth/handler/webapp/whatsapp_wati_callback.go
pkg/latte/intent_authenticate_email_login_link.go
pkg/latte/intent_authenticate_oob_otp_phone.go
pkg/latte/node_authenticate_email_login_link.go
pkg/latte/node_authenticate_oob_otp_phone.go
pkg/latte/node_verify_email.go
pkg/latte/node_verify_phone_sms.go
pkg/lib/authn/otp/service.go
pkg/lib/workflow/dependencies.go
resources/authgear/templates/en/web/enter_oob_otp.html
resources/authgear/templates/en/web/verify_identity.html

Update OTP nodes output to include masked target and failed attempt limit exceeded 

---

pkg/auth/routes.go
pkg/auth/wire_gen.go
pkg/auth/wire_middleware.go
pkg/lib/workflow/client_id_middleware.go
pkg/lib/workflow/context.go
pkg/lib/workflow/deps.go
pkg/lib/workflow/service_test.go
pkg/lib/workflow/session.go

Fix client ID is missing in workflow API

---

pkg/latte/intent_create_session.go
pkg/latte/intent_login.go
pkg/lib/authn/authenticationinfo/model.go
pkg/lib/interaction/nodes/do_ensure_session.go
pkg/lib/oauth/handler/handler_token.go

Fire UserAuthenticatedEvent during code exchange if sso disabled

---

pkg/lib/oauth/handler/resolve.go

Allow redirect_uri that has the same origin of x_custom_ui_uri

---

pkg/lib/infra/middleware/cors_matcher.go

Allowed origin should include x_custom_ui_uri

---

pkg/lib/authn/otp/service.go

Report more accurate failed attempt rate limit error

---

pkg/auth/wire_gen.go
pkg/latte/intent_forgot_password.go
pkg/latte/node_send_forgot_password_code.go
pkg/lib/deps/deps_common.go
pkg/lib/workflow/dependencies.go

Implement forgot password workflow intent

---

pkg/auth/handler/api/workflow_new.go

Accept client_id for non-OAuth workflow

---

docs/specs/templates.md
docs/specs/user-model.md

Specify email magic link

---

docs/specs/index.md
docs/specs/sms_gateway.md

Draft sms gateway spec

---

pkg/api/errors.go
pkg/latte/input_take_current_login_id.go
pkg/latte/intent_change_email.go
pkg/latte/intent_find_verify_identity.go
pkg/latte/node_change_email.go
pkg/latte/node_do_update_identity.go
pkg/lib/workflow/dependencies.go

Add change email workflow

---

pkg/lib/oauth/handler/handler_authz.go
pkg/lib/oauth/handler/handler_authz_test.go
pkg/lib/oauth/handler/resolve.go
pkg/lib/oauth/handler/result_authz.go
pkg/lib/oauth/oidc/handler/handler_end_session.go
pkg/lib/oauth/response_mode.go
pkg/lib/oauth/response_mode_test.go
pkg/util/urlutil/origin.go
pkg/util/urlutil/origin_test.go

ref https://github.com/authgear/2023C01-latte-customization/issues/65

Expose redirect_uri via postMessage when redirecting

---

pkg/auth/routes.go
pkg/auth/webapp/dynamic_csp_middleware.go
pkg/auth/wire_gen.go
pkg/auth/wire_middleware.go
pkg/lib/web/csp.go
pkg/lib/web/csp_test.go

Support frame ancestors in consent screen

---

pkg/lib/infra/sms/client.go

fyi: https://mangatmodi.medium.com/go-check-nil-interface-the-right-way-d142776edef1

Fix always return ambiguous SMS client err when type is not specified

---

Makefile

Do not push image if it exists in the registry

---

pkg/portal/graphql/app.go
pkg/portal/graphql/context.go
pkg/portal/graphql/query.go
pkg/portal/model/app.go
pkg/portal/service/app.go
portal/src/graphql/portal/AppsScreen.tsx
portal/src/graphql/portal/apollo.ts
portal/src/graphql/portal/globalTypes.generated.ts
portal/src/graphql/portal/query/appListQuery.generated.ts
portal/src/graphql/portal/query/appListQuery.graphql
portal/src/graphql/portal/query/appListQuery.ts
portal/src/graphql/portal/schema.graphql
portal/src/util/graphql.ts

Return app list

---

portal/src/graphql/portal/LocalizationConfigurationScreen.tsx
portal/src/locale-data/en.json
portal/src/resources.ts

Support editing more templates in portal

---

pkg/admin/facade/oauth.go
pkg/auth/handler/webapp/viewmodels/base.go
pkg/lib/config/generate.go
pkg/lib/config/oauth.go
pkg/lib/config/secret.go
pkg/lib/oauth/authz_filters.go
pkg/lib/oauth/client_like.go
pkg/lib/oauth/handler/handler_anonymous_user.go
pkg/lib/oauth/handler/handler_authz.go
pkg/lib/oauth/handler/handler_authz_test.go
pkg/lib/oauth/handler/handler_token.go
pkg/lib/oauth/oidc/id_token.go
pkg/lib/oauth/oidc/scopes.go
pkg/lib/oauth/session_manager.go
pkg/lib/sessionlisting/listing.go

Support first party confidential client Part 1

---

pkg/auth/deps.go
pkg/auth/handler/oauth/deps.go
pkg/auth/handler/oauth/redirect.go
pkg/auth/routes.go
pkg/auth/wire_gen.go
pkg/auth/wire_handler.go
pkg/lib/oauth/handler/deps.go
pkg/lib/oauth/handler/handler_proxy_redirect.go
pkg/lib/oauth/handler/handler_proxy_redirect_test.go
pkg/lib/oauth/handler/resolve.go
pkg/lib/oauth/handler/resolve_test.go

Add proxy redirect endpoint to handle custom ui redirection

---

docs/specs/oidc.md
docs/specs/user-model.md

Specify `x_application_type=confidential`

---

authui/package-lock.json
authui/package.json
authui/src/authgear.ts
pkg/auth/handler/webapp/viewmodels/base.go
pkg/auth/webapp/dynamic_csp_middleware.go
pkg/auth/wire_gen.go
pkg/lib/config/environment.go
pkg/lib/deps/deps_provider.go
pkg/lib/web/csp.go
pkg/lib/web/csp_test.go
resources/authgear/templates/en/web/__html_head.html

Setup sentry on Auth UI

---

pkg/latte/node_do_update_identity.go
pkg/lib/authn/authenticator/oob/provider.go
pkg/lib/authn/authenticator/oob/store.go
pkg/lib/authn/authenticator/service/service.go
pkg/lib/facade/coordinator.go
pkg/lib/facade/identity.go
pkg/lib/interaction/context.go
pkg/lib/interaction/intents/authenticate.go
pkg/lib/interaction/intents/forgot_password.go
pkg/lib/interaction/nodes/do_update_identity.go
pkg/lib/interaction/nodes/select_identity_end.go
pkg/lib/workflow/dependencies.go

ref https://github.com/authgear/2023C01-latte-customization/issues/212

Update orphan authenticator when updating Identities

---

docs/specs/rate-limit.md

Add new rate limits spec

---

portal/src/graphql/portal/LoginMethodConfigurationScreen.tsx
portal/src/graphql/portal/MFAConfigurationScreen.tsx
portal/src/graphql/portal/PasswordSettings.tsx
portal/src/locale-data/en.json
portal/src/types.ts
portal/src/util/duration.test.ts
portal/src/util/duration.ts
portal/src/util/input.ts

Update portal to use new rate limit configs

---

cmd/portal/cmd/cmdinternal/internal.go
cmd/portal/cmd/cobraviper.go
cmd/portal/internal/configsource.go

How to use
```
$ make build TARGET=portal BIN_NAME=authgear-portal
./authgear-portal internal pack -f data.json -o ./myapp
./authgear-portal internal pack -i ./myapp > data.new.json
```

Add pack and unpack command

---

cmd/portal/cmd/cmdinternal/migrate_resources_migrate_config_test.go
cmd/portal/cmd/cmdinternal/migrate_resources_migrate_rate_limits.go
cmd/portal/cmd/cmdinternal/testdata/rate_limits__default_values.yaml
cmd/portal/cmd/cmdinternal/testdata/rate_limits__keep_new_config_if_exist.yaml
cmd/portal/cmd/cmdinternal/testdata/rate_limits__migrate_old_config.yaml
cmd/portal/cmd/cmdinternal/utils.go
cmd/portal/cmd/cmdinternal/utils_test.go
go.mod

Add rate limits config migration script

---

cmd/authgear/background/wire_gen.go
pkg/admin/wire_gen.go
pkg/auth/wire_gen.go
pkg/lib/authn/otp/form.go
pkg/lib/authn/otp/service.go
pkg/lib/config/feature.go
pkg/lib/config/feature_test_mode.go
pkg/lib/config/testdata/default_feature.yaml
pkg/lib/deps/deps_config.go
pkg/resolver/wire_gen.go
pkg/util/secretcode/link_otp.go
pkg/util/secretcode/oob_otp.go

Add feature config for fixed oob otp and deterministic link otp

---

pkg/auth/handler/api/workflow_new.go

ref https://github.com/authgear/authgear-server/issues/3075

Update interface of workflow api for user agent binding

---

pkg/auth/deps.go
pkg/auth/handler/api/user_agent.go
pkg/auth/handler/api/workflow_get.go
pkg/auth/handler/api/workflow_input.go
pkg/auth/handler/api/workflow_new.go
pkg/auth/wire_gen.go
pkg/lib/workflow/cookie.go
pkg/lib/workflow/deps.go
pkg/lib/workflow/errors.go
pkg/lib/workflow/id.go
pkg/lib/workflow/service.go
pkg/lib/workflow/service_test.go
pkg/lib/workflow/session.go

ref ref https://github.com/authgear/authgear-server/issues/3075

Implement user agent binding in workflow api

---

pkg/util/graphqlutil/page.go
portal/src/CommandBarContainer.module.css
portal/src/graphql/adminapi/AuditLogList.module.css
portal/src/graphql/adminapi/AuditLogScreen.module.css
portal/src/graphql/adminapi/AuditLogScreen.tsx
portal/src/locale-data/en.json

Rename audit log tabs

---

pkg/lib/config/feature_test_mode.go
pkg/lib/config/test_mode.go
pkg/lib/config/testdata/default_feature.yaml
pkg/lib/deps/deps_config.go
pkg/lib/infra/mail/sender.go
pkg/lib/infra/sms/client.go
pkg/portal/deps/deps_task.go
pkg/portal/wire_gen.go
pkg/worker/wire_gen.go

Suppress email and SMS delivery in test mode

---

portal/src/graphql/portal/LocalizationConfigurationScreen.tsx

Fix portal localization screen become buggy after changing language

---

pkg/auth/webapp/session_middleware.go

Handle oauth session not found gracefully

---

migrations/audit/20230515140227-add_user_id_index_to_audit_logs.sql
pkg/admin/graphql/query.go
pkg/lib/audit/read_store.go
portal/src/graphql/adminapi/AuditLogScreen.module.css
portal/src/graphql/adminapi/AuditLogScreen.tsx
portal/src/graphql/adminapi/globalTypes.generated.ts
portal/src/graphql/adminapi/node.ts
portal/src/graphql/adminapi/query/auditLogListQuery.generated.ts
portal/src/graphql/adminapi/query/auditLogListQuery.graphql
portal/src/graphql/adminapi/query/userQuery.ts
portal/src/graphql/adminapi/schema.graphql
portal/src/hook/useDebounced.ts
portal/src/locale-data/en.json

Support searching audit logs by user id in admin api graphql

---

portal/src/graphql/adminapi/UserDetailSummary.tsx
portal/src/graphql/adminapi/UserDetailsScreen.tsx

Show raw user ID in user details screen

---

portal/src/graphql/adminapi/AuditLogScreen.module.css
portal/src/graphql/adminapi/AuditLogScreen.tsx

Use outlined search box in audit log screen

---

cmd/authgear/background/wire_gen.go
pkg/admin/wire_gen.go
pkg/auth/wire_gen.go
pkg/lib/event/deps.go
pkg/resolver/wire_gen.go

Disable tutorial hook

---

pkg/lib/config/identity.go

Ensure user cannot save a config with empty client id in sso providers

---

migrations/authgear/20230522120934-add_more_index.sql
pkg/lib/authn/identity/loginid/store.go
pkg/lib/authn/identity/oauth/store.go

Add more index

---

pkg/lib/infra/db/hook_handle.go

Use default isolation level

---

pkg/admin/facade/audit_log.go
pkg/admin/loader/audit_log.go
pkg/admin/transport/handler_graphql.go
pkg/admin/wire_gen.go

Reorganize audit db connection boundary

---

pkg/lib/config/messaging_whatsapp.go
pkg/lib/config/secret_whatsapp.go
pkg/lib/config/testdata/default_config.yaml
pkg/lib/infra/whatsapp/on_premises.go
pkg/lib/infra/whatsapp/service.go

Move whatsapp template config to secret

---

portal/src/graphql/portal/SingleSignOnConfigurationScreen.tsx

Fix unable to edit sso configs if there are no existing sso configs

---

pkg/lib/config/feature_messaging.go
pkg/lib/config/testdata/default_feature.yaml
pkg/lib/messaging/limits.go
pkg/lib/messaging/sender.go

Add whatsapp usage limit

---

cmd/portal/cmd/cmdpricing/stripe_service.go
cmd/portal/cmd/cmdusage/collect_count.go
pkg/lib/usage/count_collector.go
pkg/lib/usage/usage_record.go
pkg/portal/libstripe/model.go
pkg/portal/model/subscription.go

Collect whatsapp usage and upload to stripe

---

pkg/portal/graphql/billing.go
pkg/portal/libstripe/model.go
pkg/portal/libstripe/service.go
pkg/portal/model/subscription.go
pkg/portal/service/subscription.go
portal/src/graphql/portal/SubscriptionCurrentPlanSummary.module.css
portal/src/graphql/portal/SubscriptionCurrentPlanSummary.tsx
portal/src/graphql/portal/SubscriptionEnterprisePlan.tsx
portal/src/graphql/portal/SubscriptionPlanCard.module.css
portal/src/graphql/portal/SubscriptionScreen.tsx
portal/src/graphql/portal/globalTypes.generated.ts
portal/src/graphql/portal/query/subscriptionScreenQuery.generated.ts
portal/src/graphql/portal/query/subscriptionScreenQuery.graphql
portal/src/graphql/portal/schema.graphql
portal/src/locale-data/en.json

requires https://github.com/authgear/authgear-server/pull/3160
ref #3157

Display new prices and cost estimations in portal

---

pkg/admin/wire_gen.go
pkg/api/event/nonblocking/sms_sent.go
pkg/api/event/nonblocking/whatsapp_sent.go
pkg/auth/wire_gen.go
pkg/lib/config/feature_messaging.go
pkg/lib/messaging/message_sms.go
pkg/lib/messaging/message_whatsapp.go
pkg/lib/messaging/sender.go
pkg/lib/usage/count_collector.go

ref #3145 
requires https://github.com/authgear/authgear-server/pull/3161

Allow disable usage counting for sms and whatsapp

---

pkg/lib/config/config.go
pkg/lib/config/schema_test.go
pkg/lib/config/testdata/default_config.yaml
pkg/lib/config/testdata/workflow_authentication_method_tests.yaml
pkg/lib/config/testdata/workflow_identification_method_tests.yaml
pkg/lib/config/testdata/workflow_login_flow_tests.yaml
pkg/lib/config/testdata/workflow_reauth_flow_tests.yaml
pkg/lib/config/testdata/workflow_signup_flow_tests.yaml
pkg/lib/config/testdata/workflow_signup_login_flow_tests.yaml
pkg/lib/config/testdata/workflow_tests.yaml
pkg/lib/config/testdata/workflow_workflow_object_id_tests.yaml
pkg/lib/config/workflow.go
pkg/lib/config/workflow_test.go

Add workflow JSON schema

---

pkg/util/graphqlutil/page.go
portal/src/CommandBarContainer.tsx
portal/src/graphql/adminapi/UsersList.tsx
portal/src/graphql/adminapi/UsersScreen.tsx
portal/src/graphql/adminapi/query/usersListQuery.generated.ts
portal/src/graphql/adminapi/query/usersListQuery.graphql
portal/src/locale-data/en.json

Remove pagination in user search result

---

portal/src/locale-data/en.json

Fix sso integration guide link is not working

---

pkg/util/graphqlutil/page.go
portal/src/graphql/adminapi/UsersScreen.module.css
portal/src/graphql/adminapi/UsersScreen.tsx
portal/src/locale-data/en.json

Reduce user search result items

---

authui/package-lock.json
authui/package.json
authui/src/date.ts
authui/src/lockout.ts
resources/authgear/templates/en/translation.json
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

Use luxon duration to format countdown numbers

---

cmd/portal/cmd/cmdinternal/check.go
cmd/portal/cmd/cmdinternal/internal.go
cmd/portal/internal/check.go
cmd/portal/internal/db.go
cmd/portal/internal/migrate_resources.go

`go run ./cmd/portal internal check config-sources`
ref #3098

Add checker for config source integrity

---

portal/src/graphql/portal/SubscriptionScreen.tsx

Open a mailto link on click go enterprise

---

pkg/lib/authn/authenticator/service/service.go
pkg/lib/facade/authenticator.go
pkg/lib/facade/coordinator.go
pkg/lib/interaction/context.go
pkg/lib/interaction/nodes/authn_passkey.go
pkg/lib/interaction/nodes/authn_password.go
pkg/lib/interaction/nodes/authn_totp.go
pkg/lib/lockout/service.go
pkg/lib/workflow/dependencies.go

Fix lockout and ratelimit attempts are multi counted under some situation

---

pkg/auth/handler/webapp/wechat_auth.go
resources/authgear/templates/en/web/wechat_auth.html

So that our form controller will disable the button during form submission.
ref #3239

Turn proceed wechat button into a button

---

portal/src/graphql/portal/ProjectWizardScreen.tsx
portal/src/locale-data/en.json

Allow choosing phone related options in project setup wizard

---

pkg/api/event/nonblocking/project.go
pkg/api/event/nonblocking/project_app_created.go
pkg/portal/graphql/app_mutation.go
pkg/portal/graphql/context.go
pkg/portal/service/app.go

Add event project.app.created

---

pkg/api/event/nonblocking/project.go
pkg/api/event/nonblocking/project_app_updated.go
pkg/portal/graphql/app_mutation.go

Include both old and new app config in event project.app.updated

---

portal/src/graphql/portal/SubscriptionCurrentPlanSummary.tsx
portal/src/graphql/portal/SubscriptionScreen.tsx
portal/src/graphql/portal/SubscriptionScreenFooter.tsx
portal/src/locale-data/en.json

Always allow cancelling subscriptions

---

pkg/lib/authn/identity/service/service.go
pkg/lib/authn/identity/service/service_test.go

Fix identity duplicate checking

---

cmd/portal/analytic/output.go
cmd/portal/analytic/wire.go
cmd/portal/analytic/wire_gen.go
cmd/portal/cmd/cmdanalytic/report.go
cmd/portal/cmd/cmdanalytic/setup_google_sheets.go
pkg/lib/analytic/deps.go
pkg/lib/analytic/output_csv.go
pkg/lib/analytic/output_google_spreadsheet.go
pkg/lib/analytic/project_hourly_report.go
pkg/util/googleutil/google.go
pkg/util/periodical/periodical.go
pkg/util/periodical/periodical_test.go

Support project hourly report

---

.env.example
cmd/portal/server/config.go
cmd/portal/server/server.go
pkg/portal/config/portal_frontend_sentry.go
pkg/portal/deps/deps.go
pkg/portal/deps/providers.go
pkg/portal/model/system_config.go
pkg/portal/service/system_config.go
pkg/portal/wire_gen.go
portal/package-lock.json
portal/package.json
portal/src/ReactApp.tsx
portal/src/system-config.ts

Set up sentry for portal frontend

---

portal/src/InternalRedirect.tsx
portal/src/ReactApp.tsx
portal/src/graphql/portal/AdminAPIConfigurationScreen.tsx
portal/src/graphql/portal/Authenticated.tsx
portal/src/graphql/portal/EditOAuthClientScreen.tsx
portal/src/graphql/portal/HookConfigurationScreen.tsx
portal/src/graphql/portal/SMTPConfigurationScreen.tsx
portal/src/graphql/portal/SingleSignOnConfigurationScreen.tsx

Fix reauthentication on portal

---

pkg/lib/facade/coordinator.go
pkg/lib/feature/verification/service.go
portal/src/graphql/adminapi/UserDetailsConnectedIdentities.tsx
portal/src/locale-data/en.json

Fix disconnecting wechat and disconnecting last identity

---

resources/authgear/templates/en/messages/authenticate_primary_oob_sms.txt
resources/authgear/templates/en/messages/authenticate_secondary_oob_sms.txt
resources/authgear/templates/en/messages/setup_primary_oob_sms.txt
resources/authgear/templates/en/messages/setup_secondary_oob_sms.txt
resources/authgear/templates/en/messages/verification_sms.txt

Remove host in sms messages

---

pkg/lib/config/feature_usage_limit.go

Allow usage quota be set to zero

---

pkg/portal/libstripe/service.go

Fix billing anchor day calculated wrongly

---

resources/authgear/templates/en/messages/whatsapp_otp_code.txt

Remove app name from whatsapp otp template

---

pkg/lib/facade/authenticator.go
pkg/lib/facade/coordinator.go
pkg/lib/interaction/context.go
pkg/lib/interaction/intents/authenticate.go
pkg/lib/interaction/nodes/authn_end.go

Fix otp verification duplicated if phone number isn't verified

---

resources/authgear/templates/en/web/tester.html

ref #3286 
@fungc-io Please see this updated ui

Update styles of tester user info section

---

pkg/util/deviceinfo/deviceinfo.go
pkg/util/deviceinfo/deviceinfo_test.go

Update iOS machine mapping

---

portal/src/graphql/adminapi/UserDetailsSession.tsx

Adjust width of client id in session list

---

pkg/admin/loader/user.go
pkg/lib/authn/authenticator/service/service.go
pkg/lib/authn/identity/service/service.go
pkg/lib/authn/user/queries.go
pkg/lib/feature/customattrs/service_noevent.go
pkg/lib/feature/stdattrs/service_noevent.go
pkg/lib/feature/verification/service.go
pkg/lib/feature/verification/service_mock_test.go
pkg/lib/feature/verification/service_test.go
pkg/lib/feature/verification/store_pq.go

ref #3233 
If you are interested in the actual time consumed in each interaction nodes, you can try this branch which added logs to show the duration of each steps:
https://github.com/tung2744/authgear-server/tree/3233-logs

Optimize user queries

---

pkg/lib/authenticationflow/declarative/data_use_authentication_candidate.go
pkg/lib/authenticationflow/declarative/intent_create_authenticator_oob_otp.go
pkg/lib/authenticationflow/declarative/intent_login_flow_step_authenticate.go
pkg/lib/authenticationflow/declarative/intent_use_authenticator_oob_otp.go
pkg/lib/authenticationflow/declarative/node_do_just_in_time_create_authenticator.go
pkg/lib/authenticationflow/declarative/node_use_authenticator_passkey.go
pkg/lib/authenticationflow/declarative/node_use_authenticator_password.go
pkg/lib/authenticationflow/declarative/node_use_authenticator_totp.go
pkg/lib/authenticationflow/declarative/node_use_identity_passkey.go
pkg/lib/authenticationflow/declarative/util.go
pkg/lib/authenticationflow/dependencies.go
pkg/lib/authn/authenticator/service/service.go
pkg/lib/config/authentication_flow.go
pkg/lib/facade/authenticator.go
pkg/lib/facade/coordinator.go
pkg/lib/interaction/context.go
pkg/lib/interaction/nodes/authn_passkey.go
pkg/lib/interaction/nodes/authn_password.go
pkg/lib/interaction/nodes/authn_totp.go
pkg/lib/workflow/dependencies.go

Just in time create primary OOB OTP authenticator in authflow

---

pkg/auth/handler/webapp/viewmodels/authflow_branch.go
resources/authgear/templates/en/web/__authflow_branch.html

Fix branches are missing in PromoteFlow

---

pkg/auth/handler/webapp/viewmodels/authflow_branch.go
pkg/lib/authenticationflow/declarative/intent_create_authenticator_oob_otp.go
resources/authgear/templates/en/web/__authflow_branch.html

Fix authflow otp issues

---

pkg/lib/oauth/handler/handler_token.go

Issue ID token for anonymous user

---

pkg/auth/handler/webapp/authflow_controller.go
pkg/auth/handler/webapp/authflow_enter_password.go
pkg/auth/handler/webapp/authflow_forgot_password.go
pkg/auth/handler/webapp/authflow_forgot_password_success.go
pkg/auth/handler/webapp/deps.go
pkg/auth/routes.go
pkg/auth/webapp/authflow_routes.go
pkg/auth/webapp/session_authflow.go
pkg/auth/wire_gen.go
pkg/auth/wire_handler.go
pkg/lib/authenticationflow/declarative/generate_config_account_recovery_flow.go
pkg/lib/authenticationflow/declarative/generate_config_account_recovery_flow_test.go
resources/authgear/templates/en/web/authflow_enter_password.html
resources/authgear/templates/en/web/authflow_forgot_password.html
resources/authgear/templates/en/web/authflow_forgot_password_success.html

requires https://github.com/authgear/authgear-server/pull/3419
ref #3408 
https://github.com/authgear/authgear-server/assets/34942210/44659982-79de-4cdf-a443-f8dbc311cd87

Add authflow forgot password page

---

pkg/lib/oauth/handler/handler_token.go

Fix app2app request grant type is not allowed even app2app enabled

---

docs/specs/authentication-flow-api-reference.md

Update authflow docs for account recovery flow

---

pkg/auth/webapp/wechat_redirect_uri_middleware.go

Currently our example app always pass wechat redirect uri to the server, make it unusable with other projects.

Skip wechat redirect uri validation if wechat is not enabled

---

pkg/lib/authenticationflow/declarative/util.go

Allow default flows to be overridden

---

pkg/auth/wire_gen.go
pkg/lib/config/configsource/database.go
pkg/lib/config/configsource/local_fs.go
pkg/lib/config/configsource/store.go
pkg/lib/config/context.go
pkg/lib/deps/deps_provider.go
pkg/lib/oauth/handler/handler_authz.go
pkg/lib/oauth/handler/handler_proxy_redirect.go
pkg/lib/oauth/handler/handler_token.go
pkg/lib/oauth/handler/resolve.go
pkg/lib/oauth/handler/resolve_test.go

Allow all verified domains to be redirect uri

---

pkg/auth/webapp/wechat_redirect_uri_middleware.go

Fix bug introduced by https://github.com/authgear/authgear-server/pull/3442

Fix wechat is always treated as disabled if no x_wechat_redirect_uri exist

---

pkg/auth/handler/webapp/authflow_controller.go
pkg/auth/webapp/session_authflow.go

Remember all screens from different flows

---

authui/package-lock.json
authui/package.json
authui/packages/parcel-namer-authgear/src/index.js
authui/src/build.html
authui/src/intl-tel-input.d.ts
authui/src/intlTelInput.ts
authui/src/overrides.css

UI fixes of tel inputs

---

pkg/auth/handler/webapp/authflow_controller.go
pkg/auth/handler/webapp/authflow_controller_test.go
pkg/auth/handler/webapp/authflow_reauth.go

Try to work around query parameter being blocked by mobile Safari 17 private mode

---

pkg/auth/handler/webapp/authflow_controller.go
pkg/auth/webapp/session_authflow.go

Handle finished authflow more rebustly

---

pkg/auth/handler/webapp/authflow_controller.go
pkg/auth/handler/webapp/authflow_no_authenticator.go
pkg/auth/handler/webapp/deps.go
pkg/auth/routes.go
pkg/auth/webapp/authflow_routes.go
pkg/auth/wire_gen.go
pkg/auth/wire_handler.go
pkg/lib/authenticationflow/declarative/util.go
resources/authgear/templates/en/web/authflow_no_authenticator.html

Handle no authenticator error in ReauthFlow

---

docs/specs/app2app.md

@louischan-oursky Please see if any comments on the design.

Describe login_hint in app2app spec

---

pkg/auth/handler/webapp/error.go
pkg/auth/handler/webapp/panic_middleware.go
pkg/auth/webapp/service2.go
pkg/auth/wire_gen.go
pkg/lib/infra/middleware/panic.go
pkg/util/backgroundjob/runner.go
pkg/util/log/factory.go
pkg/util/log/ignore.go
pkg/util/log/ignore_test.go
pkg/util/log/panic.go
pkg/util/log/stack_hook.go
pkg/util/log/writer_hook.go
pkg/util/sentry/hook.go
resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/__error.html
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

Improve error reporting

---

authui/src/authflow_polling.ts
authui/src/authgear.ts
pkg/auth/handler/webapp/authflow_oob_otp_link.go
resources/authgear/templates/en/web/authflow_oob_otp_link.html

Add polling for login link

---

pkg/auth/handler/webapp/panic_middleware.go

Fix infinite redirect when panic

---

cmd/authgear/background/wire_gen.go
pkg/admin/wire_gen.go
pkg/auth/wire_gen.go
pkg/lib/authn/otp/form.go
pkg/lib/authn/otp/service.go
pkg/lib/config/config.go
pkg/lib/config/feature_test_mode.go
pkg/lib/config/test_mode.go
pkg/lib/config/testdata/default_config.yaml
pkg/lib/deps/deps_config.go
pkg/resolver/wire_gen.go
pkg/util/validation/formats.go

Support fixed oob otp for specific targets in config

---

pkg/auth/handler/webapp/authflow_controller.go

ref https://github.com/authgear/authgear-server/issues/3502#issuecomment-1838818066

Fix finish of account recovery flow deleted web session

---

pkg/auth/handler/webapp/authflow_forgot_password.go
resources/authgear/templates/en/web/authflow_enter_password.html
resources/authgear/templates/en/web/authflow_forgot_password.html

Support alternative forgot password methods

---

pkg/lib/authenticationflow/declarative/node_do_send_account_recovery_code.go
pkg/lib/authenticationflow/dependencies.go
pkg/lib/authn/otp/kind_forgot_password.go
pkg/lib/feature/forgotpassword/service.go

Separate rate limit buckets of whatsapp and sms in forgot password

---

portal/src/CommandBarContainer.module.css
portal/src/ReactApp.module.css
portal/src/ScreenLayout.module.css
portal/src/ScreenLayoutScrollView.module.css
portal/src/index.css
portal/tailwind.config.js

Fix portal content is not showing in mobile

---

pkg/auth/handler/webapp/authflow_controller.go
portal/src/graphql/portal/LoginMethodConfigurationScreen.tsx

ref #3528 
There is another issue which related to secondary oob otp authenticator, follow up in https://github.com/authgear/authgear-server/issues/3549

Fix portal is not showing otp mode correctly

---

authui/src/authflowv2/base.css
authui/src/authflowv2/components.css
authui/src/authflowv2/components/body-text.css
authui/src/authflowv2/components/code-block.css
authui/src/authflowv2/components/divider.css
pkg/lib/web/html.go
resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/authflowv2/__divider.html
resources/authgear/templates/en/web/authflowv2/enter_password.html
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

ref #3555 
require #3599 
https://github.com/authgear/authgear-server/assets/63200569/966f949d-9e1d-47ab-b31c-78cc012634bc

Implement common component styles

---

authui/src/authflowv2/base.css
authui/src/authflowv2/components.css
authui/src/authflowv2/components/input.css
resources/authgear/templates/en/web/authflowv2/enter_password.html

Add text input component

---

authui/src/authflowv2/base.css
authui/src/authflowv2/components/body-text.css
pkg/auth/handler/webapp/authflowv2/signup.go
resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/authflowv2/enter_password.html
resources/authgear/templates/en/web/authflowv2/signup.html
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

requires #3567 
ref #3569 
TODO:

AuthUI V2 - Signup

---

.golangci.yml
pkg/admin/loader/audit_log.go
pkg/admin/loader/authenticator.go
pkg/admin/loader/identity.go
pkg/admin/loader/user.go
pkg/lib/analytic/count_collector.go
pkg/lib/authenticationflow/declarative/intent_account_recovery_flow_steps.go
pkg/lib/authenticationflow/declarative/intent_signup_flow_step_fill_in_user_profile.go
pkg/lib/authenticationflow/input.go
pkg/lib/authn/identity/service/service.go
pkg/lib/oauth/handler/handler_token.go
pkg/lib/workflow/workflow.go
pkg/portal/service/collaborator.go

ref #3619
All issues found are just conditions that never hold. No actual runtime error were found.

Configure govet properly

---

authui/src/authflowv2/base.css
authui/src/authflowv2/components.css
authui/src/authflowv2/components/alert-message.css
authui/src/authflowv2/icons/material-symbols.css
pkg/lib/web/html.go
resources/authgear/templates/en/web/authflowv2/__alert_message.html
resources/authgear/templates/en/web/authflowv2/enter_password.html

Add alert message template

---

docs/specs/authentication-flow-api-reference.md
pkg/api/model/authenticator.go
pkg/auth/handler/webapp/authflow_controller.go
pkg/auth/handler/webapp/viewmodels/authflow_branch.go
pkg/lib/authenticationflow/declarative/data_create_authenticator_option.go
pkg/lib/authenticationflow/declarative/intent_create_authenticator_oob_otp.go
pkg/lib/authenticationflow/declarative/intent_signup_flow_step_create_authenticator.go
pkg/lib/authenticationflow/declarative/utils_common.go
pkg/lib/authenticationflow/declarative/utils_create_authenticator.go
pkg/lib/authn/authenticator/oobotp_authenticator.go
resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/__authflow_branch.html
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

Handle skippable otp authenticator verification

---

authui/src/authflowv2.ts
authui/src/countdown.ts
resources/authgear/templates/en/web/authflowv2/enter_password.html

Add countdown stimulus controller

---

pkg/auth/handler/webapp/authflow_create_password.go

ref #3642
https://github.com/authgear/authgear-server/assets/63200569/4fec43ff-d410-4935-86cf-f691684e61df

Fix missing confirm password handling in create password screen

---

authui/src/authflowv2/components.css
authui/src/authflowv2/components/icon.css
authui/src/authflowv2/components/phone-input.css
authui/src/authflowv2/components/select.css
authui/src/authflowv2/components/widget.css
authui/src/authflowv2/text-field.ts
authui/src/customSelect.ts
authui/src/form.ts
authui/src/phoneInput.ts
pkg/util/template/func.go
resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/authflowv2/__error.html
resources/authgear/templates/en/web/authflowv2/__html_head.html
resources/authgear/templates/en/web/authflowv2/__phone_input.html
resources/authgear/templates/en/web/authflowv2/login.html
resources/authgear/templates/en/web/authflowv2/signup.html
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

Implement login & integrate phone input

---

portal/src/graphql/portal/EditOAuthClientForm.tsx
portal/src/locale-data/en.json

Allow configuring post_logout_redirect_uri for confidential clients

---

pkg/auth/handler/webapp/authflowv2/deps.go
pkg/auth/handler/webapp/authflowv2/setup_oob_otp.go
pkg/auth/routes.go
pkg/auth/wire_gen.go
pkg/auth/wire_handler.go
resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/authflowv2/__error.html
resources/authgear/templates/en/web/authflowv2/__phone_input.html
resources/authgear/templates/en/web/authflowv2/setup_oob_otp.html
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

ref #3573
dependencies:
Email|Phone
-|-

Add v2 setup 2fa OOB OTP page

---

authui/src/authflowv2.ts
pkg/auth/handler/webapp/authflowv2/deps.go
pkg/auth/handler/webapp/authflowv2/view_recovery_code.go
pkg/auth/handler/webapp/settings_recovery_code.go
pkg/auth/handler/webapp/setup_recovery_code.go
pkg/auth/routes.go
pkg/auth/wire_gen.go
pkg/auth/wire_handler.go
resources/authgear/templates/en/web/authflowv2/view_recovery_code.html

ref #3571
dependencies:
Desktop|Mobile
-|-

Add v2 view recovery code page

---

authui/src/authflowv2/components/input.css
authui/src/authflowv2/components/otp-input.css
authui/src/authflowv2/components/phone-input.css
authui/src/authflowv2/components/select.css
authui/src/customSelect.ts
resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/authflowv2/__page_frame.html
resources/authgear/templates/en/web/authflowv2/__password_input.html
resources/authgear/templates/en/web/authflowv2/__phone_input.html
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

RTL support

---

pkg/auth/handler/webapp/authflow_controller.go
pkg/lib/authenticationflow/declarative/error.go
pkg/lib/authenticationflow/declarative/intent_signup_flow.go
pkg/lib/authenticationflow/declarative/intent_signup_login_flow.go
resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/authflowv2/__error.html
resources/authgear/templates/en/web/authflowv2/fatal_error.html
resources/authgear/templates/en/web/authflowv2/signup.html
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

Add fatal error message for public signup disabled

---

pkg/auth/handler/webapp/authflow_controller.go

Ensure public signup error is non-recoverable error

---

resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/authflowv2/account_status.html
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

ref #3582
require #3660 
https://github.com/authgear/authgear-server/assets/63200569/4630b2e4-e64c-4f51-bad0-303dfde714f0

Add error display for different account status 

---

pkg/auth/webapp/session_authflow.go

Fix verify step always show sms screen if no branches

---

authui/src/authflowv2/icons/sso-icons.css
resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/authflowv2/login.html
resources/authgear/templates/en/web/authflowv2/signup.html
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

Auth ui v2 - Add SSO login

---

authui/src/authflowv2/components/layout.css
authui/src/authflowv2/components/widget.css
resources/authgear/templates/en/web/authflowv2/layout.html

Adjust default layout styles

---

authui/src/authflowv2/components/divider.css
authui/src/authflowv2/components/secondary-button.css
pkg/auth/handler/webapp/viewmodels/authflow_branch.go
resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/authflowv2/__authflow_branch.html
resources/authgear/templates/en/web/authflowv2/create_password.html
resources/authgear/templates/en/web/authflowv2/enter_oob_otp.html
resources/authgear/templates/en/web/authflowv2/setup_oob_otp.html
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

ref #3597
**Signup**
**Login**

Auth UI v2 - Alternative signup methods

---

.make-lint-expect
authui/src/authflowv2/components.css
authui/src/authflowv2/components/screen-icon-layout.css
authui/src/authflowv2/components/widget.css
pkg/auth/deps.go
pkg/auth/handler/webapp/authflow_controller.go
pkg/auth/handler/webapp/authflow_controller_mock_test.go
pkg/auth/handler/webapp/authflow_controller_test.go
pkg/auth/handler/webapp/authflowv2/deps.go
pkg/auth/handler/webapp/authflowv2/routes.go
pkg/auth/handler/webapp/authflowv2/select_account.go
pkg/auth/handler/webapp/confirm_terminate_other_sessions.go
pkg/auth/handler/webapp/oauth_entrypoint.go
pkg/auth/routes.go
pkg/auth/webapp/authflow_routes.go
pkg/auth/wire_gen.go
pkg/auth/wire_handler.go
pkg/lib/deps/deps_common.go
pkg/lib/endpoints/endpoints.go
resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/authflowv2/select_account.html
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

Auth ui v2 - Implement select account screen

---

authui/src/authflowv2/components/alert-message.css
pkg/auth/handler/webapp/authflowv2/deps.go
pkg/auth/handler/webapp/authflowv2/enter_recovery_code.go
pkg/auth/routes.go
pkg/auth/wire_gen.go
pkg/auth/wire_handler.go
resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/authflowv2/__authflow_branch.html
resources/authgear/templates/en/web/authflowv2/__error.html
resources/authgear/templates/en/web/authflowv2/enter_oob_otp.html
resources/authgear/templates/en/web/authflowv2/enter_recovery_code.html
resources/authgear/templates/en/web/authflowv2/setup_oob_otp.html
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

Auth UI v2 - Add enter recovery code page

---

authui/src/form.ts
authui/src/otpInput.ts
resources/authgear/templates/en/web/authflowv2/__otp_input.html
resources/authgear/templates/en/web/authflowv2/enter_oob_otp.html

Auth UI v2 - Clear otp input on submit

---

pkg/auth/handler/webapp/authflowv2/change_password.go
pkg/auth/handler/webapp/authflowv2/deps.go
pkg/auth/routes.go
pkg/auth/wire_gen.go
pkg/auth/wire_handler.go
resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/authflowv2/change_password.html
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

ref #3585
https://github.com/authgear/authgear-server/assets/63200569/2f460e11-e221-480a-aac5-7537e7c10658

Add authflowv2 change password page

---

pkg/lib/oauth/metadata.go

Output correct token_endpoint_auth_methods_supported

---

authui/src/authflowv2/components/screen-icon-layout.css
authui/src/authflowv2/components/screen-icon.css
authui/src/cssattrs.ts
pkg/auth/handler/webapp/authflowv2/deps.go
pkg/auth/handler/webapp/authflowv2/error.go
pkg/auth/handler/webapp/authflowv2/forgot_password.go
pkg/auth/routes.go
pkg/auth/wire_gen.go
pkg/auth/wire_handler.go
resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/authflowv2/__error.html
resources/authgear/templates/en/web/authflowv2/enter_password.html
resources/authgear/templates/en/web/authflowv2/forgot_password.html
resources/authgear/templates/en/web/authflowv2/select_account.html
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

ref #3588 
Opened this pr first to unblock the remaining task of forgot password

Implement forgot password v2

---

pkg/auth/handler/webapp/authflowv2/deps.go
pkg/auth/handler/webapp/authflowv2/forgot_password.go
pkg/auth/handler/webapp/authflowv2/forgot_password_link_sent.go
pkg/auth/handler/webapp/authflowv2/forgot_password_success.go
pkg/auth/handler/webapp/authflowv2/routes.go
pkg/auth/routes.go
pkg/auth/wire_gen.go
pkg/auth/wire_handler.go
pkg/lib/endpoints/endpoints.go
resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/authflowv2/forgot_password_link_sent.html
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

Implement v2 forgot password link sent

---

pkg/lib/authenticationflow/declarative/intent_account_recovery_flow_step_verify_account_recovery_code.go
pkg/lib/authenticationflow/declarative/node_do_send_account_recovery_code.go

Fix authflow account recovery screen not returning rate limit error on resend

---

pkg/auth/handler/webapp/authflowv2/deps.go
pkg/auth/handler/webapp/authflowv2/forgot_password_otp.go
pkg/auth/routes.go
pkg/auth/wire_gen.go
pkg/auth/wire_handler.go
pkg/lib/web/html.go
resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/authflowv2/__forgot_password_alternatives.html
resources/authgear/templates/en/web/authflowv2/__otp_input.html
resources/authgear/templates/en/web/authflowv2/forgot_password_generic_otp.html
resources/authgear/templates/en/web/authflowv2/forgot_password_otp.html
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

ref #3589 
dependencies
Email|SMS|WhatsApp|
-|-|-

Auth UI v2 -  Account Recovery OTP stage

---

pkg/auth/handler/webapp/authflow_controller.go
pkg/auth/handler/webapp/authflow_controller_mock_test.go
pkg/auth/handler/webapp/authflow_controller_test.go
pkg/auth/handler/webapp/authflowv2/deps.go
pkg/auth/handler/webapp/authflowv2/reset_password.go
pkg/auth/handler/webapp/authflowv2/reset_password_success.go
pkg/auth/handler/webapp/authflowv2/routes.go
pkg/auth/routes.go
pkg/auth/webapp/authflow_routes.go
pkg/auth/webapp/session_authflow.go
pkg/auth/wire_gen.go
pkg/auth/wire_handler.go
pkg/lib/web/html.go
resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/authflowv2/__error_page_layout.html
resources/authgear/templates/en/web/authflowv2/fatal_error.html
resources/authgear/templates/en/web/authflowv2/reset_password.html
resources/authgear/templates/en/web/authflowv2/reset_password_success.html
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

ref #3590 
require #3697 #3701 
follow up #3715 
demo video
https://github.com/authgear/authgear-server/assets/63200569/a6e62584-01c2-4edc-840a-6ade2551a68d
invalid link display

Add authflowv2 reset password and success pages

---

authui/src/customSelect.ts
authui/src/form.ts
authui/src/phoneInput.ts

ref #3664 
I've tested the fix in chrome desktop, safari desktop and safari mobile.

Handle restoration of value from bfcache in phone input

---

authui/src/authflowv2/base.css

Fix ios 15 safari missing ring in input

---

authui/src/authflowv2/components/modal.css
authui/src/authflowv2/components/screen-icon.css
resources/authgear/templates/en/web/authflowv2/__error_page_layout.html
resources/authgear/templates/en/web/authflowv2/__lockout.html
resources/authgear/templates/en/web/authflowv2/account_status.html
resources/authgear/templates/en/web/authflowv2/not_found.html

Sync page layout implementation and update screen icon alignment

---

pkg/auth/handler/webapp/authflowv2/change_password.go
pkg/auth/handler/webapp/authflowv2/create_password.go
pkg/auth/handler/webapp/authflowv2/enter_password.go
pkg/auth/handler/webapp/authflowv2/reset_password.go
pkg/auth/handler/webapp/authflowv2/viewmodels/password_input_error.go
pkg/auth/handler/webapp/viewmodels/base.go
pkg/auth/handler/webapp/viewmodels/viewmodel.go
resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/authflowv2/__password_field.html
resources/authgear/templates/en/web/authflowv2/change_password.html
resources/authgear/templates/en/web/authflowv2/create_password.html
resources/authgear/templates/en/web/authflowv2/enter_password.html
resources/authgear/templates/en/web/authflowv2/reset_password.html

ref #3615
https://github.com/authgear/authgear-server/assets/63200569/de1081af-a384-4100-828b-e293c8c2cd02

Put password fields error to view model

---

authui/src/authflowv2/components/code-block.css
pkg/auth/handler/webapp/authflowv2/deps.go
pkg/auth/handler/webapp/authflowv2/setup_totp.go
pkg/auth/routes.go
pkg/auth/wire_gen.go
pkg/auth/wire_handler.go
resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/authflowv2/__otp_input.html
resources/authgear/templates/en/web/authflowv2/setup_totp.html
resources/authgear/templates/en/web/authflowv2/setup_totp_verify.html
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

ref #3574 
Used query param ~~`x_action`~~ `q_setup_totp_step=verify` instead of different path because will need to override `checkPath`
Setup|Verify
-|-

Auth UI v2 - Add setup totp page

---

resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/authflowv2/reset_password_success.html
resources/authgear/templates/en/web/authflowv2/setup_totp.html
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

Use br for authui v2 translations

---

resources/authgear/templates/en/web/authflowv2/enter_oob_otp.html
resources/authgear/templates/en/web/authflowv2/forgot_password_otp.html
resources/authgear/templates/en/web/authflowv2/setup_oob_otp.html
resources/authgear/templates/en/web/authflowv2/setup_totp_verify.html
resources/authgear/templates/en/web/authflowv2/view_recovery_code.html

Remove header from layouts except login and signup

---

authui/src/authflowv2/icons/material-symbols.css

Hide material icon before font file is loaded

---

pkg/auth/handler/webapp/authflowv2/deps.go
pkg/auth/handler/webapp/authflowv2/enter_totp.go
pkg/auth/routes.go
pkg/auth/wire_gen.go
pkg/auth/wire_handler.go
resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/authflowv2/enter_totp.html
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

Auth UI v2 - Implement enter totp page

---

authui/src/authflowv2.ts
pkg/auth/handler/webapp/authflowv2/deps.go
pkg/auth/handler/webapp/authflowv2/oob_otp_link.go
pkg/auth/routes.go
pkg/auth/wire_gen.go
pkg/auth/wire_handler.go
resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/authflowv2/forgot_password_link_sent.html
resources/authgear/templates/en/web/authflowv2/oob_otp_link.html
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

Implement authflow v2 login link

---

resources/authgear/templates/en/web/authflowv2/setup_totp.html
resources/authgear/templates/en/web/authflowv2/view_recovery_code.html

Disable copy label change on copy

---

pkg/auth/deps.go
pkg/auth/handler/webapp/authflowv2/deps.go
pkg/auth/handler/webapp/authflowv2/routes.go
pkg/auth/handler/webapp/authflowv2/verify_login_link.go
pkg/auth/handler/webapp/implementation_switcher.go
pkg/auth/handler/webapp/panic_middleware.go
pkg/auth/routes.go
pkg/auth/wire_gen.go
pkg/auth/wire_handler.go
pkg/lib/authn/otp/sender.go
pkg/lib/config/ui.go
pkg/lib/endpoints/endpoints.go
resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/authflowv2/verify_login_link.html
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

ref #3594 
requires https://github.com/authgear/authgear-server/pull/3739
TODO:

Implement v2 verify login link

---

pkg/lib/authenticationflow/declarative/generate_config_login_flow.go
pkg/lib/authenticationflow/declarative/generate_config_login_flow_test.go
pkg/lib/authenticationflow/declarative/intent_login_flow_step_authenticate.go
pkg/lib/authenticationflow/declarative/milestone.go
pkg/lib/authenticationflow/declarative/node_do_use_authenticator_password.go
pkg/lib/authenticationflow/declarative/node_use_authenticator_password.go
resources/authgear/templates/en/web/authflowv2/enter_password.html

ref #3585
https://github.com/authgear/authgear-server/assets/63200569/3fe86c29-e58c-46b6-ad96-5553552229c3

Fix force change password comes before 2FA

---

resources/authgear/templates/en/web/authflow_oob_otp_link.html
resources/authgear/templates/en/web/login_link_otp.html

ref #3740
https://github.com/authgear/authgear-server/assets/63200569/5b16d29c-f141-4a33-84d9-697a0c19ee1b

Fix remember device not working for login link

---

authui/src/authflowv2/base.css
authui/src/authflowv2/components/icon.css
authui/src/authflowv2/components/modal.css
authui/src/authflowv2/components/select.css
authui/src/authflowv2/dialog.ts
authui/src/authflowv2/icons/twemoji-countries.css
authui/src/customSelect.ts
authui/src/phoneInput.ts
resources/authgear/templates/en/web/authflowv2/__lockout.html
resources/authgear/templates/en/web/authflowv2/__phone_input.html

ref #3728
~~Haven't resolved flag display issue~~ Used raw font file without applying subset. Will handle subset in #3742 instead.

Auth UI v2 - Fix phone input issues

---

pkg/auth/handler/webapp/authflowv2/deps.go
pkg/auth/handler/webapp/authflowv2/use_passkey.go
pkg/auth/routes.go
pkg/auth/wire_gen.go
pkg/auth/wire_handler.go
resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/authflowv2/login.html
resources/authgear/templates/en/web/authflowv2/signup.html
resources/authgear/templates/en/web/authflowv2/use_passkey.html
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

Implement v2 use passkey

---

authui/src/authflowv2/text-field.ts
authui/src/otpInput.ts
resources/authgear/templates/en/web/authflowv2/__otp_input.html

Auth UI v2 - Unmask otp last digit when focused

---

pkg/auth/handler/webapp/authflowv2/deps.go
pkg/auth/handler/webapp/authflowv2/terminate_other_sessions.go
pkg/auth/routes.go
pkg/auth/wire_gen.go
pkg/auth/wire_handler.go
resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/authflowv2/terminate_other_sessions.html
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

ref #3584 
https://github.com/authgear/authgear-server/assets/63200569/d80f14a2-33a2-4874-ad85-76d14c6ce63b

Implement authflow v2 terminate other sessions page

---

pkg/lib/web/html.go
resources/authgear/templates/en/web/authflowv2/__device_token_checkbox.html
resources/authgear/templates/en/web/authflowv2/enter_oob_otp.html
resources/authgear/templates/en/web/authflowv2/enter_password.html
resources/authgear/templates/en/web/authflowv2/enter_recovery_code.html
resources/authgear/templates/en/web/authflowv2/enter_totp.html
resources/authgear/templates/en/web/authflowv2/oob_otp_link.html
resources/authgear/templates/en/web/authflowv2/setup_totp_verify.html

Extract device token checkbox to a reusable component

---

pkg/lib/web/html.go
resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/authflowv2/__toc_pp_footer.html
resources/authgear/templates/en/web/authflowv2/login.html
resources/authgear/templates/en/web/authflowv2/signup.html
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

Auth UI v2 - Add disclaimer to login and signup

---

resources/authgear/templates/en/translation.json
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

Update v2 use passkey text

---

authui/src/authflowv2.ts
authui/src/authflowv2/new-password-field.ts
authui/src/authflowv2/password-policy.ts
authui/src/authflowv2/password-strength-meter.ts
pkg/lib/web/html.go
resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/authflowv2/__error.html
resources/authgear/templates/en/web/authflowv2/__new_password_field.html
resources/authgear/templates/en/web/authflowv2/__password_field.html
resources/authgear/templates/en/web/authflowv2/__password_input.html
resources/authgear/templates/en/web/authflowv2/change_password.html
resources/authgear/templates/en/web/authflowv2/create_password.html
resources/authgear/templates/en/web/authflowv2/reset_password.html
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

ref #3733 
https://github.com/authgear/authgear-server/assets/34942210/f7478b81-d2c8-4d30-912f-fb85a1a3e600

Add local password policy validation and error states

---

resources/authgear/templates/en/web/authflowv2/__password_input.html
resources/authgear/templates/en/web/authflowv2/__phone_input.html
resources/authgear/templates/en/web/authflowv2/enter_recovery_code.html
resources/authgear/templates/en/web/authflowv2/forgot_password.html
resources/authgear/templates/en/web/authflowv2/login.html
resources/authgear/templates/en/web/authflowv2/setup_oob_otp.html
resources/authgear/templates/en/web/authflowv2/signup.html

Remove unnecessary tab index

---

go.mod
go.sum
pkg/auth/routes.go
pkg/portal/routes.go
pkg/util/httputil/gzip.go

Apply gzip to static assets

---

resources/authgear/templates/en/web/authflowv2/__authflow_branch.html

ref #3787
|   |   |
|---|---|
|   <img width="581" alt="image" src="https://github.com/authgear/authgear-server/assets/63200569/b870bf18-6c75-40fb-9720-88028933874b"> |   <img width="633" alt="image" src="https://github.com/authgear/authgear-server/assets/63200569/4246181b-cb17-4ba0-ba46-5bacbe2d872c"> |

Fix authflow branch icons

---

authui/src/authflowv2/password-policy.ts
authui/src/authflowv2/zxcvbn.ts

Auth UI v2 - Fix dynamic import type for zxcvbn

---

authui/src/authflowv2/components/screen-icon-layout.css
authui/src/authflowv2/components/widget.css
resources/authgear/templates/en/web/authflowv2/__lockout.html
resources/authgear/templates/en/web/authflowv2/account_status.html
resources/authgear/templates/en/web/authflowv2/change_password.html
resources/authgear/templates/en/web/authflowv2/create_password.html
resources/authgear/templates/en/web/authflowv2/enter_oob_otp.html
resources/authgear/templates/en/web/authflowv2/enter_password.html
resources/authgear/templates/en/web/authflowv2/enter_recovery_code.html
resources/authgear/templates/en/web/authflowv2/enter_totp.html
resources/authgear/templates/en/web/authflowv2/forgot_password.html
resources/authgear/templates/en/web/authflowv2/forgot_password_link_sent.html
resources/authgear/templates/en/web/authflowv2/forgot_password_otp.html
resources/authgear/templates/en/web/authflowv2/login.html
resources/authgear/templates/en/web/authflowv2/oob_otp_link.html
resources/authgear/templates/en/web/authflowv2/prompt_create_passkey.html
resources/authgear/templates/en/web/authflowv2/reset_password.html
resources/authgear/templates/en/web/authflowv2/reset_password_success.html
resources/authgear/templates/en/web/authflowv2/select_account.html
resources/authgear/templates/en/web/authflowv2/setup_oob_otp.html
resources/authgear/templates/en/web/authflowv2/setup_totp.html
resources/authgear/templates/en/web/authflowv2/setup_totp_verify.html
resources/authgear/templates/en/web/authflowv2/signup.html
resources/authgear/templates/en/web/authflowv2/use_passkey.html
resources/authgear/templates/en/web/authflowv2/view_recovery_code.html

Adjust watermark styles

---

pkg/auth/handler/webapp/authflow_controller.go
pkg/auth/wire_gen.go

ref #3785 
https://github.com/authgear/authgear-server/assets/63200569/ad79c0e6-da8e-43e8-82e7-400518c0bbb5

Redirect to login on root path if signuped cookies is set to true 

---

resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/authflowv2/__error.html
resources/authgear/templates/en/web/authflowv2/use_passkey.html
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

ref #3786 
https://github.com/authgear/authgear-server/assets/63200569/ab7e46d3-4f5c-4551-aaba-5e0d04ce630e

Display passkey missing error message

---

authui/.browserslistrc

Auth UI v2 - Update browserlist for authui

---

pkg/lib/authenticationflow/accept.go
pkg/lib/authenticationflow/intent.go
resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/authflowv2/__error.html
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

ref #3771
- User tries to login with email
- User tries to sign up with email
- User tries to login with Google or other oauth providers
- Signup with email already registered

Auth UI v2 - Update error message for conflict identity

---

portal/src/graphql/adminapi/AuditLogList.tsx

ref #3641
**Before**
https://github.com/authgear/authgear-server/assets/3119725/212640f1-950d-498f-a5eb-dc9f9213c8cf
**After**
https://github.com/authgear/authgear-server/assets/3119725/054f8e21-3de3-4378-93bc-cc096ff0df69

Fix audit log not fully shown on first load due to overflow

---

resources/authgear/templates/en/web/authflowv2/__device_token_checkbox.html
resources/authgear/templates/en/web/authflowv2/enter_recovery_code.html

Auth UI v2 - Fix enter recover code page's device token checkbox margin

---

authui/src/authflowv2/components/otp-input.css

Auth UI v2 - Fix pasting to otp input on iOS

---

authui/src/authflowv2.ts
authui/src/authflowv2/alert-message.ts
authui/src/authflowv2/components/alert-message.css
authui/src/authflowv2/form.ts
resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/authflowv2/__alert_message.html
resources/authgear/templates/en/web/authflowv2/change_password.html
resources/authgear/templates/en/web/authflowv2/create_password.html
resources/authgear/templates/en/web/authflowv2/enter_oob_otp.html
resources/authgear/templates/en/web/authflowv2/enter_password.html
resources/authgear/templates/en/web/authflowv2/enter_recovery_code.html
resources/authgear/templates/en/web/authflowv2/enter_totp.html
resources/authgear/templates/en/web/authflowv2/forgot_password.html
resources/authgear/templates/en/web/authflowv2/forgot_password_link_sent.html
resources/authgear/templates/en/web/authflowv2/forgot_password_otp.html
resources/authgear/templates/en/web/authflowv2/login.html
resources/authgear/templates/en/web/authflowv2/oob_otp_link.html
resources/authgear/templates/en/web/authflowv2/prompt_create_passkey.html
resources/authgear/templates/en/web/authflowv2/reset_password.html
resources/authgear/templates/en/web/authflowv2/select_account.html
resources/authgear/templates/en/web/authflowv2/setup_oob_otp.html
resources/authgear/templates/en/web/authflowv2/setup_totp_verify.html
resources/authgear/templates/en/web/authflowv2/signup.html
resources/authgear/templates/en/web/authflowv2/terminate_other_sessions.html
resources/authgear/templates/en/web/authflowv2/use_passkey.html
resources/authgear/templates/en/web/authflowv2/verify_login_link.html
resources/authgear/templates/en/web/authflowv2/view_recovery_code.html
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

ref #3698 
https://github.com/authgear/authgear-server/assets/63200569/1355d5fa-0128-4749-888a-17797e119516

Add alert message to every page with form

---

authui/src/authflowv2/base.css

ref #3788
https://github.com/authgear/authgear-server/assets/63200569/87f5d713-94d6-4e9b-bd1c-576d32776a02

Allow set outline-none to non-input element

---

resources/authgear/templates/en/translation.json
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

Update copywriting of password containing banned words

---

authui/src/authflowv2/alert-message.ts
pkg/auth/deps.go
pkg/auth/handler/webapp/authflow_controller.go
pkg/auth/handler/webapp/authflow_controller_mock_test.go
pkg/auth/handler/webapp/authflow_controller_test.go
pkg/auth/handler/webapp/authflow_finish_flow.go
pkg/auth/handler/webapp/authflowv2/change_password.go
pkg/auth/handler/webapp/authflowv2/change_password_success.go
pkg/auth/handler/webapp/authflowv2/deps.go
pkg/auth/handler/webapp/authflowv2/finish_flow.go
pkg/auth/handler/webapp/authflowv2/routes.go
pkg/auth/handler/webapp/deps.go
pkg/auth/handler/webapp/panic_middleware.go
pkg/auth/routes.go
pkg/auth/webapp/authflow_routes.go
pkg/auth/webapp/result.go
pkg/auth/webapp/session_authflow.go
pkg/auth/wire_gen.go
pkg/auth/wire_handler.go
resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/authflowv2/change_password_success.html
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

ref #3695 
require #3807 
https://github.com/authgear/authgear-server/assets/63200569/be7a1d73-1064-40aa-9f58-36a54056c04c

Add force update password success page

---

portal/src/locale-data/en.json

Update Google Tag Manager integration guide url

---

portal/src/locale-data/en.json

Fix missing error message translation

---

pkg/auth/handler/webapp/authflowv2/deps.go
pkg/auth/handler/webapp/authflowv2/no_authenticator.go
pkg/auth/handler/webapp/authflowv2/routes.go
pkg/auth/routes.go
pkg/auth/wire_gen.go
pkg/auth/wire_handler.go
pkg/lib/authenticationflow/declarative/utils_common.go
resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/authflowv2/fatal_error.html
resources/authgear/templates/en/web/authflowv2/no_authenticator.html
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

Add v2 no authenticator screen

---

pkg/util/checksum/checkusm_test.go

Add test to checksum

---

authui/src/authflowv2/base.css
authui/src/authflowv2/components/alert-message.css
authui/src/authflowv2/components/body-text.css
authui/src/authflowv2/components/checkbox.css
authui/src/authflowv2/components/code-block.css
authui/src/authflowv2/components/divider.css
authui/src/authflowv2/components/input.css
authui/src/authflowv2/components/label-button.css
authui/src/authflowv2/components/layout.css
authui/src/authflowv2/components/link-button.css
authui/src/authflowv2/components/otp-input.css
authui/src/authflowv2/components/password-policy.css
authui/src/authflowv2/components/password-strength-meter.css
authui/src/authflowv2/components/phone-input.css
authui/src/authflowv2/components/primary-button.css
authui/src/authflowv2/components/screen-description.css
authui/src/authflowv2/components/screen-title.css
authui/src/authflowv2/components/secondary-button.css
authui/src/authflowv2/components/select.css
authui/src/authflowv2/components/tertiary-button.css
resources/authgear/templates/en/web/authflowv2/__password_input.html

Add dark mode support

---

pkg/api/model/session_info.go
pkg/api/model/session_info_test.go

Treat absent boolean header as false

---

authui/src/authflowv2/base.css
authui/src/authflowv2/components/label-button.css
authui/src/authflowv2/components/link-button.css
authui/src/authflowv2/components/primary-button.css
resources/authgear/templates/en/web/authflowv2/__device_token_checkbox.html

v2 dark mode adjustments

---

resources/authgear/templates/en/web/authflowv2/forgot_password_link_sent.html

Fix forgot password link sent screen layout

---

pkg/auth/handler/webapp/viewmodels/authflow_branch.go
pkg/auth/handler/webapp/viewmodels/authflow_branch_test.go
resources/authgear/templates/en/web/authflowv2/login.html

Put passkey option to the bottom

---

portal/src/locale-data/en.json

Update FormConfirmOverridingDialog text

---

authui/src/authflowv2/customSelect.ts
authui/src/authflowv2/phoneInput.ts

Fix country list keyword search includes dom element

---

authui/src/authflowv2/customSelect.ts
authui/src/authflowv2/phoneInput.ts

Some phone input fixes

---

pkg/auth/handler/webapp/authflowv2/enter_password.go

Was added for authui playground back then.

Remove unused enter password handlers

---

authui/src/authflowv2/components/select.css

Hide select clear button in mobile

---

pkg/auth/handler/webapp/authflowv2/internal_signup_login.go
pkg/auth/handler/webapp/authflowv2/login.go
pkg/auth/handler/webapp/authflowv2/viewmodels/oauth_error.go
resources/authgear/templates/en/web/authflowv2/login.html
resources/authgear/templates/en/web/authflowv2/signup.html

Display oauth conflict error in alert message

---

authui/src/authflowv2/customSelect.ts
authui/src/authflowv2/phoneInput.ts

Fix phone input is trying to set value before options are loaded

---

pkg/lib/deps/providers.go
pkg/util/sentry/hook.go

Fix sentry hub is nil in task context

---

pkg/lib/authn/otp/template.go
pkg/lib/web/html.go
pkg/util/template/resource.go
pkg/util/template/resource_fs.go

Prevent overriding html in app fs except email htmls

---

pkg/portal/graphql/app.go
portal/src/graphql/portal/mutations/updateAppTemplatesMutation.generated.ts
portal/src/graphql/portal/mutations/updateAppTemplatesMutation.graphql

Do not list all resources on updating translations or resources

---

resources/authgear/templates/en/web/authflow_enter_password.html
resources/authgear/templates/en/web/authflow_login.html
resources/authgear/templates/en/web/authflowv2/enter_password.html
resources/authgear/templates/en/web/authflowv2/login.html
resources/authgear/templates/en/web/authflowv2/signup.html
resources/authgear/templates/en/web/enter_password.html
resources/authgear/templates/en/web/login.html

Fix login id not autofilled on iOS

---

resources/authgear/templates/en/translation.json
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

Update translation for unsupported passkey

---

portal/src/graphql/portal/LoginMethodConfigurationScreen.tsx
portal/src/types.ts

Only show combine signup login flow toggle if v2 ui is enabled

---

resources/authgear/templates/en/web/authflowv2/__html_head.html

Preload fonts in v2 ui

---

pkg/util/template/translation.go
portal/src/graphql/portal/LocalizationConfigurationScreen.tsx
portal/src/graphql/portal/ManageLanguageWidget.tsx
portal/src/graphql/portal/UISettingsScreen.tsx

Fix portal handling for empty default localization

---

portal/src/AppRoot.tsx
portal/src/CommandBarContainer.module.css
portal/src/FormContainer.tsx
portal/src/FormContainerBase.tsx
portal/src/RoleAndGroupsFormLayout.module.css
portal/src/RoleAndGroupsFormLayout.tsx
portal/src/ScreenHeader.module.css
portal/src/graphql/adminapi/AddRolesScreen.tsx
portal/src/graphql/adminapi/RolesScreen.tsx
portal/src/graphql/adminapi/mutations/createRoleMutation.ts
portal/src/graphql/portal/EditOAuthClientScreen.module.css
portal/src/graphql/portal/Web3ConfigurationScreen.tsx
portal/src/hook/useSimpleForm.ts
portal/src/index.css
portal/src/locale-data/en.json
portal/src/model/role.ts

Portal - Implement create roles

---

docs/specs/api-resolver.md
docs/specs/hook.md
docs/specs/roles-groups.md

Specify roles and groups

---

portal/src/graphql/adminapi/DeleteRoleDialog.tsx
portal/src/graphql/adminapi/RolesList.tsx
portal/src/graphql/adminapi/mutations/deleteRoleMutation.ts
portal/src/locale-data/en.json

ref #3908 
require #3938 
pending question https://www.figma.com/file/bhUac10bqlsRVXF5HiwCjW?node-id=67:5533&mode=design#726975676
https://github.com/authgear/authgear-server/assets/63200569/83f76e84-fd95-4776-ad61-90676d950544

Implement delete role 

---

portal/src/StyledTagPicker.module.css
portal/src/StyledTagPicker.tsx

ref #3906 
https://github.com/authgear/authgear-server/assets/63200569/a10fe0db-d9de-406a-be6f-69e19e621d50

Add StyledTagPicker

---

pkg/auth/deps.go
pkg/auth/handler/webapp/viewmodels/base.go
pkg/auth/handler/webapp/viewmodels/deps.go
pkg/auth/wire_gen.go
resources/authgear/templates/en/web/__error.html
resources/authgear/templates/en/web/authflowv2/__error.html

Log unknown viewmodel error

---

portal/src/StyledTagPicker.module.css
portal/src/StyledTagPicker.tsx
portal/src/components/roles-and-groups/AddRoleGroupsDialog.module.css
portal/src/components/roles-and-groups/AddRoleGroupsDialog.tsx
portal/src/components/roles-and-groups/DeleteRoleGroupDialog.tsx
portal/src/graphql/adminapi/RoleDetailsScreen.tsx
portal/src/graphql/adminapi/RolesScreen.tsx
portal/src/locale-data/en.json

ref #3905 
https://github.com/authgear/authgear-server/assets/34942210/197e666b-e1df-44ce-915d-bf2ba157279a

Implement add role to group

---

portal/src/RoleAndGroupsLayout.module.css
portal/src/RoleAndGroupsLayout.tsx
portal/src/components/roles-and-groups/RolesEmptyView.tsx
portal/src/graphql/adminapi/AddRolesScreen.tsx
portal/src/graphql/adminapi/GroupsScreen.module.css
portal/src/graphql/adminapi/GroupsScreen.tsx
portal/src/graphql/adminapi/RoleDetailsScreen.tsx
portal/src/graphql/adminapi/RolesScreen.module.css
portal/src/graphql/adminapi/RolesScreen.tsx
portal/src/locale-data/en.json

Add group screen empty state

---

portal/src/components/roles-and-groups/DeleteRoleGroupDialog.tsx
portal/src/graphql/adminapi/DeleteGroupDialog.tsx
portal/src/graphql/adminapi/DeleteRoleDialog.tsx
portal/src/graphql/adminapi/GroupsList.module.css
portal/src/graphql/adminapi/GroupsList.tsx
portal/src/graphql/adminapi/GroupsScreen.tsx
portal/src/graphql/adminapi/RolesList.tsx
portal/src/graphql/adminapi/mutations/deleteGroupMutation.ts
portal/src/hook/useSnapshotData.ts
portal/src/locale-data/en.json

ref #3911 #3912 
require #3955

Implement Groups List and Group Delete

---

portal/src/AppRoot.tsx
portal/src/graphql/adminapi/AddGroupScreen.tsx
portal/src/graphql/adminapi/AddRoleScreen.tsx
portal/src/graphql/adminapi/RoleDetailsScreen.tsx
portal/src/graphql/adminapi/mutations/createGroupMutation.ts
portal/src/graphql/adminapi/mutations/createRoleMutation.ts
portal/src/graphql/adminapi/mutations/updateRoleMutation.ts
portal/src/locale-data/en.json
portal/src/model/group.ts
portal/src/model/role.ts

ref #3910 
requires https://github.com/authgear/authgear-server/pull/3963

Implement create group screen

---

portal/src/AppRoot.tsx
portal/src/graphql/adminapi/GroupDetailsScreen.tsx
portal/src/graphql/adminapi/node.ts
portal/src/graphql/adminapi/query/groupQuery.ts
portal/src/locale-data/en.json

Setup group details screen

---

portal/src/components/roles-and-groups/DeleteGroupDialog.tsx
portal/src/components/roles-and-groups/GroupDetailsSettingsForm.tsx
portal/src/graphql/adminapi/GroupDetailsScreen.tsx
portal/src/graphql/adminapi/GroupsList.tsx
portal/src/graphql/adminapi/mutations/updateGroupMutation.ts
portal/src/locale-data/en.json

ref #3913 
requires https://github.com/authgear/authgear-server/pull/3971

Implement group details settings tab

---

pkg/lib/feature/forgotpassword/service.go

Fix an edge case that related to test mode and account recovery

---

pkg/portal/graphql/viewer.go
pkg/portal/loader/user.go
pkg/portal/model/user.go
portal/src/ExternalLink.tsx
portal/src/ScreenHeader.module.css
portal/src/ScreenHeader.tsx
portal/src/ScreenNav.module.css
portal/src/ScreenNav.tsx
portal/src/graphql/portal/globalTypes.generated.ts
portal/src/graphql/portal/query/viewerQuery.generated.ts
portal/src/graphql/portal/query/viewerQuery.graphql
portal/src/graphql/portal/schema.graphql
portal/src/locale-data/en.json

ref #3872 
**Mobile**
**Desktop**

Add feedback and discuss links to portal header

---

authui/src/authflowv2/components/alert-message.css
pkg/auth/handler/webapp/authflowv2/viewmodels/password_input_error.go
resources/authgear/templates/en/web/authflowv2/change_password.html
resources/authgear/templates/en/web/authflowv2/change_password_success.html
resources/authgear/templates/en/web/authflowv2/create_password.html
resources/authgear/templates/en/web/authflowv2/enter_password.html
resources/authgear/templates/en/web/authflowv2/forgot_password_link_sent.html
resources/authgear/templates/en/web/authflowv2/oob_otp_link.html
resources/authgear/templates/en/web/authflowv2/prompt_create_passkey.html
resources/authgear/templates/en/web/authflowv2/reset_password.html
resources/authgear/templates/en/web/authflowv2/reset_password_success.html
resources/authgear/templates/en/web/authflowv2/select_account.html
resources/authgear/templates/en/web/authflowv2/setup_totp.html
resources/authgear/templates/en/web/authflowv2/terminate_other_sessions.html
resources/authgear/templates/en/web/authflowv2/verify_login_link.html
resources/authgear/templates/en/web/authflowv2/view_recovery_code.html

Show unknown error on screen if any

---

portal/src/graphql/portal/LoginMethodConfigurationScreen.tsx
portal/src/graphql/portal/MFAConfigurationScreen.tsx
portal/src/graphql/portal/PasswordSettings.tsx
portal/src/locale-data/en.json
portal/src/types.ts

Add password expiry config to portal 

---

docs/specs/authentication-flow.md

ref #3949
Implementation actually does not use id field at all

Rename id field in authflow doc

---

pkg/lib/rolesgroups/store_group.go
pkg/lib/rolesgroups/store_role.go

Fix group and role search behaviour

---

portal/src/CommandBarContainer.module.css
portal/src/FormContainer.tsx
portal/src/components/roles-and-groups/dialog/AddUserGroupsDialog.tsx
portal/src/components/roles-and-groups/dialog/DeleteUserGroupDialog.tsx
portal/src/components/roles-and-groups/list/UserDetailsScreenGroupListContainer.tsx
portal/src/components/roles-and-groups/list/UserGroupsList.module.css
portal/src/components/roles-and-groups/list/UserGroupsList.tsx
portal/src/graphql/adminapi/UserDetailsScreen.module.css
portal/src/graphql/adminapi/UserDetailsScreen.tsx
portal/src/graphql/adminapi/query/userQuery.generated.ts
portal/src/graphql/adminapi/query/userQuery.graphql
portal/src/graphql/adminapi/query/userQuery.ts
portal/src/locale-data/en.json

ref #3980 
pending question: do we need to respect user page's grid layout

Implement User groups tab

---

portal/src/components/roles-and-groups/empty-view/RolesAndGroupsEmptyView.module.css
portal/src/components/roles-and-groups/list/GroupsList.tsx
portal/src/components/roles-and-groups/list/RolesList.tsx
portal/src/components/roles-and-groups/list/common/RolesAndGroupsBaseList.tsx
portal/src/graphql/adminapi/GroupDetailsScreen.tsx
portal/src/graphql/adminapi/GroupsScreen.tsx
portal/src/graphql/adminapi/RoleDetailsScreen.tsx
portal/src/graphql/adminapi/query/groupQuery.ts
portal/src/graphql/adminapi/query/roleQuery.ts
portal/src/locale-data/en.json

Some roles and groups related fixes

---

portal/src/locale-data/en.json

Update copy writings of groups empty view

---

migrations/authgear/20240318191059-add_indexes_to_foreign_key_columns.sql

Create indexes for all foreign key columns

---

pkg/api/errors.go
pkg/lib/authenticationflow/declarative/node_login_flow_change_password.go
pkg/lib/interaction/nodes/change_password.go
resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/__error.html
resources/authgear/templates/en/web/authflowv2/__error.html
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

Block force change password with previous password

---

portal/src/graphql/portal/LocalizationConfigurationScreen.tsx
portal/src/graphql/portal/ManageLanguageWidget.module.css
portal/src/graphql/portal/ManageLanguageWidget.tsx
portal/src/graphql/portal/ReplaceLanguagesConfirmationDialog.tsx
portal/src/graphql/portal/UISettingsScreen.tsx
portal/src/locale-data/en.json

ref #3627
**Hint on new languages**
**Dropdown items**
**Confirmation when existing languages will be removed**

Add hint and confirmation for updating languages in portal

---

cmd/authgear/background/wire_gen.go
cmd/authgear/elasticsearch/wire_gen.go
pkg/admin/graphql/query.go
pkg/admin/wire_gen.go
pkg/auth/wire_gen.go
pkg/lib/authn/user/model.go
pkg/lib/authn/user/store.go
pkg/lib/infra/db/sql_builder.go
pkg/resolver/wire_gen.go
portal/src/graphql/adminapi/globalTypes.generated.ts
portal/src/graphql/adminapi/schema.graphql

Support filter users by role keys

---

pkg/admin/graphql/query.go
pkg/lib/authn/user/model.go
pkg/lib/authn/user/store.go
pkg/lib/infra/db/sql_builder.go
portal/src/components/users/GroupsFilterDropdown.tsx
portal/src/components/users/RolesFilterDropdown.tsx
portal/src/components/users/UsersFilterBar.module.css
portal/src/components/users/UsersFilterBar.tsx
portal/src/graphql/adminapi/UsersScreen.module.css
portal/src/graphql/adminapi/UsersScreen.tsx
portal/src/graphql/adminapi/globalTypes.generated.ts
portal/src/graphql/adminapi/query/usersListQuery.generated.ts
portal/src/graphql/adminapi/query/usersListQuery.graphql
portal/src/graphql/adminapi/schema.graphql
portal/src/locale-data/en.json

ref #3986 
requires https://github.com/authgear/authgear-server/pull/4014

Implement roles and groups filtering

---

portal/src/StyledTagPicker.tsx

ref #3969
https://github.com/authgear/authgear-server/assets/63200569/c1a1a264-f752-4404-8417-8c1193205a9f

Set tag picker callout width equals to tag picker

---

pkg/lib/rolesgroups/store_group_user.go
pkg/lib/rolesgroups/store_role_user.go
portal/src/components/roles-and-groups/list/GroupRolesList.tsx
portal/src/components/roles-and-groups/list/GroupsList.tsx
portal/src/components/roles-and-groups/list/RoleGroupsList.tsx
portal/src/components/roles-and-groups/list/RolesList.tsx
portal/src/components/roles-and-groups/list/UserGroupsList.tsx
portal/src/components/roles-and-groups/list/UserRolesList.tsx
portal/src/components/roles-and-groups/list/common/ActionButtonCell.tsx
portal/src/graphql/adminapi/UsersList.tsx
portal/src/graphql/adminapi/UsersScreen.tsx
portal/src/graphql/adminapi/query/usersListQuery.generated.ts
portal/src/graphql/adminapi/query/usersListQuery.graphql
portal/src/locale-data/en.json

Add columns roles and groups to users list

---

portal/src/graphql/adminapi/UsersList.module.css
portal/src/graphql/adminapi/UsersList.tsx

ref #3982
https://github.com/authgear/authgear-server/assets/63200569/b8a7229c-2b7a-467d-8298-612c50e8b3c7

Pin the first column of Users List

---

docs/specs/user-import.md

Specify user import

---

portal/src/graphql/adminapi/UsersScreen.tsx

Fix isSearch criteria

---

portal/src/graphql/adminapi/UsersList.tsx

Pass missing column data to cell renderer

---

pkg/util/intlresource/prepare.go
pkg/util/template/translation_test.go

Fix fallback translation not resolving custom level translation

---

pkg/portal/deps.go
pkg/portal/graphql/app_mutation.go
pkg/portal/graphql/context.go
pkg/portal/model/onboard.go
pkg/portal/service/deps.go
pkg/portal/service/onboard.go
pkg/portal/wire_gen.go
portal/src/graphql/portal/CreateProjectScreen.tsx
portal/src/graphql/portal/globalTypes.generated.ts
portal/src/graphql/portal/mutations/createAppMutation.generated.ts
portal/src/graphql/portal/mutations/createAppMutation.graphql
portal/src/graphql/portal/mutations/createAppMutation.ts
portal/src/graphql/portal/schema.graphql
portal/src/locale-data/en.json

Accept phone number on create project

---

portal/src/locale-data/en.json

Update role/group create validation error

---

portal/src/graphql/adminapi/GroupsScreen.tsx
portal/src/graphql/adminapi/RolesScreen.tsx

Show error for role/group list query

---

pkg/auth/handler/webapp/controller.go
pkg/auth/handler/webapp/sso_callback.go
pkg/auth/wire_gen.go

Fix sso cannot be used in interaction

---

pkg/api/apierrors/error.go
pkg/auth/deps.go
pkg/auth/routes.go
pkg/auth/wire_gen.go
pkg/auth/wire_middleware.go
pkg/lib/authenticationflow/deps.go
pkg/lib/authenticationflow/rate_limit_middleware.go
pkg/lib/config/authentication_flow.go
pkg/lib/config/authentication_flow_rate_limits.go
pkg/lib/config/testdata/default_config.yaml

Implement RateLimitMiddleware

---

portal/src/graphql/adminapi/AddUserScreen.tsx

Fix create user error

---

portal/src/error/error.ts
portal/src/graphql/adminapi/AddGroupScreen.tsx
portal/src/graphql/adminapi/AddRoleScreen.tsx
portal/src/locale-data/en.json

Update error message of duplicated role/group key

---

portal/src/components/roles-and-groups/form/GroupDetailsSettingsForm.tsx
portal/src/components/roles-and-groups/form/RoleAndGroupsFormContainer.tsx
portal/src/graphql/adminapi/AddGroupScreen.tsx
portal/src/graphql/adminapi/AddRoleScreen.tsx
portal/src/graphql/adminapi/RoleDetailsScreen.tsx

Disable create button when required fields are not filled

---

portal/src/DefaultButton.tsx

Set DefaultButton default bg color to white

---

pkg/admin/graphql/user_mutation.go

Fix nil dereference in delete user

---

pkg/admin/graphql/query.go
pkg/lib/rolesgroups/queries.go
pkg/lib/rolesgroups/store_group.go
pkg/lib/rolesgroups/store_role.go
portal/src/components/roles-and-groups/dialog/AddGroupRolesDialog.tsx
portal/src/components/roles-and-groups/dialog/AddRoleGroupsDialog.tsx
portal/src/components/roles-and-groups/dialog/AddTagsDialog.tsx
portal/src/components/roles-and-groups/dialog/AddUserGroupsDialog.tsx
portal/src/components/roles-and-groups/dialog/AddUserRolesDialog.tsx
portal/src/graphql/adminapi/UsersList.module.css
portal/src/graphql/adminapi/globalTypes.generated.ts
portal/src/graphql/adminapi/query/groupsListQuery.generated.ts
portal/src/graphql/adminapi/query/groupsListQuery.graphql
portal/src/graphql/adminapi/query/rolesListQuery.generated.ts
portal/src/graphql/adminapi/query/rolesListQuery.graphql
portal/src/graphql/adminapi/schema.graphql

Resolve suggestions on open tag picker dialog

---

pkg/portal/graphql/context.go
pkg/portal/graphql/query.go
pkg/portal/graphql/viewer.go
pkg/portal/model/user.go
pkg/portal/wire_gen.go
portal/src/PhoneTextField.tsx
portal/src/graphql/portal/CreateProjectScreen.tsx
portal/src/graphql/portal/globalTypes.generated.ts
portal/src/graphql/portal/query/viewerQuery.generated.ts
portal/src/graphql/portal/query/viewerQuery.graphql
portal/src/graphql/portal/schema.graphql

Use geoip for create project phone input

---

portal/src/PhoneTextField.tsx

Fix initialcountry prop not applied for phone input

---

portal/src/locale-data/en.json

Update portal admin invite copywriting

---

pkg/portal/graphql/app_mutation.go

Assign phone before create app transaction

---

portal/src/PhoneTextField.tsx
portal/src/graphql/adminapi/PhoneScreen.tsx
portal/src/graphql/adminapi/UserProfileForm.tsx
portal/src/graphql/portal/CreateProjectScreen.tsx
portal/src/util/phone.test.ts
portal/src/util/phone.ts

ref https://github.com/authgear/authgear-server/issues/3873

Expose partial phone number

---

pkg/lib/interaction/intents/verify_identity.go
pkg/lib/interaction/nodes/remove_authenticator.go
pkg/lib/interaction/nodes/remove_identity.go
pkg/lib/interaction/nodes/update_identity_end.go

Guard against removing other user's authenticator

---

pkg/admin/routes.go
pkg/auth/routes.go
pkg/images/routes.go
pkg/portal/routes.go
pkg/resolver/routes.go
pkg/util/httputil/permissions_policy.go
pkg/util/httputil/permissions_policy_header.go
pkg/util/httputil/permissions_policy_header_test.go
pkg/util/httputil/permissions_policy_test.go

Add permissions-policy header

---

portal/src/graphql/adminapi/UserDetailsScreen.tsx
portal/src/graphql/adminapi/UserDetailsSession.tsx
portal/src/locale-data/en.json

Add tooltip for session's client id column

---

docs/specs/account-linking.md
docs/specs/authentication-flow.md
docs/specs/idp-account-linking.md
docs/specs/sso-providers.md

Specify account linking

---

e2e/Makefile
e2e/README.md
e2e/cmd/dumpschema/main.go
e2e/pkg/e2eclient/client.go
e2e/pkg/e2eclient/types.go
e2e/pkg/testrunner/matcher.go
e2e/pkg/testrunner/matcher_test.go
e2e/pkg/testrunner/models.go
e2e/pkg/testrunner/runner.go
e2e/pkg/testrunner/schema.go
e2e/pkg/testrunner/testcase.go
e2e/run.sh
e2e/schema.json
e2e/tests/authflow_selection/custom_flow.test.yaml
e2e/tests/authflow_selection/custom_group.test.yaml
e2e/tests/authflow_selection/default_config.test.yaml
e2e/tests/issue_3583/test.yaml
e2e/tests/issue_3585/test.yaml
e2e/tests/issue_3708/test.yaml
e2e/tests/login/test.yaml
e2e/tests/oauth/adfs.test.yaml
e2e/tests/oauth/facebook.test.yaml
e2e/tests/oauth/google.test.yaml
e2e/tests/receipe_1/test.yaml
e2e/tests/signup/test.yaml

Add e2e test cases for flow allowlist

---

pkg/lib/authenticationflow/declarative/intent_account_linking_oauth.go
pkg/lib/authenticationflow/declarative/intent_signup_flow.go
pkg/lib/authenticationflow/declarative/milestone.go
pkg/lib/authenticationflow/declarative/node_do_create_user.go

Address comments in https://github.com/authgear/authgear-server/pull/4142

Some account linking fixes

---

posthog/posthog.ts

Fix some problems in posthog

---

cmd/portal/cmd/cmdanalytic/analytic.go
cmd/portal/cmd/cmdanalytic/posthog.go
pkg/lib/analytic/appdb_store.go
pkg/lib/analytic/posthog.go

Add a command to set user properties on Posthog

---

resources/authgear/templates/en/translation.json
scripts/python/generate_translations.py

Use "Türkiye" as the English name

---

pkg/lib/authenticationflow/service_test.go
pkg/lib/authenticationflow/session.go

Fix accept-language is ignored in authflow

---

e2e/pkg/testrunner/cmd.go
e2e/pkg/testrunner/testcase.go
e2e/run.sh
e2e/tests/account_linking/email_users.json
e2e/tests/account_linking/error.test.yaml
e2e/tests/account_linking/login_and_link.test.yaml
e2e/tests/account_linking/login_and_link_create_authenticator_before.test.yaml
e2e/tests/account_linking/login_and_link_identification_after.test.yaml
e2e/tests/account_linking/login_and_link_identification_before.test.yaml
e2e/tests/account_linking/login_and_link_nested_step.test.yaml
e2e/tests/account_linking/login_and_link_simple.test.yaml

ref DEV-1229
ref https://github.com/authgear/authgear-server/issues/4143
requires https://github.com/authgear/authgear-server/pull/4166

Add e2e tests to account linking

---

docs/specs/authentication-flow-api-reference.md
e2e/tests/account_linking/error.test.yaml
e2e/tests/account_linking/login_and_link_create_authenticator_before.test.yaml
e2e/tests/account_linking/login_and_link_identification_after.test.yaml
e2e/tests/account_linking/login_and_link_identification_before.test.yaml
e2e/tests/account_linking/login_and_link_nested_step.test.yaml
e2e/tests/account_linking/login_and_link_simple.test.yaml
e2e/tests/account_linking/overrides.test.yaml
pkg/auth/handler/webapp/authflowv2/account_linking.go
pkg/lib/authenticationflow/declarative/data_account_linking.go
pkg/lib/authenticationflow/declarative/intent_account_linking.go
pkg/lib/authenticationflow/declarative/intent_check_conflict_and_create_identity.go
pkg/lib/authenticationflow/declarative/intent_promote_flow.go
pkg/lib/authenticationflow/declarative/intent_signup_flow.go
pkg/lib/authenticationflow/declarative/milestone.go
pkg/lib/authenticationflow/declarative/node_promote_identity_login_id.go
pkg/lib/authenticationflow/declarative/node_promote_identity_oauth.go
pkg/lib/authenticationflow/declarative/node_use_account_linking_identification.go
pkg/lib/authenticationflow/declarative/utils_account_linking.go
pkg/lib/config/account_linking.go
pkg/lib/config/authentication_flow.go
pkg/lib/config/config.go
pkg/lib/config/schema_test.go
pkg/lib/config/testdata/account_linking_tests.yaml
pkg/lib/config/testdata/default_config.yaml
resources/authgear/templates/en/web/authflowv2/account_linking.html

ref DEV-1246
ref https://github.com/authgear/authgear-server/issues/4167
requires https://github.com/authgear/authgear-server/pull/4192

Update account linking config interface according to latest spec

---

pkg/auth/handler/webapp/authflowv2/internal_signup_login.go
resources/authgear/templates/en/web/authflowv2/signup.html

ref DEV-1250
Passkey in signup login flow was already supported, what is missing is we didn't handle passkey in default ui.

Support passkey in default ui in signup login flow

---

cmd/authgear/elasticsearch/deps.go
cmd/authgear/elasticsearch/reindex.go
cmd/authgear/elasticsearch/wire_gen.go

Fix concurrency issue on updating user last_indexed_at

---

.tool-versions
cmd/authgear/Dockerfile
cmd/portal/Dockerfile
go.mod

Upgrade go to 1.21.10

---

pkg/api/apierrors/skip_logging.go
pkg/api/apierrors/skip_logging_test.go

Further reduce noise

---

portal/package-lock.json
portal/package.json
portal/src/ScreenHeader.tsx
portal/src/index.html
portal/src/index.tsx
portal/src/locale-data/en.json

Move Osano widget to header nav

---

portal/src/error/parse.ts
portal/src/graphql/portal/LoginMethodConfigurationScreen.tsx
portal/src/graphql/portal/UISettingsScreen.tsx
portal/src/locale-data/en.json

Add specific error message for ui/phone_input/allowlist

---

pkg/lib/authn/otp/errors.go
pkg/lib/authn/otp/sender.go
resources/authgear/templates/de/translation.json
resources/authgear/templates/el/translation.json
resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/__error.html
resources/authgear/templates/en/web/authflowv2/__error.html
resources/authgear/templates/es-419/translation.json
resources/authgear/templates/es-ES/translation.json
resources/authgear/templates/es/translation.json
resources/authgear/templates/fil/translation.json
resources/authgear/templates/fr/translation.json
resources/authgear/templates/id/translation.json
resources/authgear/templates/it/translation.json
resources/authgear/templates/ja/translation.json
resources/authgear/templates/ko/translation.json
resources/authgear/templates/ms/translation.json
resources/authgear/templates/nl/translation.json
resources/authgear/templates/pl/translation.json
resources/authgear/templates/pt-BR/translation.json
resources/authgear/templates/pt-PT/translation.json
resources/authgear/templates/pt/translation.json
resources/authgear/templates/th/translation.json
resources/authgear/templates/vi/translation.json
resources/authgear/templates/zh-CN/translation.json
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

Show error message if WhatsApp is not configured

---

migrations/authgear/20240516162438-add_password_expire_after.sql
pkg/lib/authn/authenticator/password/expiry.go
pkg/lib/authn/authenticator/password/expiry_test.go
pkg/lib/authn/authenticator/password/provider.go
pkg/lib/authn/authenticator/password/store.go
pkg/lib/authn/authenticator/password_authenticator.go
pkg/lib/authn/authenticator/password_spec.go
pkg/lib/userimport/model.go
pkg/lib/userimport/model_test.go
pkg/lib/userimport/service.go
pkg/util/validation/formats.go
pkg/util/validation/formats_test.go

Support marking password as expired on user import

---

authui/src/tailwind-light-theme.css
authui/src/tailwind.css
resources/authgear/templates/de/translation.json
resources/authgear/templates/el/translation.json
resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/enter_login_id.html
resources/authgear/templates/en/web/settings.html
resources/authgear/templates/en/web/settings_identity.html
resources/authgear/templates/es-419/translation.json
resources/authgear/templates/es-ES/translation.json
resources/authgear/templates/es/translation.json
resources/authgear/templates/fil/translation.json
resources/authgear/templates/fr/translation.json
resources/authgear/templates/id/translation.json
resources/authgear/templates/it/translation.json
resources/authgear/templates/ja/translation.json
resources/authgear/templates/ko/translation.json
resources/authgear/templates/ms/translation.json
resources/authgear/templates/nl/translation.json
resources/authgear/templates/pl/translation.json
resources/authgear/templates/pt-BR/translation.json
resources/authgear/templates/pt-PT/translation.json
resources/authgear/templates/pt/translation.json
resources/authgear/templates/th/translation.json
resources/authgear/templates/vi/translation.json
resources/authgear/templates/zh-CN/translation.json
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

Update ui of delete login id button

---

e2e/tests/account_linking/login_and_link_identification_after.test.yaml
e2e/tests/account_linking/login_and_link_skip_create_oob_otp.test.yaml
e2e/tests/signup/secondary_oob.test.yaml
pkg/lib/authenticationflow/declarative/data_create_authenticator_option.go
pkg/lib/authenticationflow/declarative/intent_create_authenticator_oob_otp.go
pkg/lib/authenticationflow/declarative/utils_create_authenticator.go

Fix secondary oob otp setup always skipped

---

resources/authgear/templates/en/messages/translation.json
resources/authgear/templates/en/messages/verification_sms.txt

Remove an extra period in English SMS verification template

---

.github/workflows/ci.yaml
.tool-versions
Makefile
cmd/authgear/Dockerfile
cmd/portal/Dockerfile
go.mod
go.sum

Ensure important modules are up-to-date

---

portal/src/AppRoot.tsx

Fix wrong redirection on url group `/authentication`

---

portal/src/AppRoot.tsx
portal/src/ScreenNav.tsx
portal/src/graphql/portal/CustomTextConfigurationScreen.module.css
portal/src/graphql/portal/CustomTextConfigurationScreen.tsx
portal/src/graphql/portal/GetStartedScreen.tsx
portal/src/graphql/portal/LocalizationConfigurationScreen.module.css
portal/src/graphql/portal/LocalizationConfigurationScreen.tsx
portal/src/graphql/portal/LoginMethodConfigurationScreen.tsx
portal/src/graphql/portal/ManageLanguageWidget.tsx
portal/src/graphql/portal/UISettingsScreen.tsx
portal/src/graphql/portal/VerifyDomainScreen.tsx
portal/src/hook/useResourceForm.ts
portal/src/locale-data/en.json

ref #4290 
ref #4291 
ref #4334 
ref DEV-1381
ref DEV-1382
ref DEV-1418
@tung2744

Restructure localisation resources setup pages

---

pkg/auth/wire_gen.go
pkg/lib/config/captcha.go
pkg/lib/config/schema_test.go
pkg/lib/config/secret.go
pkg/lib/config/secret_captcha.go
pkg/lib/config/testdata/captcha_tests.yaml
pkg/lib/config/testdata/parse_secret_tests.yaml
pkg/lib/config/testdata/secret_config_validate_tests.yaml
pkg/lib/deps/deps_config.go
pkg/lib/feature/captcha/provider.go
pkg/lib/infra/captcha/cloudflare.go

ref #4325 
@louischan-oursky thanks, copied items from issue below
>  Keep the old configuration intact
>  Introduce the new configuration
>>        The Go structs
>>        The JSON schema
>>        Write tests to test for valid and invalid configurations

Implement new captcha configuration

---

portal/src/OnboardingSurveyScreen.tsx
portal/src/graphql/portal/CreateProjectScreen.tsx

https://linear.app/authgear/issue/DEV-1378/use-company-name-for-new-project-name
| in onboarding survey | in create project |
| - | - |
| ![image](https://github.com/authgear/authgear-server/assets/68701054/0463fb72-4a05-498a-b258-0e7896331d11) | ![image](https://github.com/authgear/authgear-server/assets/68701054/17761677-05c8-4b39-89dc-b67753df961f) |

Provide company name in project name

---

authui/package-lock.json
authui/package.json
portal/package-lock.json

Fix package vulnerability

---

pkg/lib/config/config.go
pkg/lib/config/secret.go
pkg/lib/config/testdata/captcha_tests.yaml
pkg/lib/config/testdata/config_tests.yaml
pkg/lib/config/testdata/secret_config_validate_tests.yaml

Add test cases to check captcha credential 

---

go.mod
pkg/auth/webapp/csrf_middleware.go

Improve CSRF error tracking

---

pkg/portal/graphql/context.go
pkg/portal/graphql/query.go
pkg/portal/graphql/viewer.go
pkg/portal/model/user.go
pkg/portal/service/onboard.go
portal/src/OnboardingRedirect.tsx
portal/src/OnboardingSurveyScreen.tsx
portal/src/graphql/portal/AppsScreen.tsx
portal/src/graphql/portal/globalTypes.generated.ts
portal/src/graphql/portal/query/viewerQuery.generated.ts
portal/src/graphql/portal/query/viewerQuery.graphql
portal/src/graphql/portal/schema.graphql

#4345 
https://linear.app/authgear/issue/DEV-1422/redirect-new-users-to-onboarding-survey-after-signing-up
demo: (note my local branch was not up to date, so company name was not filled in project name)
https://github.com/authgear/authgear-server/assets/68701054/06807bdc-f248-44e6-a22a-59d3d9130ce6

Change navigation uri in OnboardingRedirect

---

pkg/admin/facade/oauth.go
pkg/api/model/claims.go
pkg/auth/handler/webapp/tester.go
pkg/auth/wire_gen.go
pkg/lib/config/oauth.go
pkg/lib/oauth/grant_offline.go
pkg/lib/oauth/handler/handler_anonymous_user.go
pkg/lib/oauth/handler/handler_token.go
pkg/lib/oauth/handler/service_token.go
pkg/lib/oauth/oidc/id_token.go
pkg/lib/oauth/oidc/id_token_test.go
pkg/lib/oauth/oidc/scopes.go
pkg/lib/oauth/protocol/token.go
pkg/lib/oauth/redis/store.go
pkg/lib/oauth/scope.go
pkg/lib/oauth/store_grant.go

Issue device secret in token endpoint

---

pkg/lib/config/configsource/resources.go
pkg/lib/config/configsource/resources_test.go

Disallow changing client id in authgear yaml

---

portal/src/AppRoot.tsx
portal/src/ScreenNav.tsx
portal/src/graphql/portal/CustomTextConfigurationScreen.tsx
portal/src/graphql/portal/GetStartedScreen.tsx
portal/src/locale-data/en.json

Update portal copywritings

---

authui/src/authflowv2/components/widget.css
resources/authgear/templates/en/web/authflowv2/__page_frame.html

Fix mobile view background color

---

docs/specs/oidc.md
pkg/auth/deps.go
pkg/auth/handler/webapp/settings_delete_account.go
pkg/auth/handler/webapp/settings_delete_account_success.go
pkg/auth/webapp/success_page_middleware.go
pkg/auth/wire_gen.go
pkg/lib/endpoints/endpoints.go
pkg/lib/oauth/handler/handler_authz.go
pkg/lib/oauth/handler/handler_authz_mock_test.go
pkg/lib/oauth/oidc/ui.go
resources/authgear/templates/en/web/settings_delete_account_success.html

Ref DEV-1232
Demo with flutter sdk:
https://github.com/authgear/authgear-sdk-flutter/pull/61
https://github.com/authgear/authgear-server/assets/11769136/b51bf53e-ffbd-466d-bfdb-4fbdc5137214

Add delete_account settings action

---

.tool-versions
cmd/authgear/Dockerfile
cmd/portal/Dockerfile
custombuild/cmd/authgearx/Dockerfile
custombuild/cmd/portalx/Dockerfile
custombuild/go.mod
go.mod

https://pkg.go.dev/vuln/GO-2024-2963

Update go to 1.22.5 to fix vuln

---

pkg/lib/web/image.go
pkg/lib/web/image_test.go
pkg/lib/web/static_assets.go
pkg/portal/appresource/manager.go
pkg/portal/appresource/manager_test.go
pkg/util/resource/size_limit_descriptor.go
portal/src/graphql/portal/DesignScreen/form.ts
portal/src/util/operators.test.ts
portal/src/util/operators.ts

Increase background image size limit in authui v2 customisation

---

authui/src/authflowv2/components/widget.css

Fix authui layout become narrowed

---

authui/src/authflowv2/components.css
authui/src/authflowv2/components/brand-logo.css
authui/src/authflowv2/components/screen-logo-layout.css
authui/src/authflowv2/components/screen-title-description.css
authui/src/authflowv2/components/widget.css
resources/authgear/templates/en/web/authflowv2/__error_page_layout.html
resources/authgear/templates/en/web/authflowv2/__lockout.html
resources/authgear/templates/en/web/authflowv2/account_linking.html
resources/authgear/templates/en/web/authflowv2/account_status.html
resources/authgear/templates/en/web/authflowv2/change_password_success.html
resources/authgear/templates/en/web/authflowv2/enter_oob_otp.html
resources/authgear/templates/en/web/authflowv2/enter_password.html
resources/authgear/templates/en/web/authflowv2/enter_recovery_code.html
resources/authgear/templates/en/web/authflowv2/enter_totp.html
resources/authgear/templates/en/web/authflowv2/forgot_password.html
resources/authgear/templates/en/web/authflowv2/forgot_password_link_sent.html
resources/authgear/templates/en/web/authflowv2/forgot_password_otp.html
resources/authgear/templates/en/web/authflowv2/login.html
resources/authgear/templates/en/web/authflowv2/oob_otp_link.html
resources/authgear/templates/en/web/authflowv2/prompt_create_passkey.html
resources/authgear/templates/en/web/authflowv2/reset_password_success.html
resources/authgear/templates/en/web/authflowv2/select_account.html
resources/authgear/templates/en/web/authflowv2/setup_totp_verify.html
resources/authgear/templates/en/web/authflowv2/signup.html
resources/authgear/templates/en/web/authflowv2/terminate_other_sessions.html
resources/authgear/templates/en/web/authflowv2/use_passkey.html
resources/authgear/templates/en/web/authflowv2/wechat.html

- The default logo height = 40px & max-width: 350px
- Adjusted padding top of container (for margin-top: 24px)
- Introduce & Apply new layout (for margin bottom: 32px)

Dev 1428 update logo size in authui v2

---

pkg/lib/oauth/grant_code.go
pkg/lib/oauth/handler/handler_authz.go
pkg/lib/oauth/handler/handler_authz_test.go
pkg/lib/oauth/handler/handler_token.go
pkg/lib/oauth/handler/handler_token_mock_test.go
pkg/lib/oauth/handler/service_code_grant.go
pkg/lib/oauth/handler/service_token.go
pkg/lib/oauth/resolver.go

Create new refresh token inside original offline grant if offline grant is used as session in select account

---

authui/src/authflowv2/components/otp-input.css
authui/src/authflowv2/components/widget.css
authui/src/authflowv2/otpInput.ts
resources/authgear/templates/en/web/authflowv2/__html_head.html
resources/authgear/templates/en/web/authflowv2/__otp_input.html

Now with javascript enable otp looks like this:
When javascript disabled otp looks like this:
Note that when javascript disabled the login page logo default position is on the left:

Add next button to verification page

---

pkg/auth/handler/webapp/authflowv2/select_account.go
pkg/lib/config/oauth.go
pkg/lib/deps/deps_common.go
pkg/lib/oauth/deps.go
pkg/lib/oauth/handler/deps.go
pkg/lib/oauth/handler/handler_authz.go
pkg/lib/oauth/handler/handler_authz_test.go
pkg/lib/oauth/handler/handler_proxy_redirect.go
pkg/lib/oauth/handler/handler_token.go
pkg/lib/oauth/handler/handler_token_mock_test.go
pkg/lib/oauth/handler/handler_token_test.go
pkg/lib/oauth/handler/resolve.go
pkg/lib/oauth/handler/resolve_test.go
pkg/lib/oauth/handler/service_app_initiated_sso_to_web.go
pkg/lib/oauth/oidc/scopes.go
pkg/lib/oauth/pre_authenticated_url_token.go
pkg/lib/oauth/protocol/authz.go
pkg/lib/oauth/redis/keys.go
pkg/lib/oauth/redis/store.go
pkg/lib/oauth/scope.go
pkg/lib/oauth/store_grant.go
pkg/lib/oauth/store_grant_mock.go

Rename App Initiated SSO to Web to Pre-Authenticated URL

---

authui/src/authflowv2/components/widget.css

Fix widget padding in mobile view

---

e2e/tests/account_linking/incoming_login_id_invalid_login_id.test.yaml
pkg/lib/authenticationflow/declarative/utils_account_linking.go
pkg/lib/authenticationflow/dependencies.go
pkg/lib/authn/identity/claim_key.go
pkg/lib/authn/identity/info.go
pkg/lib/authn/identity/loginid/checker.go
pkg/lib/authn/identity/loginid/provider.go
pkg/lib/interaction/nodes/verify_identity_via_whatsapp.go

Fix login ID is not checked before normalization in account linking

---

authui/src/authflowv2/components/widget.css

Update logo position:
https://linear.app/authgear/issue/DEV-1428/update-logo-size-in-authui-v2#comment-0459abe6

Update padding top for logo position

---

portal/src/graphql/portal/DesignScreen/DesignScreen.tsx

Now Design page go back to the top when the screen becomes narrow
Demo video:
https://github.com/user-attachments/assets/306a97ba-2118-4897-b63e-942675c2e00a

Update layout of design screen

---

pkg/lib/authenticationflow/declarative/intent_signup_flow.go
pkg/lib/authenticationflow/declarative/milestone.go
pkg/lib/authenticationflow/declarative/node_do_create_user.go

Never report userID as empty in account linking

---

portal/src/graphql/adminapi/UserDetailsScreen.tsx
portal/src/graphql/portal/SubscriptionCurrentPlanSummary.tsx
portal/src/graphql/portal/SubscriptionPlanCard.tsx
portal/src/graphql/portal/SubscriptionScreenFooter.tsx
portal/src/util/formatDateOnly.ts
portal/src/util/formatDatetime.ts

Note: Cannot check subscription pages layout since it requires stripe api key

Update Date format in the portal

---

go.mod
go.sum

Update originmatcher to ac10088d8800

---

authui/src/authflowv2/components/layout.css
authui/src/authflowv2/components/widget.css

Ref DEV-1559
https://github.com/user-attachments/assets/c2ae097a-b1da-48e7-89a9-1c67253e517b
cc @fungc-io see if ok? idk who the designer is but maybe you can ping them here too and see if looks good

authui v2: Adjust widget responsive layout

---

pkg/util/phone/legal_and_valid_parser_test.go
pkg/util/phone/legal_parser.go
pkg/util/phone/legal_parser_test.go

Fix LegalParser and add more tests to demo the behavior of the two parsers

---

portal/src/graphql/portal/DesignScreen/form.ts
portal/src/model/themeAuthFlowV2.test.ts
portal/src/model/themeAuthFlowV2.ts

Ref DEV-1541
https://github.com/user-attachments/assets/a5d7db89-852c-4d2d-a06e-50e4e69f544c

authui v2: Apply custom border radius to secondary button

---

authui/src/authflowv2/components.css
authui/src/authflowv2/components/dialog.css
authui/src/authflowv2/components/widget.css
resources/authgear/templates/en/web/authflowv2/__lockout.html

Rename `.modal` css class as `.dialog`

---

authui/src/authflowv2/components/layout.css

Improve Auth UI responsive layout take 2

---

pkg/lib/authn/identity/service/service.go

Fix regression of web anonymous user

---

pkg/lib/oauth/resolver.go

Fix app_access_token session is always ignored if an invalid app_session exist

---

pkg/auth/routes.go

https://linear.app/authgear/issue/DEV-1525/update-all-other-sdks-for-opening-account-deletion-page#comment-ea152620

Fix app session apis does not have dpop middleware

---

pkg/api/event/nonblocking/bot_protection_verification_failed.go
pkg/lib/botprotection/provider.go
pkg/lib/deps/deps_common.go

ref DEV-1565
Copied from SQL row as JSON
```json5
{
"id": "0000000000000286",
"app_id": "accounts",
"created_at": "2024-07-24 08:05:29",
"user_id": "8227a171-f628-4bb3-bb8b-7d4b40abf368",
"activity_type": "bot_protection.failed",
"ip_address": "127.0.0.1",
"user_agent": "PostmanRuntime/7.40.0",
"client_id": "",
"data": "{\"id\": \"0000000000000286\", \"seq\": 646, \"type\": \"bot_protection.failed\", \"context\": {\"app_id\": \"accounts\", \"user_id\": \"8227a171-f628-4bb3-bb8b-7d4b40abf368\", \"language\": \"zh-HK\", \"timestamp\": 1721808329, \"ip_address\": \"127.0.0.1\", \"user_agent\": \"PostmanRuntime/7.40.0\", \"triggered_by\": \"user\", \"audit_context\": null, \"preferred_languages\": []}, \"payload\": {\"provider\": \"cloudflare\", \"verify_token\": \"dummy\"}}"
}
```

Log invalid captcha challenge token for audit

---

e2e/tests/account_linking/dev-1632.test.yaml
pkg/lib/authenticationflow/declarative/intent_check_conflict_and_create_identity.go
pkg/lib/authenticationflow/declarative/intent_promote_identity_login_id.go
pkg/lib/authenticationflow/declarative/node_promote_identity_oauth.go
pkg/lib/authenticationflow/declarative/utils_account_linking.go

Exclude identity conflicts of the same account

---

Makefile
pkg/lib/oauth/store_grant_mock.go

Fix make check tidy

---

portal/src/graphql/portal/CustomDomainListScreen.tsx
portal/src/locale-data/en.json

Ref DEV-1538
https://github.com/user-attachments/assets/04f33567-3186-457b-a53c-696d0cfff4b8
@fungc-io do we need handling for existing redirect url values set when user remove custom domain?

Disable redirect url form when no custom domain is set

---

portal/src/graphql/portal/DesignScreen/DesignScreen.tsx
portal/src/graphql/portal/DesignScreen/form.ts
portal/src/locale-data/en.json
portal/src/model/themeAuthFlowV2.test.ts
portal/src/model/themeAuthFlowV2.ts

Ref DEV-1555
Based on #4490 #4496
https://github.com/user-attachments/assets/bbaae0e8-13dd-4b82-8557-ad269cdad068

Dep(#4490,#4496): Add config for logo height

---

docs/specs/2fa-grace-period.md
docs/specs/authentication-flow.md

Specify 2FA grace period

---

docs/specs/app2app.md

Correct app2app spec

---

authui/src/authflowv2/components/brand-logo.css
authui/src/authflowv2/components/screen-logo-layout.css
authui/src/inline-preview.ts
resources/authgear/templates/en/web/authflowv2/__header.html
resources/authgear/templates/en/web/authflowv2/enter_totp.html

Ref DEV-1673
I personally prefer the pure css solution before the refactoring (`&>img[src=""]`) but let's go with the class name direction for now
https://github.com/user-attachments/assets/55722a59-e17b-41ae-8be6-309e4808ef6e

Handle hiding brand logo container for inline preview

---

portal/src/components/design/ColorPicker.tsx

Ref DEV-1684
https://github.com/user-attachments/assets/5906de93-fce2-4ccd-b7a3-f2daa8fa40df

Allow color picker for invalid input string

---

portal/src/graphql/portal/DesignScreen/form.ts
portal/src/model/themeAuthFlowV2.test.ts
portal/src/model/themeAuthFlowV2.ts

Ref DEV-1697
https://github.com/user-attachments/assets/da610dba-ce10-4c19-91ac-010454856314

Set phone input border radius along with main input

---

pkg/lib/authenticationflow/declarative/utils_account_linking.go
pkg/lib/authenticationflow/dependencies.go
pkg/lib/authn/identity/loginid/provider.go
pkg/lib/authn/identity/loginid/store.go
pkg/lib/authn/identity/oauth/provider.go
pkg/lib/authn/identity/oauth/store.go
pkg/lib/authn/identity/service/service.go
pkg/lib/authn/identity/service/service_mock_test.go
pkg/lib/config/account_linking.go
pkg/lib/facade/coordinator.go
pkg/lib/facade/identity.go

Fix high CPU usage due to query not written in a way to utilize index

---

pkg/lib/authn/identity/info.go
pkg/lib/authn/identity/loginid_identity.go
pkg/lib/authn/identity/oauth_identity.go

Add more values to oauth identity aware standard claims

---

cmd/authgear/background/wire_gen.go
e2e/cmd/e2e/pkg/wire_gen.go
migrations/authgear/20240731135615-add_ldap_identity.sql
pkg/admin/wire_gen.go
pkg/api/model/identity.go
pkg/lib/authn/identity/claim_key.go
pkg/lib/authn/identity/info.go
pkg/lib/authn/identity/ldap/deps.go
pkg/lib/authn/identity/ldap/provider.go
pkg/lib/authn/identity/ldap/store.go
pkg/lib/authn/identity/ldap_identity.go
pkg/lib/authn/identity/ldap_spec.go
pkg/lib/authn/identity/service/service.go
pkg/lib/authn/identity/service/service_mock_test.go
pkg/lib/authn/identity/service/service_test.go
pkg/lib/authn/identity/spec.go
pkg/lib/deps/deps_common.go
pkg/redisqueue/wire_gen.go
pkg/resolver/wire_gen.go

Create LDAP identity service

---

.dockerignore
.github/actions/install-native-deps/action.yaml
.github/actions/libvips/action.yaml
.github/workflows/ci.yaml
.github/workflows/custom-build.yaml
.github/workflows/mirror.yaml
.gitignore
pkg/lib/web/image_test.go

Migrate to Workload Identity Federation

---

pkg/lib/authenticationflow/declarative/node_do_use_identity_oauth.go
pkg/lib/authenticationflow/declarative/node_oauth.go

Update OAuth identity when it is used in login

---

cmd/authgear/background/wire_gen.go
e2e/cmd/e2e/pkg/wire_gen.go
pkg/admin/facade/interaction.go
pkg/admin/facade/user.go
pkg/admin/graphql/context.go
pkg/admin/graphql/user_mutation.go
pkg/admin/wire_gen.go
pkg/lib/authn/authenticator/password/deps.go
pkg/lib/authn/authenticator/password/errors.go
pkg/lib/authn/authenticator/password/generator.go
pkg/lib/authn/authenticator/password/generator_test.go
pkg/lib/facade/coordinator.go
pkg/lib/facade/user.go
pkg/lib/interaction/context.go
pkg/lib/interaction/nodes/reset_password.go
pkg/redisqueue/wire_gen.go
portal/src/graphql/adminapi/AddUserScreen.tsx
portal/src/graphql/adminapi/ChangePasswordScreen.tsx
portal/src/graphql/adminapi/globalTypes.generated.ts
portal/src/graphql/adminapi/schema.graphql
portal/src/locale-data/en.json

ref DEV-1629
dependencies
**Create User**
**Change Password**

Add generate password option to create user and change password

---

pkg/lib/facade/coordinator.go

Fix nil spec is added and used incorrectly

---

cmd/authgear/background/wire_gen.go
e2e/cmd/e2e/pkg/wire_gen.go
pkg/admin/wire_gen.go
pkg/lib/authn/authenticator/password/deps.go
pkg/lib/authn/authenticator/password/generator.go
pkg/lib/authn/authenticator/password/generator_test.go
pkg/redisqueue/wire_gen.go

Fix flaky password generator test

---

pkg/lib/authn/identity/service/service.go

Disallow a user to have more than one identity of the same provider

---

e2e/README.md
e2e/pkg/testrunner/matcher.go
e2e/pkg/testrunner/matcher_test.go

- Add never type to e2e matcher
- Fix tuple type and nil handling in e2e matcher

Support never and tuple matcher in e2e test

---

authui/src/authflowv2.ts
authui/src/authflowv2/botprotection/botProtectionStandalonePage.ts
authui/src/authflowv2/botprotection/botProtectionStandalonePageSubmitBtn.ts
authui/src/authflowv2/botprotection/botProtectionWidget.ts
authui/src/authflowv2/botprotection/cloudflareTurnstile.ts
authui/src/authflowv2/botprotection/recaptchav2.ts
resources/authgear/templates/en/web/authflowv2/verify_bot_protection.html

Fixes dev-1774.
The regression is caused by 7834fd6096b090852b1e5d62d3231de4b9741f73
Previous implementation in PR #4476 
https://github.com/user-attachments/assets/d73ecec5-7b67-4935-8e49-833c23de835f
https://github.com/user-attachments/assets/aee653d7-a61b-418d-ade9-eed2b812054c

Fix regression on captcha widget rendering in catpcha standalone page

---

e2e/README.md
e2e/cmd/e2e/cmd/cobraviper.go
e2e/cmd/e2e/cmd/sql_insert_update.go
e2e/cmd/e2e/cmd/sql_select.go
e2e/cmd/e2e/pkg/sql.go
e2e/cmd/e2e/pkg/sql_insert_update.go
e2e/cmd/e2e/pkg/sql_select.go
e2e/pkg/testrunner/cmd.go
e2e/pkg/testrunner/models.go
e2e/pkg/testrunner/queryResult.go
e2e/pkg/testrunner/testcase.go
e2e/schema.json

Add a new step to run a database query and assert the result
1. reauth need fetch user_id from db to `generateIDToken`
2. userimport needs to verify user attributes are populated correctly (uppercase/lowercase) in db
Please see https://github.com/authgear/authgear-server/pull/4562/commits/28f884a9f658ca279b21bd056c98d6f06908c618 at PR #4562
ref DEV-1253

Add `step: query` to e2e tests for SELECT queries

---

portal/src/graphql/portal/BotProtectionConfigurationScreen.tsx

ref DEV-1773
https://github.com/user-attachments/assets/0addea77-1ed6-4330-92a5-d0d0b7c5a9ac

Provide default values on FormBotProtectionRequirement on enable

---

pkg/lib/authenticationflow/declarative/generate_config_account_recovery_flow.go
pkg/lib/authenticationflow/declarative/generate_config_bot_protection.go
pkg/lib/authenticationflow/declarative/generate_config_login_flow.go
pkg/lib/authenticationflow/declarative/generate_config_signup_flow.go
pkg/lib/authenticationflow/declarative/generate_config_signup_login_flow.go

ref sentry https://oursky.slack.com/archives/C01P0NCS3F1/p1723522268603209

Fix nil pointer bug if `bot_protection.requirements.signupOrLogin` is empty

---

pkg/auth/handler/saml/deps.go
pkg/auth/handler/saml/login.go
pkg/auth/handler/saml/metadata.go
pkg/auth/routes.go
pkg/auth/wire_handler.go
pkg/lib/deps/deps_common.go
pkg/lib/endpoints/endpoints.go
pkg/lib/saml/service.go

ref DEV-1723
requires https://github.com/authgear/authgear-server/pull/4567

SAML: Add login endpoint

---

pkg/auth/handler/webapp/authflowv2/routes.go
pkg/auth/webapp/authflow_routes.go
pkg/auth/webapp/session_authflow.go

Use full redirect to visit /finish

---

pkg/auth/handler/webapp/identity.go
pkg/lib/authn/identity/filters.go
pkg/lib/authn/identity/info.go
pkg/lib/interaction/nodes/create_identity_begin.go
pkg/lib/interaction/nodes/select_identity_begin.go
pkg/lib/interaction/nodes/select_identity_end.go

Fix old UI crash by LDAP server

---

authui/package-lock.json
authui/package.json
portal/package-lock.json
portal/package.json

To resolve vuln, see DEV-1791 for more

Bump to `axios@1.7.4`

---

pkg/lib/authn/otp/attempt_tracker_redis.go
pkg/lib/authn/otp/service.go

Make OTP failed attempt tracking key has expiration

---

.github/workflows/ci.yaml

| Before          | After                                   |
|---------------------|------------------------------------------|
| <img width="411" alt="image" src="https://github.com/user-attachments/assets/d2c6aaba-53a6-485f-b1a1-cd69ea7152f9">                | Step name should all starts with `Run ...`                            |

Make npm audit name consistent with other ci steps

---

pkg/auth/handler/saml/metadata.go
pkg/lib/config/saml.go
pkg/lib/config/testdata/config_tests.yaml
pkg/lib/saml/error.go
pkg/lib/saml/service.go

ref DEV-1729
requires https://github.com/authgear/authgear-server/pull/4573

SAML: Add name id configs

---

pkg/auth/handler/webapp/authflowv2/setup_oob_otp.go
pkg/auth/handler/webapp/bot_protection.go
pkg/auth/webapp/authflow.go
pkg/auth/webapp/bot_protection.go
resources/authgear/templates/en/web/authflowv2/setup_oob_otp.html

- #4579 
https://github.com/user-attachments/assets/20807210-2fa8-48ac-9bb7-2b5e45548765

Implement captcha in create authenticator screen

---

portal/src/locale-data/en.json

Update create user screen header copywriting

---

pkg/auth/handler/webapp/authflowv2/setup_oob_otp.go

I have no idea why after merging, the code looks different from the PR. https://github.com/authgear/authgear-server/pull/4582/files#diff-9f8003575980903355d8da8e95a87dc52bb4c30cde970e48b7e89b20329b22df

Fix git merge error

---

pkg/lib/lockout/record.go
pkg/lib/lockout/record_test.go
pkg/lib/lockout/storage_redis.go

Fix clear lockout attempt does not set expire

---

cmd/authgear/background/wire_gen.go
e2e/cmd/e2e/pkg/wire_gen.go
pkg/admin/wire_gen.go
pkg/lib/elasticsearch/service.go
pkg/redisqueue/wire_gen.go
pkg/resolver/wire_gen.go

Demo:
https://github.com/user-attachments/assets/af424908-b71f-4d95-884a-8f70f7bb0494

Support search user with ldap identity

---

portal/src/locale-data/en.json

Change `Default` -> `Primary`

---

resources/authgear/templates/en/web/authflowv2/select_account.html
resources/authgear/templates/en/web/authflowv2/signup.html
resources/authgear/templates/en/web/authflowv2/verify_login_link.html

https://github.com/user-attachments/assets/6a139cac-1f1c-43fd-ba51-8112259a85f1

Fix organization name is not previewable

---

.github/workflows/custom-build.yaml

To avoid build error in oursky/authgear-server

Switch to use oursky fork of google-github-actions

---

authui/src/authflowv2/botprotection/botProtection.ts
pkg/auth/handler/webapp/authflow_controller.go
pkg/auth/handler/webapp/bot_protection.go
pkg/auth/handler/webapp/viewmodels/authflow_branch.go
pkg/auth/webapp/session_authflow.go
resources/authgear/templates/en/web/authflowv2/__authflow_branch.html

https://github.com/user-attachments/assets/89c98626-2928-4245-a080-a849a9000960
https://github.com/user-attachments/assets/0f163de2-2816-4faa-99e7-c9599b98c9fc

Use captcha modal for oobotp email and sms on switch branch

---

pkg/lib/authenticationflow/declarative/data_identification.go
pkg/lib/authn/identity/info.go
pkg/lib/authn/identity/ldap_identity.go
pkg/lib/authn/identity/service/service.go

Please note that 
```
pkg/auth/handler/webapp/authflowv2/account_linking.go
134:                    // TODO(DEV-1672)
pkg/lib/authenticationflow/declarative/intent_check_conflict_and_create_identity.go
95:             // TODO(DEV-1672)
```
was handled in [4607](https://github.com/authgear/authgear-server/pull/4607)

Tidy up the todo comment in feat ldap

---

portal/src/components/common/BaseImagePicker.tsx
portal/src/graphql/portal/DesignScreen/form.ts
portal/src/model/themeAuthFlowV2.test.ts
portal/src/model/themeAuthFlowV2.ts

https://github.com/user-attachments/assets/6bfe49ec-dce7-49f9-8ed1-16043792ac13

Fix logo alignment when add/remove logo

---

portal/src/graphql/portal/BotProtectionConfigurationScreen.tsx

https://github.com/user-attachments/assets/0a0ccd2f-de5f-4519-94ab-ed5c7e6f1249

Conform disabled special authenticator mode to allSignupLogin in bot protection configuration screen

---

migrations/authgear/20240731135615-add_ldap_identity.sql
pkg/lib/authenticationflow/declarative/utils_ldap.go
pkg/lib/authn/identity/claim_key.go
pkg/lib/authn/identity/info.go
pkg/lib/authn/identity/ldap/provider.go
pkg/lib/authn/identity/ldap/store.go
pkg/lib/authn/identity/ldap_identity.go
pkg/lib/authn/identity/ldap_identity_test.go
pkg/lib/authn/identity/ldap_spec.go
pkg/lib/authn/identity/service/service.go
pkg/lib/authn/identity/service/service_mock_test.go
pkg/lib/authn/identity/service/service_test.go
pkg/lib/authn/user/model_test.go
pkg/lib/ldap/attribute.go
pkg/lib/ldap/attribute_decoder.go
pkg/lib/ldap/attribute_decoder_test.go
pkg/lib/ldap/attribute_name_and_value.go
pkg/lib/ldap/encoding.go
pkg/lib/ldap/entry.go

Handle known only attributes

---

portal/src/components/design/ColorPicker.tsx

Demo:
https://github.com/user-attachments/assets/34ef246d-7c7b-4852-a2c2-c82247a132de

Reset Input Field After discard

---

portal/src/components/design/TextDecoration.module.css
portal/src/components/design/TextDecoration.tsx
portal/src/graphql/portal/DesignScreen/DesignScreen.tsx
portal/src/graphql/portal/DesignScreen/form.ts
portal/src/graphql/portal/DesignScreen/viewModel.ts
portal/src/images/ic-text-decoration-none.svg
portal/src/images/ic-text-decoration-underline.svg
portal/src/locale-data/en.json
portal/src/model/themeAuthFlowV2.test.ts
portal/src/model/themeAuthFlowV2.ts

https://github.com/user-attachments/assets/b51a6320-2e1d-4329-9781-d43f9ee07c79

Implement customise link text decoration

---

authui/src/inline-preview.ts
portal/src/graphql/portal/DesignScreen/DesignScreen.tsx
portal/src/graphql/portal/DesignScreen/viewModel.ts
portal/src/model/themeAuthFlowV2.ts

Demo:
https://github.com/user-attachments/assets/7a49e645-3f9a-4b7b-a71e-8bbe033c6b3f
- Now Design Screen theme customisation changes synchronously 
- Select Preview Page shows loading

Missing loading state when the preview is pending re render

---

docs/specs/admin-api-get-users.md

ref dev-1811
Add documentation for get user admin API
@louischan-oursky

Specify get user Admin GraphQL APIs

---

pkg/lib/authn/identity/passkey/provider.go
pkg/lib/authn/identity/service/service.go
pkg/lib/authn/identity/service/service_mock_test.go

Fix unexpected error when setting up passkey

---

e2e/cmd/proxy/mockldap/handlers.go
e2e/tests/account_linking/incoming_ldap_conflicts_login_id.test.yaml
e2e/tests/account_linking/incoming_ldap_conflicts_oauth.test.yaml
e2e/tests/account_linking/incoming_login_id_conflicts_ldap.test.yaml
e2e/tests/account_linking/incoming_oauth_conflicts_ldap.test.yaml
e2e/tests/account_linking/ldap_user.json
e2e/tests/account_linking/ldap_user.sql
e2e/tests/ldap/users.sql
pkg/auth/handler/webapp/authflowv2/account_linking.go
pkg/lib/authenticationflow/declarative/intent_check_conflict_and_create_identity.go
pkg/lib/authenticationflow/declarative/utils_account_linking.go
pkg/lib/config/account_linking.go

Incoming LDAP on existing email
https://github.com/user-attachments/assets/81ee1f88-0181-40db-826d-f7c417bdd99a
Incoming LoginID on existing LDAP
https://github.com/user-attachments/assets/05571bc3-f6c9-45de-8be1-c763b0c89759
Please Note that this PR Require [#4597](https://github.com/authgear/authgear-server/pull/4597) first

Check if ldap identity is compatible with account linking

---

portal/src/locale-data/en.json

Update copywriting of portal add user by phone number

---

pkg/lib/facade/coordinator.go
pkg/lib/oauth/redis/store.go
pkg/lib/oauth/session_manager.go
pkg/lib/oauth/store_grant.go
pkg/lib/oauth/store_grant_mock.go
pkg/lib/session/idpsession/manager.go
pkg/lib/session/idpsession/store.go
pkg/lib/session/idpsession/store_mock_test.go
pkg/lib/session/idpsession/store_redis.go

Clean up Redis hashes when deleting/anonymizing users

---

e2e/go.mod
e2e/pkg/e2eclient/client.go
e2e/tests/admin_api/get_users_admin_api_user.sql
e2e/tests/admin_api/get_users_by_standard_attribute_test.go
pkg/admin/facade/user.go
pkg/admin/graphql/context.go
pkg/admin/graphql/query.go
pkg/api/errors.go
pkg/lib/authn/identity/loginid/normalizer.go
pkg/lib/authn/identity/loginid/provider.go
pkg/lib/authn/identity/service/service.go
pkg/lib/authn/identity/service/service_mock_test.go
pkg/lib/facade/coordinator.go
pkg/lib/facade/user.go
portal/src/graphql/adminapi/globalTypes.generated.ts
portal/src/graphql/adminapi/schema.graphql

tag @louischan-oursky 
Preview:
https://github.com/user-attachments/assets/f4f88edb-330d-4285-9366-c815fbbc19cb

Add getUsersByStandardAttribute admin API

---

portal/src/graphql/adminapi/AdminActionButton.tsx
portal/src/graphql/adminapi/UserDetailSummary.module.css
portal/src/graphql/adminapi/UserDetailSummary.tsx
portal/src/graphql/adminapi/UserDetailsAdminActions.module.css
portal/src/graphql/adminapi/UserDetailsAdminActions.tsx
portal/src/graphql/adminapi/UserDetailsScreen.tsx
portal/src/locale-data/en.json

Add User Details Disable/Delete tab

---

go.mod
pkg/auth/handler/saml/deps.go
pkg/auth/handler/saml/handle_login_result.go
pkg/auth/handler/saml/login.go
pkg/auth/handler/saml/login_finish.go
pkg/auth/handler/saml/services.go
pkg/auth/routes.go
pkg/auth/wire_handler.go
pkg/lib/authn/authenticationinfo/model.go
pkg/lib/config/saml.go
pkg/lib/config/secret_cert.go
pkg/lib/config/testdata/config_tests.yaml
pkg/lib/config/testdata/default_config.yaml
pkg/lib/deps/deps_common.go
pkg/lib/oauth/oidc/id_token.go
pkg/lib/oauth/store_grant_mock.go
pkg/lib/saml/samlbinding/http_post.go
pkg/lib/saml/samlerror/missing_nameid.go
pkg/lib/saml/samlprotocol/authn_request.go
pkg/lib/saml/samlprotocol/const.go
pkg/lib/saml/samlprotocol/error.go
pkg/lib/saml/samlprotocol/id.go
pkg/lib/saml/samlprotocol/response.go
pkg/lib/saml/samlprotocol/samlprotocolhttp/result.go
pkg/lib/saml/samlprotocol/schema.go
pkg/lib/saml/samlsession/model.go
pkg/lib/saml/service.go
pkg/lib/saml/service_mock_test.go
pkg/lib/saml/service_test.go

ref DEV-1727
Same as before, you can use this site to test:
https://sptest.iamshowcase.com/authnrequest
If you want to test `IsPassive`, you need the tools here:
https://www.samltool.com/encode.php
Write a saml request manually, and use the encoder above to generate the `SAMLRequest` query parameter, and send it to `http://localhost:3000/saml2/login/{your_sp_id}?SAMLRequest={your_encoded_request}`.
Here is an example request:
```xml
<samlp:AuthnRequest
xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
ForceAuthn="false"
IsPassive="true"
ID="a1b83a399445569c760a9f733cce58d7aec680316"
IssueInstant="2024-08-20T11:10:25Z"
Destination="http://localhost:3000/saml2/login/sp1"
AssertionConsumerServiceURL="https://sptest.iamshowcase.com/acs" …
```

SAML: Finish SSO flow

---

docs/specs/admin-api-get-users.md
e2e/tests/admin_api/get_user_by_loginid_test.go
pkg/admin/facade/user.go
pkg/admin/graphql/context.go
pkg/admin/graphql/query.go
pkg/lib/authn/identity/loginid/errors.go
pkg/lib/authn/identity/loginid/provider.go
pkg/lib/authn/identity/service/service.go
pkg/lib/authn/identity/service/service_mock_test.go
pkg/lib/facade/coordinator.go
pkg/lib/facade/user.go
portal/src/graphql/adminapi/globalTypes.generated.ts
portal/src/graphql/adminapi/schema.graphql

ref dev-1849
@louischan-oursky check check when you free 🙏
Preview:
https://github.com/user-attachments/assets/88ef08de-ea90-46d6-acd7-bef328d67260

Add getUserByLoginID admin API

---

e2e/.env
e2e/cmd/e2e/pkg/configsource.go
e2e/go.mod
e2e/go.sum
e2e/golangbugs/http_client_cookie_jar_bug_test.go
e2e/pkg/e2eclient/client.go
e2e/pkg/testrunner/cmd.go
e2e/pkg/testrunner/testcase.go
e2e/tests/ldap/authgear.yaml
e2e/tests/login/device_token/additional_password/test.yaml
e2e/tests/login/device_token/additional_password/users.json
e2e/tests/receipe_1/authgear.yaml
e2e/var/authgear.yaml
pkg/lib/authenticationflow/declarative/intent_create_authenticator_oob_otp.go
pkg/lib/authenticationflow/declarative/intent_create_authenticator_password.go
pkg/lib/authenticationflow/declarative/intent_create_authenticator_totp.go
pkg/lib/authenticationflow/declarative/intent_inspect_device_token.go
pkg/lib/authenticationflow/declarative/intent_login_flow_step_authenticate.go
pkg/lib/authenticationflow/declarative/intent_login_flow_step_create_authenticator.go
pkg/lib/authenticationflow/declarative/intent_reauth_flow_step_authenticate.go
pkg/lib/authenticationflow/declarative/intent_signup_flow_step_create_authenticator.go
pkg/lib/authenticationflow/declarative/intent_use_authenticator_oob_otp.go
pkg/lib/authenticationflow/declarative/intent_use_authenticator_passkey.go
pkg/lib/authenticationflow/declarative/intent_use_authenticator_password.go
pkg/lib/authenticationflow/declarative/intent_use_authenticator_totp.go
pkg/lib/authenticationflow/declarative/intent_use_recovery_code.go
pkg/lib/authenticationflow/declarative/milestone.go
pkg/lib/authenticationflow/declarative/node_do_use_device_token.go
pkg/lib/authenticationflow/declarative/node_skip_creation_by_existing_authenticator.go

Implement missing milestones on inspect device token

---

pkg/admin/graphql/audit_log.go
portal/src/graphql/adminapi/globalTypes.generated.ts
portal/src/graphql/adminapi/schema.graphql
portal/src/locale-data/en.json

https://github.com/user-attachments/assets/d0e32f25-8596-4f6e-9256-30fb916eaac3

Add bot protection fail event to portal audit log screen

---

CONTRIBUTING.md
e2e/tests/admin_api/get_user_by_oauth_test.go
e2e/tests/admin_api/get_users_admin_api_user.sql
e2e/var/authgear.yaml
pkg/admin/facade/user.go
pkg/admin/graphql/context.go
pkg/admin/graphql/query.go
pkg/lib/authn/identity/service/service.go
pkg/lib/facade/coordinator.go
pkg/lib/facade/user.go
portal/src/graphql/adminapi/globalTypes.generated.ts
portal/src/graphql/adminapi/schema.graphql

ref dev-1850
Preview:
https://github.com/user-attachments/assets/2768a3ac-d825-4d5a-b768-df50a43cd87e

Add getUserByOAuth API

---

authui/src/authflowv2/phoneInput.ts
pkg/auth/handler/webapp/authflowv2/forgot_password.go

ref DEV-1535
https://github.com/user-attachments/assets/0324d5fa-25c2-432c-bdee-e4286cd10a36

Fix forgot password empty phone number still proceed

---

e2e/tests/admin_api/create_identity_test.go
e2e/tests/admin_api/create_identity_user.sql
pkg/admin/deps.go
pkg/admin/facade/identity.go
pkg/admin/facade/interaction.go
pkg/admin/wire_gen.go
pkg/lib/facade/coordinator.go
pkg/lib/facade/identity.go

Make sure createIdentity will create OOB OTP authenticator

---

portal/src/graphql/adminapi/DeleteUserDialog.tsx

Update DeleteUserDialog schedule deletion onDismiss behaviour

---

pkg/lib/web/html.go
resources/authgear/templates/en/web/authflowv2/__base_page_frame.html
resources/authgear/templates/en/web/authflowv2/__page_frame.html

Seperate page frame html

---

pkg/auth/handler/saml/handle_login_result.go
pkg/auth/handler/saml/login.go
pkg/lib/saml/samlbinding/error.go
pkg/lib/saml/samlbinding/http_redirect.go
pkg/lib/saml/samlsession/model.go
pkg/lib/saml/samlsession/ui.go
pkg/lib/saml/service.go

Support saml idp-initiated sso flow

---

docs/specs/event.md
pkg/admin/wire_gen.go
pkg/api/event/blocking/oidc_jwt_pre_create.go
pkg/lib/authn/identity/service/service.go
pkg/lib/deps/deps_common.go
pkg/lib/facade/coordinator.go
pkg/lib/facade/identity.go
pkg/lib/oauth/token_encoding.go
pkg/lib/oauth/token_encoding_mock_test.go
pkg/lib/oauth/token_encoding_test.go
pkg/resolver/wire_gen.go

Include identities that have standard attributes in oidc.jwt.pre_create

---

portal/src/components/design/AppLogoPicker.tsx
portal/src/graphql/portal/DesignScreen/DesignScreen.tsx
portal/src/graphql/portal/DesignScreen/form.ts
portal/src/graphql/portal/DesignScreen/viewModel.ts
portal/src/locale-data/en.json

https://github.com/user-attachments/assets/cc9f31f4-bd46-4018-8b57-15f9ef2bfc4d

Fix app logo not show fallback logo

---

migrations/authgear/20240826112239-add_ldap_last_login_username.sql
pkg/lib/authenticationflow/declarative/intent_ldap.go
pkg/lib/authenticationflow/declarative/intent_lookup_identity_ldap.go
pkg/lib/authenticationflow/dependencies.go
pkg/lib/authn/identity/claim_key.go
pkg/lib/authn/identity/info.go
pkg/lib/authn/identity/ldap/provider.go
pkg/lib/authn/identity/ldap/store.go
pkg/lib/authn/identity/ldap_identity.go
pkg/lib/authn/identity/ldap_spec.go
pkg/lib/authn/identity/service/service.go
pkg/lib/authn/identity/service/service_mock_test.go
portal/src/graphql/adminapi/UserDetailsConnectedIdentities.module.css
portal/src/graphql/adminapi/UserDetailsConnectedIdentities.tsx

Update ldap identity display

---

resources/authgear/templates/en/web/authflowv2/__settings_page_frame.html

Make settings page frame content take full height of body

---

authui/src/authflowv2/components/select.css
authui/src/authflowv2/customSelect.ts
resources/authgear/templates/en/web/authflowv2/__phone_input.html

The original problem can be reproduced by configuring Authgear to only allow use phone number as login id and allow user to select many countries (I enables all countries in my demo). Basically make the login page to only contain the phone input without other options
https://github.com/user-attachments/assets/705d6244-f4ba-4918-afd1-001d4573b158
https://github.com/user-attachments/assets/a579ec63-8c69-46ab-9b8b-ae32d2989d34

Fix custom select dropdown

---

pkg/lib/authn/authenticator/password/generator.go
pkg/lib/authn/authenticator/password/generator_test.go
portal/src/util/passwordGenerator.test.ts
portal/src/util/passwordGenerator.ts

Preview:
https://github.com/user-attachments/assets/ae196e04-d19d-4b07-be09-b611c2c576ce
https://github.com/user-attachments/assets/d6cfe584-a9c3-4c2b-a518-b84f7365e464

Fix password generator doesnt have default character set when requirement is enabled

---

portal/src/locale-data/en.json

Add (seconds) to Resend Cooldown Duration in portal

---

portal/src/components/roles-and-groups/list/common/ActionButtonCell.tsx
portal/src/graphql/adminapi/UsersList.tsx

Fix anonymized/scheduled anonymized users action cells in portal usersList

---

portal/src/ReactApp.tsx

ref DEV-1767
https://github.com/user-attachments/assets/694793b1-fdbe-470f-8135-873f14387a55

Do not send posthog.resetGroups error to sentry

---

pkg/auth/handler/saml/login.go
pkg/auth/handler/webapp/authflow_controller.go
pkg/lib/config/config.go
pkg/lib/config/saml.go
pkg/lib/config/testdata/config_tests.yaml
pkg/lib/saml/service.go
pkg/lib/saml/service_test.go

ref dev-1999
requires https://github.com/authgear/authgear-server/pull/4698

SAML: Read custom authflow settings in oidc client in saml flow

---

pkg/auth/handler/saml/login.go
pkg/auth/handler/saml/services.go
pkg/lib/config/secret_saml.go
pkg/lib/deps/deps_config.go
pkg/lib/saml/samlbinding/http_post.go
pkg/lib/saml/samlbinding/http_redirect.go
pkg/lib/saml/samlbinding/http_redirect_test.go
pkg/lib/saml/samlerror/invalid_signature.go
pkg/lib/saml/samlprotocol/error.go
pkg/lib/saml/service.go
pkg/lib/saml/service_test.go

SAML: Verify request signature

---

pkg/lib/saml/samlprotocol/const.go
pkg/lib/saml/service.go
pkg/lib/saml/service_test.go

SAML: Reject unsupported bindings

---

CONTRIBUTING.md
Makefile
authui/package.json
authui/packages/vite-plugin-authgear-authui/src/index.js
authui/vite.config.ts
nginx.conf

Support Hot Module Replacement using Vite

---

docs/specs/deployment-wise-sms-gateway.md

Add spec for env sms config

---

authui/src/authflowv2/base.css
authui/src/authflowv2/components/body-text.css
authui/src/authflowv2/components/label-button.css
authui/src/authflowv2/components/link-button.css
portal/src/graphql/portal/DesignScreen/form.ts
portal/src/model/themeAuthFlowV2.test.ts
portal/src/model/themeAuthFlowV2.ts
portal/src/util/theme.ts

@louischan-oursky added new color for link and label button🙏
Preview:
https://github.com/user-attachments/assets/2cbef9d3-b354-4ec2-8c81-1898eb8ed1e6

Fix link button text color

---

pkg/lib/oauthrelyingparty/linkedin/provider.go
pkg/lib/oauthrelyingparty/linkedin/provider_test.go
pkg/lib/oauthrelyingparty/oauthrelyingpartyutil/oidc.go

ref DEV-2012
https://github.com/user-attachments/assets/5f632fa5-7b25-4f29-8cf7-f237bb5332a7

Implement linkedin oauth provider as OIDC provider

---

pkg/util/template/engine.go
pkg/util/template/resource.go
pkg/util/template/resource_test.go
pkg/util/template/translation_map.go

Validate templates when the template is updated

---

portal/src/components/audit-log/ActivityTypeFilterDropdown.tsx
portal/src/components/audit-log/AuditLogFilterBar.module.css

ref DEV-1876
Previously only mobile have searchable dropdown. Now desktop too.
https://github.com/user-attachments/assets/5a65c94b-c329-4cb5-af54-357520e419a0

Render searchable dropdown for audit log activity filter

---

resources/authgear/templates/en/web/authflowv2/forgot_password.html

ref DEV-2058
Maybe should enquire fung on `what error to show under input field` vs `what error to show in alert message`

Fix forgot password error display

---

portal/src/graphql/adminapi/UserDetailsAdminActions.module.css
portal/src/graphql/adminapi/UserDetailsAdminActions.tsx
portal/src/graphql/adminapi/mutations/scheduleAccountDeletionMutation.generated.ts
portal/src/graphql/adminapi/mutations/scheduleAccountDeletionMutation.graphql
portal/src/graphql/adminapi/mutations/setDisabledStatusMutation.generated.ts
portal/src/graphql/adminapi/mutations/setDisabledStatusMutation.graphql
portal/src/graphql/adminapi/mutations/unscheduleAccountDeletionMutation.generated.ts
portal/src/graphql/adminapi/mutations/unscheduleAccountDeletionMutation.graphql
portal/src/locale-data/en.json

Improve User Details Disable/Delete tab

---

portal/src/graphql/portal/CustomAttributesConfigurationScreen.tsx

ref DEV-2064
Took reference from https://github.com/authgear/authgear-server/blob/main/portal/src/graphql/adminapi/UsersScreen.tsx#L230

Add `Add New Attribute` button to Custom Attributes screen

---

pkg/lib/config/saml.go
pkg/lib/config/testdata/config_tests.yaml
pkg/lib/endpoints/endpoints.go
pkg/lib/saml/samlprotocol/authn_request.go
pkg/lib/saml/samlprotocol/const.go
pkg/lib/saml/samlsession/ui.go
pkg/lib/saml/service.go
pkg/lib/saml/service_mock_test.go
pkg/lib/saml/service_test.go

SAML/SLO: Update config & metadata

---

pkg/auth/handler/webapp/csrf_middleware.go
pkg/auth/webapp/csrf.go
pkg/auth/webapp/deps.go
pkg/util/httputil/cookie.go
pkg/util/httputil/cookie_test.go

Fix httputil.CookieManager and CSRFMiddleware

---

pkg/lib/authn/otp/sender.go
pkg/lib/feature/forgotpassword/sender.go
pkg/lib/translation/data.go
pkg/lib/translation/service.go
pkg/lib/translation/service_test.go
pkg/portal/service/collaborator.go
pkg/util/template/effective_resource.go
pkg/util/template/engine.go
pkg/util/template/engine_test.go
pkg/util/template/resolver.go
pkg/util/template/resource.go
pkg/util/template/resource_test.go

[DEV-2066] Report language tag when render templates

---

pkg/lib/infra/redisqueue/task.go
pkg/lib/userimport/model.go
pkg/redisqueue/consumer.go
pkg/util/backoff/counter.go
pkg/util/backoff/counter_test.go

ref DEV-1481, DEV-1483
~NOTE: there's a breaking change with respect to the user import API status field, not sure if want to add a new field to indicate success/failure instead.~

Improve redis queue error handling

---

authui/package-lock.json
authui/package.json
portal/package-lock.json
portal/package.json

https://github.com/advisories/GHSA-64vr-g452-qvp3
https://github.com/vitejs/vite/security/advisories/GHSA-9cwx-2883-4wfx

Bump vite to 5.4.6

---

portal/src/util/projectname.ts

Fix undefined app ID in Create New Project Screen

---

portal/src/components/audit-log/AuditLogFilterBar.module.css

Fix audit log filter bar horizontal spacing

---

e2e/pkg/testrunner/cmd.go
e2e/tests/user_import/user_import_test.go
pkg/lib/config/database_env.go
pkg/lib/infra/db/appdb/deps.go
pkg/lib/infra/db/auditdb/deps.go
pkg/lib/infra/db/connection_options.go
pkg/lib/infra/db/globaldb/deps.go
pkg/lib/infra/db/handle.go
pkg/lib/infra/db/hook_handle.go
pkg/lib/infra/db/mock_handle.go
pkg/lib/infra/db/pool.go
pkg/lib/infra/db/tx_conn.go

Use prepared statements for SQL queries

---

authui/package-lock.json
portal/package-lock.json

https://github.com/advisories/GHSA-gcx4-mw62-g8wm

Bump rollup to 4.22.4

---

portal/src/locale-data/en.json

ref DEV-2122
https://github.com/user-attachments/assets/d4013650-a5bf-4d6d-b0e1-809f6fcbbdb4

Fix anchors in portal not using react router links

---

resources/authgear/templates/de/translation.json
resources/authgear/templates/el/translation.json
resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/authflowv2/not_found.html
resources/authgear/templates/es-419/translation.json
resources/authgear/templates/es-ES/translation.json
resources/authgear/templates/es/translation.json
resources/authgear/templates/fil/translation.json
resources/authgear/templates/fr/translation.json
resources/authgear/templates/id/translation.json
resources/authgear/templates/it/translation.json
resources/authgear/templates/ja/translation.json
resources/authgear/templates/ko/translation.json
resources/authgear/templates/ms/translation.json
resources/authgear/templates/nl/translation.json
resources/authgear/templates/pl/translation.json
resources/authgear/templates/pt-BR/translation.json
resources/authgear/templates/pt-PT/translation.json
resources/authgear/templates/pt/translation.json
resources/authgear/templates/th/translation.json
resources/authgear/templates/vi/translation.json
resources/authgear/templates/zh-CN/translation.json
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

Update page not found title copywriting

---

authui/src/authflowv2/components/brand-logo.css
authui/src/authflowv2/components/screen-logo-layout.css

ref DEV-2016
Cont'd - PR #4767 
https://github.com/user-attachments/assets/706b2ad4-980d-440a-9517-a7420b06c2f1

Follow up on brand logo margin

---

pkg/auth/deps.go
pkg/auth/handler/webapp/authflow_controller.go
pkg/auth/handler/webapp/authflow_controller_mock_test.go
pkg/auth/handler/webapp/authflowv2/deps.go
pkg/auth/handler/webapp/authflowv2/select_account.go
pkg/auth/handler/webapp/controller.go
pkg/auth/handler/webapp/deps.go
pkg/auth/handler/webapp/error_renderer.go
pkg/auth/routes.go
pkg/auth/webapp/deps.go
pkg/auth/wire_handler.go

ref DEV-2085
- Tested normal login flow
- Tested terminate other sessions

Fix back to select account screen after logged in will be navigated to settings

---

pkg/admin/transport/handler_user_export_create.go
pkg/lib/userexport/errors.go
pkg/lib/userexport/model.go
pkg/lib/userexport/model_test.go
pkg/lib/userexport/service.go
pkg/redisqueue/wire_gen.go

ref dev-2056
Preview:
[accounts-userexport_RHY34ZR76GVNSC6PC83DPA0FSWMD4P1F-20240925074610Z.csv](https://github.com/user-attachments/files/17134774/accounts-userexport_RHY34ZR76GVNSC6PC83DPA0FSWMD4P1F-20240925074610Z.csv)

Support user export to CSV format

---

pkg/admin/deps.go
pkg/admin/transport/handler_user_export_create.go
pkg/admin/transport/handler_user_import_create.go
pkg/admin/wire_gen.go
pkg/lib/config/feature_admin_api.go
pkg/lib/config/testdata/default_feature.yaml
pkg/lib/usage/errors.go
pkg/lib/usage/limit.go
pkg/lib/usage/limit_test.go

Add quota to user import/export job

---

portal/src/graphql/adminapi/AddUserScreen.tsx

ref DEV-1917
https://github.com/user-attachments/assets/8717d590-c9d0-43ae-8a7d-c7dc516bd0ca

Hide password field if password not in primary authn

---

.make-lint-translation-keys-expect
resources/authgear/templates/en/web/authflowv2/signup.html

ref DEV-1420
https://github.com/user-attachments/assets/4dafb406-de80-4331-8798-9637608f6c63

Hide logo if not first signup screen

---

docs/specs/user-export.md
docs/specs/user-import.md

ref DEV-1884
Also tag @mickmak-busicat @christinachee

Specify User Export API

---

pkg/admin/deps.go
pkg/admin/transport/handler_user_import_create.go
pkg/admin/transport/handler_user_import_get.go
pkg/admin/wire_gen.go
pkg/api/errors.go
pkg/lib/deps/deps_common.go
pkg/lib/infra/redisqueue/errors.go
pkg/lib/infra/redisqueue/producer.go
pkg/lib/userimport/deps.go
pkg/lib/userimport/errors.go
pkg/lib/userimport/job.go
pkg/lib/userimport/model.go
pkg/lib/userimport/store.go
pkg/lib/userimport/store_redis.go
pkg/redisqueue/consumer.go

Run user import job as multiple tasks

---

e2e/cmd/e2e/cmd/cobraviper.go
e2e/cmd/e2e/cmd/create_session.go
e2e/cmd/e2e/pkg/create_session.go
e2e/cmd/e2e/pkg/sql.go
e2e/pkg/e2eclient/client.go
e2e/pkg/e2eclient/samlclient.go
e2e/pkg/testrunner/cmd.go
e2e/pkg/testrunner/models.go
e2e/pkg/testrunner/testcase.go
e2e/tests/saml/slo.test.yaml
e2e/tests/saml/sso.test.yaml
e2e/var/authgear.yaml
pkg/lib/config/saml.go
pkg/lib/session/idpsession/e2e.go
pkg/lib/session/idpsession/provider.go

saml: Add e2e tests for slo

---

pkg/api/apierrors/error.go
pkg/api/apierrors/error_test.go
pkg/util/validation/validate.go

Handle JSON syntax error

---

pkg/admin/deps.go
pkg/admin/transport/handler_user_export_create.go
pkg/admin/wire_gen.go
pkg/lib/userexport/model.go
pkg/lib/userexport/model_test.go
pkg/lib/userexport/service.go
pkg/lib/userexport/service_test.go
pkg/util/validation/schema_builder.go

Improve user export validation

---

cmd/portal/internal/check.go
pkg/lib/config/saml.go
pkg/lib/config/secret_saml.go
pkg/lib/config/testdata/config_tests.yaml
pkg/lib/saml/service.go

ref DEV-2004
Already checked HK & US production with `portal internal configsource check-database`

Remove deprecated id from saml config

---

resources/authgear/templates/en/web/authflowv2/settings_identity_list_email.html
resources/authgear/templates/en/web/authflowv2/settings_identity_list_phone.html
resources/authgear/templates/en/web/authflowv2/settings_identity_list_username.html

[Settings v2] Disallow creating more identities of same type in settings

---

pkg/lib/saml/samlsession/ui.go

Fix client id is not set in uiparam in saml flows

---

authui/src/authflowv2/components/settings-title.css

[Settings v2] Fix profile name text align in settings

---

CONTRIBUTING.md
docker-compose.yaml
e2e/docker-compose.yaml

Document how to set up LDAP locally

---

pkg/lib/config/feature_messaging.go
pkg/lib/config/feature_usage_limit.go
pkg/lib/config/testdata/parse_feature_tests.yaml
pkg/lib/usage/limit.go

Fix the serialization of UsageLimitConfig.Quota

---

.make-lint-translation-keys-expect
authui/src/authflowv2.ts
authui/src/authflowv2/date.ts
authui/src/date.ts
authui/src/lockout.ts
pkg/auth/deps.go
pkg/auth/handler/webapp/authflowv2/settings_biometric.go
pkg/auth/handler/webapp/authflowv2/settings_delete_account.go
pkg/auth/handler/webapp/authflowv2/settings_mfa_password.go
pkg/auth/handler/webapp/authflowv2/settings_mfa_totp.go
pkg/auth/handler/webapp/authflowv2/settings_oob_otp.go
pkg/auth/handler/webapp/authflowv2/settings_passkey.go
pkg/auth/handler/webapp/authflowv2/settings_sessions.go
pkg/auth/handler/webapp/viewmodels/settings.go
resources/authgear/templates/en/web/authflowv2/__base_page_frame.html
resources/authgear/templates/en/web/authflowv2/__csrf_error_page_layout.html
resources/authgear/templates/en/web/authflowv2/__html_head.html

ref DEV-2166
CI: https://github.com/IniZio/authgear-server/pull/8

[Settings v2] Fix new timespans not formatted in settings

---

pkg/redisqueue/consumer.go

Change some logs to info

---

Makefile
pkg/lib/lockout/record.go
pkg/lib/lockout/record_test.go
pkg/lib/ratelimit/gcra.go
pkg/lib/ratelimit/gcra_test.go
pkg/lib/ratelimit/reservation.go
pkg/lib/usage/limit_test.go
pkg/redisqueue/consumer.go

Fix the usage of time functions

---

pkg/lib/accountmanagement/service_authenticator.go
resources/authgear/templates/en/web/authflowv2/settings_identity_add_email.html
resources/authgear/templates/en/web/authflowv2/settings_identity_add_phone.html
resources/authgear/templates/en/web/authflowv2/settings_identity_edit_email.html
resources/authgear/templates/en/web/authflowv2/settings_identity_edit_phone.html
resources/authgear/templates/en/web/authflowv2/settings_mfa_create_oob_otp.html

ref DEV-2119
[![CI](https://github.com/IniZio/authgear-server/actions/workflows/ci.yaml/badge.svg?branch=DEV-2119-update-error-field-display)](https://github.com/IniZio/authgear-server/tree/DEV-2119-update-error-field-display)

[Settings v2] Fix input field error for email / phone in settings

---

pkg/lib/config/feature_messaging.go
pkg/lib/config/testdata/default_feature.yaml

Remove the default usage limit of messaging

---

pkg/auth/handler/api/presign_images_upload.go
pkg/latte/intent_migrate.go
pkg/latte/intent_signup.go
pkg/lib/accountmanagement/rate_limit_middleware.go
pkg/lib/authenticationflow/declarative/intent_promote_flow.go
pkg/lib/authenticationflow/declarative/intent_signup_flow.go
pkg/lib/authenticationflow/declarative/utils_common.go
pkg/lib/authenticationflow/dependencies.go
pkg/lib/authenticationflow/rate_limit_middleware.go
pkg/lib/authn/authenticator/service/rate_limits.go
pkg/lib/authn/authenticator/service/service.go
pkg/lib/authn/mfa/service.go
pkg/lib/authn/otp/service.go
pkg/lib/feature/siwe/service.go
pkg/lib/feature/siwe/service_mock_test.go
pkg/lib/interaction/context.go
pkg/lib/interaction/nodes/do_create_user.go
pkg/lib/interaction/nodes/select_identity_end.go
pkg/lib/messaging/limits.go
pkg/lib/ratelimit/limiter.go
pkg/lib/ratelimit/limiter_global.go
pkg/lib/ratelimit/reservation.go
pkg/lib/workflow/dependencies.go
pkg/redisqueue/consumer.go

Fix rate limit in task queue does not work as expected

---

authui/src/authflowv2/components/image-input.css
authui/src/authflowv2/imageInput.ts
resources/authgear/templates/de/translation.json
resources/authgear/templates/el/translation.json
resources/authgear/templates/en/translation.json
resources/authgear/templates/en/web/authflowv2/__image_input.html
resources/authgear/templates/en/web/authflowv2/enter_face_image.html
resources/authgear/templates/es-419/translation.json
resources/authgear/templates/es-ES/translation.json
resources/authgear/templates/es/translation.json
resources/authgear/templates/fil/translation.json
resources/authgear/templates/fr/translation.json
resources/authgear/templates/id/translation.json
resources/authgear/templates/it/translation.json
resources/authgear/templates/ja/translation.json
resources/authgear/templates/ko/translation.json
resources/authgear/templates/ms/translation.json
resources/authgear/templates/nl/translation.json
resources/authgear/templates/pl/translation.json
resources/authgear/templates/pt-BR/translation.json
resources/authgear/templates/pt-PT/translation.json
resources/authgear/templates/pt/translation.json
resources/authgear/templates/th/translation.json
resources/authgear/templates/vi/translation.json
resources/authgear/templates/zh-CN/translation.json
resources/authgear/templates/zh-HK/translation.json
resources/authgear/templates/zh-TW/translation.json

ref DEV-2188
- Fix ios html video will auto-enter full screen
- Mirror camera and camera output
- Reduce image size (now ~700kb, can further improve)
- login no need click once more capture

[OpenCV FR] Handle mobile UX

---

authui/src/authflowv2/components/image-input.css
authui/src/authflowv2/imageInput.ts

ref DEV-2188
Fixes [these comments from fung](https://oursky.slack.com/archives/C03AH1ACM/p1729491741482999?thread_ts=1729250499.619599&cid=C03AH1ACM)
> 1. These sentences too seperated on mobile
> 2. When login, the camera should freeze when i press the "Capture and upload button" (Nice-to-have) (see video)
> 3. On mobile it's very easy to trigger image too small/quality too low error (see video)
[see slack](https://oursky.slack.com/archives/C03AH1ACM/p1729493931107979?thread_ts=1729250499.619599&cid=C03AH1ACM)

[OpenCV FR] Fix misc mobile UI issues

---

pkg/util/template/resource.go
resources/authgear/templates/en/web/authflowv2/settings_identity_verify_phone.html
resources/authgear/templates/en/web/authflowv2/settings_mfa_enter_oob_otp.html

Skip validating non-customizable templates

---

pkg/auth/handler/webapp/authflowv2/not_found.go
pkg/auth/handler/webapp/authflowv2/reset_password.go
pkg/auth/handler/webapp/authflowv2/settings.go
pkg/auth/handler/webapp/authflowv2/settings_delete_account.go
pkg/auth/handler/webapp/authflowv2/settings_profile.go
pkg/auth/handler/webapp/authflowv2/settings_profile_edit.go
pkg/auth/handler/webapp/authflowv2/settings_sessions.go
pkg/auth/handler/webapp/authflowv2/verify_login_link.go
pkg/portal/transport/graphql_handler.go
pkg/portal/wire_gen.go

Try to eliminate deadlocks

---

pkg/auth/webapp/cookie.go

Rename `web_session` cookie

---

authui/packages/vite-plugin-authgear-authui/src/index.js

Ensure css are not merged by turbo when switching between v1 and v2 ui

---

pkg/lib/userimport/model.go

Do not output summary if job is not completed

---

pkg/lib/config/session.go
pkg/lib/session/cookie.go
portal/src/graphql/portal/CookieLifetimeConfigurationScreen.tsx

Deprecate cookie_non_persistent

---

resources/authgear/templates/en/web/authflowv2/settings_mfa_password.html

Fix information about secondary password cannot be displayed

---

portal/src/components/applications/OAuthClientSAMLForm.tsx

UI updates of SAML portal

---

pkg/auth/handler/webapp/viewmodels/settings_profile.go

Deduplicate emails in settings profile

---

portal/src/components/applications/OAuthClientSAMLForm.tsx
portal/src/components/common/OutlinedActionButton.tsx
portal/src/graphql/adminapi/UserDetailsAdminActions.tsx
portal/src/locale-data/en.json

Update ui of application saml form download buttons

---

pkg/auth/handler/webapp/authflowv2/settings_mfa_create_oob_otp.go
pkg/auth/handler/webapp/authflowv2/settings_mfa_create_totp.go
resources/authgear/templates/en/web/authflowv2/settings_mfa_create_oob_otp.html
resources/authgear/templates/en/web/authflowv2/settings_mfa_create_totp.html

Back to 2fa page directly if no related authenticator exist

---

authui/.browserslistrc
pkg/admin/csp_middleware.go
pkg/auth/webapp/dynamic_csp_middleware_test.go
pkg/lib/web/csp.go
pkg/lib/web/csp_test.go
pkg/portal/csp_middleware.go
pkg/portal/routes.go
pkg/util/httputil/csp.go

Remove 'unsafe-inline'

---

postgres/Dockerfile
postgresql.conf

Set up pgaudit locally

---

custombuild/go.mod
custombuild/go.sum
e2e/go.mod
e2e/go.sum
go.mod
go.sum
pkg/lib/infra/db/hook_handle.go
pkg/lib/infra/db/pool.go
pkg/lib/infra/db/scanner.go
pkg/lib/infra/db/sql_executor.go
pkg/lib/infra/db/tx_conn.go
pkg/lib/oauth/pq/store_authz.go

Remove github.com/jmoiron/sqlx

---

.make-lint-translation-keys-expect
pkg/auth/handler/webapp/viewmodels/base.go
pkg/auth/handler/webapp/viewmodels/settings_profile.go
pkg/auth/webapp/result.go
pkg/auth/webapp/url.go
resources/authgear/templates/en/web/authflowv2/settings.html
resources/authgear/templates/en/web/authflowv2/settings_identity_edit_email.html
resources/authgear/templates/en/web/authflowv2/settings_identity_edit_phone.html
resources/authgear/templates/en/web/authflowv2/settings_identity_edit_username.html
resources/authgear/templates/en/web/authflowv2/settings_mfa.html
resources/authgear/templates/en/web/authflowv2/settings_mfa_create_oob_otp.html
resources/authgear/templates/en/web/authflowv2/settings_mfa_create_password.html
resources/authgear/templates/en/web/authflowv2/settings_mfa_create_totp.html

ref DEV-2248
- Added a query `q_from` to store the originating url, so that the back button can back to there.

Optimize navigations in settings in some special cases

---

pkg/auth/handler/webapp/authflowv2/not_found.go
pkg/auth/handler/webapp/not_found.go
pkg/auth/handler/webapp/renderer.go
pkg/auth/routes.go

Return a correct response on not found routes

---

portal/src/graphql/portal/AppsScreen.tsx
portal/src/graphql/portal/query/viewerQuery.ts

Fix viewer query is not refetched to reflect the lastest session state

---

authui/src/authflowv2/botprotection/cloudflareTurnstileError.ts

Do not auto retry on unusual visitor behavior error

---

e2e/tests/login/device_token/disabled_if_no_2fa/test.yaml
e2e/tests/login/device_token/disabled_if_no_2fa/users.json
pkg/lib/authenticationflow/declarative/intent_login_flow_step_authenticate.go
pkg/lib/authenticationflow/declarative/utils_common.go
pkg/lib/facade/coordinator.go

Do not allow using device token to login if no secondary authenticator exist

---

portal/src/locale-data/en.json

Mention SAML in confidential app description

---

pkg/auth/handler/webapp/authflowv2/select_account.go

Fix suppress idp session is not working correctly

---

pkg/lib/oauth/handler/handler_token.go

Fix incorrect context being used in handler_token.go

---

pkg/lib/userimport/job.go
pkg/lib/userimport/model.go
pkg/lib/userimport/service.go

Fix incorrect task import output

---

.vettedpositions
authui/packages/vite-plugin-authgear-authui/src/index.js
pkg/util/httputil/file_server.go
pkg/util/httputil/file_server_test.go

Fix /oauth-redirect is mistakenly handled as 404

---

pkg/portal/libstripe/model.go
pkg/portal/libstripe/service.go
pkg/portal/model/subscription.go
portal/src/components/billing/CurrentPlanCard.tsx
portal/src/components/billing/PlanCard.tsx
portal/src/graphql/portal/SubscriptionScreen.tsx
portal/src/locale-data/en.json
portal/src/util/plan.test.ts
portal/src/util/plan.ts

Switch to 2025 plans

---

.vettedpositions
pkg/auth/handler/webapp/authflow_controller.go
pkg/lib/saml/samlsession/ui.go

Fix client id is not populated to authflow session in saml flow

---

pkg/lib/config/configsource/resources.go
pkg/lib/config/feature_messaging.go
portal/src/BlueMessageBar.tsx
portal/src/graphql/portal/SMTPConfigurationScreen.tsx
portal/src/locale-data/en.json

Support disabling custom smtp

---

cmd/portal/cmd/cmdpricing/create_stripe_plans_2025.go
cmd/portal/cmd/cmdpricing/pricing.go

Just a script running once. Maybe we don't have to merge this pr.
ref DEV-2327

[DO NOT MERGE] Add script to create 2025 plans

---

.github/workflows/ci.yaml
custombuild/go.mod
custombuild/go.sum
e2e/go.mod
e2e/go.sum
go.mod
go.sum
packagetracker/.gitignore
packagetracker/Makefile
packagetracker/README.md
packagetracker/go.mod.tpl
pkg/lib/saml/samlprotocol/const.go
pkg/lib/saml/samlprotocol/duration.go
pkg/lib/saml/samlprotocol/metadata.go
pkg/lib/saml/samlprotocol/schema.go
pkg/lib/saml/samlprotocol/time.go
pkg/lib/saml/service.go

Remove github.com/crewjam/saml

---

CONTRIBUTING.md
pkg/lib/userexport/service.go

Some fixes for user export local setup

---

portal/src/graphql/portal/SubscriptionScreen.tsx

Hide manage subscription link if the project do not have a subscription

---

pkg/lib/config/configsource/resources.go
pkg/portal/deps.go
pkg/portal/service/app.go
pkg/portal/wire_gen.go

Propagate SMTP secret update to all projects in Authgear ONCE

---

authui/src/passkey.ts

Handle the misbehavior of Firefox present in passkey handling

---

portal/package-lock.json
portal/package.json
portal/src/AppRoot.tsx
portal/src/ErrorBoundSuspense.tsx
portal/src/FlavoredErrorBoundSuspense.module.css
portal/src/FlavoredErrorBoundSuspense.tsx
portal/src/ReactApp.tsx
portal/src/locale-data/en.json

ref DEV-2367
https://github.com/user-attachments/assets/493ab630-0d99-4be4-bfa0-92e7260ce6f5

Handle module load failure with reload button

---

authui/src/authflowv2.ts
authui/src/errors.ts

Ignore network errors

---

.vettedpositions
pkg/auth/deps.go
pkg/auth/handler/webapp/authflow_wechat.go
pkg/auth/handler/webapp/csrf_middleware.go
pkg/auth/handler/webapp/error_renderer.go
pkg/auth/handler/webapp/implementation_switcher.go
pkg/auth/handler/webapp/panic_middleware.go
pkg/auth/handler/webapp/setting_implementation_switcher.go
pkg/auth/handler/webapp/sso_callback.go
pkg/auth/handler/webapp/wechat_callback.go
pkg/auth/routes.go
pkg/auth/webapp/authflow_routes.go
pkg/auth/wire_handler.go
pkg/lib/config/ui.go
pkg/lib/endpoints/endpoints.go
pkg/lib/web/ui_implementation.go
portal/src/system-config.ts

Make v2 default without any settings

---

docs/specs/user-export.md
pkg/lib/userexport/model.go
pkg/lib/userexport/service.go

Expose delete_at in user export

---

.make-lint-translation-keys-expect
resources/authgear/templates/en/web/authflowv2/settings_identity_list_oauth.html

Fix provider alias is used as provider type

---

authui/src/authflowv2/components/watermark.css
portal/src/components/design/BorderRadius.tsx
portal/src/model/themeAuthFlowV2.ts
resources/authgear/templates/en/web/authflowv2/__watermark.html

Some authui fixes

---

portal/src/AppRoot.tsx
portal/src/ErrorBoundSuspense.tsx
portal/src/FlavoredErrorBoundSuspense.tsx
portal/src/ReactApp.tsx
portal/src/locale-data/en.json

Fix error boundary regression by using a simpler approach

---

.dockerignore
.gitignore
CONTRIBUTING.md
Makefile
flake.lock
flake.nix
portal/scripts/npm-postinstall.sh

I have been using Nix for some time. I am going to uninstall homebrew and asdf on my machine, so I need to make this repository support Nix.

Support Nix to setup development environment

---

custombuild/go.mod
custombuild/go.sum

Update authgear/iamsmart to 45db5c837ec26c3570a46797204a13fe7e63c741

---

pkg/auth/handler/webapp/authflow_forgot_password.go
pkg/auth/handler/webapp/authflowv2/forgot_password.go
pkg/auth/webapp/session_authflow.go
pkg/lib/authn/otp/errors.go
pkg/lib/authn/otp/sender.go
pkg/lib/infra/whatsapp/errors.go
pkg/lib/infra/whatsapp/on_premises.go
pkg/lib/infra/whatsapp/service.go
pkg/lib/messaging/sender.go
pkg/lib/oauth/handler/handler_token.go
pkg/lib/otelauthgear/metric.go
pkg/lib/session/idpsession/provider.go

ref DEV-2376
I've written down the investigation result of each error in the issue.
Most of them should be converted to metrics. Some need further investigation.

Fix or ignore some known errors

---

portal/src/AppRoot.tsx
portal/src/graphql/portal/AddSingleSignOnConfigurationScreen.tsx
portal/src/graphql/portal/EditSingleSignOnConfigurationScreen.tsx
portal/src/graphql/portal/SingleSignOnConfigurationScreen.tsx
portal/src/graphql/portal/SingleSignOnConfigurationWidget.tsx
portal/src/types.ts

Support multiple sso provider of same type

---

pkg/lib/messaging/limits.go
pkg/lib/usage/limit.go

Fix nil pointer exception when usage limit reached

---

pkg/lib/oauthrelyingparty/apple/provider.go
pkg/lib/oauthrelyingparty/apple/provider_test.go

Fix sign in with Apple client_secret has missing sub, and invalid aud

---

pkg/lib/web/embedded_resource.go
pkg/lib/web/embedded_resource_authgeardev.go
pkg/lib/web/embedded_resource_embed.go
pkg/lib/web/embedded_resource_embed_test.go
pkg/lib/web/embedded_resource_noauthgeardev.go
pkg/lib/web/embedded_resource_test.go
pkg/lib/web/embedded_resource_workdir.go
pkg/lib/web/embedded_resource_workdir_test.go
pkg/lib/web/testdata/embed/a/index.deadbeef.js
pkg/lib/web/testdata/embed/a/manifest.json

Fix container fail to start after PR4981

---

cmd/authgear/cmd/cmdaudit/audit.go
cmd/authgear/cmd/cmddatabase/database.go
cmd/portal/cmd/cmddatabase/database.go
pkg/lib/db/util/dump.go
pkg/lib/db/util/restore.go
pkg/lib/infra/db/appdb/deps.go
pkg/lib/infra/db/auditdb/deps.go
pkg/lib/infra/db/connection_options.go
pkg/lib/infra/db/globaldb/deps.go
pkg/lib/infra/db/hook_handle.go
pkg/lib/infra/db/pool.go
pkg/lib/infra/db/pool_test.go
pkg/lib/infra/db/searchdb/deps.go

Make purpose part of the pool key

---

.make-lint-translation-keys-expect
authui/src/authflowv2/components/widget.css
resources/authgear/templates/en/web/authflowv2/__settings_page_frame.html
resources/authgear/templates/en/web/authflowv2/settings_delete_account.html

Some settings ui fixes

---

.vettedpositions
pkg/auth/handler/webapp/alternatives.go
pkg/auth/handler/webapp/authflow_controller.go
pkg/auth/handler/webapp/authflow_wechat.go
pkg/auth/handler/webapp/authflowv2/routes.go
pkg/auth/handler/webapp/authflowv2/settings_change_password.go
pkg/auth/handler/webapp/authflowv2/settings_delete_account_success.go
pkg/auth/handler/webapp/authflowv2/verify_login_link.go
pkg/auth/handler/webapp/authflowv2/wechat.go
pkg/auth/handler/webapp/error_renderer.go
pkg/auth/handler/webapp/login_link_otp.go
pkg/auth/handler/webapp/panic_middleware.go
pkg/auth/handler/webapp/verify_login_link.go
pkg/auth/handler/webapp/wechat_auth.go
pkg/auth/routes.go
pkg/auth/webapp/authflow_routes.go
pkg/auth/webapp/result.go
pkg/auth/webapp/service2.go
pkg/auth/webapp/session_authflow.go
pkg/auth/webapp/session_middleware.go
pkg/lib/oauth/handler/handler_authz.go

Fix settings action always return error

---

portal/src/graphql/portal/DesignScreen/viewModel.ts

Fix portal design screen not showing authgear watermark in some cases

---

.env.example
cmd/portal/server/config.go
cmd/portal/server/server.go
pkg/lib/config/feature_messaging.go
pkg/lib/config/testdata/default_feature.yaml
pkg/lib/config/testdata/merge_feature.yaml
pkg/portal/config/portal_features.go
pkg/portal/deps/deps.go
pkg/portal/deps/providers.go
pkg/portal/model/system_config.go
pkg/portal/service/system_config.go
pkg/portal/wire_gen.go
portal/src/AppRoot.tsx
portal/src/ScreenNav.tsx
portal/src/graphql/portal/SMSProviderConfigurationScreen.tsx
portal/src/locale-data/en.json
portal/src/system-config.ts

ref DEV-2431
requires https://github.com/authgear/authgear-server/pull/4990

Add feature flags for custom sms gateways

---

.tool-versions
cmd/authgear/Dockerfile
cmd/portal/Dockerfile
custombuild/cmd/authgearx/Dockerfile
custombuild/cmd/portalx/Dockerfile
custombuild/go.mod
e2e/go.mod
flake.lock
flake.nix
go.mod
k6/go.mod
packagetracker/go.mod.tpl

Update go to 1.23.5

---

pkg/lib/authn/identity/oauth/provider.go
pkg/lib/authn/identity/oauth_identity.go
pkg/lib/authn/identity/oauth_identity_test.go
pkg/lib/oauthrelyingparty/apple/provider.go
pkg/lib/oauthrelyingparty/apple/provider_test.go

Handle "name" of Sign in with Apple

---

pkg/admin/graphql/session_mutation.go
portal/src/graphql/adminapi/globalTypes.generated.ts
portal/src/graphql/adminapi/schema.graphql

ref DEV-2470
https://github.com/IniZio/authgear-server/tree/DEV-2470-update-createSession-mutation-response-fields

Match createSession mutation response with token endpoint

---

.tool-versions
cmd/authgear/Dockerfile
cmd/portal/Dockerfile
custombuild/cmd/authgearx/Dockerfile
custombuild/cmd/portalx/Dockerfile
custombuild/go.mod
e2e/go.mod
flake.nix
go.mod
k6/go.mod
packagetracker/go.mod.tpl

I do not know how to update the nix files so I didn't modify them.

Update go to 1.23.6

---

.vettedpositions
pkg/auth/handler/webapp/alternatives.go
pkg/auth/handler/webapp/authflow_controller.go
pkg/auth/handler/webapp/authflowv2/select_account.go
pkg/auth/handler/webapp/confirm_terminate_other_sessions.go
pkg/auth/handler/webapp/controller.go
pkg/auth/handler/webapp/create_passkey.go
pkg/auth/handler/webapp/create_password.go
pkg/auth/handler/webapp/enter_oob_otp.go
pkg/auth/handler/webapp/enter_password.go
pkg/auth/handler/webapp/enter_recovery_code.go
pkg/auth/handler/webapp/enter_totp.go
pkg/auth/handler/webapp/forgot_password_success.go
pkg/auth/handler/webapp/login_link_otp.go
pkg/auth/handler/webapp/prompt_create_passkey.go
pkg/auth/handler/webapp/setup_login_link_otp.go
pkg/auth/handler/webapp/setup_oob_otp.go
pkg/auth/handler/webapp/setup_totp.go
pkg/auth/handler/webapp/setup_whatsapp_otp.go
pkg/auth/handler/webapp/use_passkey.go
pkg/auth/handler/webapp/verify_identity.go
pkg/auth/handler/webapp/wechat_auth.go
pkg/auth/handler/webapp/whatsapp_otp.go
portal/src/ScreenHeader.tsx
portal/src/ScreenNav.tsx
portal/src/hook/authgear.ts

Fix session expire error when opening settings

---

.vettedpositions
pkg/admin/routes.go
pkg/auth/handler/webapp/panic_middleware.go
pkg/auth/routes.go
pkg/images/routes.go
pkg/lib/otelauthgear/nethttp.go
pkg/lib/otelauthgear/nethttp_test.go
pkg/portal/routes.go
pkg/resolver/routes.go
pkg/util/otelutil/nethttp.go
pkg/util/otelutil/nethttp_test.go

Record metric even there is a panic

---

docs/specs/sms_gateway.md

Document sms gateway protocol

---

portal/src/graphql/portal/SMSProviderConfigurationScreen.tsx
portal/src/util/deno.ts

Update authgear_deno_hook version in portal templates

---

portal/src/graphql/portal/LoginMethodConfigurationScreen.tsx

Link to faq of libphonenumber directly

---

portal/src/Tooltip.tsx
portal/src/graphql/portal/DesignScreen/DesignScreen.tsx
portal/src/graphql/portal/GetStartedScreen.tsx
portal/src/hook/tester.ts
portal/src/locale-data/en.json

Add try button in design screen

---

pkg/latte/intent_login.go

Return available MFAs for latte's select MFA step

---

pkg/latte/intent_create_login_id.go

ref DEV-2519
Avoid passing phone number around, will use uistate in custom ui instead

Remove phone number hint output for latte account binding

---

portal/src/locale-data/en.json

Fix copy writing of try button hint

---

resources/authgear/templates/en/web/authflowv2/login.html
resources/authgear/templates/en/web/authflowv2/signup.html

Adjust layout spacing when there is only oauth option

---

portal/src/graphql/portal/SMTPConfigurationScreen.tsx

Retain smtp form states after switching provider

---

portal/src/Tooltip.module.css

Remove customized paddings from tooltip

---

portal/src/graphql/portal/SMSProviderConfigurationScreen.tsx

Add frontend validation for sender fields

---

authui/package-lock.json
authui/package.json
portal/package-lock.json
portal/package.json

https://github.com/advisories/GHSA-jr5f-v2jv-69x6

Bump axios to 1.8.2

---

portal/src/DefaultLayout.module.css
portal/src/DefaultLayout.tsx
portal/src/graphql/portal/AnalyticsScreen.tsx

Fix content container is not touching the screen end in default layout

---

cmd/portal/cmd/cmdinternal/collaborator.go
cmd/portal/cmd/cmdinternal/internal.go
cmd/portal/internal/collaborator.go
once/docker-entrypoint.sh

Dev 2564 collaborator commands

---

pkg/api/apierrors/error.go
pkg/api/apierrors/error_test.go
pkg/auth/handler/webapp/authflowv2/viewmodels/oauth_error.go
pkg/auth/handler/webapp/viewmodels/password_policy.go
pkg/latte/proofofphonenumberverification/webhook.go
pkg/lib/accountmigration/deno.go
pkg/lib/accountmigration/webhook.go
pkg/lib/authn/authenticator/password/error_test.go
pkg/lib/hook/hook_deno.go
pkg/lib/hook/hook_web.go
pkg/lib/ratelimit/error.go
pkg/lib/userexport/model_test.go
pkg/util/graphqlutil/api_error.go
pkg/util/httputil/json_test.go
pkg/util/template/funcerror.go

Fix apierror info is modified accidentally in AsAPIError

---

portal/src/OnboardingSurveyScreen.tsx

Fix initial country is not selected in onboarding survey

---

pkg/auth/handler/saml/handle_login_result.go
pkg/lib/config/config.go
pkg/lib/config/default_test.go
pkg/lib/config/jsonpointers.go
pkg/lib/config/saml.go
pkg/lib/config/testdata/config_tests.yaml
pkg/lib/saml/samlprotocol/const.go
pkg/lib/saml/samlprotocol/error.go
pkg/lib/saml/samlprotocol/error_unsupported_attribute_type.go
pkg/lib/saml/samlprotocol/schema.go
pkg/lib/saml/service.go
pkg/lib/saml/service_test.go

Implement SAML attribute mapping

---

portal/src/components/saml/AutoGenerateFirstCertificate.tsx

Do not mutate the app config directly which is an immutable object

---

.vettedpositions
pkg/lib/config/saml.go
pkg/lib/config/templates.go
pkg/lib/config/testdata/config_tests.yaml
pkg/lib/deps/deps_common.go
pkg/lib/saml/service.go
pkg/lib/saml/service_mock_test.go
pkg/lib/saml/service_test.go
pkg/util/template/engine.go
pkg/util/template/formats.go
pkg/util/template/formats_test.go
pkg/util/template/resource.go
pkg/util/template/template.go
pkg/util/template/text.go
pkg/util/template/text_test.go
pkg/util/template/validation.go
pkg/util/template/validation_test.go
pkg/util/validation/formats.go

ref DEV-2597
based on https://github.com/authgear/authgear-server/pull/5082

Support template SAML attribute

---

cmd/authgear/background/wire_gen.go
e2e/cmd/e2e/pkg/wire_gen.go
pkg/admin/wire_gen.go
pkg/lib/config/environment.go
pkg/lib/config/messaging_whatsapp.go
pkg/lib/config/testdata/default_config.yaml
pkg/lib/deps/deps_provider.go
pkg/lib/infra/whatsapp/cloud_api.go
pkg/lib/infra/whatsapp/on_premises.go
pkg/lib/infra/whatsapp/service.go
pkg/redisqueue/wire_gen.go
pkg/resolver/wire_gen.go

Support WHATSAPP_API_TYPE to change the default API type

---

cmd/portal/plan/service.go

Do not copy feature config to config source in command

---

portal/src/locale-data/en.json

Update copy writings of phone number validation options

---

portal/src/ErrorRenderer.tsx

Fix error message cannot be shown in fields

---

pkg/lib/config/feature_admin_api.go
pkg/lib/config/testdata/merge_feature.yaml

Merge admin_api feature config field-wise

---

authui/package-lock.json
authui/package.json
portal/package-lock.json
portal/package.json
portalgraphiql/package-lock.json
portalgraphiql/package.json

https://github.com/vitejs/vite/security/advisories/GHSA-4r4m-qw57-chr8

Bump vite to 6.2.4

---

CONTRIBUTING.md
docker-compose.yaml
e2e/Makefile
e2e/docker-compose.yaml
k6/docker-compose.yaml
k6/setup.sh

Remove postgres12 from local setup

---

resources/authgear/templates/en/web/authflowv2/settings_identity_verify_phone.html

Fix back is not working in settings verify phone

---

.vettedpositions
pkg/lib/infra/db/handle.go
pkg/lib/infra/db/hook_handle.go
pkg/lib/infra/db/pool.go
pkg/lib/infra/db/pool_test.go
pkg/lib/infra/db/prepared_statements_handle.go
pkg/util/otelutil/oteldatabasesql/instrumentation.go

Track connection use time and connection wait time

---

pkg/lib/analytic/posthog.go
pkg/util/timeutil/month.go
pkg/util/timeutil/month_test.go

Report MAU of previous to Posthog

---

pkg/lib/authenticationflow/declarative/generate_config_account_recovery_flow.go
pkg/lib/authenticationflow/declarative/intent_account_recovery_flow_step_identify.go
pkg/lib/config/authentication_flow.go

Ensure the runtime default of on_failure is ignore

---

.vettedpositions
pkg/api/apierrors/error.go
pkg/api/apierrors/kinds.go
pkg/auth/handler/webapp/authflow_controller.go
pkg/auth/handler/webapp/deps.go
pkg/auth/handler/webapp/error_renderer.go
pkg/lib/authenticationflow/declarative/error.go
pkg/lib/infra/sms/custom/client.go
pkg/lib/infra/sms/smsapi/api.go
pkg/lib/infra/sms/twilio/client.go
portal/src/components/sms-provider/TestSMSDialog.tsx
portal/src/error/parse.ts
portal/src/graphql/portal/SMSProviderConfigurationScreen.tsx
portal/src/locale-data/en.json

Handle more twilio errors

---

authui/package-lock.json
authui/package.json
portal/package-lock.json
portal/package.json
portalgraphiql/package-lock.json
portalgraphiql/package.json

https://github.com/advisories/GHSA-xcj6-pq6g-qj4x

Bump vite to 6.2.5

---

e2e/tests/latte/authgear.yaml
e2e/tests/latte/login.test.yaml
e2e/tests/latte/signup.test.yaml
e2e/tests/latte/user.sql
pkg/lib/authenticationflow/declarative/generate_config_signup_flow_test.go
pkg/lib/config/authentication_flow.go
pkg/lib/config/testdata/signup_flow_tests.yaml

More latte authflow fixes

---

.vettedpositions
pkg/auth/handler/oauth/challenge.go
pkg/auth/handler/oauth/challenge_test.go
pkg/lib/config/config.go

Add back missing validation

---

.tool-versions
cmd/authgear/Dockerfile
cmd/portal/Dockerfile
custombuild/cmd/authgearx/Dockerfile
custombuild/cmd/portalx/Dockerfile
custombuild/go.mod
e2e/go.mod
flake.nix
go.mod
k6/go.mod
once/Dockerfile
once/partial.dockerfile
packagetracker/go.mod.tpl

Update go to 1.24.2

---

authui/package-lock.json
authui/package.json
portal/package-lock.json
portal/package.json
portalgraphiql/package-lock.json
portalgraphiql/package.json

https://github.com/advisories/GHSA-356w-63v5-8wf4

Bump vite to 6.2.6

---

docs/specs/convention.md

Document configuration convention and violations

---

portal/src/graphql/adminapi/AddUserScreen.tsx
portal/src/graphql/portal/HookConfigurationScreen.module.css

Some portal ui fixes

---

packagetracker/go.mod.tpl
pkg/lib/saml/samlbinding/flate.go
pkg/lib/saml/samlprotocol/duration.go
pkg/lib/saml/samlprotocol/metadata.go
pkg/lib/saml/samlprotocol/schema.go
pkg/lib/saml/samlprotocol/time.go
pkg/lib/saml/samlprotocol/update_helper.go

The changes are irrelevant to us.
See https://github.com/crewjam/saml/compare/v0.5.0..v0.5.1

Bump crewjam/saml to 0.5.1

---

pkg/lib/messaging/sender.go

Always log delivery error immediately

---

docs/specs/sms_gateway.md

Document the implemented custom SMS request

---

portal/src/components/onboarding/OnboardingSurveyLayout.module.css
portal/src/components/onboarding/OnboardingSurveyLayout.tsx

- It seems the current bundler cannot handle image urls in css correctly

Fix onboarding background is missing

---

portal/src/graphql/portal/LoginMethodConfigurationScreen.tsx
portal/src/types.ts

Disable Whatsapp when it is Authgear ONCE

---

portal/src/ScreenNav.tsx
portal/src/graphql/portal/SMSProviderConfigurationScreen.tsx
portal/src/graphql/portal/SMTPConfigurationScreen.tsx
portal/src/locale-data/en.json

Remove the word "Custom" in SMTP and SMS provider in Authgear ONCE

---

portal/src/components/onboarding/OnboardingSurveyLayout.module.css

Set a background color even background image is not loaded

---

portal/.storybook/preview.tsx
portal/src/ReactApp.tsx
portal/src/components/common/AppLocaleProvider.tsx
portal/src/components/v2/TextField/TextField.tsx

Fix extra spaces appears in TextField when no icon is set

---

portal/src/ReactApp.tsx
portal/src/components/project-wizard/ProjectWizardLayout.module.css
portal/src/components/project-wizard/ProjectWizardLayout.tsx
portal/src/components/project-wizard/ProjectWizardStepper.module.css
portal/src/components/project-wizard/ProjectWizardStepper.tsx
portal/src/components/project-wizard/Text.module.css
portal/src/components/project-wizard/Text.tsx
portal/src/components/v2/FormField/FormField.module.css
portal/src/components/v2/FormField/FormField.tsx
portal/src/components/v2/TextField/TextField.module.css
portal/src/components/v2/TextField/TextField.stories.tsx
portal/src/components/v2/TextField/TextField.tsx
portal/src/locale-data/en.json
portal/src/screens/v2/ProjectWizard/ProjectWizardScreen.tsx
portal/src/screens/v2/ProjectWizard/Step1.tsx
portal/src/screens/v2/ProjectWizard/form.ts

Implement project wizard step 1 - UI only

---

portal/.stylelintrc.json
portal/src/components/v2/WhiteButton/WhiteButton.module.css
portal/src/components/v2/WhiteButton/WhiteButton.stories.ts
portal/src/components/v2/WhiteButton/WhiteButton.tsx
portal/src/screens/v2/OnboardingSurvey/Start.tsx
portal/src/screens/v2/OnboardingSurvey/Step1.tsx
portal/src/screens/v2/OnboardingSurvey/Step2.tsx
portal/src/screens/v2/OnboardingSurvey/Step3.tsx
portal/src/screens/v2/OnboardingSurvey/Step4.tsx

Implement WhiteButton

---

.github/workflows/authgear-once.yaml
Makefile
cmd/once/cmdonce/cmdsetup/cobra.go
cmd/once/cmdonce/cmdsetup/tea.go
cmd/once/cmdonce/cmdstart/cobra.go
cmd/once/cmdonce/cmdstop/cobra.go
cmd/once/cmdonce/cmdupgrade/cobra.go
cmd/once/cmdonce/cmdversion/cobra.go
cmd/once/cmdonce/cobra.go
cmd/once/cmdonce/internal/cobra.go
cmd/once/cmdonce/internal/constants_local.go
cmd/once/cmdonce/internal/constants_production.go
cmd/once/cmdonce/internal/constants_staging.go
cmd/once/cmdonce/internal/docker.go
cmd/once/cmdonce/internal/error.go
cmd/once/cmdonce/internal/license.go
cmd/once/cmdonce/internal/machine_fingerprint.go
cmd/once/cmdonce/internal/machine_fingerprint_test.go
cmd/once/cmdonce/internal/tea.go
once/docker-entrypoint.sh
pkg/util/termutil/termutil.go

Check and activate license

---

cmd/once/cmdonce/cmdsetup/tea.go
cmd/once/cmdonce/internal/docker.go

Add --restart=always to ensure the container restarts along with daemon

---

cmd/once/cmdonce/cmdsetup/cobra.go
cmd/once/cmdonce/cmdsetup/tea.go
cmd/once/cmdonce/cmdstart/cobra.go
cmd/once/cmdonce/internal/docker.go
once/docker-entrypoint.sh

Persist the actually used image in the container volume

---

portal/src/components/v2/PrimaryButton/PrimaryButton.tsx
portal/src/components/v2/SecondaryButton/SecondaryButton.tsx
portal/src/components/v2/TextButton/TextButton.module.css
portal/src/components/v2/TextButton/TextButton.stories.tsx
portal/src/components/v2/TextButton/TextButton.tsx
portal/src/components/v2/WhiteButton/WhiteButton.tsx

ref DEV-2660
Related commit: [b61b0a3](https://github.com/authgear/authgear-server/pull/5163/commits/b61b0a3910fd85f5f5a6c5c331d825427408cfbd)

Reimplement TextButton without radix

---

.vettedpositions
once/bashrc
once/nginx/nginx.conf.sample
once/nginx/snippets/authgear_location.conf
pkg/portal/config/authgear.go
pkg/portal/session/middleware_session_info.go

Fix portal session middleware cannot access Authgear in ONCE

---

portal/src/locale-data/en.json

Update copywriting of project wizard

---

.vettedpositions
cmd/once/cmdonce/cmdsetup/tea.go
pkg/lib/oauthrelyingparty/oauthrelyingpartyutil/oidc.go
pkg/lib/oauthrelyingparty/oauthrelyingpartyutil/oidc_test.go
pkg/portal/session/middleware_session_info.go

Use AUTHGEAR_ENDPOINT_INTERNAL to rewrite openid discovery document

---

.vettedpositions
pkg/auth/deps.go
pkg/auth/handler/webapp/authflowv2/deps.go
pkg/auth/handler/webapp/authflowv2/noproject_preview_widget.go
pkg/auth/handler/webapp/viewmodels/base.go
pkg/auth/routes.go
pkg/auth/wire_handler.go
resources/authgear/templates/en/web/authflowv2/preview_widget.html

Add preview widget route

---

portal/src/components/v2/ColorPickerField/ColorPickerField.tsx
portal/src/components/v2/FormField/FormField.stories.tsx
portal/src/components/v2/ImageInput/ImageInput.module.css
portal/src/components/v2/ImageInput/ImageInput.tsx
portal/src/components/v2/TextArea/TextArea.tsx

Chromatic review UI fixes

---

portal/src/index.html
portal/vite.config.ts

Ensure fluent ui style placeholder is at the end

---

pkg/lib/config/identity.go
pkg/lib/config/schema_test.go
pkg/lib/config/secret.go
pkg/lib/config/testdata/config_tests.yaml
pkg/lib/config/testdata/default_config.yaml
pkg/lib/config/testdata/secret_config_validate_tests.yaml
pkg/lib/interaction/nodes/use_identity_oauth_provider.go

Allow oauth provider configs to be inactive

---

cmd/once/cmdonce/cobra.go

Hide subcommand `completion`

---

once/Dockerfile
once/docker-entrypoint.sh
once/partial.dockerfile
once/project-resources/authgear.features.yaml

Enable custom UI and app2app for ONCE project

---

cmd/once/cmdonce/cmdsetup/questions.go

Fix typo in once setup command

---

.vettedpositions
cmd/authgear/background/wire_gen.go
cmd/authgear/elasticsearch/wire_gen.go
cmd/authgear/pgsearch/wire_gen.go
e2e/cmd/e2e/pkg/wire_gen.go
pkg/admin/wire_gen.go
pkg/auth/handler/webapp/authflowv2/settings_identity_list_oauth.go
pkg/lib/authn/identity/candidate.go
pkg/lib/authn/identity/service/service.go
pkg/lib/authn/identity/service/service_test.go
pkg/lib/interaction/nodes/use_identity_oauth_provider.go
pkg/redisqueue/wire_gen.go
pkg/resolver/wire_gen.go

Fix settings cannot connect demo oauth providers

---

.vettedpositions
pkg/auth/handler/webapp/authflow_wechat.go
pkg/auth/handler/webapp/authflowv2/wechat.go
pkg/auth/handler/webapp/wechat_callback.go
pkg/auth/webapp/session_authflow.go

Use HandleOAuthCallback in handling wechat callback

---

e2e/tests/admin_api/create_user_test.go
pkg/admin/facade/user.go
pkg/admin/graphql/context.go
pkg/admin/graphql/user_mutation.go
pkg/lib/facade/coordinator.go
pkg/lib/facade/user.go
portal/src/graphql/adminapi/AddUserScreen.tsx
portal/src/graphql/adminapi/globalTypes.generated.ts
portal/src/graphql/adminapi/schema.graphql

Slightly change the meaning of `password` in createUser mutation

---

.github/workflows/run-checks.yaml

NPM_AUDIT_LEVEL is ineffective in pr checks

Set AUDIT_LEVEL in workflows

---

pkg/auth/handler/webapp/viewmodels/settings.go
resources/authgear/templates/en/web/authflowv2/settings_mfa.html

Display MFA settings if user has one corresponding authenticator

---

pkg/api/event/event_payload.go
pkg/api/event/hook_response.go
pkg/api/model/amr.go
pkg/api/model/authentication.go
pkg/lib/authenticationflow/declarative/data_authenticate_option.go
pkg/lib/authenticationflow/declarative/data_create_authenticator_option.go
pkg/lib/authenticationflow/declarative/node_did_reauthenticate.go
pkg/lib/authenticationflow/declarative/node_do_consume_recovery_code.go
pkg/lib/authenticationflow/declarative/node_do_create_session.go
pkg/lib/authenticationflow/declarative/node_do_use_device_token.go
pkg/lib/authenticationflow/declarative/utils_amr.go
pkg/lib/authenticationflow/declarative/utils_amr_test.go
pkg/lib/authenticationflow/declarative/utils_event.go
pkg/lib/authenticationflow/declarative/utils_event_test.go
pkg/lib/authn/authenticator/info.go
pkg/lib/interaction/graph_test.go

ref DEV-2787
requires https://github.com/authgear/authgear-server/pull/5238

Add amr values for each authentication

---

resources/authgear/templates/en/web/authflowv2/settings_mfa_view_recovery_code.html

Fix settings recovery code screen cannot back

---

pkg/lib/authenticationflow/accept.go
pkg/lib/authenticationflow/declarative/intent_account_recovery_flow_step_verify_account_recovery_code.go
pkg/lib/authenticationflow/declarative/node_authn_oob.go
pkg/lib/authenticationflow/declarative/node_verify_claim.go
pkg/lib/authenticationflow/errors.go
pkg/lib/authenticationflow/input.go
pkg/lib/authenticationflow/testdata_simplified_test.go

Document InputReactor can mutate the flow and node

---

portal/src/CodeEditor.tsx

Fix deno types cannot be loaded in monaco

---

.make-lint-translation-keys-expect
authui/src/authflowv2/components/dialog.css
resources/authgear/templates/en/web/authflowv2/__bot_protection_dialog.html

Add a cancel button to bot protection dialog

---

pkg/lib/config/configsource/resources.go
pkg/lib/config/feature_oauth.go
pkg/lib/config/testdata/default_feature.yaml
pkg/lib/config/testdata/merge_feature.yaml
pkg/lib/oauth/handler/handler_token.go

Support overriding keys in oauth.client feature config

---

portal/src/ScreenNav.tsx
portal/src/graphql/portal/EditConfigurationScreen.tsx
portal/src/locale-data/en.json

Add edit config to portal

---

portal/src/AppRoot.tsx
portal/src/components/users/ResetPasswordForm.module.css
portal/src/components/users/ResetPasswordForm.tsx
portal/src/graphql/adminapi/AddPasswordScreen.module.css
portal/src/graphql/adminapi/AddPasswordScreen.tsx
portal/src/graphql/adminapi/UserDetailsAccountSecurity.tsx
portal/src/locale-data/en.json

ref DEV-2811
https://github.com/user-attachments/assets/4b5e5e8b-20ed-4e9d-9801-52067b5ace32

Allow creating password in portal even the user has no password

---

portal/src/util/deno.ts

Update deno types to 1.6.1

---

resources/authgear/templates/en/web/authflowv2/settings.html

Show /settings/identity/oauth only when there is at least 1 oauth

---

authui/src/authflowv2/components/layout.css

Fix padding is missing in layout

---

.vettedpositions
custombuild/go.mod
custombuild/go.sum
go.mod
go.sum
nginx.conf
pkg/admin/routes.go
pkg/admin/transport/handler_graphql.go
pkg/api/apierrors/error.go
pkg/api/apierrors/error_test.go
pkg/portal/routes.go
pkg/portal/transport/graphql_handler.go
pkg/util/graphqlutil/handler.go
pkg/util/log/skip_logging.go
pkg/util/log/skip_logging_test.go
portal/src/ImageFilePicker.tsx
portal/src/ThemeConfigurationWidget.tsx
portal/src/components/common/BaseImagePicker.tsx
portal/src/components/design/AppLogoPicker.tsx
portal/src/components/design/ImagePicker.tsx
portal/src/components/v2/ImageInput/ImageInput.module.css
portal/src/components/v2/ImageInput/ImageInput.stories.tsx
portal/src/components/v2/ImageInput/ImageInput.tsx
portal/src/error/resources.ts
portal/src/graphql/portal/DesignScreen/DesignScreen.tsx
portal/src/graphql/portal/UISettingsScreen.tsx
portal/src/locale-data/en.json
portal/src/screens/v2/ProjectWizard/Step3.tsx

ref DEV-2845
ref DEV-2834
https://github.com/user-attachments/assets/abc1767f-2bc0-4d87-9fc0-d88fc06d5a6b

Improve error handling in request too large in portal

---

pkg/lib/authenticationflow/declarative/node_do_create_passkey.go

Fix identity spec was nil when create passkey

---

portal/src/components/common/Accordion.module.css
portal/src/components/common/Accordion.tsx
portal/src/graphql/portal/EditOAuthClientForm.tsx
portal/src/locale-data/en.json

ref DEV-2625
https://github.com/user-attachments/assets/35f519dd-dbf0-4fd7-b740-cd024c40a12d

Use accordion to hide post login uris

---

CONTRIBUTING.md
hack/custom-resources/authgear.secrets.yaml
pkg/portal/service/audit.go
pkg/portal/service/deps.go
pkg/portal/service/wire.go
pkg/portal/service/wire_gen.go
pkg/portal/wire_gen.go

Fix portal audit logs are not using the correct audit db

---

portal/src/graphql/portal/HookConfigurationScreen.tsx
portal/src/locale-data/en.json

Add example code to hook events

---

authui/package-lock.json
authui/package.json
portal/package-lock.json
portal/package.json

https://github.com/authgear/authgear-server/security/dependabot/231
https://github.com/authgear/authgear-server/security/dependabot/232

Bump axios to 1.11.0

---

portal/src/AppRoot.tsx
portal/src/PaginationWidget.tsx
portal/src/ScreenContentHeader.module.css
portal/src/ScreenContentHeader.tsx
portal/src/ScreenNav.tsx
portal/src/components/api-resources/CreateResourceButton.tsx
portal/src/components/api-resources/DeleteResourceDialog.tsx
portal/src/components/api-resources/ResourceList.module.css
portal/src/components/api-resources/ResourceList.tsx
portal/src/components/api-resources/ResourceListEmptyView.module.css
portal/src/components/api-resources/ResourceListEmptyView.tsx
portal/src/graphql/adminapi/mutations/deleteResourceMutation.generated.ts
portal/src/graphql/adminapi/mutations/deleteResourceMutation.graphql
portal/src/graphql/adminapi/query/resourcesQuery.generated.ts
portal/src/graphql/adminapi/query/resourcesQuery.graphql
portal/src/locale-data/en.json
portal/src/screens/APIResources/APIResourcesScreen.tsx

[Portal] API Resources Listing

---

portal/src/AppRoot.tsx
portal/src/NavBreadcrumb.tsx
portal/src/PaginationWidget.tsx
portal/src/ScreenContentHeader.module.css
portal/src/ScreenContentHeader.tsx
portal/src/ScreenNav.tsx
portal/src/components/api-resources/CreateResourceButton.tsx
portal/src/components/api-resources/DeleteResourceDialog.tsx
portal/src/components/api-resources/ResourceForm.module.css
portal/src/components/api-resources/ResourceForm.tsx
portal/src/components/api-resources/ResourceList.module.css
portal/src/components/api-resources/ResourceList.tsx
portal/src/components/api-resources/ResourceListEmptyView.module.css
portal/src/components/api-resources/ResourceListEmptyView.tsx
portal/src/error/error.ts
portal/src/formatting.css
portal/src/graphql/adminapi/mutations/createResourceMutation.generated.ts
portal/src/graphql/adminapi/mutations/createResourceMutation.graphql
portal/src/graphql/adminapi/mutations/deleteResourceMutation.generated.ts
portal/src/graphql/adminapi/mutations/deleteResourceMutation.graphql
portal/src/graphql/adminapi/query/resourcesQuery.generated.ts
portal/src/graphql/adminapi/query/resourcesQuery.graphql
portal/src/hook/useSimpleForm.ts
portal/src/index.css
portal/src/locale-data/en.json
portal/src/screens/APIResources/APIResourceDetailsScreen.tsx
portal/src/screens/APIResources/APIResourcesScreen.tsx
portal/src/screens/APIResources/CreateAPIResourceScreen.tsx

ref DEV-2894
https://github.com/user-attachments/assets/962c72aa-31ba-43ca-a19c-8e23a7b7a8cb

[Portal] Create Resource

---

docs/specs/event.md
pkg/admin/graphql/audit_log.go
pkg/api/event/nonblocking/user_reauthenticated.go
pkg/latte/intent_login.go
pkg/latte/intent_migrate.go
pkg/latte/intent_signup.go
pkg/latte/node_do_ensure_session.go
pkg/lib/authenticationflow/declarative/intent_login_flow.go
pkg/lib/authenticationflow/declarative/intent_signup_flow.go
pkg/lib/authenticationflow/declarative/node_did_reauthenticate.go
pkg/lib/authenticationflow/declarative/node_do_create_session.go
pkg/lib/config/hook.go
pkg/lib/config/testdata/config_tests.yaml
pkg/lib/config/testdata/hook_tests.yaml
pkg/lib/oauth/handler/handler_token.go
pkg/lib/oauth/redis/store.go
pkg/util/slogutil/named_logger.go
pkg/util/slogutil/named_logger_test.go
pkg/util/slogutil/skip_logging_handler.go
pkg/util/slogutil/skip_logging_handler_test.go
portal/src/graphql/adminapi/globalTypes.generated.ts
portal/src/graphql/adminapi/schema.graphql
portal/src/locale-data/en.json

Add user.reauthenticated and do not update last login in reauthentication

---

.claude/commands/add_portal_admin_api_mutation.md
.claude/commands/add_portal_admin_api_query.md
e2e/tests/m2m/token.test.yaml
e2e/tests/m2m/unassigned_client_fixture.sql
pkg/lib/resourcescope/commands.go
pkg/lib/resourcescope/store_scope.go
portal/src/AppRoot.tsx
portal/src/components/api-resources/ApplicationList.tsx
portal/src/components/api-resources/EditApplicationScopesList.module.css
portal/src/components/api-resources/EditApplicationScopesList.tsx
portal/src/components/api-resources/UnauthorizeApplicationDialog.tsx
portal/src/graphql/adminapi/AuditLogScreen.tsx
portal/src/graphql/adminapi/GroupsScreen.tsx
portal/src/graphql/adminapi/RolesScreen.tsx
portal/src/graphql/adminapi/UsersScreen.tsx
portal/src/graphql/adminapi/mutations/replaceScopesOfClientID.generated.ts
portal/src/graphql/adminapi/mutations/replaceScopesOfClientID.graphql
portal/src/graphql/adminapi/query/getClientResourceScopes.generated.ts
portal/src/graphql/adminapi/query/getClientResourceScopes.graphql
portal/src/graphql/adminapi/query/resourceScopesQuery.generated.ts
portal/src/graphql/adminapi/query/resourceScopesQuery.graphql
portal/src/locale-data/en.json
portal/src/screens/api-resources/APIResourceDetailsScreenApplicationsTab.tsx
portal/src/screens/api-resources/APIResourceDetailsScreenScopesTab.tsx
portal/src/screens/api-resources/APIResourcesScreen.tsx
portal/src/screens/api-resources/EditApplicationScopesScreen.tsx
portal/src/screens/api-resources/EditScopeScreen.tsx
portal/src/util/pagination.test.ts
portal/src/util/pagination.ts

ref DEV-2898
https://github.com/user-attachments/assets/53db2f77-f7ac-4fd7-bc2e-fd421b347eea

[Portal] Application scopes

---

.vettedpositions
pkg/auth/webapp_request_middleware.go
pkg/images/deps/middleware_request.go
pkg/lib/deps/middleware_request.go
pkg/util/graphqlutil/api_error.go

Remove force logging

---

portal/src/components/api-resources/ApplicationResourcesList.tsx
portal/src/components/api-resources/EditApplicationScopesList.tsx
portal/src/graphql/portal/EditOAuthClientForm.tsx
portal/src/graphql/portal/EditOAuthClientFormResourcesContent.module.css
portal/src/graphql/portal/EditOAuthClientFormResourcesContent.tsx
portal/src/graphql/portal/EditOAuthClientScreen.tsx
portal/src/hook/usePivot.ts
portal/src/locale-data/en.json
portal/src/screens/api-resources/EditOAuthClientResourceScopeScreen.tsx

[Portal] Relayout m2m resource section

---

.vettedpositions
custombuild/go.mod
custombuild/go.sum
e2e/go.mod
e2e/go.sum
go.mod
go.sum
pkg/lib/otelauthgear/metric.go
pkg/lib/otelauthgear/nethttp.go
pkg/lib/otelauthgear/nethttp_test.go
pkg/util/otelutil/nethttp.go
pkg/util/otelutil/oteldatabasesql/instrumentation.go
pkg/util/otelutil/otelredis.go
pkg/util/otelutil/setup.go

Add instrumentation on runtime

---

cmd/portal/analytic/wire_gen.go
pkg/admin/graphql/audit_log.go
pkg/admin/wire_gen.go
pkg/api/event/nonblocking/m2m_token_created.go
pkg/lib/analytic/posthog.go
pkg/lib/config/secret_data.go
pkg/lib/config/secret_data_test.go
pkg/lib/oauth/handler/handler_token.go
pkg/lib/oauth/handler/service_token.go
pkg/portal/service/onboard.go
pkg/util/timeutil/range.go
pkg/util/timeutil/range_test.go
portal/src/graphql/adminapi/globalTypes.generated.ts
portal/src/graphql/adminapi/schema.graphql
portal/src/locale-data/en.json

Count m2m token generated

---

cmd/portal/analytic/wire_gen.go
pkg/admin/graphql/audit_log.go
pkg/admin/wire_gen.go
pkg/api/event/nonblocking/m2m_token_created.go
pkg/lib/analytic/posthog.go
pkg/lib/config/secret_data.go
pkg/lib/config/secret_data_test.go
pkg/lib/oauth/handler/handler_token.go
pkg/lib/oauth/handler/service_token.go
pkg/portal/service/onboard.go
pkg/util/timeutil/range.go
pkg/util/timeutil/range_test.go
portal/src/ScreenContent.module.css
portal/src/graphql/adminapi/globalTypes.generated.ts
portal/src/graphql/adminapi/schema.graphql
portal/src/graphql/portal/EditOAuthClientFormQuickStartContent.module.css
portal/src/graphql/portal/EditOAuthClientFormQuickStartContent.tsx
portal/src/graphql/portal/EditOAuthClientScreen.tsx
portal/src/locale-data/en.json

[Portal] M2M Quick Start

---

portal/src/screens/api-resources/APIResourceDetailsScreenScopesTab.tsx

Fix added scopes are not shown in list

---

pkg/auth/deps.go
pkg/auth/handler/oauth/token.go
pkg/lib/config/configsource/resources.go
pkg/lib/config/oauth.go
pkg/lib/config/testdata/config_tests.yaml
pkg/lib/deps/deps_common.go
pkg/lib/oauth/handler/handler_authz.go
pkg/lib/oauth/handler/handler_token.go
pkg/lib/oauth/handler/handler_token_mock_test.go
pkg/lib/oauth/handler/handler_token_test.go
pkg/lib/oauth/handler/ratelimit.go
pkg/lib/oauth/handler/service_settings_action_grant.go
pkg/lib/oauth/settings_action_code.go
pkg/lib/ratelimit/ratelimits.go
pkg/lib/ratelimit/ratelimits_test.go
pkg/lib/ratelimit/reservation.go

ref DEV-2917
ref DEV-2919
ref DEV-2907

Add rate limits to token endpoint

---

pkg/lib/event/service.go

Do not use session user id as event context user id

---

portal/src/graphql/portal/EditOAuthClientForm.tsx
portal/src/locale-data/en.json

Show tooltip to explain why issue jwt toggle is disabled

---

pkg/lib/analytic/posthog.go

Fix m2m token count name of posthog group

---

portal/src/locale-data/en.json
portal/src/screens/api-resources/APIResourceDetailsScreenApplicationsTab.tsx

Do not display confidential app in api resource application list

---

portal/src/components/api-resources/APIResourceScreenLayout.tsx
portal/src/graphql/portal/Authenticated.tsx
portal/src/graphql/portal/CreateOAuthClientScreen.tsx
portal/src/graphql/portal/EditOAuthClientForm.tsx
portal/src/graphql/portal/EditOAuthClientFormQuickStartContent.tsx
portal/src/graphql/portal/EditOAuthClientScreen.tsx
portal/src/locale-data/en.json
portal/src/screens/api-resources/APIResourceDetailsScreenTestTab.tsx

ref DEV-2958
ref DEV-2954
ref DEV-2956
ref DEV-2957
ref DEV-2955

Portal ui/ux updates of m2m related screens

---

pkg/lib/oauth/handler/handler_anonymous_user.go
pkg/lib/oauth/handler/handler_token.go

Return a better error message when trying to use anonymous user in supported application

---

portal/src/components/api-resources/ResourceList.tsx
portal/src/components/common/TextWithCopyButton.module.css
portal/src/components/common/TextWithCopyButton.tsx
portal/src/components/roles-and-groups/list/GroupsList.tsx
portal/src/components/roles-and-groups/list/RolesList.tsx
portal/src/components/roles-and-groups/list/common/TextCell.tsx
portal/src/screens/api-resources/APIResourcesScreen.tsx

Some ux updates in detail lists

---

portal/src/EditCustomAttributeForm.tsx
portal/src/error/parse.ts
portal/src/graphql/portal/CreateOAuthClientScreen.tsx
portal/src/graphql/portal/EditOAuthClientForm.tsx
portal/src/graphql/portal/LockoutSettings.tsx
portal/src/graphql/portal/LoginMethodConfigurationScreen.tsx
portal/src/locale-data/en.json

Use custom error message for access token lifetime

---

portal/src/locale-data/en.json
portal/src/screens/api-resources/APIResourceDetailsScreenTestTab.tsx

Display selected client name in test

---

pkg/lib/authenticationflow/declarative/intent_authn_oob.go
pkg/lib/authenticationflow/declarative/intent_verify_claim.go
pkg/lib/authenticationflow/declarative/node_authn_oob.go
pkg/lib/authenticationflow/declarative/node_verify_claim.go

Put only the send-code operation in delayed one time function

---

.vettedpositions
e2e/cmd/proxy/mockoidc/encryption.go
e2e/tests/external_jwt/invalid_login_ids.test.yaml
e2e/tests/external_jwt/signup.test.yaml
e2e/var/authgear.yaml
pkg/lib/authenticationflow/declarative/input_interface.go
pkg/lib/authenticationflow/declarative/input_step_identify.go
pkg/lib/authenticationflow/declarative/input_take_login_id.go
pkg/lib/authenticationflow/declarative/intent_create_identity_login_id.go
pkg/lib/authenticationflow/declarative/intent_signup_flow_step_identify.go
pkg/lib/authenticationflow/dependencies.go
pkg/lib/config/config.go
pkg/lib/config/external_jwt.go
pkg/lib/config/testdata/config_tests.yaml
pkg/lib/config/testdata/default_config.yaml
pkg/lib/deps/deps_common.go
pkg/lib/deps/deps_config.go
pkg/lib/deps/deps_provider.go
pkg/lib/deps/providers.go
pkg/lib/externaljwt/deps.go
pkg/lib/externaljwt/errors.go
pkg/lib/externaljwt/service.go

Support using external_jwt to signup

---

custombuild/go.mod
custombuild/go.sum
e2e/go.mod
e2e/go.sum
go.mod
go.sum

https://github.com/advisories/GHSA-2464-8j7c-4cjm

Update github.com/go-viper/mapstructure/v2 to v2.4.0

---

.claude/commands/update_vettedpositions.md
.vettedpositions
pkg/auth/handler/oauth/authorize.go
pkg/lib/oauth/handler/handler_authz.go
pkg/lib/oauth/handler/handler_authz_test.go
pkg/lib/oauth/handler/handler_token.go
pkg/lib/oauth/handler/result_authz.go

Open database connection only on valid request received

---

pkg/latte/intent_login.go
pkg/latte/intent_migrate.go
pkg/latte/intent_signup.go
pkg/lib/authenticationflow/declarative/intent_login_flow.go
pkg/lib/authenticationflow/declarative/intent_signup_flow.go
pkg/lib/interaction/nodes/do_ensure_session.go
pkg/lib/oauth/handler/handler_token.go
pkg/lib/oauth/redis/store.go
pkg/lib/session/idpsession/store_redis.go

Add more logs about session

---

.vettedpositions
pkg/admin/graphql/user_mutation.go
pkg/auth/handler/webapp/authflowv2/reset_password.go
pkg/auth/handler/webapp/authflowv2/reset_password_success.go
pkg/lib/authenticationflow/declarative/data_new_password.go
pkg/lib/authenticationflow/declarative/intent_account_recovery_flow.go
pkg/lib/authenticationflow/declarative/intent_account_recovery_flow_step_reset_password.go
pkg/lib/authenticationflow/declarative/intent_account_recovery_flow_step_verify_account_recovery_code.go
pkg/lib/authenticationflow/declarative/intent_login_flow.go
pkg/lib/authenticationflow/declarative/intent_promote_flow.go
pkg/lib/authenticationflow/declarative/intent_reauth_flow.go
pkg/lib/authenticationflow/declarative/intent_signup_flow.go
pkg/lib/authenticationflow/declarative/intent_signup_login_flow.go
pkg/lib/authenticationflow/declarative/milestone.go
pkg/lib/authenticationflow/declarative/node_use_account_recovery_code.go
pkg/lib/authenticationflow/declarative/utils_common.go
pkg/lib/authenticationflow/flow.go
pkg/lib/authenticationflow/flow_test.go
pkg/lib/authn/otp/service.go
pkg/lib/authn/otp/state.go

Support admin api forgot password in authflow

---

e2e/tests/issue_DEV_3005_identify_with_phone_authenticate_with_email/test.yaml
e2e/tests/issue_DEV_3005_identify_with_phone_authenticate_with_email/user.sql

Add e2e test for DEV-3005

---

pkg/latte/intent_login.go
pkg/latte/intent_migrate.go
pkg/latte/intent_signup.go
pkg/lib/authenticationflow/declarative/intent_login_flow.go
pkg/lib/authenticationflow/declarative/intent_signup_flow.go
pkg/lib/interaction/nodes/do_ensure_session.go
pkg/lib/oauth/handler/handler_token.go
pkg/lib/oauth/handler/service_token.go
pkg/lib/oauth/redis/store.go
pkg/lib/session/idpsession/store_redis.go

Log error cases of refresh token

---

authui/package-lock.json
authui/package.json
portal/package-lock.json
portal/package.json
portalgraphiql/package-lock.json
portalgraphiql/package.json

https://github.com/advisories/GHSA-jqfw-vq24-v9c3
https://github.com/advisories/GHSA-g4jq-h2w9-997c

Bump vite to 6.3.6

---

portal/src/graphql/adminapi/UserDetailsAccountSecurity.tsx
portal/src/locale-data/en.json
portal/src/types.ts

Handle 2fa grace period correctly in portal

---

pkg/lib/authn/otp/sender.go

ref DEV-3074
The channel is not set in the code if we use email or phone, therefore it is always "sending".

Fix otp code channel not updated after sending sms and email
