authgear/authgear-server

- pkg/auth/config/config.go
- pkg/auth/config/secret.go
- pkg/auth/config/server.go
- pkg/auth/config/source/errors.go
- pkg/auth/config/source/local_file.go
- pkg/auth/config/source/source.go
- pkg/auth/config/testdata/config_tests.yaml
- pkg/auth/config/testdata/hook_tests.yaml
- pkg/auth/config/testdata/messaging_tests.yaml
- pkg/auth/config/testdata/secret_tests.yaml
- pkg/httputil/host.go
- pkg/validation/error.go
- pkg/validation/value_test.go
> Add local configuration source

- pkg/auth/config/config.go
- pkg/auth/config/identity.go
- pkg/auth/config/schema.go
- pkg/auth/config/schema_test.go
- pkg/auth/config/testdata/config_tests.yaml
- pkg/auth/config/testdata/default_config.yaml
- pkg/validation/schema.go
> Fix and restructure OAuth SSO config

- docs/spec.md
Consolidate and reorganize the relevant parts of https://github.com/skygeario/features into a single document
> Consolidate feature documents

- pkg/auth/config/config.go
- pkg/auth/config/database.go
- pkg/auth/config/redis.go
- pkg/auth/config/schema_test.go
- pkg/auth/config/testdata/database_tests.yaml
- pkg/auth/config/testdata/default_config.yaml
- pkg/auth/config/testdata/redis_tests.yaml
- pkg/auth/dependency/auth/redis/event_store.go
- pkg/auth/dependency/challenge/provider.go
- pkg/auth/dependency/forgotpassword/store.go
- pkg/auth/dependency/interaction/redis/store.go
- pkg/auth/dependency/oauth/redis/store_grant.go
- pkg/auth/dependency/session/redis/store.go
- pkg/auth/dependency/webapp/state_store_redis.go
- pkg/db/context.go
- pkg/db/pool.go
- pkg/deps/deps_config.go
- pkg/deps/providers.go
- pkg/redis/context.go
- pkg/redis/pool.go
> Configurable pool size

- Dockerfile
- cmd/authgear/config/options.go
- cmd/authgear/server/wire_gen.go
- docker-compose.yaml
- migrations/20200630155506-add_login_at.sql
- pkg/auth/dependency/interaction/flows/user_ctrl.go
- pkg/auth/dependency/user/commands.go
- pkg/auth/dependency/user/commands_raw.go
- pkg/auth/dependency/user/store.go
- pkg/log/default.go
> Fix last login at

- pkg/auth/dependency/oidc/id_token.go
- pkg/auth/deps/deps.go
> Add additional claims

- pkg/auth/dependency/auth/session_middleware.go
> Treat sessions with not found user as invalid

- docs/specs/api-resolver.md
- docs/specs/oidc.md
- docs/specs/templates.md
- docs/specs/user-model.md
- docs/specs/verification.md
- pkg/auth/config/authenticator.go
- pkg/auth/config/config.go
- pkg/auth/config/identity.go
- pkg/auth/config/testdata/config_tests.yaml
- pkg/auth/config/testdata/default_config.yaml
- pkg/auth/config/verification.go
- pkg/deps/deps_config.go
> Add user verification feature specs

- pkg/auth/config/identity.go
- pkg/auth/dependency/identity/loginid/provider.go
- pkg/auth/dependency/identity/provider/conversion.go
- pkg/auth/dependency/newinteraction/context.go
- pkg/auth/dependency/newinteraction/graph.go
- pkg/auth/dependency/newinteraction/intent.go
- pkg/auth/dependency/newinteraction/intents/login.go
- pkg/auth/dependency/newinteraction/intents/signup.go
- pkg/auth/dependency/newinteraction/node.go
- pkg/auth/dependency/newinteraction/nodes/create_identity_begin.go
- pkg/auth/dependency/newinteraction/nodes/create_identity_end.go
- pkg/auth/dependency/newinteraction/nodes/create_identity_login_id.go
- pkg/auth/dependency/newinteraction/nodes/create_identity_oauth.go
- pkg/auth/dependency/newinteraction/nodes/do_create_session.go
- pkg/auth/dependency/newinteraction/nodes/do_create_user.go
- pkg/auth/dependency/newinteraction/nodes/select_identity_login_id.go
- pkg/auth/dependency/newinteraction/nodes/utils_authn.go
> Add user & identity creation nodes

- cmd/authgear/server/wire_gen.go
- pkg/auth/dependency/authenticator/keys.go
- pkg/auth/dependency/authenticator/oob/authenticator.go
- pkg/auth/dependency/authenticator/oob/provider.go
- pkg/auth/dependency/authenticator/provider/conversion.go
- pkg/auth/dependency/authenticator/provider/provider.go
- pkg/auth/dependency/identity/provider/provider.go
- pkg/auth/dependency/newinteraction/context.go
- pkg/auth/dependency/newinteraction/nodes/authn_oob_trigger.go
- pkg/auth/dependency/newinteraction/nodes/create_authenticator_oob_setup.go
- pkg/auth/dependency/newinteraction/nodes/oob_resend.go
- pkg/auth/dependency/newinteraction/nodes/utils_authn.go
- pkg/auth/dependency/webapp/service.go
- pkg/auth/handler/webapp/create_password.go
- pkg/auth/handler/webapp/login.go
- pkg/auth/handler/webapp/oob_otp.go
- pkg/auth/handler/webapp/signup.go
- pkg/auth/handler/webapp/viewmodels/password_policy.go
- pkg/deps/deps_request.go
- pkg/otp/result.go
> Interaction graph web - Part 3

- cmd/authgear/server/wire_gen.go
- pkg/auth/dependency/forgotpassword/deps.go
- pkg/auth/dependency/forgotpassword/provider.go
- pkg/auth/dependency/newinteraction/context.go
- pkg/auth/dependency/newinteraction/intents/forgot_password.go
- pkg/auth/dependency/newinteraction/intents/reset_password.go
- pkg/auth/dependency/newinteraction/nodes/forgot_password.go
- pkg/auth/dependency/newinteraction/nodes/reset_password.go
- pkg/auth/dependency/webapp/intent.go
- pkg/auth/dependency/webapp/service.go
- pkg/auth/handler/webapp/forgot_password.go
- pkg/auth/handler/webapp/forgot_password_success.go
- pkg/auth/handler/webapp/reset_password.go
- pkg/deps/deps_common.go
> Forgot password

- pkg/auth/dependency/newinteraction/intents/authenticate.go
- pkg/auth/dependency/newinteraction/nodes/authn_begin.go
- pkg/auth/dependency/newinteraction/nodes/authn_end.go
- pkg/auth/dependency/newinteraction/nodes/authn_oob.go
- pkg/auth/dependency/newinteraction/nodes/authn_password.go
- pkg/auth/dependency/newinteraction/nodes/authn_totp.go
> Distinguish between no authenticator and no authenticator needed

- .gitignore
- README.md
- cmd/authgear/server/server.go
- pkg/auth/config/server.go
> Require TLS when development mode is on

- cmd/authgear/migrate.go
- cmd/authgear/migrate/migrate.go
> Require number of migrations to revert

- pkg/auth/dependency/authenticator/info.go
- pkg/auth/dependency/newinteraction/graph.go
- pkg/auth/dependency/newinteraction/graph_test.go
- pkg/auth/dependency/newinteraction/nodes/do_create_session.go
- pkg/auth/dependency/oidc/metadata.go
- pkg/core/authn/acr.go
- pkg/core/authn/amr.go
> Populate AMR and ACR

- pkg/core/url/data.go
- pkg/core/url/data_test.go
- pkg/image/data_uri.go
- pkg/image/data_uri_test.go
- pkg/otp/totp.go
- pkg/otp/totp_test.go
> Generate and encode TOTP QR code image

- pkg/mail/sender.go
- pkg/sms/client.go
> Do not send email / SMS if development mode is on

- cmd/authgear/server/wire_gen.go
- pkg/auth/dependency/auth/session_manager.go
- pkg/auth/dependency/newinteraction/context.go
- pkg/auth/dependency/newinteraction/nodes/do_create_session.go
- pkg/auth/dependency/oauth/session_manager.go
- pkg/auth/dependency/session/cookie.go
- pkg/auth/dependency/session/manager.go
- pkg/auth/dependency/session/resolver.go
- pkg/auth/dependency/session/resolver_test.go
- pkg/auth/dependency/webapp/csrf_middleware.go
- pkg/auth/dependency/webapp/service.go
- pkg/auth/dependency/webapp/service_mock_test.go
- pkg/auth/dependency/webapp/state.go
- pkg/deps/deps_common.go
- pkg/deps/deps_utils.go
- pkg/httputil/cookie.go
- pkg/httputil/samesite.go
- pkg/httputil/samesite_test.go
> Bind web state to user agent

- pkg/auth/dependency/identity/info.go
- pkg/auth/dependency/newinteraction/nodes/do_create_session.go
- pkg/auth/dependency/oauth/grant_offline.go
- pkg/auth/dependency/oidc/id_token.go
- pkg/auth/dependency/session/session.go
- pkg/core/authn/attrs.go
- pkg/core/authn/info.go
> Save identity display ID claim into session attributes

- cmd/authgear/server/routes.go
- cmd/authgear/server/wire_gen.go
- cmd/authgear/server/wire_handler.go
- pkg/auth/dependency/authenticator/service/service.go
- pkg/auth/dependency/authenticator/totp/errors.go
- pkg/auth/dependency/authenticator/totp/provider.go
- pkg/auth/dependency/newinteraction/intents/authenticate.go
- pkg/auth/dependency/newinteraction/nodes/authn_end.go
- pkg/auth/dependency/newinteraction/nodes/create_authenticator_begin.go
- pkg/auth/dependency/newinteraction/nodes/create_authenticator_totp.go
- pkg/auth/dependency/newinteraction/nodes/create_authenticator_totp_setup.go
- pkg/auth/dependency/webapp/service.go
- pkg/auth/handler/webapp/deps.go
- pkg/auth/handler/webapp/enter_totp.go
- pkg/auth/handler/webapp/setup_totp.go
- pkg/auth/template/template.go
- pkg/deps/deps_common.go
- static/authui/css/main.css
- templates/auth_ui_enter_totp.html
- templates/auth_ui_setup_totp.html
- templates/auth_ui_translation.json
> MFA with TOTP

- pkg/auth/dependency/newinteraction/graph.go
- pkg/auth/dependency/webapp/auth_entry_point_middleware.go
- pkg/auth/dependency/webapp/intent.go
- pkg/auth/dependency/webapp/intl_middleware.go
- pkg/auth/dependency/webapp/service.go
- pkg/auth/dependency/webapp/state.go
- pkg/auth/dependency/webapp/state_middleware.go
- pkg/auth/dependency/webapp/url_provider.go
- pkg/core/intl/parse.go
- templates/auth_ui_login.html
- templates/auth_ui_promote.html
- templates/auth_ui_signup.html
> Fix not preserving OAuth parameter at internal links

- pkg/auth/config/template.go
> Remove template item key

- pkg/auth/dependency/authenticator/password/checker.go
- pkg/auth/dependency/authenticator/password/history_store.go
- pkg/auth/dependency/authenticator/password/provider.go
- pkg/auth/handler/webapp/template.go
- templates/auth_ui_translation.json
> Fix password reuse policy

- pkg/auth/dependency/authenticator/oob/provider.go
- pkg/auth/dependency/newinteraction/nodes/authn_oob_trigger.go
- pkg/auth/dependency/newinteraction/nodes/create_authenticator_oob_setup.go
- pkg/auth/dependency/verification/code.go
- pkg/auth/handler/webapp/enter_oob_otp.go
- pkg/otp/result.go
- templates/auth_ui_enter_oob_otp.html
> Fix OOB target display

- cmd/authgear/server/wire_gen.go
- pkg/auth/dependency/newinteraction/context.go
- pkg/auth/dependency/newinteraction/errors.go
- pkg/auth/dependency/newinteraction/graph.go
- pkg/auth/dependency/newinteraction/graph_test.go
- pkg/auth/dependency/newinteraction/node.go
- pkg/auth/dependency/newinteraction/nodes/authn_begin.go
- pkg/auth/dependency/newinteraction/nodes/authn_end.go
- pkg/auth/dependency/newinteraction/nodes/do_use_authenticator.go
- pkg/auth/dependency/newinteraction/nodes/use_device_token.go
- pkg/auth/dependency/webapp/service.go
- pkg/auth/handler/webapp/authentication_begin.go
- pkg/auth/handler/webapp/enter_oob_otp.go
- pkg/auth/handler/webapp/enter_password.go
- pkg/auth/handler/webapp/enter_totp.go
- pkg/mfa/cookie.go
- pkg/mfa/deps.go
- static/authui/css/main.css
- templates/auth_ui_enter_oob_otp.html
- templates/auth_ui_enter_password.html
- templates/auth_ui_enter_recovery_code.html
- templates/auth_ui_enter_totp.html
- templates/auth_ui_translation.json
> MFA with device token

- pkg/auth/handler/webapp/authentication_begin.go
- pkg/auth/handler/webapp/login.go
- pkg/auth/handler/webapp/promote.go
- pkg/auth/handler/webapp/settings_identity.go
- pkg/auth/handler/webapp/signup.go
- pkg/auth/handler/webapp/sso_callback.go
- pkg/auth/webapp/cookie.go
- pkg/auth/webapp/csrf.go
- pkg/auth/webapp/csrf_middleware.go
- pkg/auth/webapp/deps.go
- pkg/auth/webapp/service.go
- pkg/auth/wire_gen.go
- pkg/lib/authn/mfa/cookie.go
- pkg/lib/config/http.go
- pkg/lib/session/idpsession/cookie.go
- pkg/lib/session/idpsession/resolver.go
- pkg/lib/session/idpsession/resolver_test.go
- pkg/resolver/wire_gen.go
> Support configuring cookie name prefix

- pkg/admin/graphql/authenticator.go
- pkg/auth/handler/webapp/authentication_begin.go
- pkg/lib/authn/authenticator/filters.go
- pkg/lib/authn/authenticator/info.go
- pkg/lib/authn/authenticator/info_test.go
- pkg/lib/authn/authenticator/keys.go
- pkg/lib/authn/authenticator/service/conversion.go
- pkg/lib/authn/authenticator/service/service.go
- pkg/lib/authn/authenticator/spec.go
- pkg/lib/authn/claims.go
- pkg/lib/feature/verification/service.go
- pkg/lib/feature/verification/service_test.go
- pkg/lib/interaction/graph_test.go
- pkg/lib/interaction/nodes/create_authenticator_begin.go
- pkg/lib/interaction/nodes/create_authenticator_oob_setup.go
- pkg/lib/interaction/nodes/create_authenticator_password.go
- pkg/lib/interaction/nodes/create_authenticator_totp.go
- pkg/lib/interaction/nodes/create_authenticator_totp_setup.go
- pkg/lib/interaction/nodes/utils_authn.go
> Unify claims

- cmd/authgear/config/config.go
- cmd/authgear/config/options.go
- pkg/auth/deps.go
- pkg/auth/endpoints.go
- pkg/auth/wire_gen.go
- pkg/lib/config/http.go
- pkg/lib/config/source/local_fs.go
- pkg/lib/config/testdata/default_config.yaml
> Replace host config with public origin

- pkg/admin/wire_gen.go
- pkg/auth/wire_gen.go
- pkg/lib/deps/deps_common.go
- pkg/lib/feature/verification/service.go
- pkg/lib/feature/verification/service_mock_test.go
- pkg/lib/feature/verification/service_test.go
- pkg/resolver/wire_gen.go
> Treat identity as verified if there is a verified identity with same email

- cmd/portal/server/config.go
- cmd/portal/server/server.go
- pkg/admin/deps.go
- pkg/admin/wire.go
- pkg/admin/wire_gen.go
- pkg/lib/admin/authz/adder.go
- pkg/lib/admin/authz/deps.go
- pkg/lib/admin/authz/middleware.go
- pkg/lib/admin/authz/middleware_adder_test.go
- pkg/lib/admin/authz/middleware_test.go
- pkg/portal/config/admin_api.go
- pkg/portal/deps.go
- pkg/portal/deps/deps.go
- pkg/portal/deps/providers.go
- pkg/portal/routes.go
- pkg/portal/service/admin_api.go
- pkg/portal/service/deps.go
- pkg/portal/transport/admin_api_handler.go
- pkg/portal/transport/deps.go
- pkg/portal/wire.go
- pkg/portal/wire_gen.go
> Proxy Admin API graphql endpoint

- docs/specs/verification.md
- pkg/admin/wire_gen.go
- pkg/auth/wire_gen.go
- pkg/lib/authn/identity/claim_key.go
- pkg/lib/authn/identity/loginid/checker.go
- pkg/lib/authn/identity/loginid/provider.go
- pkg/lib/config/config.go
- pkg/lib/config/identity.go
- pkg/lib/config/testdata/config_tests.yaml
- pkg/lib/config/testdata/default_config.yaml
- pkg/lib/config/verification.go
- pkg/lib/feature/verification/service.go
- pkg/lib/feature/verification/service_test.go
- pkg/resolver/wire_gen.go
@chpapa Discussed with @louischan-oursky that we'd like to make individual claims verifiable. The API (OIDC tokens) should not have breaking changes, but configuration need to have breaking changes, so we update the configuration shape now.
ref #198
> Update configuration shape for verifiable claims

- pkg/portal/routes.go
- pkg/portal/session/deps.go
- pkg/portal/session/middleware_session_info.go
- pkg/portal/session/middleware_session_required.go
- pkg/portal/wire.go
- pkg/portal/wire_gen.go
> Require session to access Admin API in portal

- portal/package-lock.json
- portal/package.json
- portal/src/ReactApp.tsx
- portal/src/ScreenHeader.tsx
- portal/src/ScreenNav.tsx
- portal/src/ShowLoading.tsx
- portal/src/locale-data/en.json
- portal/tsconfig.json
> Add localization to portal

- portal/.stylelintrc.json
- portal/src/ReactApp.module.scss
- portal/src/ReactApp.tsx
- portal/src/ShowLoading.module.scss
- portal/src/ShowLoading.tsx
- portal/src/index.scss
> Document the purpose of ShowLoading

- pkg/lib/config/configsource/kubernetes.go
- pkg/lib/config/configsource/local_fs.go
- pkg/lib/config/configsource/source.go
- pkg/portal/deps.go
- pkg/portal/deps/deps.go
- pkg/portal/graphql/app.go
- pkg/portal/graphql/context.go
- pkg/portal/graphql/query.go
- pkg/portal/loader/app.go
- pkg/portal/model/app.go
- pkg/portal/service/app.go
- pkg/portal/service/authz.go
- pkg/portal/service/deps.go
- pkg/portal/wire_gen.go
- pkg/util/graphqlutil/lazy.go
- pkg/util/graphqlutil/lazy_test.go
- portal/nginx.conf
> Support Kubernetes config source in portal

- portal/src/ShowError.tsx
- portal/src/graphql/adminapi/UserList.tsx
- portal/src/graphql/portal/AppScreen.tsx
- portal/src/graphql/portal/AppsScreen.tsx
- portal/src/graphql/portal/Authenticated.tsx
- portal/src/locale-data/en.json
> Add retry to ShowError

- portal/src/graphql/adminapi/relay.ts
- portal/src/graphql/portal/relay.ts
> Fix Relay error handling

- Makefile
- pkg/lib/authn/user/queries.go
- pkg/lib/authn/user/store.go
- pkg/lib/infra/db/pagination.go
- pkg/lib/infra/db/pagination_test.go
- portal/src/graphql/adminapi/schema.graphql
- portal/src/graphql/portal/schema.graphql
- scripts/exportschemas/main.go
- scripts/npm/export-graphql-schema.js
The new cursor format is base64-encoded string `offset:<entry offset>`.
fix #218
> Use offset-based pagination in Admin API

- pkg/lib/authn/identity/loginid/checker_test.go
- pkg/lib/config/identity.go
- pkg/lib/config/testdata/default_config.yaml
> Update login ID key configuration design

- pkg/lib/oauth/handler/handler_token_issue.go
- pkg/lib/oauth/protocol/token.go
> Fix incorrect type for OAuth expires_in

- portal/src/NavBreadcrumb.module.scss
- portal/src/NavBreadcrumb.tsx
- portal/src/graphql/adminapi/UsersScreen.tsx
- portal/src/hook/useNavIsActive.ts
- portal/src/locale-data/en.json
> Add breadcrumb

- pkg/admin/routes.go
- pkg/admin/wire.go
- pkg/admin/wire_gen.go
- pkg/auth/routes.go
- pkg/auth/wire_gen.go
- pkg/auth/wire_middleware.go
- pkg/lib/authn/identity/loginid/checker.go
- pkg/lib/authn/identity/loginid/checker_test.go
- pkg/lib/config/identity.go
- pkg/lib/config/testdata/default_config.yaml
- pkg/lib/infra/middleware/body_limit.go
- pkg/lib/infra/middleware/deps.go
- pkg/portal/routes.go
- pkg/portal/wire.go
- pkg/portal/wire_gen.go
- pkg/resolver/routes.go
- pkg/resolver/wire.go
- pkg/resolver/wire_gen.go
- pkg/util/password/constants.go
- pkg/util/password/dispatch.go
> Enforce length limit on user inputs

- portal/package-lock.json
- portal/package.json
- portal/src/graphql.d.ts
- portal/src/graphql/adminapi/UsersList.tsx
- portal/src/graphql/adminapi/__generated__/UsersListQuery.ts
- portal/src/locale-data/en.json
- portal/src/util/formatDatetime.ts
- portal/src/util/types.ts
- portal/src/util/user.ts
Issue #241 
Fetch extra user info from claims by updating query
Added corresponding column
> Add more user columns

- go.mod
- go.sum
- pkg/lib/config/identity.go
- pkg/lib/config/testdata/config_tests.yaml
> Validate oauth provider config

- templates/auth_ui_enter_login_id.html
- templates/auth_ui_settings_identity.html
- templates/auth_ui_translation.json
> Use better term for username

- pkg/admin/graphql/authenticator.go
- pkg/admin/graphql/identity.go
- pkg/admin/graphql/scalars.go
- pkg/portal/graphql/app.go
- pkg/portal/graphql/scalars.go
- pkg/portal/model/app.go
- pkg/util/graphqlutil/json.go
- portal/src/graphql.d.ts
- portal/src/graphql/adminapi/__generated__/UsersListQuery.ts
- portal/src/graphql/adminapi/schema.graphql
- portal/src/graphql/portal/schema.graphql
- portal/src/util/user.ts
> Return raw & effective config

- pkg/lib/oauth/grant_offline.go
- pkg/lib/session/access/event.go
- pkg/lib/session/access/event_test.go
- pkg/lib/session/idpsession/provider_test.go
- pkg/lib/session/idpsession/session.go
> Remove session extra info

- pkg/lib/config/database.go
- pkg/lib/config/testdata/database_tests.yaml
- pkg/lib/config/testdata/default_config.yaml
- pkg/lib/infra/db/context.go
- pkg/lib/infra/db/pool.go
> Support db.ConnMaxIdleTime

- pkg/admin/graphql/schema.go
- pkg/lib/config/configsource/escape.go
- pkg/lib/config/configsource/escape_test.go
- pkg/lib/config/configsource/kubernetes.go
- pkg/lib/config/configsource/local_fs.go
- pkg/lib/config/configsource/source.go
- pkg/lib/config/test/config.go
- pkg/portal/graphql/app.go
- pkg/portal/graphql/context.go
- pkg/portal/graphql/mutation.go
- pkg/portal/graphql/schema.go
- pkg/portal/loader/app.go
- pkg/portal/model/app.go
- pkg/portal/service/app.go
- pkg/portal/service/app_test.go
- pkg/portal/service/authz.go
- pkg/portal/service/config.go
- pkg/portal/service/deps.go
- pkg/portal/wire_gen.go
- pkg/util/graphqlutil/api_error.go
- pkg/util/graphqlutil/data_loader.go
- pkg/util/graphqlutil/data_loader_test.go
- pkg/util/graphqlutil/lazy.go
- pkg/util/graphqlutil/lazy_test.go
- portal/src/graphql/portal/schema.graphql
> Add update app config API

- static/authui/css/main.css
- templates/auth_ui_logout.html
- templates/auth_ui_settings.html
- templates/auth_ui_settings_identity.html
- templates/auth_ui_translation.json
> Update /settings/identity design 

- templates/auth_ui_create_password.html
- templates/auth_ui_enter_login_id.html
- templates/auth_ui_enter_oob_otp.html
- templates/auth_ui_enter_password.html
- templates/auth_ui_enter_recovery_code.html
- templates/auth_ui_enter_totp.html
- templates/auth_ui_forgot_password.html
- templates/auth_ui_login.html
- templates/auth_ui_promote.html
- templates/auth_ui_reset_password.html
- templates/auth_ui_setup_oob_otp.html
- templates/auth_ui_setup_totp.html
- templates/auth_ui_signup.html
- templates/auth_ui_verify_identity.html
> Add autocomplete to text input

- portal/.eslintrc.json
- portal/src/CheckboxWithContent.module.scss
- portal/src/DetailsListWithOrdering.tsx
- portal/src/ExtendableWidget.tsx
- portal/src/graphql/adminapi/UserDetailsAccountSecurity.tsx
- portal/src/graphql/adminapi/UserDetailsConnectedIdentities.tsx
- portal/src/graphql/adminapi/UserDetailsScreen.tsx
- portal/src/graphql/adminapi/UserDetailsSession.tsx
- portal/src/graphql/portal/AuthenticationAuthenticatorSettings.tsx
- portal/src/graphql/portal/AuthenticationConfigurationScreen.module.scss
- portal/src/graphql/portal/AuthenticationConfigurationScreen.tsx
- portal/src/graphql/portal/AuthenticationLoginIDSettings.module.scss
- portal/src/graphql/portal/AuthenticationLoginIDSettings.tsx
- portal/src/locale-data/en.json
Closes #276
Closes #281 
add aria label
use label in fluent UI if possible
fix inconsistent font
> Fix accessibility issues

- portal/src/graphql/portal/AuthenticationLoginIDSettings.tsx
issue #288 
use onChange instead
> Fix onChanged deprecated warning

- pkg/auth/handler/webapp/viewmodels/base.go
- static/authui/js/main.js
- templates/auth_ui_html_head.html
> Use HTML5 history

- pkg/admin/wire_gen.go
- pkg/auth/wire_gen.go
- pkg/lib/authn/authenticator/filters.go
- pkg/lib/authn/authenticator/info.go
- pkg/lib/authn/authenticator/service/conversion.go
- pkg/lib/authn/authenticator/service/service.go
- pkg/lib/authn/identity.go
- pkg/lib/authn/identity/info.go
- pkg/lib/authn/identity/service/service.go
- pkg/lib/authn/identity/service/service_mock_test.go
- pkg/lib/authn/user/queries.go
- pkg/lib/config/identity.go
- pkg/lib/config/verification.go
- pkg/lib/deps/deps_common.go
- pkg/lib/facade/authenticator.go
- pkg/lib/facade/coordinator.go
- pkg/lib/facade/deps.go
- pkg/lib/facade/identity.go
- pkg/lib/feature/verification/service.go
- pkg/lib/interaction/context.go
- pkg/lib/interaction/nodes/do_create_user.go
- pkg/lib/interaction/nodes/do_update_identity.go
- pkg/resolver/wire_gen.go
> Fix verification interaction with other features

- pkg/auth/deps.go
- pkg/auth/handler/webapp/settings.go
- pkg/auth/wire_gen.go
- pkg/lib/authn/mfa/service.go
- static/authui/css/main.css
- templates/auth_ui_settings.html
- templates/auth_ui_settings_identity.html
- templates/auth_ui_translation.json
fix #310 
Most buttons are not functional. They will be implemented by later PRs.
We also discovered a problem with our localization system. We cannot localize date time (yet). ICU MessageFormat has support for datetime formatting. But our MessageFormat does not support it (yet).
> Add security section in settings screen

- portal/src/index.html
> Setup Awesome font 5 using CDN

- portal/src/AppRoot.tsx
- portal/src/ExtendableWidget.module.scss
- portal/src/ExtendableWidget.tsx
- portal/src/ScreenNav.tsx
- portal/src/graphql.d.ts
- portal/src/graphql/portal/SingleSignOnConfigurationScreen.module.scss
- portal/src/graphql/portal/SingleSignOnConfigurationScreen.tsx
- portal/src/graphql/portal/SingleSignOnConfigurationWidget.module.scss
- portal/src/graphql/portal/SingleSignOnConfigurationWidget.tsx
- portal/src/graphql/portal/mutations/__generated__/UpdateAppAndSecretConfigMutation.ts
- portal/src/graphql/portal/mutations/updateAppAndSecretMutation.ts
- portal/src/graphql/portal/query/__generated__/AppAndSecretConfigQuery.ts
- portal/src/graphql/portal/query/appAndSecretConfigQuery.ts
- portal/src/locale-data/en.json
- portal/src/types.ts
- portal/src/util/misc.ts
Closes #282
Closes #298 
based on PR #317
> [Portal] Single sign on screen

- pkg/admin/deps.go
- pkg/admin/graphql/authenticator.go
- pkg/admin/graphql/context.go
- pkg/admin/graphql/deps.go
- pkg/admin/graphql/entity.go
- pkg/admin/graphql/identity.go
- pkg/admin/graphql/identity_mutation.go
- pkg/admin/graphql/mutation.go
- pkg/admin/graphql/schema.go
- pkg/admin/loader/identity.go
- pkg/admin/loader/interaction.go
- pkg/admin/service/deps.go
- pkg/admin/service/interaction.go
- pkg/admin/web_endpoints.go
- pkg/admin/wire_gen.go
- pkg/portal/graphql/app.go
- pkg/portal/graphql/context.go
- pkg/portal/graphql/deps.go
- pkg/portal/graphql/nodes.go
- pkg/portal/wire_gen.go
- pkg/util/graphqlutil/api_error.go
- pkg/util/graphqlutil/context.go
- pkg/util/graphqlutil/data_loader.go
- portal/src/graphql/adminapi/__generated__/UserDetailsScreenQuery.ts
- portal/src/graphql/adminapi/__generated__/globalTypes.ts
- portal/src/graphql/adminapi/schema.graphql
- portal/src/graphql/portal/mutations/updateAppConfigMutation.ts
- portal/src/graphql/portal/schema.graphql
- scripts/graphqlschema/main.go
> Implement delete identity mutation

- cmd/authgear/server/server.go
- pkg/lib/config/environment.go
- pkg/lib/deps/providers.go
> Remove extra fields in EnvironmentConfig

- pkg/admin/graphql/authenticator_mutation.go
- pkg/admin/graphql/context.go
- pkg/admin/loader/authenticator.go
- pkg/admin/wire_gen.go
- pkg/api/apierrors/error.go
- pkg/auth/handler/webapp/template.go
- pkg/lib/authn/authenticator/filters.go
- pkg/lib/interaction/errors.go
- pkg/lib/interaction/intents/remove_authenticator.go
- pkg/lib/interaction/nodes/authn_begin.go
- pkg/lib/interaction/nodes/create_authenticator_begin.go
- pkg/lib/interaction/nodes/create_authenticator_oob_setup.go
- pkg/lib/interaction/nodes/do_remove_authenticator.go
- pkg/lib/interaction/nodes/do_remove_identity.go
- pkg/lib/interaction/nodes/remove_authenticator.go
- pkg/lib/interaction/nodes/use_identity_anonymous.go
- pkg/lib/oauth/handler/handler_token.go
- portal/src/graphql/adminapi/schema.graphql
- templates/auth_ui_translation.json
> Add delete authenticator mutation

- pkg/lib/authn/authenticator/filters.go
- pkg/lib/authn/authenticator/service/service.go
- pkg/lib/authn/identity.go
- pkg/lib/authn/identity/info.go
- pkg/lib/config/config.go
- pkg/lib/config/testdata/config_tests.yaml
- pkg/lib/interaction/nodes/authn_begin.go
- pkg/lib/interaction/nodes/create_authenticator_begin.go
> Enforce constraint between identity and matching primary authenticator

- pkg/lib/config/identity.go
- pkg/lib/config/testdata/config_tests.yaml
- pkg/lib/config/testdata/secret_config_validate_tests.yaml
> Require OAuth provider alias in configuration

- pkg/admin/deps.go
- pkg/admin/graphql/context.go
- pkg/admin/graphql/models.go
- pkg/admin/graphql/user.go
- pkg/admin/loader/deps.go
- pkg/admin/loader/verification.go
- pkg/admin/model/claim.go
- pkg/admin/wire_gen.go
- pkg/lib/feature/verification/service.go
- portal/src/graphql/adminapi/schema.graphql
@chpapa Exposing the verification status of user claims in Admin API
fix #345
> Expose claim verification status in GraphQL queries

- portal/src/graphql/portal/AnonymousUsersConfigurationScreen.tsx
- portal/src/locale-data/en.json
> Add localization for anonymous identity conflict behaviour

- pkg/admin/graphql/context.go
- pkg/admin/graphql/user_mutation.go
- pkg/admin/loader/interaction.go
- pkg/admin/loader/user.go
- pkg/lib/feature/forgotpassword/errors.go
- pkg/lib/feature/forgotpassword/provider.go
- pkg/lib/interaction/context.go
- pkg/lib/interaction/nodes/reset_password.go
- portal/src/graphql/adminapi/schema.graphql
> Add reset password mutation

- portal/src/graphql/portal/AppsScreen.module.scss
- portal/src/graphql/portal/AppsScreen.tsx
- portal/src/graphql/portal/__generated__/AppsScreenQuery.ts
- portal/src/graphql/portal/mutations/updateAppAndSecretMutation.ts
- portal/src/locale-data/en.json
- portal/src/types.ts
> Improve apps list UI

- pkg/lib/interaction/input.go
- pkg/lib/interaction/input_test.go
> Handle nil for interaction runtime polymorphism

- portal/src/AppRoot.tsx
- portal/src/graphql/adminapi/AddEmailScreen.module.scss
- portal/src/graphql/adminapi/AddEmailScreen.tsx
- portal/src/graphql/adminapi/AddPhoneScreen.module.scss
- portal/src/graphql/adminapi/AddPhoneScreen.tsx
- portal/src/graphql/adminapi/AddUsernameScreen.module.scss
- portal/src/graphql/adminapi/AddUsernameScreen.tsx
- portal/src/graphql/adminapi/PrimaryIdentitiesSelectionForm.module.scss
- portal/src/graphql/adminapi/PrimaryIdentitiesSelectionForm.tsx
- portal/src/graphql/adminapi/UserDetailCommandBar.module.scss
- portal/src/graphql/adminapi/UserDetailCommandBar.tsx
- portal/src/graphql/adminapi/UserDetailsConnectedIdentities.module.scss
- portal/src/graphql/adminapi/UserDetailsConnectedIdentities.tsx
- portal/src/graphql/adminapi/UserDetailsScreen.module.scss
- portal/src/graphql/adminapi/UserDetailsScreen.tsx
- portal/src/hook/useInput.ts
- portal/src/locale-data/en.json
- portal/src/theme.tsx
- portal/src/types.ts
Closes #331
- update list cell design
- update list structure, one type per list
- add add identity button / menu
- primary identities form
- add email, phone and username screens
> Update user detail screen connected identities tab

- portal/src/AppRoot.tsx
- portal/src/ListCellLayout.module.scss
- portal/src/graphql/adminapi/ResetPasswordScreen.module.scss
- portal/src/graphql/adminapi/ResetPasswordScreen.tsx
- portal/src/graphql/adminapi/UserDetailsAccountSecurity.module.scss
- portal/src/graphql/adminapi/UserDetailsAccountSecurity.tsx
- portal/src/locale-data/en.json
Closes #330 
- update layout
- remove detail button
- display all authenticators, one list per authenticator type
- add remove button for secondary authenticator
- create reset password button
> [Portal] Update user detail account security screen

- pkg/lib/config/configsource/kubernetes.go
- pkg/lib/config/configsource/kubernetes_test.go
> Make k8s config map FS has explicit root

- pkg/lib/deps/middleware_request.go
- pkg/portal/config/admin_api.go
- pkg/portal/deps.go
- pkg/portal/service/admin_api.go
- pkg/portal/service/admin_api_test.go
- pkg/portal/transport/admin_api_handler.go
- pkg/portal/transport/deps.go
- pkg/portal/wire_gen.go
> Use correct Host when proxying Admin API

- portal/src/graphql/adminapi/AddEmailScreen.tsx
- portal/src/graphql/adminapi/AddPhoneScreen.module.scss
- portal/src/graphql/adminapi/AddPhoneScreen.tsx
- portal/src/graphql/adminapi/AddUsernameScreen.tsx
- portal/src/graphql/adminapi/UserDetailsConnectedIdentities.module.scss
- portal/src/graphql/adminapi/UserDetailsConnectedIdentities.tsx
- portal/src/graphql/adminapi/UserDetailsScreen.tsx
- portal/src/graphql/adminapi/__generated__/globalTypes.ts
- portal/src/graphql/adminapi/mutations/__generated__/CreateIdentityMutation.ts
- portal/src/graphql/adminapi/mutations/__generated__/DeleteIdentityMutation.ts
- portal/src/graphql/adminapi/mutations/createIdentityMutation.ts
- portal/src/graphql/adminapi/mutations/deleteIdentityMutation.ts
- portal/src/graphql/adminapi/query/__generated__/UserQuery.ts
- portal/src/graphql/adminapi/query/userQuery.ts
- portal/src/graphql/portal/SingleSignOnConfigurationScreen.tsx
- portal/src/locale-data/en.json
- portal/src/util/error.ts
- portal/src/util/validation.ts
Closes #367
Closes #368
TODO: handle show password field for add username (#375)
> [Portal] Integrate create delete identity mutation

- portal/src/graphql/adminapi/AddUserScreen.module.scss
- portal/src/graphql/adminapi/AddUserScreen.tsx
- portal/src/graphql/adminapi/mutations/__generated__/CreateUserMutation.ts
- portal/src/graphql/adminapi/mutations/createUserMutation.ts
- portal/src/locale-data/en.json
- portal/src/util/error.ts
- portal/src/util/validation.ts
Closes #369
- update user screen
- add hook for mutation
- handle error
> [Portal] Integrate create user mutation

- portal/src/graphql/adminapi/ResetPasswordScreen.tsx
- portal/src/graphql/adminapi/mutations/__generated__/ResetPasswordMutation.ts
- portal/src/graphql/adminapi/mutations/resetPasswordMutation.ts
- portal/src/locale-data/en.json
- portal/src/util/error.ts
- portal/src/util/validation.ts
> [Portal] Integrate reset password mutation

- portal/src/PasswordField.tsx
- portal/src/graphql/adminapi/AddUsernameScreen.module.scss
- portal/src/graphql/adminapi/AddUsernameScreen.tsx
- portal/src/graphql/adminapi/ResetPasswordScreen.tsx
- portal/src/graphql/adminapi/UserDetailsScreen.tsx
- portal/src/graphql/adminapi/query/userQuery.ts
- portal/src/locale-data/en.json
> Handle add password on add username

- portal/src/graphql/adminapi/mutations/deleteAuthenticatorMutation.ts
> Refetch user detail after delete authenticator mutation

- portal/src/index.tsx
> Disable axe due to monaco editor performance issue

- portal/src/graphql/adminapi/PrimaryIdentitiesSelectionForm.tsx
- portal/src/graphql/adminapi/UserDetailsConnectedIdentities.tsx
- portal/src/locale-data/en.json
> Display oauth identities in separate list, show icon according to provider type

- templates/auth_ui_verify_identity.html
> Use normal mobile keyboard for email verification code

- pkg/admin/graphql/context.go
- pkg/admin/graphql/user_mutation.go
- pkg/admin/loader/verification.go
- pkg/lib/feature/verification/service.go
- pkg/util/graphqlutil/lazy.go
- portal/src/graphql/adminapi/schema.graphql
> Implement mutation for verified status of user claims

- pkg/portal/graphql/app.go
- pkg/portal/service/app.go
- pkg/portal/service/app_test.go
- portal/src/graphql/portal/schema.graphql
> Implement query for app template files

- pkg/admin/graphql/authenticator_mutation.go
- pkg/admin/graphql/identity_mutation.go
- portal/src/graphql/adminapi/UsersList.tsx
- portal/src/graphql/adminapi/mutations/__generated__/CreateIdentityMutation.ts
- portal/src/graphql/adminapi/mutations/__generated__/DeleteAuthenticatorMutation.ts
- portal/src/graphql/adminapi/mutations/__generated__/DeleteIdentityMutation.ts
- portal/src/graphql/adminapi/mutations/createIdentityMutation.ts
- portal/src/graphql/adminapi/mutations/deleteAuthenticatorMutation.ts
- portal/src/graphql/adminapi/mutations/deleteIdentityMutation.ts
- portal/src/graphql/adminapi/query/userQuery.ts
- portal/src/graphql/adminapi/schema.graphql
> Return parent entities in mutation for easier client-side caching

- portal/src/graphql/adminapi/UserDetailsAccountSecurity.tsx
- portal/src/graphql/adminapi/mutations/__generated__/CreateIdentityMutation.ts
- portal/src/graphql/adminapi/mutations/__generated__/DeleteIdentityMutation.ts
- portal/src/graphql/adminapi/mutations/createIdentityMutation.ts
- portal/src/graphql/adminapi/mutations/deleteIdentityMutation.ts
fix #417 
@axolotl0212 Please note the correct authenticator claims to use in case other screens need to use it. Authenticator claims are different from identity claims.
> Fix authenticator list display

- portal/src/TodoButtonWrapper.module.scss
- portal/src/TodoButtonWrapper.tsx
- portal/src/graphql/adminapi/UserDetailCommandBar.tsx
- portal/src/graphql/adminapi/UserDetailsConnectedIdentities.tsx
- portal/src/graphql/adminapi/UserDetailsScreen.tsx
- portal/src/graphql/portal/ForgotPasswordSettings.tsx
- portal/src/locale-data/en.json
Closes #421 
- TODO button + dialog
- comment out section which does not work
> Hide not functional component / section

- portal/src/AppRoot.tsx
- portal/src/ScreenNav.tsx
- portal/src/graphql/portal/OAuthClientConfigurationScreen.module.scss
- portal/src/graphql/portal/OAuthClientConfigurationScreen.tsx
- portal/src/locale-data/en.json
- portal/src/types.ts
> Layout OAuth client list screen

- portal/src/graphql/portal/SingleSignOnConfigurationWidget.tsx
- portal/src/locale-data/en.json
- templates/auth_ui_login.html
- templates/auth_ui_promote.html
- templates/auth_ui_signup.html
- templates/auth_ui_translation.json
fix https://github.com/authgear/authgear-server/issues/358
> Use proper OAuth provider branding

- pkg/lib/interaction/nodes/select_identity_begin.go
> Fix not producing anonymous user disabled error

- portal/src/AppRoot.tsx
- portal/src/LabelWithTooltip.module.scss
- portal/src/LabelWithTooltip.tsx
- portal/src/graphql/portal/CreateOAuthClientScreen.module.scss
- portal/src/graphql/portal/CreateOAuthClientScreen.tsx
- portal/src/graphql/portal/ModifyOAuthClientForm.module.scss
- portal/src/graphql/portal/ModifyOAuthClientForm.tsx
- portal/src/graphql/portal/OAuthClientConfigurationScreen.tsx
- portal/src/hook/useInput.ts
- portal/src/locale-data/en.json
- portal/src/types.ts
- portal/src/util/clipboard.ts
- portal/src/util/error.ts
- portal/src/util/random.ts
- portal/src/util/validation.ts
> Add oauth client screen

- portal/src/graphql/portal/OAuthClientConfigurationScreen.module.scss
- portal/src/graphql/portal/OAuthClientConfigurationScreen.tsx
- portal/src/locale-data/en.json
base on #434
Closes #435 
- Update OAuth client list UI
- Added remove button
> Update OAuth client list ui

- pkg/lib/config/oauth.go
- pkg/lib/config/testdata/config_tests.yaml
- portal/README.md
fix #440 
@axolotl0212 Please note the new field in OAuth client config.
> Add OAuth client name for developer use

- portal/src/DetailsListWithOrdering.tsx
- portal/src/OrderButtons.module.scss
- portal/src/OrderButtons.tsx
- portal/src/WidgetWithOrdering.module.scss
- portal/src/WidgetWithOrdering.tsx
- portal/src/graphql/portal/AuthenticationAuthenticatorSettings.module.scss
- portal/src/graphql/portal/AuthenticationAuthenticatorSettings.tsx
- portal/src/graphql/portal/AuthenticationConfigurationScreen.module.scss
- portal/src/graphql/portal/AuthenticationCountryCallingCodeList.tsx
- portal/src/graphql/portal/AuthenticationLoginIDSettings.module.scss
- portal/src/graphql/portal/AuthenticationLoginIDSettings.tsx
- portal/src/locale-data/en.json
- portal/src/types.ts
> Update authentication screen login

- portal/src/AppRoot.tsx
- portal/src/graphql/portal/CreateOAuthClientScreen.tsx
- portal/src/graphql/portal/EditOAuthClientScreen.module.scss
- portal/src/graphql/portal/EditOAuthClientScreen.tsx
- portal/src/graphql/portal/ModifyOAuthClientForm.tsx
- portal/src/graphql/portal/OAuthClientConfigurationScreen.tsx
- portal/src/locale-data/en.json
- portal/src/types.ts
base on #434
Closes #437
- reuse modify oauth client form
> Edit OAuth client screen

- portal/src/ButtonWithLoading.tsx
- portal/src/graphql/adminapi/AddEmailScreen.module.scss
- portal/src/graphql/adminapi/AddEmailScreen.tsx
- portal/src/graphql/adminapi/AddPhoneScreen.module.scss
- portal/src/graphql/adminapi/AddPhoneScreen.tsx
- portal/src/graphql/adminapi/PrimaryIdentitiesSelectionForm.tsx
- portal/src/graphql/adminapi/UserDetailsConnectedIdentities.module.scss
- portal/src/graphql/adminapi/UserDetailsConnectedIdentities.tsx
- portal/src/graphql/adminapi/UserDetailsScreen.tsx
- portal/src/graphql/adminapi/mutations/__generated__/SetVerifiedStatusMutation.ts
- portal/src/graphql/adminapi/mutations/setVerifiedStatusMutation.ts
- portal/src/graphql/adminapi/query/__generated__/UserQuery.ts
- portal/src/graphql/adminapi/query/userQuery.ts
- portal/src/locale-data/en.json
- portal/src/theme.tsx
Closes #385 
- get verified state from verified claims
- integrate set verified state mutation
> Handle verified claims in user detail screen

- pkg/admin/loader/interaction.go
- pkg/auth/handler/webapp/viewmodels/base.go
- pkg/auth/wire_gen.go
- pkg/lib/config/authentication.go
- pkg/lib/config/testdata/config_tests.yaml
- pkg/lib/interaction/nodes/do_create_user.go
- static/authui/css/main.css
- templates/auth_ui_login.html
- templates/auth_ui_promote.html
- templates/auth_ui_signup.html
- templates/auth_ui_translation.json
> Add configuration to disable public signup

- pkg/lib/config/oauth.go
- pkg/lib/config/testdata/config_tests.yaml
> Added minimum value to oauth access token lifetime #449

- pkg/lib/config/configsource/kubernetes.go
- pkg/lib/config/configsource/kubernetes_test.go
- pkg/portal/service/config.go
> Use single k8s secret for app config files

- portal/src/graphql/portal/CreateOAuthClientScreen.tsx
- portal/src/graphql/portal/EditOAuthClientScreen.tsx
- portal/src/graphql/portal/ModifyOAuthClientForm.tsx
Just found this problem, due to initial state does not match with state returned by ModifyOAuthClientForm
> Fix create OAuth client screen block navigation on new form

- portal/src/graphql/adminapi/UserDetailCommandBar.tsx
> Hide login as this user button, show remove and disable button

- portal/src/graphql/adminapi/AddPhoneScreen.tsx
- portal/src/graphql/adminapi/AddUserScreen.tsx
- portal/src/graphql/adminapi/AddUsernameScreen.tsx
- portal/src/graphql/adminapi/ResetPasswordScreen.tsx
- portal/src/graphql/adminapi/UserDetailsScreen.tsx
- portal/src/graphql/portal/AnonymousUsersConfigurationScreen.tsx
- portal/src/graphql/portal/AuthenticationConfigurationScreen.tsx
- portal/src/graphql/portal/CreateOAuthClientScreen.tsx
- portal/src/graphql/portal/EditOAuthClientScreen.tsx
- portal/src/graphql/portal/OAuthClientConfigurationScreen.tsx
- portal/src/graphql/portal/PasswordsScreen.tsx
- portal/src/graphql/portal/SingleSignOnConfigurationScreen.tsx
- portal/src/graphql/portal/query/appAndSecretConfigQuery.ts
- portal/src/graphql/portal/query/appConfigQuery.ts
> Query hook return cast data

- portal/.eslintrc.json
- portal/src/TodoButtonWrapper.tsx
- portal/src/graphql/adminapi/UserDetailsAccountSecurity.tsx
- portal/src/graphql/adminapi/UserDetailsConnectedIdentities.tsx
- portal/src/graphql/portal/OAuthClientConfigurationScreen.tsx
> Fix dialog subText deprecation warning

- portal/src/NavigationBlockerDialog.tsx
- portal/src/graphql/portal/SingleSignOnConfigurationScreen.tsx
- portal/src/graphql/portal/SingleSignOnConfigurationWidget.tsx
> Remove un-necessary useState

- portal/src/graphql/adminapi/AddEmailScreen.tsx
- portal/src/graphql/adminapi/AddPhoneScreen.tsx
- portal/src/graphql/adminapi/AddUserScreen.tsx
- portal/src/graphql/adminapi/AddUsernameScreen.tsx
- portal/src/graphql/adminapi/ResetPasswordScreen.tsx
- portal/src/graphql/portal/AuthenticationAuthenticatorSettings.tsx
- portal/src/graphql/portal/AuthenticationLoginIDSettings.tsx
- portal/src/graphql/portal/CreateOAuthClientScreen.tsx
- portal/src/graphql/portal/EditOAuthClientScreen.tsx
- portal/src/graphql/portal/ForgotPasswordSettings.tsx
- portal/src/graphql/portal/PasswordPolicySettings.tsx
- portal/src/graphql/portal/SingleSignOnConfigurationScreen.tsx
fix #404 
pressing enter submit the form
> Use form component for forms, add submit type to submit button

- README.md
- pkg/portal/service/app.go
- pkg/portal/service/app_test.go
fix #470 
@axolotl0212 You may want to take a look at the second commit, which should solve your problem.
> Fix cannot update secret

- portal/src/graphql/adminapi/UserDetailsAccountSecurity.tsx
- portal/src/graphql/adminapi/UserDetailsConnectedIdentities.tsx
- portal/src/graphql/portal/OAuthClientConfigurationScreen.tsx
> Block dismiss dialog while loading

- portal/src/ButtonWithLoading.tsx
> Fix button in loading state behaviour

- .env.example
- pkg/portal/config/app.go
- pkg/portal/service/app.go
- pkg/portal/service/config.go
> Add default branding for new app

- pkg/portal/service/app.go
- pkg/util/slice/strings.go
- pkg/util/slice/strings_test.go
> Fix duplicate ingress being created at app creation

- hack/ingress.tpl.yaml
- migrations/portal/20201008183330-add_domains.sql
- migrations/portal/20201009162506-custom_domain_flag.sql
- pkg/portal/config/app.go
- pkg/portal/db/scanner.go
- pkg/portal/db/sql_builder.go
- pkg/portal/deps.go
- pkg/portal/graphql/app.go
- pkg/portal/graphql/context.go
- pkg/portal/graphql/domain.go
- pkg/portal/graphql/domain_mutation.go
- pkg/portal/loader/deps.go
- pkg/portal/loader/domain.go
- pkg/portal/model/domain.go
- pkg/portal/service/app.go
- pkg/portal/service/config.go
- pkg/portal/service/deps.go
- pkg/portal/service/domain.go
- pkg/portal/wire_gen.go
- portal/src/graphql/portal/schema.graphql
> Implement domain verification & k8s integration

- portal/src/AppRoot.tsx
- portal/src/ScreenNav.tsx
- portal/src/graphql/portal/UserInterfaceScreen.module.scss
- portal/src/graphql/portal/UserInterfaceScreen.tsx
- portal/src/locale-data/en.json
connect #482 
The `Supported Languages` and `Default country / area code` fields are removed.
> Implement user interface screen

- portal/src/FormTextField.tsx
- portal/src/error/ErrorDialog.tsx
- portal/src/error/FormContext.ts
- portal/src/error/FormFieldContext.ts
- portal/src/error/ShowUnhandledValidationErrorCauses.tsx
- portal/src/error/duplicated.ts
- portal/src/error/error.ts
- portal/src/error/invariant.ts
- portal/src/error/password.ts
- portal/src/error/useGenericError.ts
- portal/src/error/useValidationError.ts
- portal/src/error/validation.ts
- portal/src/graphql/portal/SingleSignOnConfigurationScreen.tsx
- portal/src/graphql/portal/SingleSignOnConfigurationWidget.tsx
- portal/src/locale-data/en.json
fix #400 
- Skip transforming error to Violation
- Split error handling to two layers
TODO: implement this to all screen
> Refactor error handling

- portal/src/graphql/adminapi/apollo.ts
> Fix User.verifiedClaims merge warning

- portal/src/graphql/adminapi/UserDetailsAccountSecurity.tsx
- portal/src/graphql/adminapi/UserDetailsConnectedIdentities.tsx
- portal/src/graphql/portal/OAuthClientConfigurationScreen.tsx
> Improve dialog UX

- migrations/portal/20201013145939-collaborator-and-invitation.sql
- pkg/lib/config/configsource/kubernetes.go
- pkg/lib/config/configsource/source.go
- pkg/portal/deps.go
- pkg/portal/graphql/app.go
- pkg/portal/graphql/collaborator.go
- pkg/portal/graphql/collaborator_mutation.go
- pkg/portal/graphql/context.go
- pkg/portal/loader/collaborator.go
- pkg/portal/loader/deps.go
- pkg/portal/model/collaborator.go
- pkg/portal/routes.go
- pkg/portal/service/authz.go
- pkg/portal/service/collaborator.go
- pkg/portal/service/config.go
- pkg/portal/service/deps.go
- pkg/portal/transport/admin_api_handler.go
- pkg/portal/wire_gen.go
- pkg/util/graphqlutil/lazy.go
- pkg/util/graphqlutil/lazy_test.go
- portal/src/graphql/portal/schema.graphql
> Enforce portal access control - Part 1

- portal/src/ScreenNav.tsx
- portal/src/graphql/adminapi/ResetPasswordScreen.tsx
- portal/src/graphql/adminapi/UserDetailsScreen.tsx
- portal/src/graphql/portal/AuthenticationConfigurationScreen.tsx
- portal/src/graphql/portal/PasswordsScreen.tsx
- portal/src/hook/usePivot.ts
> Disallow navigate to same page

- pkg/lib/authn/authenticator/password/deps.go
- pkg/lib/authn/authenticator/password/provider.go
- pkg/lib/config/authenticator.go
- pkg/lib/config/testdata/config_tests.yaml
- pkg/lib/config/testdata/default_config.yaml
connect #462
Frontend already handled empty password.
https://github.com/authgear/authgear-server/blob/2d15d634c5ace571628b38694c594e782206a262/portal/src/PasswordField.tsx#L89-L114
> Validate password in resetPassword mutation

- .env.example.k8s
- hack/k8s-manifest.yaml
- portal/README.md
- portal/nginx.conf
fix #485 
@axolotl0212 For custom domain, you'll need to use multi-tenant mode to test the APIs. Please try the instructions in the PR and let me know whether you can get it to work.
> Describe development k8s setup

- hack/ingress.tpl.yaml
- pkg/portal/service/app.go
- pkg/portal/service/config.go
- pkg/portal/service/domain.go
> Fix custom domain API

- pkg/admin/wire_gen.go
- pkg/auth/deps.go
- pkg/auth/handler/webapp/change_secondary_password.go
- pkg/auth/handler/webapp/create_authenticator_begin.go
- pkg/auth/handler/webapp/create_password.go
- pkg/auth/handler/webapp/deps.go
- pkg/auth/handler/webapp/settings.go
- pkg/auth/routes.go
- pkg/auth/webapp/state_middleware.go
- pkg/auth/wire_gen.go
- pkg/auth/wire_handler.go
- pkg/lib/authn/mfa/service.go
- pkg/lib/deps/deps_common.go
- pkg/lib/facade/coordinator.go
- pkg/lib/interaction/nodes/create_authenticator_begin.go
- pkg/resolver/wire_gen.go
- static/authui/css/main.css
- templates/auth_ui_change_secondary_password.html
- templates/auth_ui_create_password.html
- templates/auth_ui_settings.html
- templates/auth_ui_translation.json
> Implement password MFA settings UI

- portal/src/graphql/portal/DNSConfigurationScreen.module.scss
- portal/src/graphql/portal/DNSConfigurationScreen.tsx
- portal/src/graphql/portal/OAuthClientConfigurationScreen.module.scss
- portal/src/graphql/portal/OAuthClientConfigurationScreen.tsx
- portal/src/locale-data/en.json
closes #469 
TODO: review the description in each field
> Add allowed origin config to OAuth client list

- portal/src/AppRoot.tsx
- portal/src/error/domain.ts
- portal/src/error/domainVerificationFailed.ts
- portal/src/error/duplicatedDomain.ts
- portal/src/error/error.ts
- portal/src/error/invalidDomain.ts
- portal/src/graphql/portal/DNSConfigurationScreen.tsx
- portal/src/graphql/portal/VerifyDomainScreen.module.scss
- portal/src/graphql/portal/VerifyDomainScreen.tsx
- portal/src/graphql/portal/mutations/__generated__/VerifyDomainMutation.ts
- portal/src/graphql/portal/mutations/verifyDomainMutation.ts
- portal/src/hook/useInput.ts
- portal/src/locale-data/en.json
> Layout verify domain screen

- go.mod
- go.sum
- pkg/admin/graphql/entity.go
- pkg/admin/graphql/query.go
- pkg/portal/graphql/nodes.go
- pkg/portal/graphql/query.go
- portal/src/graphql/adminapi/schema.graphql
- portal/src/graphql/portal/schema.graphql
> Add nodes to root query

- .env.example
- .env.example.k8s
- pkg/portal/config/app.go
- pkg/portal/service/app.go
- pkg/portal/transport/runtime_config_handler.go
- pkg/portal/wire_gen.go
> Use domain suffix instead of Go template

- portal/src/ReactApp.tsx
- portal/src/ScreenHeader.module.scss
- portal/src/ScreenHeader.tsx
- portal/src/context/RuntimeConfigContext.ts
- portal/src/graphql/portal/AppsScreen.module.scss
- portal/src/graphql/portal/AppsScreen.tsx
- portal/src/graphql/portal/CreateAppScreen.module.scss
- portal/src/graphql/portal/CreateAppScreen.tsx
- portal/src/graphql/portal/query/appListQuery.ts
- portal/src/locale-data/en.json
> Update app list UI

- portal/src/graphql/portal/GeneralSettings.module.scss
- portal/src/graphql/portal/GeneralSettings.tsx
- portal/src/graphql/portal/SettingsScreen.tsx
- portal/src/locale-data/en.json
> Create settings screen general tab

- portal/src/externalLinks.ts
- portal/src/graphql/portal/SingleSignOnConfigurationScreen.tsx
> Update help link in SSO screen

- portal/src/graphql/portal/ForgotPasswordSettings.tsx
- portal/src/graphql/portal/PasswordlessAuthenticatorScreen.tsx
- portal/src/graphql/portal/PasswordsScreen.tsx
- portal/src/graphql/portal/apollo.ts
- portal/src/graphql/portal/mutations/updateAppTemplatesMutation.ts
- portal/src/templates.ts
> Integrate forgot password query and mutation

- portal/src/graphql/portal/SessionSettings.module.scss
- portal/src/graphql/portal/SessionSettings.tsx
- portal/src/graphql/portal/SettingsScreen.module.scss
- portal/src/graphql/portal/SettingsScreen.tsx
- portal/src/locale-data/en.json
- portal/src/types.ts
close #529 
Removed `cookie_domain` and added `idle_timeout_enabled` input field.
> Implement settings screen session tab

- pkg/lib/infra/sms/client.go
> Optional SMS Provider config

- hack/k8s-manifest.yaml
- portal/README.md
> Update redirect URI in README and k8s config

- pkg/lib/config/config.go
- pkg/lib/config/testdata/config_tests.yaml
> Allow same authenticator type in primary & secondary authenticators

- pkg/portal/db/handle.go
- pkg/portal/db/pool.go
- pkg/portal/deps/deps.go
- pkg/portal/deps/providers.go
- pkg/portal/transport/admin_api_handler.go
- pkg/portal/wire_gen.go
> Use singleton DB connection pool in portal

- pkg/admin/facade/identity.go
- pkg/admin/facade/user.go
- pkg/admin/graphql/context.go
- pkg/admin/graphql/identity_mutation.go
- pkg/admin/graphql/user_mutation.go
> Return entity reference only in mutating service facade functions

- pkg/auth/handler/webapp/validation.go
- pkg/auth/handler/webapp/viewmodels/base.go
- pkg/lib/config/config.go
- pkg/lib/config/config_test.go
- pkg/lib/config/testdata/config_tests.yaml
- pkg/lib/config/testdata/country_calling_code_config_test.yaml
- pkg/lib/config/testdata/default_config.yaml
- pkg/lib/config/ui.go
- portal/src/error/ErrorDialog.tsx
- portal/src/graphql/adminapi/AddPhoneScreen.tsx
- portal/src/graphql/portal/AuthenticationCountryCallingCodeList.module.scss
- portal/src/graphql/portal/AuthenticationCountryCallingCodeList.tsx
- portal/src/graphql/portal/AuthenticationLoginIDSettings.module.scss
- portal/src/graphql/portal/AuthenticationLoginIDSettings.tsx
- portal/src/locale-data/en.json
- portal/src/types.ts
- portal/src/util/countryCallingCode.ts
fix #487 
fix #390 
- updated backend country code config shape
- updated frontend UI
> Update country code config

- portal/src/graphql/adminapi/UserDetailsAccountSecurity.tsx
- portal/src/graphql/portal/AuthenticationAuthenticatorSettings.tsx
- portal/src/locale-data/en.json
> Add translation for authenticator type

- resources/authgear/templates/__default__/messages/verification_email.html
- resources/authgear/templates/__default__/messages/verification_email.mjml
> Include verification code in email

- pkg/lib/feature/forgotpassword/provider.go
> Use correct phone number claim name

- portal/src/error/ErrorDialog.tsx
- portal/src/error/ShowUnhandledValidationErrorCauses.module.scss
- portal/src/error/ShowUnhandledValidationErrorCauses.tsx
- portal/src/error/apps.ts
- portal/src/error/error.ts
- portal/src/error/useGenericError.ts
- portal/src/error/useValidationError.ts
- portal/src/graphql/adminapi/AddEmailScreen.tsx
- portal/src/graphql/adminapi/AddPhoneScreen.tsx
- portal/src/graphql/adminapi/AddUserScreen.tsx
- portal/src/graphql/adminapi/AddUsernameScreen.tsx
- portal/src/graphql/adminapi/ResetPasswordScreen.tsx
- portal/src/graphql/portal/AcceptAdminInvitationScreen.tsx
- portal/src/graphql/portal/AnonymousUsersConfigurationScreen.tsx
- portal/src/graphql/portal/AuthenticationAuthenticatorSettings.tsx
- portal/src/graphql/portal/CreateAppScreen.tsx
- portal/src/graphql/portal/CreateOAuthClientScreen.tsx
- portal/src/graphql/portal/DNSConfigurationScreen.tsx
- portal/src/graphql/portal/EditOAuthClientScreen.tsx
- portal/src/graphql/portal/InviteAdminScreen.tsx
- portal/src/graphql/portal/SingleSignOnConfigurationScreen.tsx
- portal/src/locale-data/en.json
fix #561 #576 #575
Now useGenericError needs to handle validation error which also changes unhandled causes. Need to find a better way to handle this
TODO: handle create app error
> Fix missing error message

- portal/src/ShowError.tsx
> Only show debug info in error message in dev env

- portal/src/ModifiedIndicator.module.scss
- portal/src/ModifiedIndicatorPortal.tsx
- portal/src/graphql/adminapi/AddEmailScreen.module.scss
- portal/src/graphql/adminapi/AddPhoneScreen.module.scss
- portal/src/graphql/adminapi/AddUserScreen.module.scss
- portal/src/graphql/adminapi/AddUsernameScreen.module.scss
- portal/src/graphql/adminapi/ResetPasswordScreen.module.scss
- portal/src/graphql/portal/AnonymousUsersConfigurationScreen.module.scss
- portal/src/graphql/portal/CreateOAuthClientScreen.module.scss
- portal/src/graphql/portal/DNSConfigurationScreen.module.scss
- portal/src/graphql/portal/EditOAuthClientScreen.module.scss
- portal/src/graphql/portal/InviteAdminScreen.module.scss
- portal/src/graphql/portal/OAuthClientConfigurationScreen.module.scss
- portal/src/graphql/portal/SingleSignOnConfigurationScreen.module.scss
- portal/src/graphql/portal/VerifyDomainScreen.module.scss
> Make modified indicator sticky

- pkg/lib/translation/service.go
> Inject app name into render context of message headers

- pkg/auth/handler/webapp/change_password.go
- pkg/auth/handler/webapp/change_secondary_password.go
- pkg/auth/handler/webapp/forgot_password.go
- pkg/auth/handler/webapp/reset_password.go
> Preserve state in entrypoint

- pkg/admin/routes.go
- pkg/portal/routes.go
- pkg/util/httputil/content_type.go
- pkg/util/httputil/content_type_test.go
> Enforce content type checking in graphql endpoint

- pkg/portal/deps.go
- pkg/portal/service/collaborator.go
- pkg/portal/wire_gen.go
- portal/src/error/collaborator.ts
- portal/src/error/error.ts
- portal/src/graphql/portal/AcceptAdminInvitationScreen.tsx
- portal/src/locale-data/en.json
> Check collaborator invitee email

- portal/src/graphql/portal/AuthenticationAuthenticatorSettings.tsx
> Fix state comparison in authenticator screen

- pkg/auth/webapp/service.go
- pkg/auth/webapp/store.go
- resources/authgear/templates/__default__/translation.json
- resources/authgear/templates/__default__/web/__error.html
> Refresh ua token per interaction

- pkg/auth/handler/webapp/forgot_password.go
- pkg/auth/handler/webapp/forgot_password_success.go
- pkg/auth/handler/webapp/viewmodels/base.go
- pkg/auth/webapp/service.go
- pkg/lib/interaction/intents/forgot_password.go
- pkg/lib/interaction/nodes/forgot_password.go
- resources/authgear/templates/__default__/web/enter_password.html
- resources/authgear/templates/__default__/web/forgot_password_success.html
- resources/authgear/templates/__default__/web/login.html
- resources/authgear/templates/__default__/web/signup.html
> Return to previous URL when forgot password ends

- portal/src/locale-data/en.json
> Explain the public origin

- pkg/lib/authn/sso/oidc.go
- pkg/util/jwsutil/jwsutil.go
- pkg/util/jwsutil/jwsutil_test.go
> Fix Azure OIDC ID token signature verification

- README.md
- portal/README.md
@elly0t Updated README according to yesterday's setup troubleshooting session. Please let me know if I miss anything.
> Update dev setup instruction

- resources/authgear/static/authgear.js
> Replace document with fetched document when submitting form

- pkg/portal/graphql/domain_mutation.go
> Reset custom domain public origin to default domain if deleted

- pkg/lib/config/config.go
- pkg/lib/config/config_test.go
- pkg/lib/config/http.go
- pkg/lib/config/testdata/config_tests.yaml
- pkg/lib/config/testdata/country_calling_code_config_test.yaml
- pkg/lib/config/testdata/default_config.yaml
- pkg/lib/config/testdata/secret_config_validate_tests.yaml
- pkg/portal/util/resources/validate_test.go
- pkg/util/validation/formats.go
- pkg/util/validation/schema_test.go
- portal/src/FormTextFieldList.module.scss
- portal/src/FormTextFieldList.tsx
- portal/src/error/FormFieldContext.ts
- portal/src/error/useValidationError.ts
- portal/src/error/validation.ts
- portal/src/graphql/portal/EditOAuthClientScreen.tsx
- portal/src/graphql/portal/ModifyOAuthClientForm.module.scss
- portal/src/graphql/portal/ModifyOAuthClientForm.tsx
- portal/src/graphql/portal/OAuthClientConfigurationScreen.module.scss
- portal/src/graphql/portal/OAuthClientConfigurationScreen.tsx
- portal/src/locale-data/en.json
> Create new url list input component

- portal/src/graphql/portal/DNSConfigurationScreen.module.scss
- portal/src/graphql/portal/VerifyDomainScreen.module.scss
> Fix verify domain success message bar style

- pkg/lib/config/generate.go
- pkg/portal/service/app.go
> Set cookie domain for new app

- portal/src/graphql/portal/OAuthClientConfigurationScreen.module.scss
- portal/src/graphql/portal/OAuthClientConfigurationScreen.tsx
- portal/src/locale-data/en.json
> Add API endpoint session to client applications screen 

- pkg/auth/handler/webapp/change_password.go
- pkg/auth/handler/webapp/change_secondary_password.go
- pkg/lib/interaction/nodes/change_password.go
- resources/authgear/templates/__default__/web/change_password.html
- resources/authgear/templates/__default__/web/change_secondary_password.html
> Require old password when changing password

- migrations/portal/20201029181516-collaborator_role.sql
- migrations/portal/20201029192724-app_quota.sql
- pkg/portal/config/app.go
- pkg/portal/graphql/app_mutation.go
- pkg/portal/graphql/collaborator.go
- pkg/portal/graphql/collaborator_mutation.go
- pkg/portal/graphql/context.go
- pkg/portal/graphql/errors.go
- pkg/portal/model/collaborator.go
- pkg/portal/service/app.go
- pkg/portal/service/authz.go
- pkg/portal/service/collaborator.go
- pkg/portal/wire_gen.go
- portal/src/graphql/portal/schema.graphql
> Limit amount of owned apps per user

- pkg/util/phone/phone.go
- pkg/util/phone/phone_test.go
fix https://github.com/authgear/authgear-deploy/issues/31
> Fix phone number validation

- pkg/lib/authn/otp/format.go
- pkg/lib/config/authenticator.go
> Increase minimum code length from 4 to 6

- pkg/admin/wire_gen.go
- pkg/auth/wire_gen.go
- pkg/lib/authn/mfa/ratelimit.go
- pkg/lib/authn/mfa/service.go
- pkg/lib/deps/deps_common.go
- pkg/lib/feature/verification/ratelimit.go
- pkg/lib/feature/verification/service.go
- pkg/lib/feature/verification/service_mock_test.go
- pkg/lib/interaction/context.go
- pkg/lib/interaction/nodes/do_consume_recovery_code.go
- pkg/lib/interaction/ratelimit.go
- pkg/resolver/wire_gen.go
> Improve rate limit behavior

- pkg/lib/config/secret.go
- pkg/lib/config/testdata/secret_config_validate_tests.yaml
- portal/src/error/useValidationError.ts
- portal/src/graphql/portal/SingleSignOnConfigurationScreen.tsx
- portal/src/graphql/portal/SingleSignOnConfigurationWidget.tsx
> Handle missing OAuth provider client secret

- portal/src/graphql/adminapi/AddEmailScreen.tsx
- portal/src/graphql/adminapi/AddPhoneScreen.tsx
- portal/src/graphql/adminapi/AddUserScreen.tsx
- portal/src/graphql/adminapi/AddUsernameScreen.tsx
- portal/src/graphql/adminapi/PrimaryIdentitiesSelectionForm.tsx
- portal/src/graphql/adminapi/ResetPasswordScreen.tsx
- portal/src/graphql/adminapi/UserDetailsConnectedIdentities.tsx
- portal/src/graphql/portal/AnonymousUsersConfigurationScreen.tsx
- portal/src/graphql/portal/AuthenticationAuthenticatorSettings.tsx
- portal/src/graphql/portal/AuthenticationConfigurationScreen.tsx
- portal/src/graphql/portal/AuthenticationLoginIDSettings.tsx
- portal/src/graphql/portal/CreateOAuthClientScreen.tsx
- portal/src/graphql/portal/DNSConfigurationScreen.tsx
- portal/src/graphql/portal/EditOAuthClientScreen.tsx
- portal/src/graphql/portal/ForgotPasswordSettings.tsx
- portal/src/graphql/portal/InviteAdminScreen.tsx
- portal/src/graphql/portal/OAuthClientConfigurationScreen.tsx
- portal/src/graphql/portal/PasswordPolicySettings.tsx
- portal/src/graphql/portal/PasswordlessAuthenticatorScreen.tsx
- portal/src/graphql/portal/PasswordsScreen.tsx
- portal/src/graphql/portal/SessionSettings.tsx
- portal/src/graphql/portal/SingleSignOnConfigurationScreen.tsx
- portal/src/graphql/portal/mutations/updateAppConfigMutation.ts
- portal/src/graphql/portal/mutations/updateAppTemplatesMutation.ts
- portal/src/hook/graphql.ts
- portal/src/hook/usePivot.ts
> Reset error state on switching tab and reset form state

- portal/package-lock.json
- portal/package.json
- portal/src/graphql/portal/AuthenticationCountryCallingCodeList.tsx
- portal/src/util/search.ts
> Use exact keyword for calling code search

- portal/src/graphql/adminapi/UserDetailsScreen.tsx
fix #693 
action to be implemented
> Hide command bar in user detail screen

- pkg/auth/webapp/cookie.go
- pkg/auth/webapp/csrf.go
- pkg/auth/webapp/csrf_middleware.go
- pkg/auth/wire_gen.go
- pkg/lib/authn/mfa/cookie.go
- pkg/lib/config/generate.go
- pkg/lib/config/http.go
- pkg/lib/config/session.go
- pkg/lib/session/idpsession/cookie.go
> Move cookie domain to HTTP

- pkg/admin/facade/interaction.go
- pkg/admin/wire_gen.go
- pkg/auth/wire_gen.go
- pkg/lib/authn/mfa/service.go
- pkg/lib/feature/forgotpassword/provider.go
- pkg/lib/feature/forgotpassword/ratelimit.go
- pkg/lib/feature/verification/service.go
- pkg/lib/interaction/service.go
- pkg/lib/ratelimit/storage_redis.go
- pkg/resolver/wire_gen.go
> Improve rate limit behaviors

- portal/src/graphql/adminapi/AddEmailScreen.module.scss
- portal/src/graphql/adminapi/AddEmailScreen.tsx
- portal/src/graphql/adminapi/AddPhoneScreen.module.scss
- portal/src/graphql/adminapi/AddPhoneScreen.tsx
- portal/src/graphql/adminapi/AddUsernameScreen.module.scss
- portal/src/graphql/adminapi/AddUsernameScreen.tsx
- portal/src/locale-data/en.json
- portal/src/util/loginID.ts
> Add checking for add identity form

- pkg/lib/config/configsource/kubernetes.go
> Fix stale host map when ingress is deleted

- portal/src/graphql/adminapi/AddEmailScreen.tsx
- portal/src/graphql/adminapi/AddIdentityForm.module.scss
- portal/src/graphql/adminapi/AddIdentityForm.tsx
- portal/src/graphql/adminapi/AddPhoneScreen.tsx
- portal/src/graphql/adminapi/AddUsernameScreen.module.scss
- portal/src/graphql/adminapi/AddUsernameScreen.tsx
- portal/src/graphql/adminapi/mutations/createIdentityMutation.ts
> Show password field for all add identity form if needed

- pkg/auth/handler/webapp/change_password.go
- pkg/auth/handler/webapp/change_secondary_password.go
- pkg/auth/handler/webapp/create_password.go
- pkg/auth/handler/webapp/reset_password.go
- pkg/auth/handler/webapp/viewmodels/password_policy.go
- resources/authgear/templates/__default__/web/__password_policy.html
fix https://github.com/authgear/authgear-deploy/issues/42
> Only show reuse password policy when creating primary password

- resources/authgear/static/authgear.css
fix https://github.com/authgear/authgear-deploy/issues/44
> Fix phone number fields alignment

- resources/authgear/static/authgear.css
> Fix verify identity long email layout

- resources/authgear/static/authgear.css
fix authgear/authgear-deploy#43
> Fix recovery code list overflow on mobile 

- portal/src/graphql/portal/CreateOAuthClientScreen.tsx
> Hide scrollbar in copy client ID success callout

- resources/authgear/static/authgear.css
- resources/authgear/static/authgear.js
- resources/authgear/templates/__default__/translation.json
- resources/authgear/templates/__default__/web/change_password.html
- resources/authgear/templates/__default__/web/create_password.html
fix authgear/authgear-deploy#41
> Add show and hide password button to password field 

- pkg/auth/deps.go
- pkg/auth/handler/webapp/enter_login_id.go
- pkg/auth/wire_gen.go
- pkg/lib/authn/identity/service/service.go
- resources/authgear/templates/__default__/translation.json
- resources/authgear/templates/__default__/web/enter_login_id.html
fix authgear/authgear-deploy#48
> Add description to change login ID page

- .env.example
- .env.example.k8s
- cmd/authgear/Dockerfile
- cmd/portal/Dockerfile
- hack/k8s-resources/templates
> Add missing portal resources

- hack/ingress.tpl.yaml
- pkg/lib/config/configsource/kubernetes.go
- pkg/portal/service/config.go
- pkg/portal/service/config_test.go
> Support creating multiple ingresses

- authui/src/authgear.css
- pkg/admin/deps.go
- pkg/admin/facade/deps.go
- pkg/admin/facade/session.go
- pkg/admin/graphql/context.go
- pkg/admin/graphql/models.go
- pkg/admin/graphql/session.go
- pkg/admin/graphql/session_mutation.go
- pkg/admin/graphql/user.go
- pkg/admin/wire_gen.go
- pkg/api/model/meta.go
- pkg/api/model/session.go
- pkg/api/model/user_agent.go
- pkg/auth/deps.go
- pkg/auth/handler/webapp/deps.go
- pkg/auth/handler/webapp/settings.go
- pkg/auth/handler/webapp/settings_sessions.go
- pkg/auth/routes.go
- pkg/auth/wire_gen.go
- pkg/auth/wire_handler.go
- pkg/lib/session/manager.go
- portal/src/graphql/adminapi/query/__generated__/UserQuery.ts
- portal/src/graphql/adminapi/schema.graphql
- resources/authgear/templates/en/translation.json
- resources/authgear/templates/en/web/settings.html
- resources/authgear/templates/en/web/settings_sessions.html
> Add session management API & UI

- pkg/portal/graphql/resource.go
- pkg/util/resource/descriptor.go
- pkg/util/resource/descriptor_test.go
> Fix portal API behavior for non-existent resources

- portal/src/templates.ts
> Unbreak portal template language

- pkg/admin/graphql/session.go
- pkg/api/model/session.go
- pkg/lib/oauth/grant_offline.go
- pkg/lib/session/idpsession/session.go
- portal/src/graphql/adminapi/UserDetailsScreen.tsx
- portal/src/graphql/adminapi/UserDetailsSession.module.scss
- portal/src/graphql/adminapi/UserDetailsSession.tsx
- portal/src/graphql/adminapi/__generated__/globalTypes.ts
- portal/src/graphql/adminapi/mutations/__generated__/RevokeAllSessionsMutation.ts
- portal/src/graphql/adminapi/mutations/__generated__/RevokeSessionMutation.ts
- portal/src/graphql/adminapi/mutations/revokeAllSessionsMutation.ts
- portal/src/graphql/adminapi/mutations/revokeSessionMutation.ts
- portal/src/graphql/adminapi/query/__generated__/UserQuery.ts
- portal/src/graphql/adminapi/query/userQuery.ts
- portal/src/graphql/adminapi/schema.graphql
- portal/src/locale-data/en.json
- portal/src/util/user.ts
> Implement session management UI in portal

- pkg/lib/config/configsource/resources.go
- pkg/lib/web/css.go
- pkg/lib/web/image.go
- pkg/lib/web/javascript.go
- pkg/portal/graphql/resource.go
- pkg/portal/util/resources/load.go
- pkg/util/resource/descriptor.go
- pkg/util/resource/manager.go
- pkg/util/template/resource.go
- pkg/util/template/translation.go
- portal/src/graphql/portal/schema.graphql
> Expose resource language tag in portal API

- docs/specs/delete-user.md
- docs/specs/disable-user.md
- docs/specs/index.md
> Add spec for deleting/disabling users

- pkg/admin/deps.go
- pkg/admin/facade/user.go
- pkg/admin/graphql/context.go
- pkg/admin/graphql/user_mutation.go
- pkg/admin/wire_gen.go
- pkg/auth/wire_gen.go
- pkg/lib/authn/authenticator/password/history_store.go
- pkg/lib/authn/user/commands.go
- pkg/lib/authn/user/commands_raw.go
- pkg/lib/authn/user/store.go
- pkg/lib/deps/deps_common.go
- pkg/lib/facade/coordinator.go
- pkg/lib/facade/deps.go
- pkg/lib/facade/user.go
- pkg/lib/feature/verification/service.go
- pkg/lib/feature/verification/service_mock_test.go
- pkg/lib/feature/verification/store_pq.go
- pkg/lib/oauth/handler/mock_test.go
- pkg/lib/oauth/pq/store_authz.go
- pkg/lib/oauth/store_authz.go
- pkg/resolver/wire_gen.go
- portal/src/graphql/adminapi/DeleteUserDialog.tsx
- portal/src/graphql/adminapi/UserDetailCommandBar.tsx
- portal/src/graphql/adminapi/mutations/__generated__/DeleteUserMutation.ts
- portal/src/graphql/adminapi/mutations/deleteUserMutation.ts
- portal/src/graphql/adminapi/schema.graphql
- portal/src/locale-data/en.json
> Handle deleting user

- cmd/authgear/migrate.go
- cmd/portal/migrate.go
> Make migrate command read envvar and cli args only

- authui/src/authgear.css
- pkg/auth/deps.go
- pkg/auth/handler/webapp/viewmodels/base.go
- pkg/auth/wire_gen.go
- pkg/lib/translation/service.go
- pkg/util/template/translation_map.go
- resources/authgear/templates/en/translation.json
- resources/authgear/templates/en/web/promote.html
- resources/authgear/templates/en/web/signup.html
> Add ToC & privacy policy footer in signup page

- pkg/lib/interaction/nodes/do_create_user.go
- pkg/lib/interaction/nodes/select_identity_end.go
> Fix not bypassing all IP rate limit for admin APIs

- pkg/portal/graphql/app_mutation.go
- pkg/portal/graphql/resource.go
- pkg/util/template/translation.go
- pkg/util/template/translation_test.go
- portal/src/graphql/portal/EditTemplatesWidget.tsx
- portal/src/graphql/portal/TemplatesConfigurationScreen.tsx
- portal/src/graphql/portal/mutations/updateAppAndSecretMutation.ts
- portal/src/graphql/portal/mutations/updateAppConfigMutation.ts
- portal/src/graphql/portal/mutations/updateAppRawTemplatesMutation.ts
- portal/src/graphql/portal/mutations/updateAppTemplatesMutation.ts
- portal/src/graphql/portal/query/__generated__/AppTemplatesQuery.ts
- portal/src/graphql/portal/query/appRawTemplatesQuery.ts
- portal/src/graphql/portal/query/appTemplatesQuery.ts
- portal/src/locale-data/en.json
- portal/src/templates.ts
> Support editing translation.json

- pkg/auth/wire_gen.go
- pkg/lib/deps/deps_common.go
- pkg/lib/oauth/handler/handler_token.go
> Forbid refreshing access token when user is disabled

- pkg/lib/config/oauth.go
- pkg/lib/config/session.go
- pkg/lib/config/testdata/default_config.yaml
> Increase default session lifetime

- pkg/auth/deps.go
- pkg/auth/handler/oauth/userinfo.go
- pkg/auth/wire_gen.go
- pkg/lib/config/config.go
- pkg/lib/config/generate.go
- pkg/lib/config/oauth.go
- pkg/lib/config/secret.go
- pkg/lib/config/secret_data.go
- pkg/lib/config/testdata/parse_secret_tests.yaml
- pkg/lib/config/testdata/secret_config_validate_tests.yaml
- pkg/lib/deps/deps_common.go
- pkg/lib/deps/deps_config.go
- pkg/lib/oauth/deps.go
- pkg/lib/oauth/handler/funcs.go
- pkg/lib/oauth/handler/handler_authz.go
- pkg/lib/oauth/handler/handler_authz_test.go
- pkg/lib/oauth/handler/handler_token.go
- pkg/lib/oauth/handler/handler_token_issue.go
- pkg/lib/oauth/handler/resolve.go
- pkg/lib/oauth/oidc/handler/handler_end_session.go
- pkg/lib/oauth/oidc/id_token.go
- pkg/lib/oauth/oidc/scopes.go
- pkg/lib/oauth/resolver.go
- pkg/lib/oauth/token_encoding.go
- pkg/resolver/deps.go
- pkg/resolver/endpoints.go
- pkg/resolver/wire_gen.go
- pkg/util/jwtutil/jwtutil.go
> Support using JWT as access token

- portal/src/FieldList.module.scss
- portal/src/FieldList.tsx
- portal/src/FormTextFieldList.module.scss
- portal/src/FormTextFieldList.tsx
- portal/src/graphql/portal/HooksSettings.module.scss
- portal/src/graphql/portal/HooksSettings.tsx
- portal/src/graphql/portal/SettingsScreen.tsx
- portal/src/locale-data/en.json
- portal/src/types.ts
> Add web-hook config to portal

- pkg/lib/config/session.go
- pkg/lib/config/testdata/default_config.yaml
- pkg/lib/session/idpsession/expiry.go
- pkg/lib/session/idpsession/expiry_test.go
- pkg/lib/session/idpsession/provider_test.go
- portal/src/graphql/portal/SessionSettings.tsx
> Turn on session idle timeout by default

- pkg/portal/routes.go
- portal/.gitignore
- portal/docker-compose.yaml
- portal/nginx.conf
- portal/package.json
> Add worker-src

- pkg/portal/service/app.go
- portal/src/error/apps.ts
- portal/src/error/error.ts
- portal/src/graphql/portal/CreateAppScreen.tsx
- portal/src/locale-data/en.json
> Handle more create app errors

- resources/authgear/templates/en/translation.json
> Update invalid phone number format error message

- pkg/auth/handler/webapp/enter_oob_otp.go
- pkg/auth/handler/webapp/verify_identity.go
- resources/authgear/templates/en/translation.json
- resources/authgear/templates/en/web/__error.html
- resources/authgear/templates/en/web/enter_oob_otp.html
- resources/authgear/templates/en/web/verify_identity.html
> Separate missing password or code error

- pkg/lib/config/http.go
- pkg/lib/config/testdata/default_config.yaml
> Allow data URI in img-src

- pkg/lib/feature/verification/authenticator.go
- pkg/lib/feature/verification/service.go
- pkg/lib/interaction/context.go
- pkg/lib/interaction/nodes/create_authenticator_oob_setup.go
> Check and skip oob verification if user verified

- portal/src/graphql/portal/CreateAppScreen.tsx
> Update create app screen with form submit

- docs/specs/user-model.md
- pkg/admin/wire_gen.go
- pkg/auth/wire_gen.go
- pkg/lib/authn/authenticator/keys.go
- pkg/lib/authn/authenticator/oob/code.go
- pkg/lib/authn/authenticator/oob/deps.go
- pkg/lib/authn/authenticator/oob/errors.go
- pkg/lib/authn/authenticator/oob/provider.go
- pkg/lib/authn/authenticator/oob/store_redis.go
- pkg/lib/authn/authenticator/service/service.go
- pkg/lib/authn/otp/totp.go
- pkg/lib/config/authenticator.go
- pkg/lib/config/testdata/default_config.yaml
- pkg/lib/feature/verification/service.go
- pkg/lib/interaction/context.go
- pkg/lib/interaction/nodes/authn_oob.go
- pkg/lib/interaction/nodes/authn_oob_trigger.go
- pkg/lib/interaction/nodes/create_authenticator_oob.go
- pkg/lib/interaction/nodes/create_authenticator_oob_setup.go
- pkg/lib/interaction/nodes/oob_resend.go
- pkg/lib/interaction/nodes/utils_authn.go
- pkg/resolver/wire_gen.go
> Unify one-time code / verification code

- portal/src/graphql/portal/ManageLanguageWidget.tsx
> Fix select resource locale dialog UI glitches

- pkg/lib/infra/task/executor/in_process.go
> Add log to track async task duration

- pkg/auth/handler/webapp/deps.go
- pkg/auth/handler/webapp/send_oob_otp.go
- pkg/auth/handler/webapp/viewmodels/alternatives.go
- pkg/auth/routes.go
- pkg/auth/webapp/service2.go
- pkg/auth/webapp/session_step.go
- pkg/auth/wire_gen.go
- pkg/auth/wire_handler.go
- pkg/lib/interaction/nodes/authn_oob_trigger.go
- resources/authgear/templates/en/translation.json
- resources/authgear/templates/en/web/__alternatives.html
- resources/authgear/templates/en/web/send_oob_otp.html
> Add send OOB-OTP code page

- pkg/lib/config/oauth.go
- pkg/lib/oauth/handler/handler_token.go
- pkg/lib/oauth/oidc/scopes.go
ref #796 
TODO: update SDK to stop requesting full access scope for third-party clients.
> Allow configuring OAuth client as first-party client

- authui/src/authgear.ts
- go.mod
- go.sum
- pkg/auth/handler/webapp/controller.go
- pkg/auth/handler/webapp/deps.go
- pkg/auth/handler/webapp/websocket.go
- pkg/auth/routes.go
- pkg/auth/wire_gen.go
- pkg/auth/wire_handler.go
- pkg/lib/config/http.go
- pkg/lib/config/redis.go
- pkg/lib/config/testdata/default_config.yaml
- pkg/lib/infra/redis/handle.go
- pkg/util/pubsub/http_handler.go
- pkg/util/pubsub/publisher.go
> Use websocket to listen interaction change

- docs/specs/oidc.md
- docs/specs/user-model.md
> Add spec for first-party clients

- go.mod
- go.sum
- pkg/auth/handler/webapp/controller.go
- pkg/auth/handler/webapp/websocket.go
- pkg/auth/webapp/session_store.go
- pkg/lib/authn/authenticator/oob/store_redis.go
- pkg/lib/authn/challenge/provider.go
- pkg/lib/authn/mfa/store_device_token_redis.go
- pkg/lib/feature/forgotpassword/store.go
- pkg/lib/feature/verification/store_redis.go
- pkg/lib/infra/redis/handle.go
- pkg/lib/infra/redis/pool.go
- pkg/lib/interaction/store_redis.go
- pkg/lib/oauth/redis/store_grant.go
- pkg/lib/ratelimit/storage_redis.go
- pkg/lib/session/access/event_store_redis.go
- pkg/lib/session/idpsession/store_redis.go
- pkg/util/pubsub/http_handler.go
- pkg/util/pubsub/publisher.go
> Switch redis driver

- authui/src/authgear.css
- authui/src/authgear.ts
- go.mod
- pkg/admin/deps.go
- pkg/admin/web_endpoints.go
- pkg/admin/wire_gen.go
- pkg/auth/deps.go
- pkg/auth/endpoints.go
- pkg/auth/handler/webapp/deps.go
- pkg/auth/handler/webapp/wechat_auth.go
- pkg/auth/handler/webapp/wechat_callback.go
- pkg/auth/routes.go
- pkg/auth/webapp/deps.go
- pkg/auth/webapp/session_step.go
- pkg/auth/webapp/url_provider.go
- pkg/auth/webapp/wechat_url_provider.go
- pkg/auth/wire_gen.go
- pkg/auth/wire_handler.go
- pkg/lib/authn/sso/oauth_provider.go
- pkg/lib/authn/sso/userinfo.go
- pkg/lib/authn/sso/wechat.go
- pkg/lib/authn/sso/wechat_authinfo.go
- pkg/lib/config/identity.go
- resources/authgear/templates/en/translation.json
- resources/authgear/templates/en/web/login.html
- resources/authgear/templates/en/web/promote.html
- resources/authgear/templates/en/web/settings_identity.html
- resources/authgear/templates/en/web/signup.html
- resources/authgear/templates/en/web/wechat_auth.html
> WeChat login with qr code in web

- docs/specs/oidc.md
- docs/specs/user-model.md
requires #810 
TODO: make SDK use web view for settings page
> Add session token spec

- pkg/auth/handler/webapp/enter_oob_otp.go
- pkg/auth/handler/webapp/enter_password.go
- pkg/auth/handler/webapp/enter_totp.go
- pkg/auth/handler/webapp/send_oob_otp.go
- pkg/auth/handler/webapp/viewmodels/alternatives.go
- resources/authgear/templates/en/web/enter_oob_otp.html
- resources/authgear/templates/en/web/enter_password.html
- resources/authgear/templates/en/web/enter_totp.html
> Add back missing save device token checkbox

- portal/src/graphql/portal/CreateOAuthClientScreen.tsx
- portal/src/graphql/portal/ModifyOAuthClientForm.module.scss
- portal/src/graphql/portal/ModifyOAuthClientForm.tsx
- portal/src/locale-data/en.json
- portal/src/types.ts
> Update OAuth client form to match latest config shape

- authui/src/authgear.ts
- pkg/auth/handler/webapp/controller.go
- pkg/auth/handler/webapp/websocket.go
- pkg/lib/deps/providers.go
- pkg/lib/infra/redis/handle.go
- pkg/lib/infra/redis/hub.go
- pkg/lib/infra/redis/pool.go
- pkg/util/pubsub/http_handler.go
- pkg/util/pubsub/publisher.go
fix #822 
NOTE
I did not complete the 3rd point in that issue. It is because when we do not have cookie, we try connect once and give up. So when navigation changes, we want to try again. The current behavior does this automatically.
> Improve pubsub implementation

- pkg/auth/wire_gen.go
- pkg/lib/oauth/handler/handler_authz.go
- pkg/lib/oauth/handler/handler_authz_test.go
- pkg/lib/oauth/handler/resolve.go
> Allow redirect URIs at the authorization server

- pkg/auth/handler/oauth/app_session_token.go
- pkg/auth/handler/oauth/challenge.go
- pkg/auth/handler/webapp/change_password.go
- pkg/auth/handler/webapp/change_secondary_password.go
- pkg/auth/handler/webapp/create_password.go
- pkg/auth/handler/webapp/enter_login_id.go
- pkg/auth/handler/webapp/enter_oob_otp.go
- pkg/auth/handler/webapp/enter_password.go
- pkg/auth/handler/webapp/enter_recovery_code.go
- pkg/auth/handler/webapp/enter_totp.go
- pkg/auth/handler/webapp/forgot_password.go
- pkg/auth/handler/webapp/login.go
- pkg/auth/handler/webapp/promote.go
- pkg/auth/handler/webapp/reset_password.go
- pkg/auth/handler/webapp/setup_oob_otp.go
- pkg/auth/handler/webapp/setup_totp.go
- pkg/auth/handler/webapp/signup.go
- pkg/auth/handler/webapp/verify_identity.go
- pkg/portal/graphql/collaborator_mutation.go
> Simplify validation schema setup

- portal/src/AppRoot.tsx
- portal/src/ScreenNav.tsx
- portal/src/graphql/portal/VerificationConfigurationScreen.module.scss
- portal/src/graphql/portal/VerificationConfigurationScreen.tsx
- portal/src/locale-data/en.json
- portal/src/types.ts
> Add basic user verification config screen

- authui/src/authgear.css
- authui/src/authgear.ts
- pkg/auth/handler/webapp/controller.go
- pkg/auth/handler/webapp/deps.go
- pkg/auth/handler/webapp/publisher.go
- pkg/auth/wire_gen.go
- resources/authgear/templates/en/translation.json
- resources/authgear/templates/en/web/verify_identity.html
> Improve verification UX

- portal/src/ScreenNav.tsx
- portal/src/graphql/adminapi/UsersScreen.module.scss
- portal/src/graphql/adminapi/UsersScreen.tsx
- portal/src/graphql/portal/AnonymousUsersConfigurationScreen.module.scss
- portal/src/graphql/portal/AnonymousUsersConfigurationScreen.tsx
- portal/src/graphql/portal/AuthenticationAuthenticatorSettings.module.scss
- portal/src/graphql/portal/AuthenticationLoginIDSettings.module.scss
- portal/src/graphql/portal/CORSConfigurationScreen.module.scss
- portal/src/graphql/portal/CustomDomainListScreen.module.scss
- portal/src/graphql/portal/CustomDomainListScreen.tsx
- portal/src/graphql/portal/ForgotPasswordSettings.module.scss
- portal/src/graphql/portal/HooksSettings.module.scss
- portal/src/graphql/portal/ManageLanguageWidget.module.scss
- portal/src/graphql/portal/OAuthClientConfigurationScreen.module.scss
- portal/src/graphql/portal/OAuthClientConfigurationScreen.tsx
- portal/src/graphql/portal/PasswordPolicySettings.module.scss
- portal/src/graphql/portal/PortalAdminsSettings.module.scss
- portal/src/graphql/portal/PortalAdminsSettings.tsx
- portal/src/graphql/portal/PublicOriginConfigurationScreen.module.scss
- portal/src/graphql/portal/SessionSettings.module.scss
- portal/src/graphql/portal/SingleSignOnConfigurationScreen.module.scss
- portal/src/graphql/portal/UserInterfaceScreen.module.scss
- portal/src/graphql/portal/UserInterfaceScreen.tsx
- portal/src/graphql/portal/VerificationConfigurationScreen.module.scss
> Portal style tweak

- portal/src/hook/useSimpleForm.ts
> Fix incorrect isSubmitted state

- pkg/lib/config/authenticator.go
- pkg/lib/config/testdata/default_config.yaml
> Increase default password length to 8

- authui/src/authgear.css
- resources/authgear/templates/en/translation.json
- resources/authgear/templates/en/web/login.html
- resources/authgear/templates/en/web/signup.html
> Make login and signup page more obvious

- authui/src/authgear.ts
- pkg/auth/handler/webapp/controller.go
- pkg/auth/handler/webapp/viewmodels/base.go
- pkg/auth/handler/webapp/websocket.go
- pkg/auth/webapp/session.go
- pkg/auth/webapp/url_provider.go
- pkg/auth/wire_gen.go
- pkg/util/pubsub/http_handler.go
- resources/authgear/templates/en/web/__html_head.html
> Send refresh event again after connected to ws

- portal/src/ScreenHeader.tsx
> Turn app ID in the header into link

- resources/authgear/templates/en/messages/verification_email.html
- resources/authgear/templates/en/messages/verification_email.mjml
> Enlarge the verification code in the verification email

- pkg/auth/routes.go
- pkg/auth/webapp/deps.go
- pkg/auth/webapp/result.go
- pkg/auth/webapp/session.go
- pkg/auth/webapp/session_middleware.go
- pkg/auth/webapp/ui_locales.go
- pkg/auth/webapp/url_provider.go
- pkg/auth/wire_gen.go
- pkg/auth/wire_middleware.go
- resources/authgear/templates/en/web/login.html
- resources/authgear/templates/en/web/signup.html
> Store ui_locales in HTTP session cookie

- pkg/lib/oauth/resolver.go
> Fix ErrInvalidSession being ignored

- authui/src/authgear.css
- resources/authgear/templates/en/translation.json
- resources/authgear/templates/en/web/enter_login_id.html
- resources/authgear/templates/en/web/forgot_password.html
- resources/authgear/templates/en/web/login.html
- resources/authgear/templates/en/web/promote.html
- resources/authgear/templates/en/web/settings.html
- resources/authgear/templates/en/web/settings_identity.html
- resources/authgear/templates/en/web/setup_oob_otp.html
- resources/authgear/templates/en/web/signup.html
> Apply default light and dark theme to web UI

- resources/authgear/templates/en/web/promote.html
- resources/authgear/templates/en/web/signup.html
> Fix login ID placeholder in signup page

- pkg/auth/handler/webapp/create_password.go
- pkg/auth/handler/webapp/enter_password.go
- pkg/auth/handler/webapp/interaction.go
- pkg/auth/handler/webapp/viewmodels/alternatives.go
- pkg/lib/interaction/nodes/authn_begin.go
- pkg/lib/interaction/nodes/authn_password.go
- pkg/lib/interaction/nodes/create_authenticator_password.go
- pkg/lib/interaction/nodes/utils_nodes.go
- resources/authgear/templates/en/translation.json
- resources/authgear/templates/en/web/create_password.html
- resources/authgear/templates/en/web/enter_password.html
> Prevent the same password being verified twice

- portal/src/util/search.ts
> Make search case insensitive

- authui/src/authgear.css
- resources/authgear/templates/en/web/enter_login_id.html
- resources/authgear/templates/en/web/enter_oob_otp.html
- resources/authgear/templates/en/web/fatal_error.html
- resources/authgear/templates/en/web/forgot_password_success.html
- resources/authgear/templates/en/web/login.html
- resources/authgear/templates/en/web/promote.html
- resources/authgear/templates/en/web/settings.html
- resources/authgear/templates/en/web/settings_identity.html
- resources/authgear/templates/en/web/settings_mfa.html
- resources/authgear/templates/en/web/signup.html
- resources/authgear/templates/en/web/verify_identity.html
- resources/authgear/templates/en/web/wechat_auth.html
> Tweak web UI style

- portal/src/graphql/portal/AuthenticationAuthenticatorSettings.tsx
- portal/src/locale-data/en.json
> Revise configuration error message

- pkg/auth/handler/webapp/wechat_callback.go
refs #773 
- Update wechat callback api success result for JS SDK
- Add comment to WechatCallbackHandler
> Update wechat callback api success result

- pkg/lib/authn/identity/candidate.go
- pkg/lib/authn/identity/service/service_test.go
- pkg/lib/config/identity.go
- resources/authgear/templates/en/web/login.html
- resources/authgear/templates/en/web/promote.html
- resources/authgear/templates/en/web/signup.html
refs #773 
WeChat application is platform specific, the WeChat web login button
should not be shown if user is using a mobile app. Add app type config
to WeChat app and show the button conditionally.
> Add wechat app type config and show button conditionally

- pkg/lib/authn/sso/error.go
- pkg/lib/authn/sso/userinfo.go
- pkg/lib/authn/sso/wechat.go
- pkg/lib/authn/sso/wechat_authinfo.go
- pkg/lib/config/config.go
- pkg/lib/config/identity.go
- pkg/lib/config/testdata/config_tests.yaml
> WeChat login handle same user login in Web and mobile

- pkg/portal/service/config.go
> Use DNSNames instead of CommonName

- pkg/lib/config/identity.go
- pkg/lib/config/testdata/config_tests.yaml
- pkg/util/validation/formats.go
- portal/src/graphql/adminapi/UserDetailsConnectedIdentities.tsx
- portal/src/graphql/portal/ModifyOAuthClientForm.tsx
- portal/src/graphql/portal/SingleSignOnConfigurationScreen.tsx
- portal/src/graphql/portal/SingleSignOnConfigurationWidget.module.scss
- portal/src/graphql/portal/SingleSignOnConfigurationWidget.tsx
- portal/src/locale-data/en.json
- portal/src/types.ts
> Update portal support WeChat config

- resources/authgear/templates/en/translation.json
- resources/authgear/templates/en/web/__error.html
> Translation InvalidVerificationCode error

- resources/authgear/static/authgear.css
- resources/authgear/templates/en/web/reset_password.html
> Fix password reveal button in password pages

- pkg/auth/handler/webapp/settings_mfa.go
- pkg/auth/handler/webapp/settings_recovery_code.go
- resources/authgear/templates/en/translation.json
- resources/authgear/templates/en/web/settings_mfa.html
- resources/authgear/templates/en/web/settings_recovery_code.html
> Don't allow get new recovery code when list disabled

- pkg/auth/handler/webapp/settings_mfa.go
- resources/authgear/templates/en/web/settings_mfa.html
> Change details button to add button if no authenticator is setup yet

- authui/src/authgear.ts
- pkg/auth/webapp/service2.go
- resources/authgear/templates/en/web/setup_recovery_code.html
> Navigate backward hierarchically

- portal/src/locale-data/en.json
> Update portal copywriting

- pkg/auth/webapp/session_store.go
- pkg/lib/admin/authz/adder.go
- pkg/lib/authn/authenticator/oob/authenticator.go
- pkg/lib/authn/authenticator/service/ratelimit.go
- pkg/lib/authn/challenge/challenge.go
- pkg/lib/authn/identity/anonymous/provider.go
- pkg/lib/authn/mfa/ratelimit.go
- pkg/lib/authn/sso/apple.go
- pkg/lib/feature/forgotpassword/ratelimit.go
- pkg/lib/feature/verification/ratelimit.go
- pkg/lib/infra/mail/ratelimit.go
- pkg/lib/infra/sms/ratelimit.go
- pkg/lib/interaction/graph.go
- pkg/lib/interaction/ratelimit.go
- pkg/lib/oauth/handler/handler_authz.go
- pkg/lib/oauth/handler/handler_token_issue.go
- pkg/lib/oauth/oidc/id_token.go
- pkg/util/duration/duration.go
> Increase interaction lifetime

- resources/authgear/static/authgear-dark-theme.css
- resources/authgear/static/authgear-light-theme.css
- resources/authgear/static/authgear.css
- resources/authgear/templates/en/web/change_password.html
- resources/authgear/templates/en/web/change_secondary_password.html
- resources/authgear/templates/en/web/create_password.html
- resources/authgear/templates/en/web/enter_login_id.html
- resources/authgear/templates/en/web/enter_oob_otp.html
- resources/authgear/templates/en/web/enter_password.html
- resources/authgear/templates/en/web/enter_recovery_code.html
- resources/authgear/templates/en/web/enter_totp.html
- resources/authgear/templates/en/web/forgot_password.html
- resources/authgear/templates/en/web/login.html
- resources/authgear/templates/en/web/promote.html
- resources/authgear/templates/en/web/reset_password.html
- resources/authgear/templates/en/web/setup_oob_otp.html
- resources/authgear/templates/en/web/setup_totp.html
- resources/authgear/templates/en/web/signup.html
- resources/authgear/templates/en/web/verify_identity.html
> Add better support for password manager

- resources/authgear/templates/en/web/promote.html
- resources/authgear/templates/en/web/signup.html
> Fix signup page login id placeholder

- portal/src/PortalColorPicker.tsx
> Fix misplaced color picker

- pkg/admin/facade/interaction.go
- pkg/admin/model/identity.go
> Ensure admin interaction input satisfy intended interface

- pkg/auth/handler/webapp/controller.go
- pkg/auth/handler/webapp/logout.go
- pkg/auth/handler/webapp/settings.go
- pkg/auth/handler/webapp/viewmodels/base.go
- pkg/auth/webapp/redirect.go
- pkg/auth/wire_gen.go
- pkg/lib/config/testdata/config_tests.yaml
- pkg/lib/config/ui.go
- resources/authgear/static/authgear.css
- resources/authgear/templates/en/web/__header.html
> Add home_uri

- pkg/auth/endpoints.go
- pkg/auth/webapp/url_provider.go
- pkg/lib/oauth/handler/handler_authz.go
- pkg/lib/oauth/protocol/authz.go
> Support x_page in the authorization endpoint

- pkg/lib/authn/otp/sender.go
- pkg/lib/feature/forgotpassword/provider.go
- pkg/lib/feature/welcomemessage/provider.go
- pkg/lib/infra/mail/ratelimit.go
- pkg/lib/infra/sms/ratelimit.go
- pkg/lib/interaction/nodes/select_identity_end.go
- pkg/lib/interaction/ratelimit.go
> Update rate limit

- pkg/lib/interaction/intents/authenticate.go
> Ensure verification requirement is enforced during authentication

- pkg/auth/handler/webapp/root.go
- pkg/auth/webapp/cookie.go
- pkg/auth/webapp/deps.go
- pkg/auth/webapp/service2.go
- pkg/auth/wire_gen.go
- pkg/util/duration/duration.go
> Change auth ui go to /signup by default, and go to /login if user signed up

- go.mod
- go.sum
- pkg/util/template/translation_map.go
- resources/authgear/templates/en/web/login.html
- resources/authgear/templates/en/web/promote.html
- resources/authgear/templates/en/web/signup.html
> Hide TOS and privacy policy if they are empty

- pkg/lib/config/configsource/resources.go
- pkg/lib/web/css.go
- pkg/lib/web/image.go
- pkg/lib/web/javascript.go
- pkg/portal/util/resources/apply_update.go
- pkg/util/resource/descriptor.go
- pkg/util/resource/view.go
- pkg/util/template/resource.go
- pkg/util/template/translation.go
- pkg/util/template/translation_test.go
> Validate values of translation.json

- pkg/auth/handler/webapp/viewmodels/base.go
- pkg/lib/web/static_asset_resolver.go
- pkg/lib/web/static_assets.go
- pkg/portal/util/resources/apply_update.go
- resources/authgear/static/authgear.css
- resources/authgear/templates/en/web/__header.html
> Support app_logo_dark

- portal/src/graphql/portal/CustomDomainListScreen.tsx
> Fix missing public origin in ui when portal custom domain page is just loaded

- docs/specs/sessions.md
> Clarify the behavior of offline grant

- pkg/lib/config/configsource/kubernetes.go
- pkg/lib/config/configsource/local_fs.go
- pkg/lib/config/configsource/resources.go
- pkg/lib/web/css.go
- pkg/lib/web/css_test.go
- pkg/lib/web/image.go
- pkg/lib/web/image_test.go
- pkg/lib/web/javascript.go
- pkg/lib/web/javascript_test.go
- pkg/portal/service/app.go
- pkg/portal/util/resources/apply_update.go
- pkg/portal/util/resources/apply_update_test.go
- pkg/portal/util/resources/load_test.go
- pkg/util/intlresource/match.go
- pkg/util/intlresource/match_test.go
- pkg/util/intlresource/prepare.go
- pkg/util/intlresource/prepare_test.go
- pkg/util/resource/descriptor.go
- pkg/util/resource/descriptor_test.go
- pkg/util/resource/fs.go
- pkg/util/resource/manager.go
- pkg/util/resource/manager_test.go
- pkg/util/template/engine_test.go
- pkg/util/template/resource.go
- pkg/util/template/resource_test.go
- pkg/util/template/translation.go
- pkg/util/template/translation_test.go
> Revise fallback language resource resolution

- portal/src/graphql/portal/LocalizationConfigurationScreen.module.scss
- portal/src/graphql/portal/LocalizationConfigurationScreen.tsx
- portal/src/graphql/portal/ManageLanguageWidget.module.scss
- portal/src/graphql/portal/ManageLanguageWidget.tsx
- portal/src/graphql/portal/UISettingsScreen.module.scss
- portal/src/graphql/portal/UISettingsScreen.tsx
- portal/src/locale-data/en.json
depends on https://github.com/authgear/authgear-server/pull/1020
fix #1021
> Revamp language widget

- pkg/auth/webapp/service2.go
- resources/authgear/templates/en/translation.json
- resources/authgear/templates/en/web/__error.html
fix authgear/authgear-sdk-js#64
addressed comment in #1027
> Do not redirect if interaction is aborted by webhook

- portal/src/ScreenContent.module.scss
- portal/src/ScreenContent.tsx
- portal/src/ScreenDescription.module.scss
- portal/src/ScreenDescription.tsx
- portal/src/ScreenTitle.module.scss
- portal/src/ScreenTitle.tsx
- portal/src/ThemeConfigurationWidget.module.scss
- portal/src/ThemeConfigurationWidget.tsx
- portal/src/ThemePresetWidget.module.scss
- portal/src/Widget.module.scss
- portal/src/Widget.tsx
- portal/src/WidgetTitle.module.scss
- portal/src/WidgetTitle.tsx
- portal/src/graphql/portal/UISettingsScreen.module.scss
- portal/src/graphql/portal/UISettingsScreen.tsx
- portal/src/locale-data/en.json
- portal/src/types.ts
> Add link settings

- pkg/lib/interaction/nodes/do_create_user.go
refs #1019 
Check signup rate limit in Instantiate, take the token in EffectOnCommit
To ensure the token is taken when user complete the signup. But checking the
token should be earlier, instead blocking user in the last step.
> Update signup rate limit checking

- resources/authgear/templates/en/messages/setup_secondary_oob_email.html
- resources/authgear/templates/en/messages/setup_secondary_oob_email.mjml
- resources/authgear/templates/en/messages/setup_secondary_oob_email.txt
- resources/authgear/templates/en/messages/setup_secondary_oob_sms.txt
fix #1040
@chpapa If you have time, could you have a look on the copywriting to see if they are more appropriate and relevant now?
> Correct setup secondary oob message content

- pkg/auth/handler/webapp/root.go
- pkg/auth/wire_gen.go
- resources/authgear/templates/en/web/promote.html
- resources/authgear/templates/en/web/signup.html
> Handle public signup disabled gracefully

- pkg/admin/wire_gen.go
- pkg/api/apierrors/error.go
- pkg/auth/wire_gen.go
- pkg/lib/authn/identity/loginid/provider.go
- pkg/lib/config/oauth.go
- pkg/lib/config/session.go
- pkg/lib/deps/middleware_request.go
- pkg/lib/infra/db/sql_executor.go
- pkg/lib/oauth/expiry.go
- pkg/lib/oauth/grant_offline.go
- pkg/lib/oauth/handler/handler_token.go
- pkg/lib/oauth/handler/login_hint.go
- pkg/lib/oauth/redis/store.go
- pkg/lib/oauth/resolver.go
- pkg/lib/oauth/session_manager.go
- pkg/lib/oauth/store_grant.go
- pkg/lib/session/idpsession/expiry.go
- pkg/lib/session/idpsession/manager.go
- pkg/lib/session/idpsession/provider.go
- pkg/portal/db/sql_executor.go
- pkg/resolver/wire_gen.go
- pkg/util/errorutil/barrier_test.go
- pkg/util/errorutil/secondary_test.go
- pkg/util/errorutil/wrap.go
- pkg/util/errorutil/wrap_test.go
- portal/src/graphql/portal/ModifyOAuthClientForm.module.scss
- portal/src/graphql/portal/ModifyOAuthClientForm.tsx
- portal/src/locale-data/en.json
- portal/src/types.ts
> Support idle timeout for refresh token

- pkg/auth/routes.go
- pkg/auth/webapp/deps.go
- pkg/auth/webapp/public_origin_middleware.go
- pkg/auth/wire_gen.go
- pkg/auth/wire_middleware.go
> Redirect to public origin if request origin does not match

- cmd/authgear/server/config.go
- cmd/authgear/server/server.go
- go.mod
- go.sum
- pkg/auth/config.go
- pkg/auth/routes.go
- pkg/util/httputil/etag.go
> Set more cache friendly headers in HTTP response

- .tool-versions
- cmd/authgear/Dockerfile
- cmd/portal/Dockerfile
> Upgrade to Go 1.16.2

- portal/src/graphql/portal/OnboardingCompletionScreen.tsx
> Fix incorrect SSO image in onboarding completion screen

- docs/specs/user-model.md
- pkg/lib/config/testdata/default_config.yaml
ref #906 
Maybe we can use this list as the default blacklist: https://gist.github.com/tbrianjones/5992856
> Add domain blacklist and whitelist for email login id spec

- pkg/auth/handler/webapp/settings_biometric.go
- pkg/lib/authn/identity/info.go
- pkg/lib/interaction/nodes/use_identity_biometric.go
- pkg/util/deviceinfo/deviceinfo.go
- pkg/util/deviceinfo/deviceinfo_test.go
> Show device info

- pkg/lib/hook/provider.go
- pkg/lib/hook/provider_test.go
ref #1041 
This PR is fixing an existing bug in hook provider.
- Register `before_session_create` hook only and return `is_allowed=false`
- Signup  a user
In hook provider, DispatchEvent will be called multiple times. If the first DispatchEvent
is success, dbHook is registered already even the latter events have error. If there is
error, all the later operations should be skipped, so we need check and skip them.
We cannot see this problem when aborting signup in before_user_create, as
before_user_create is the first event in signup, so dbHook is not be registered in this case 
and no further DispatchEvent will be called.
> Fix unexpected error when aborting signup in before_session_create hook

- pkg/lib/interaction/nodes/create_identity_begin.go
- pkg/lib/interaction/nodes/do_create_identity.go
- pkg/lib/interaction/nodes/incompatible_input.go
- pkg/lib/interaction/nodes/select_identity_begin.go
> Fix cannot promote anonymous user

- pkg/lib/config/oauth.go
- pkg/lib/oauth/handler/handler_token.go
- pkg/lib/oauth/oidc/scopes.go
- portal/src/graphql/portal/CreateOAuthClientScreen.tsx
- portal/src/graphql/portal/ModifyOAuthClientForm.tsx
- portal/src/locale-data/en.json
- portal/src/types.ts
> Make client default to first party

- pkg/admin/transport/handler.go
- pkg/admin/wire_gen.go
- pkg/portal/transport/graphql_handler.go
> Remove DEV_MODE config from admin api

- docs/specs/api.md
- docs/specs/biometric.md
- docs/specs/oidc.md
- docs/specs/sdk.md
- docs/specs/ui.md
- docs/specs/user-model.md
ref #943 
For all readers, they should read in this order:
1. user-model.md
2. sdk.md
For implementers, they should read in this order:
1. user-model.md
2. sdk.md
3. api.md
4. oidc.md
> Add biometric authentication draft

- portal/src/graphql/portal/LocalizationConfigurationScreen.tsx
- portal/src/graphql/portal/ManageLanguageWidget.tsx
- portal/src/graphql/portal/UISettingsScreen.tsx
- portal/src/resources.ts
> Allow language configuration in UI Settings

- docs/specs/webhook.md
> Revamp webhook spec

- portal/src/graphql/portal/OAuthClientConfigurationScreen.tsx
> Fix incorrect links in portal OAuthClientConfigurationScreen

- pkg/auth/handler/webapp/login.go
- pkg/lib/interaction/intents/authenticate.go
- pkg/lib/interaction/nodes/do_create_session.go
- pkg/lib/oauth/handler/handler_token.go
- pkg/lib/session/attrs.go
> Do not create extra IdP session for anonymous user and biometric authentication

- README.md
- portal/package-lock.json
- portal/package.json
fix #1120 
The nginx conf has support for serving the built bundle on the port `8010`. It is not new though. I visited the portal on port `8010` and the error is gone when I revert parcel to 2.0.0-beta.1
> Revert to parcel 2.0.0-beta.1

- resources/authgear/templates/en/web/change_password.html
- resources/authgear/templates/en/web/create_password.html
- resources/authgear/templates/en/web/reset_password.html
> Make password visibility button tabindex -1

- pkg/lib/interaction/ratelimit.go
> Increase signup ratelimit from 1 to 10 per minute

- pkg/auth/wire_gen.go
- pkg/lib/deps/deps_common.go
- pkg/lib/oauth/handler/handler_token.go
- pkg/lib/oauth/oidc/handler/handler_end_session.go
- pkg/lib/oauth/oidc/id_token.go
- pkg/lib/oauth/oidc/id_token_test.go
- pkg/resolver/wire_gen.go
> Direct logout

- pkg/auth/deps.go
- pkg/auth/handler/webapp/viewmodels/settings.go
- pkg/auth/wire_gen.go
- pkg/lib/authn/authenticator/filters.go
- pkg/lib/authn/identity/info.go
- pkg/lib/interaction/nodes/create_authenticator_begin.go
- resources/authgear/templates/en/web/settings.html
> Skip MFA for OAuth during signup AND login

- portal/src/graphql/portal/LoginIDConfigurationScreen.module.scss
- portal/src/graphql/portal/LoginIDConfigurationScreen.tsx
> Put modify-disabled checkbox at the bottom

- pkg/admin/routes.go
- pkg/admin/transport/handler.go
- pkg/resolver/handler/resolve.go
- pkg/resolver/routes.go
- pkg/util/httproute/httproute.go
> Route /_api/admin and /_resolver natively

- pkg/lib/authn/identity/info.go
> Make modify_disabled applicable to login_id and oauth only

- .env.example
- cmd/portal/server/config.go
- cmd/portal/server/server.go
- hack/ingress.tpl.yaml
- hack/kube-apiserver/docker-compose.yaml
- pkg/portal/config/domain.go
- pkg/portal/config/kubernetes.go
- pkg/portal/deps/deps.go
- pkg/portal/deps/providers.go
- pkg/portal/service/app.go
- pkg/portal/service/config.go
- pkg/portal/service/deps.go
- pkg/portal/service/kubernetes.go
- pkg/portal/service/kubernetes_test.go
- pkg/portal/service/testdata/ingress.tpl.yaml
- pkg/portal/service/testdata/ingress_result.yaml
- pkg/portal/service/testdata/invalid_template.tpl.yaml
- pkg/portal/wire_gen.go
> Handle update k8s resources when create and delete domain

- cmd/portal/internal.go
- cmd/portal/internal/db.go
- cmd/portal/internal/migrate_k8s_to_db.go
- cmd/portal/main.go
- pkg/lib/config/configsource/kubernetes.go
- pkg/portal/service/kubernetes.go
- pkg/util/kubeutil/kubeconfig.go
> Add migrate-k8s-to-db command

- cmd/portal/internal.go
- cmd/portal/internal/migrate_resources.go
- cmd/portal/migrate_resources.go
- cmd/portal/migrate_resources_example.go
> Add migrate-resources command

- pkg/lib/interaction/nodes/do_create_identity.go
- pkg/lib/interaction/nodes/do_remove_identity.go
- pkg/lib/interaction/nodes/do_update_identity.go
> Bypass modify_disabled for admin API

- portal/package-lock.json
- portal/package.json
- portal/src/ReactApp.tsx
> Use SDK to 0.9.0 to support direct logout

- docs/specs/webhook.md
- pkg/admin/facade/user.go
- pkg/api/event/blocking/user_pre_create.go
- pkg/api/event/context.go
- pkg/api/event/event.go
- pkg/api/event/nonblocking/identity_loginid_added.go
- pkg/api/event/nonblocking/identity_loginid_removed.go
- pkg/api/event/nonblocking/identity_loginid_updated.go
- pkg/api/event/nonblocking/identity_oauth_connected.go
- pkg/api/event/nonblocking/identity_oauth_disconnected.go
- pkg/api/event/nonblocking/user_anonymous_promoted.go
- pkg/api/event/nonblocking/user_authenticated.go
- pkg/api/event/nonblocking/user_created.go
- pkg/auth/handler/webapp/signup.go
- pkg/auth/webapp/session.go
- pkg/auth/webapp/url_provider.go
- pkg/lib/authn/user/commands.go
- pkg/lib/hook/event_mock.go
- pkg/lib/hook/provider.go
- pkg/lib/interaction/context.go
- pkg/lib/interaction/intent.go
- pkg/lib/interaction/intents/authenticate.go
- pkg/lib/interaction/nodes/do_create_identity.go
- pkg/lib/interaction/nodes/do_create_session.go
- pkg/lib/interaction/nodes/do_create_user.go
- pkg/lib/interaction/nodes/do_remove_identity.go
- pkg/lib/interaction/nodes/do_update_identity.go
- pkg/lib/oauth/handler/handler_authz.go
fix #1141 
- Added new interface `IntentWithWebhookState` to allow passing state to the webhook, see if this approach looks good?
> Include OIDC state parameter in user.pre_create hook

- cmd/portal/internal/migrate_resources.go
- cmd/portal/migrate_reources_migrate_jwks.go
- cmd/portal/migrate_resources_example.go
- pkg/lib/config/generate.go
> Fix missing use and alg attributes in JWKs

- pkg/lib/oauth/oidc/id_token.go
> Remove user claims from id token

- pkg/auth/wire_gen.go
- pkg/lib/interaction/nodes/do_create_session.go
- pkg/lib/oauth/oidc/handler/handler_end_session.go
- pkg/lib/oauth/oidc/id_token.go
- pkg/lib/oauth/session_manager.go
- pkg/lib/session/cookie.go
- pkg/lib/session/idpsession/manager.go
- pkg/lib/session/manager.go
refs #1201 
- Set SameSite strict cookie along with idp session cookie
- Check SameSite strict cookie in end_session_endpoint, direct logout if
it exists
- Clear SameSite strict cookie when logout
> Check SameSite strict cookie for direct logout

- pkg/lib/deps/deps_common.go
- pkg/lib/oauth/handler/handler_token.go
- pkg/lib/oauth/oidc/handler/handler_end_session.go
- pkg/lib/oauth/oidc/id_token.go
- portal/package-lock.json
- portal/package.json
> Remove custom grant type for getting id token

- resources/authgear/templates/en/translation.json
> Shorten the label of terminate session group button

- pkg/admin/wire_gen.go
- pkg/auth/wire_gen.go
- pkg/lib/deps/deps_common.go
- pkg/lib/interaction/context.go
- pkg/lib/interaction/nodes/do_create_session.go
- pkg/lib/oauth/grant_offline.go
- pkg/lib/oauth/handler/handler_token.go
> Clean up unreachable session

- pkg/auth/handler/webapp/interaction.go
- pkg/auth/handler/webapp/login.go
- pkg/auth/handler/webapp/promote.go
- pkg/auth/handler/webapp/settings_identity.go
- pkg/auth/handler/webapp/signup.go
- pkg/auth/webapp/auth_entry_point_middleware.go
- pkg/auth/webapp/session.go
- pkg/auth/webapp/session_store.go
- pkg/auth/webapp/url_provider.go
- pkg/lib/authn/sso/adfs.go
- pkg/lib/authn/sso/apple.go
- pkg/lib/authn/sso/authurl.go
- pkg/lib/authn/sso/azureadv2.go
- pkg/lib/authn/sso/facebook.go
- pkg/lib/authn/sso/google.go
- pkg/lib/authn/sso/linkedin.go
- pkg/lib/authn/sso/oauth_provider.go
- pkg/lib/authn/sso/oidc.go
- pkg/lib/authn/sso/wechat.go
- pkg/lib/interaction/nodes/use_identity_oauth_provider.go
- pkg/lib/oauth/handler/handler_authz.go
> Improve support for prompt

- pkg/lib/infra/redis/hub.go
- pkg/util/pubsub/http_handler.go
> Reduce pubsub logging noise

- authui/src/authgear.ts
- pkg/auth/handler/webapp/template.go
- resources/authgear/static/authgear-light-theme.css
- resources/authgear/static/authgear.css
- resources/authgear/templates/en/translation.json
- resources/authgear/templates/en/web/__modal.html
- resources/authgear/templates/en/web/__page_frame.html
- resources/authgear/templates/en/web/settings_sessions.html
> Add confirmation dialog for revoking sessions

- cmd/authgear/elasticsearch/index.go
- pkg/lib/elasticsearch/index.go
- pkg/lib/elasticsearch/index_test.go
> Avoid sending too short search keyword to elasticsearch

- pkg/lib/oauth/metadata.go
> Declare token_endpoint_auth_methods_supported

- pkg/auth/handler/webapp/enter_login_id.go
- pkg/auth/handler/webapp/viewmodels/authentication.go
- resources/authgear/templates/en/web/enter_login_id.html
- resources/authgear/templates/en/web/settings.html
- resources/authgear/templates/en/web/settings_identity.html
> Hide identity button if there is only one identity

- docs/specs/audit-log.md
- docs/specs/event.md
- docs/specs/webhook.md
> Add audit log spec draft

- pkg/lib/deps/middleware_request.go
- pkg/util/httputil/headers.go
- pkg/util/httputil/host.go
- pkg/util/httputil/host_test.go
- pkg/util/httputil/ip.go
- pkg/util/httputil/ip_test.go
- pkg/util/httputil/proto.go
- pkg/util/httputil/proto_test.go
- pkg/util/sentry/request.go
> Support X-Original-* headers 

- portal/src/graphql/portal/AuthenticatorConfigurationScreen.tsx
- portal/src/locale-data/en.json
- portal/src/types.ts
> Support disable device token through the portal

- resources/authgear/templates/en/translation.json
- resources/authgear/templates/en/web/enter_password.html
- resources/authgear/templates/zh-HK/translation.json
- resources/authgear/templates/zh-TW/translation.json
> Update enter password page title to distinguish primary or secondary password

- resources/authgear/templates/en/translation.json
- resources/authgear/templates/en/web/settings_recovery_code.html
- resources/authgear/templates/en/web/setup_recovery_code.html
- resources/authgear/templates/zh-HK/translation.json
- resources/authgear/templates/zh-TW/translation.json
> Update recovery code storage description

- portal/src/graphql/portal/UISettingsScreen.tsx
- portal/src/locale-data/en.json
- resources/authgear/templates/en/translation.json
- resources/authgear/templates/en/web/__alternatives.html
- resources/authgear/templates/en/web/enter_oob_otp.html
- resources/authgear/templates/zh-HK/translation.json
- resources/authgear/templates/zh-TW/translation.json
> Show customer support link in enter recovery code label

- cmd/authgear/cmd_audit.go
- cmd/authgear/cmd_database.go
- cmd/authgear/cmd_init.go
- cmd/authgear/cmd_internal.go
- cmd/authgear/cobraviper.go
- cmd/portal/cobraviper.go
- cmd/portal/internal.go
- cmd/portal/migrate.go
- cmd/portal/migrate_reources_migrate_jwks.go
- cmd/portal/migrate_resources.go
- cmd/portal/migrate_resources_example.go
- pkg/util/cobraviper/cobraviper.go
- Fix failed to get value if binding same argument to multiple commands
> Refactor cobraviper

- pkg/lib/feature/forgotpassword/ratelimit.go
> Adjust reset password send code rate limit

- hack/ingress.tpl.yaml
- pkg/portal/service/config.go
- pkg/portal/service/kubernetes.go
> When deleting custom domain, handle when requested resources are not found in the k8s cluster

- portal/src/FormContainer.tsx
- portal/src/graphql/portal/ApplicationsConfigurationScreen.tsx
- portal/src/graphql/portal/SingleSignOnConfigurationScreen.tsx
- portal/src/locale-data/en.json
- resources/authgear/templates/en/translation.json
- resources/authgear/templates/zh-HK/translation.json
- resources/authgear/templates/zh-TW/translation.json
fix #1271, fix #1309, fix #1308, fix #1282
> Update copywriting and links

- portal/src/graphql/portal/CustomDomainListScreen.tsx
- portal/src/types.ts
> Adjust cookie_domain when public_origin changes

- pkg/auth/routes.go
> Remove session middleware from static routes

- pkg/lib/infra/db/hook_handle.go
- pkg/lib/infra/middleware/panic_log.go
- pkg/lib/session/middleware.go
fix #1301, fix #1302 
- Ignore context cancel error
- Remove error log in session middleware
- Ignore db failed to rollback error
> Ignore non-critical errors from logs

- pkg/auth/handler/webapp/logout.go
- pkg/auth/wire_gen.go
> Use controller in logout handler

- pkg/lib/config/configsource/resources.go
- pkg/lib/config/feature.go
- pkg/lib/config/feature_oauth.go
- pkg/lib/config/test/config.go
- pkg/lib/config/testdata/parse_feature_tests.yaml
- pkg/portal/appresource/factory/factory.go
- pkg/portal/appresource/manager.go
- pkg/portal/appresource/manager_test.go
- portal/src/graphql/portal/ApplicationsConfigurationScreen.module.scss
- portal/src/graphql/portal/ApplicationsConfigurationScreen.tsx
- portal/src/locale-data/en.json
- portal/src/types.ts
require #1348
Should merge to `app-plan` branch instead, will have an updated `app-plan` branch after #1348 is merged.
> Limit the maximum number of oauth clients by feature config

- pkg/lib/config/configsource/resources.go
- pkg/lib/config/feature.go
- pkg/lib/config/feature_identity.go
- pkg/lib/config/feature_oauth.go
- pkg/lib/config/test/config.go
- pkg/lib/config/testdata/parse_feature_tests.yaml
- pkg/portal/appresource/factory/factory.go
- pkg/portal/appresource/manager.go
- pkg/portal/appresource/manager_test.go
- portal/src/graphql/portal/ApplicationsConfigurationScreen.module.scss
- portal/src/graphql/portal/ApplicationsConfigurationScreen.tsx
- portal/src/graphql/portal/SingleSignOnConfigurationScreen.module.scss
- portal/src/graphql/portal/SingleSignOnConfigurationScreen.tsx
- portal/src/graphql/portal/SingleSignOnConfigurationWidget.tsx
- portal/src/locale-data/en.json
- portal/src/types.ts
> Limit the number of sso providers by feature config

- pkg/lib/config/configsource/resources.go
- pkg/lib/config/feature.go
- pkg/lib/config/feature_hook.go
- pkg/lib/config/test/config.go
- pkg/lib/config/testdata/parse_feature_tests.yaml
- pkg/portal/appresource/manager_test.go
- portal/src/FieldList.module.scss
- portal/src/FieldList.tsx
- portal/src/graphql/portal/WebhookConfigurationScreen.tsx
- portal/src/locale-data/en.json
- portal/src/types.ts
> Limit the number of hook handlers by feature config

- docs/specs/oidc.md
- docs/specs/sdk.md
> Specify how to do reauthentication via OIDC authentication request

- portal/package-lock.json
- portal/package.json
- portal/src/ReactApp.tsx
- portal/src/graphql/portal/ApplicationsConfigurationScreen.tsx
- portal/src/graphql/portal/AuthenticatorConfigurationScreen.tsx
- portal/src/graphql/portal/CustomDomainListScreen.tsx
- portal/src/graphql/portal/LoginIDConfigurationScreen.tsx
- portal/src/graphql/portal/OnboardingConfigAppScreen.tsx
- portal/src/graphql/portal/SingleSignOnConfigurationScreen.tsx
- portal/src/graphql/portal/SingleSignOnConfigurationWidget.tsx
- portal/src/graphql/portal/UISettingsScreen.tsx
- portal/src/graphql/portal/VerificationConfigurationScreen.tsx
- portal/src/locale-data/en.json
Otherwise the link style is missing
> Update portal using fluent ui Link component for translations string

- pkg/lib/interaction/errors.go
- pkg/lib/interaction/intents/authenticate.go
- resources/authgear/templates/en/translation.json
- resources/authgear/templates/en/web/__error.html
- resources/authgear/templates/zh-HK/translation.json
- resources/authgear/templates/zh-TW/translation.json
> Report UserNotFound error

- pkg/admin/facade/audit_log.go
- pkg/admin/wire_gen.go
- pkg/lib/config/feature.go
- pkg/lib/config/feature_audit_log.go
- pkg/lib/config/testdata/parse_feature_tests.yaml
- pkg/lib/deps/deps_config.go
- portal/src/graphql/adminapi/AuditLogScreen.tsx
- portal/src/locale-data/en.json
- portal/src/types.ts
>  Limit audit logs retrieve days by feature config

- go.mod
- go.sum
- pkg/admin/wire_gen.go
- pkg/auth/wire_gen.go
- pkg/lib/feature/forgotpassword/provider.go
- pkg/lib/feature/forgotpassword/store.go
- pkg/lib/infra/redis/handle.go
- pkg/lib/infra/redis/pool.go
- pkg/lib/interaction/context.go
- pkg/lib/interaction/nodes/do_ensure_session.go
- pkg/lib/oauth/handler/handler_token.go
- pkg/lib/oauth/redis/keys.go
- pkg/lib/oauth/redis/store.go
- pkg/lib/oauth/resolver.go
- pkg/lib/oauth/session_manager.go
- pkg/lib/oauth/store_grant.go
- pkg/lib/session/idpsession/manager.go
- pkg/lib/session/idpsession/provider.go
- pkg/lib/session/idpsession/resolver.go
- pkg/lib/session/idpsession/resolver_test.go
- pkg/lib/session/manager.go
- pkg/resolver/wire_gen.go
> Avoid redis data race

- pkg/auth/handler/webapp/viewmodels/base.go
- pkg/auth/wire_gen.go
- pkg/lib/config/ui.go
- portal/src/graphql/portal/LoginIDConfigurationScreen.tsx
- portal/src/locale-data/en.json
- portal/src/types.ts
- resources/authgear/templates/en/web/enter_login_id.html
- resources/authgear/templates/en/web/forgot_password.html
- resources/authgear/templates/en/web/login.html
- resources/authgear/templates/en/web/promote.html
- resources/authgear/templates/en/web/setup_oob_otp.html
- resources/authgear/templates/en/web/signup.html
> Address phone input bugs

- pkg/lib/authn/identity/service/service.go
> Fix webhook identity payload created_at and updated_at are not up to date

- pkg/lib/web/image.go
- pkg/lib/web/image_test.go
> Update image descriptor to use fallback language in the app fs first

- pkg/admin/wire_gen.go
- pkg/auth/deps.go
- pkg/auth/handler/webapp/cookie.go
- pkg/auth/handler/webapp/select_account.go
- pkg/auth/webapp/client_id.go
- pkg/auth/webapp/cookie.go
- pkg/auth/webapp/login_hint.go
- pkg/auth/webapp/service2.go
- pkg/auth/webapp/session_middleware.go
- pkg/auth/webapp/ui_locales.go
- pkg/auth/webapp/wechat_redirect_uri_middleware.go
- pkg/auth/wire_gen.go
- pkg/lib/authn/mfa/cookie.go
- pkg/lib/deps/deps_utils.go
- pkg/lib/interaction/context.go
- pkg/lib/interaction/nodes/do_ensure_session.go
- pkg/lib/interaction/nodes/do_use_authenticator.go
- pkg/lib/interaction/nodes/use_device_token.go
- pkg/lib/nonce/nonce.go
- pkg/lib/oauth/oidc/handler/handler_end_session.go
- pkg/lib/oauth/resolver.go
- pkg/lib/session/cookie.go
- pkg/lib/session/idpsession/manager.go
- pkg/lib/session/idpsession/resolver.go
- pkg/lib/session/idpsession/resolver_test.go
- pkg/lib/session/middleware.go
- pkg/resolver/wire_gen.go
- pkg/util/httputil/cookie.go
- pkg/util/httputil/flash_message.go
> Manipulate cookies via CookieManager

- portal/src/ThemePreviewWidget.module.scss
- resources/authgear/static/authgear-dark-theme.css
- resources/authgear/static/authgear-light-theme.css
> Change primary button text color to a shade of white

- pkg/util/graphqlutil/api_error.go
> Ignore an non-error related to GraphiQL

- cmd/authgear/cmd_init.go
- cmd/portal/migrate_resources_migrate_jwk_created_at.go
- pkg/lib/config/generate.go
- pkg/lib/config/test/config.go
- pkg/portal/service/app.go
- pkg/portal/wire_gen.go
- pkg/util/jwkutil/jwkutil.go
- pkg/util/secrets/generate.go
- pkg/util/secrets/generate_test.go
> [Migration needed] Add created_at to JWK

- docs/specs/api-resolver.md
- nginx.conf
- pkg/api/model/session_info.go
- pkg/api/model/session_info_test.go
- pkg/lib/session/info.go
- pkg/portal/graphql/app.go
- pkg/portal/graphql/app_mutation.go
- pkg/portal/graphql/context.go
- pkg/portal/model/app.go
- pkg/portal/service/app.go
- pkg/portal/wire_gen.go
- pkg/util/jwkutil/pem.go
- pkg/util/jwkutil/pem_test.go
- portal/src/graphql/portal/mutations/__generated__/UpdateAppAndSecretConfigMutation.ts
- portal/src/graphql/portal/query/__generated__/AppAndSecretConfigQuery.ts
- portal/src/graphql/portal/schema.graphql
> [Helm chart upgrade needed] Expose webhook secret and Admin API secret

- portal/package-lock.json
- portal/package.json
- portal/src/AppRoot.tsx
- portal/src/OAuthRedirect.tsx
- portal/src/ScreenNav.tsx
- portal/src/WidgetTitle.tsx
- portal/src/graphql/portal/AdminAPIConfigurationScreen.module.scss
- portal/src/graphql/portal/AdminAPIConfigurationScreen.tsx
- portal/src/graphql/portal/Authenticated.tsx
- portal/src/graphql/portal/WebhookConfigurationScreen.module.scss
- portal/src/graphql/portal/WebhookConfigurationScreen.tsx
- portal/src/graphql/portal/query/__generated__/AppAndSecretConfigQuery.ts
- portal/src/graphql/portal/query/appAndSecretConfigQuery.ts
- portal/src/hook/useLocationEffect.ts
- portal/src/locale-data/en.json
- portal/src/types.ts
- portal/src/util/download.ts
> Show webhook secret and Admin API secret

- portal/src/graphql/portal/ApplicationsConfigurationScreen.module.scss
- portal/src/graphql/portal/ApplicationsConfigurationScreen.tsx
- portal/src/locale-data/en.json
> Improved UI on client_id copy

- portal/src/graphql/adminapi/apollo.ts
- portal/src/graphql/portal/AdminAPIConfigurationScreen.tsx
- portal/src/locale-data/en.json
> Add link to admin API GraphiQL

- pkg/admin/routes.go
- pkg/admin/wire.go
- pkg/admin/wire_gen.go
- pkg/auth/routes.go
- pkg/auth/wire_gen.go
- pkg/auth/wire_handler.go
- pkg/lib/deps/deps_common.go
- pkg/lib/healthz/deps.go
- pkg/lib/healthz/healthz.go
- pkg/resolver/routes.go
- pkg/resolver/wire.go
- pkg/resolver/wire_gen.go
> Incorporate data store connection checking in health check

- portal/src/graphql/portal/ApplicationsConfigurationScreen.tsx
> Fix copy button bugs on multiple apps

- portal/src/ScreenNav.tsx
> Change position of audit log on ScreenNav

- portal/src/ThemeConfigurationWidget.tsx
> Add component-level memorization on custom color

- portal/src/graphql/portal/SubscriptionScreen.tsx
> Remove commandbar on Billing Screen

- portal/src/CommandBarContainer.module.scss
> Removing min-height of CommandBarContainer

- pkg/portal/service/admin_api.go
- portal/src/graphql/portal/AdminAPIConfigurationScreen.module.scss
- portal/src/graphql/portal/AdminAPIConfigurationScreen.tsx
- portal/src/locale-data/en.json
> Improve GraphiQL documentation in Portal

- pkg/portal/graphql/app_mutation.go
- pkg/portal/graphql/collaborator_mutation.go
- pkg/portal/graphql/context.go
- pkg/portal/graphql/domain_mutation.go
- pkg/portal/graphql/nodes.go
- pkg/portal/graphql/query.go
- pkg/portal/routes.go
- pkg/portal/service/collaborator.go
- portal/src/AppRoute.tsx
- portal/src/ReactApp.tsx
- portal/src/graphql/portal/AcceptAdminInvitationScreen.module.scss
- portal/src/graphql/portal/AcceptAdminInvitationScreen.tsx
- portal/src/graphql/portal/query/__generated__/AuthenticatedForInvitationQuery.ts
- portal/src/graphql/portal/query/authenticatedForInvitationQuery.ts
- portal/src/graphql/portal/schema.graphql
- portal/src/locale-data/en.json
Ref #915 
This pull request is still in progress, feel free to review but do not merge it yet.
> Improve invitation UI UX

- resources/authgear/templates/en/messages/authenticate_primary_oob_email.html
- resources/authgear/templates/en/messages/authenticate_primary_oob_email.mjml
- resources/authgear/templates/en/messages/authenticate_secondary_oob_email.html
- resources/authgear/templates/en/messages/authenticate_secondary_oob_email.mjml
- resources/authgear/templates/en/messages/forgot_password_email.html
- resources/authgear/templates/en/messages/forgot_password_email.mjml
- resources/authgear/templates/en/messages/setup_primary_oob_email.html
- resources/authgear/templates/en/messages/setup_primary_oob_email.mjml
- resources/authgear/templates/en/messages/setup_secondary_oob_email.html
- resources/authgear/templates/en/messages/setup_secondary_oob_email.mjml
- resources/authgear/templates/en/messages/verification_email.html
- resources/authgear/templates/en/messages/verification_email.mjml
- resources/authgear/templates/en/messages/welcome_message_email.html
- resources/authgear/templates/en/messages/welcome_message_email.mjml
- resources/authgear/templates/en/translation.json
- resources/authgear/templates/zh-HK/translation.json
- resources/authgear/templates/zh-TW/translation.json
- resources/portal/templates/en/messages/collaborator_invitation_email.html
- scripts/npm/package-lock.json
- scripts/npm/package.json
> Remove image from HTML emails

- pkg/admin/routes.go
- pkg/admin/wire.go
- pkg/admin/wire_gen.go
- pkg/auth/routes.go
- pkg/auth/wire_gen.go
- pkg/auth/wire_handler.go
- pkg/lib/deps/deps_common.go
- pkg/lib/deps/providers.go
- pkg/lib/healthz/deps.go
- pkg/lib/healthz/healthz.go
- pkg/resolver/routes.go
- pkg/resolver/wire.go
- pkg/resolver/wire_gen.go
> Include global database connection checking in health check

- pkg/auth/handler/webapp/select_account.go
- pkg/auth/webapp/session.go
- pkg/auth/wire_gen.go
- pkg/lib/interaction/intents/reauthenticate.go
- pkg/lib/interaction/nodes/do_ensure_session.go
- pkg/lib/oauth/handler/handler_authz.go
> Do not assume IDP session in reauthentication

- pkg/auth/endpoints.go
- pkg/auth/handler/webapp/deps.go
- pkg/auth/handler/webapp/oauth_entrypoint.go
- pkg/auth/handler/webapp/root.go
- pkg/auth/handler/webapp/select_account.go
- pkg/auth/routes.go
- pkg/auth/webapp/session.go
- pkg/auth/webapp/url_provider.go
- pkg/auth/wire_gen.go
- pkg/auth/wire_handler.go
- pkg/lib/interaction/intents/reauthenticate.go
- pkg/lib/interaction/nodes/do_ensure_session.go
- pkg/lib/oauth/handler/handler_authz.go
> Change OAuth entrypoint from / to /_oauth_entrypoint

- pkg/admin/facade/user.go
- pkg/auth/handler/webapp/login.go
- pkg/auth/handler/webapp/select_account.go
- pkg/auth/handler/webapp/signup.go
- pkg/auth/webapp/login_hint.go
- pkg/auth/webapp/session.go
- pkg/lib/interaction/intents/authenticate.go
- pkg/lib/interaction/intents/reauthenticate.go
- pkg/lib/oauth/handler/handler_authz.go
- pkg/lib/oauth/handler/handler_token.go
- pkg/lib/oauth/protocol/authz.go
> Support x_suppress_idp_session_cookie

- portal/src/graphql/portal/AdminAPIConfigurationScreen.module.scss
- portal/src/graphql/portal/AdminAPIConfigurationScreen.tsx
- portal/src/graphql/portal/ApplicationsConfigurationScreen.tsx
- portal/src/graphql/portal/CreateOAuthClientScreen.tsx
- portal/src/graphql/portal/VerifyDomainScreen.tsx
- portal/src/graphql/portal/WebhookConfigurationScreen.tsx
- portal/src/hook/useCopyFeedback.tsx
- portal/src/locale-data/en.json
> Clarify GraphiQL tool is for inspection purpose

- pkg/auth/handler/webapp/viewmodels/authentication.go
- resources/authgear/templates/en/web/__error.html
- resources/authgear/templates/en/web/forgot_password.html
- resources/authgear/templates/en/web/login.html
> Report more accurate login ID required error message

- portal/src/locale-data/en.json
> Fix typo in token settings description

- resources/authgear/static/authgear-dark-theme.css
- resources/authgear/static/authgear-light-theme.css
> Make button:focus look the same as normal and reassign primary button color

- portal/src/graphql/portal/SubscriptionScreen.module.scss
> Add padding to ensure item is not adjacent to edge

- pkg/admin/wire_gen.go
- pkg/auth/handler/webapp/controller.go
- pkg/auth/handler/webapp/publisher.go
- pkg/auth/handler/webapp/websocket.go
- pkg/auth/webapp/session_store.go
- pkg/auth/wire_gen.go
- pkg/lib/authn/authenticationinfo/store_redis.go
- pkg/lib/authn/authenticator/oob/store_redis.go
- pkg/lib/authn/challenge/provider.go
- pkg/lib/authn/mfa/store_device_token_redis.go
- pkg/lib/config/secret_data.go
- pkg/lib/deps/providers.go
- pkg/lib/feature/forgotpassword/store.go
- pkg/lib/feature/verification/store_redis.go
- pkg/lib/infra/redis/appredis/handle.go
- pkg/lib/infra/redis/connection_options.go
- pkg/lib/infra/redis/handle.go
- pkg/lib/infra/redis/hub.go
- pkg/lib/infra/redis/pool.go
- pkg/lib/interaction/store_redis.go
- pkg/lib/oauth/redis/store.go
- pkg/lib/ratelimit/storage_redis.go
- pkg/lib/session/access/event_store_redis.go
- pkg/lib/session/idpsession/provider.go
- pkg/lib/session/idpsession/store_redis.go
- pkg/resolver/wire_gen.go
refs #1472 
Preparing for connecting analytic redis
> Refactor redis to app redis

- authui/src/authgear.ts
> Disable double tap zoom with javascript

- pkg/lib/authn/identity/oauth/provider.go
- pkg/lib/authn/identity/oauth/store.go
- pkg/lib/authn/identity/service/service.go
- pkg/lib/authn/identity/service/service_mock_test.go
- pkg/lib/facade/coordinator.go
- pkg/lib/interaction/nodes/select_identity_end.go
> Update OAuth identity on authentication

- resources/authgear/static/authgear.css
- resources/authgear/templates/en/web/__watermark.html
> Add link to the watermark

- migrations/authgear/20210921175056-add-standard-attributes.sql
- pkg/admin/wire_gen.go
- pkg/auth/wire_gen.go
- pkg/lib/authn/user/commands.go
- pkg/lib/authn/user/commands_raw.go
- pkg/lib/authn/user/deps.go
- pkg/lib/authn/user/model.go
- pkg/lib/authn/user/queries.go
- pkg/lib/authn/user/queries_raw.go
- pkg/lib/authn/user/store.go
- pkg/lib/deps/deps_common.go
- pkg/lib/facade/coordinator.go
- pkg/resolver/wire_gen.go
> Populate identity aware standard attributes

- migrations/authgear/20210921175056-add-standard-attributes.sql
- pkg/admin/wire_gen.go
- pkg/auth/wire_gen.go
- pkg/lib/authn/stdattrs/model.go
- pkg/lib/authn/stdattrs/model_test.go
- pkg/lib/authn/user/commands.go
- pkg/lib/authn/user/commands_raw.go
- pkg/lib/authn/user/deps.go
- pkg/lib/authn/user/model.go
- pkg/lib/authn/user/queries.go
- pkg/lib/authn/user/queries_raw.go
- pkg/lib/authn/user/store.go
- pkg/lib/config/config.go
- pkg/lib/config/testdata/default_config.yaml
- pkg/lib/config/user_profile.go
- pkg/lib/deps/deps_common.go
- pkg/lib/deps/deps_config.go
- pkg/lib/facade/coordinator.go
- pkg/lib/interaction/context.go
- pkg/lib/interaction/nodes/do_create_identity.go
- pkg/resolver/wire_gen.go
> Populate standard attributes

- portal/src/graphql/portal/SubscriptionScreen.module.scss
- portal/src/graphql/portal/SubscriptionScreen.tsx
- portal/src/locale-data/en.json
- portal/src/styles/variable.scss
> Update portal billing page style

- pkg/admin/facade/verification.go
- pkg/admin/graphql/context.go
- pkg/admin/graphql/scalars.go
- pkg/admin/graphql/user.go
- pkg/api/model/user.go
- pkg/auth/handler/oauth/userinfo.go
- pkg/lib/authn/user/commands.go
- pkg/lib/authn/user/model.go
- pkg/lib/authn/user/queries.go
- pkg/lib/feature/verification/service.go
- pkg/lib/oauth/oidc/id_token.go
- pkg/lib/oauth/oidc/metadata.go
- pkg/lib/oauth/token_encoding.go
- portal/src/graphql/adminapi/schema.graphql
> Expose standard attributes

- docs/specs/api-resolver.md
- docs/specs/event.md
- docs/specs/user-profile/design.md
- docs/specs/user-profile/literature-review.md
- docs/specs/webhook.md
> Design of user profile

- pkg/auth/handler/webapp/change_password.go
- pkg/auth/handler/webapp/change_secondary_password.go
- pkg/lib/authn/authenticator/password/checker.go
- pkg/lib/authn/authenticator/password/checker_test.go
- pkg/lib/authn/authenticator/password/provider.go
> Ignore password history in force password change checking

- pkg/util/deviceinfo/deviceinfo.go
- pkg/util/deviceinfo/deviceinfo_test.go
> Handle new Apple devices gracefully

- cmd/authgear/elasticsearch/deps.go
- cmd/authgear/elasticsearch/wire_gen.go
- pkg/admin/facade/user.go
- pkg/admin/facade/verification.go
- pkg/admin/graphql/context.go
- pkg/admin/graphql/user.go
- pkg/admin/graphql/user_mutation.go
- pkg/admin/wire_gen.go
- pkg/auth/wire_gen.go
- pkg/lib/authn/stdattrs/normalizer.go
- pkg/lib/authn/stdattrs/validate.go
- pkg/lib/authn/stdattrs/validate_test.go
- pkg/lib/authn/user/commands.go
- pkg/lib/authn/user/commands_raw.go
- pkg/lib/authn/user/queries.go
- pkg/lib/authn/user/store.go
- pkg/lib/deps/deps_common.go
- pkg/lib/facade/coordinator.go
- pkg/lib/facade/user.go
- pkg/lib/feature/verification/service.go
- pkg/lib/oauth/oidc/metadata.go
- pkg/resolver/wire_gen.go
- pkg/util/validation/formats.go
- pkg/util/validation/formats_test.go
- portal/src/graphql/adminapi/schema.graphql
> Add `updateUser` mutation

- .gitignore
- Makefile
- cmd/portal/Dockerfile
- cmd/portal/server/config.go
- cmd/portal/server/server.go
- docker-compose.yaml
- nginx.conf
- pkg/portal/config.go
- pkg/portal/routes.go
> Serve portal static asset with portal server in dev env

- portal/src/graphql/adminapi/AddUserScreen.tsx
> Fix password field disabled in add user screen

- pkg/lib/deps/middleware_request.go
- pkg/util/log/ignore.go
- pkg/util/log/ignore_test.go
- pkg/util/sentry/hook.go
> Do not log context.Canceled error

- portal/package-lock.json
- portal/package.json
- portal/src/graphql.d.ts
- portal/src/graphql/adminapi/UserDetailsScreen.tsx
- portal/src/graphql/adminapi/UserDetailsStandardAttributes.module.scss
- portal/src/graphql/adminapi/UserDetailsStandardAttributes.tsx
- portal/src/graphql/adminapi/query/__generated__/UserQuery.ts
- portal/src/graphql/adminapi/query/userQuery.ts
- portal/src/locale-data/en.json
- portal/src/types.ts
- portal/src/util/alpha2.ts
- portal/src/util/birthdate.test.ts
- portal/src/util/birthdate.ts
- portal/src/util/timezone.ts
> Display standard attributes on the portal

- pkg/lib/authn/sso/apple.go
- pkg/lib/authn/sso/google.go
- pkg/lib/authn/sso/wechat.go
- pkg/lib/authn/stdattrs/model.go
- pkg/lib/authn/stdattrs/model_test.go
> Try to make OAuth profile has default enabled standard attributes

- portal/src/graphql/adminapi/UserDetailsScreen.tsx
- portal/src/graphql/adminapi/UserDetailsStandardAttributes.module.scss
- portal/src/graphql/adminapi/UserDetailsStandardAttributes.tsx
> Fixes and improvements for standard attributes on portal

- portal/src/graphql/adminapi/AddPhoneScreen.tsx
- portal/src/graphql/portal/ApplicationsConfigurationScreen.tsx
- portal/src/graphql/portal/AuthenticatorConfigurationScreen.tsx
- portal/src/graphql/portal/ForgotPasswordConfigurationScreen.tsx
- portal/src/graphql/portal/ModifyOAuthClientForm.tsx
- portal/src/graphql/portal/PasswordPolicyConfigurationScreen.tsx
- portal/src/graphql/portal/SMTPConfigurationScreen.tsx
- portal/src/graphql/portal/VerificationConfigurationScreen.tsx
- portal/src/graphql/portal/WebhookConfigurationScreen.tsx
- portal/src/hook/useInput.ts
- portal/src/util/input.ts
> Unify the handling of integer text fields

- portal/src/graphql/adminapi/UsersScreen.tsx
- portal/src/graphql/portal/ManageLanguageWidget.tsx
- portal/src/graphql/portal/PhoneInputListWidget.tsx
> Fix SearchBox usage

- pkg/lib/infra/db/hook_handle.go
- pkg/util/log/panic.go
> Fix database handle being unusable after panic

- portal/package-lock.json
- portal/package.json
> Update react-messageformat to 2.0.2 to include a bugfix

- authui/src/authgear.ts
- authui/src/form.ts
- pkg/auth/handler/webapp/controller.go
- pkg/auth/webapp/service2.go
- pkg/auth/wire_gen.go
- resources/authgear/static/authgear.css
- resources/authgear/templates/en/web/__error.html
- resources/authgear/templates/en/web/__message_bar.html
- resources/authgear/templates/en/web/fatal_error.html
> Show webhook disallowed error in the same page

- resources/authgear/templates/en/web/settings_profile_edit.html
> Fix profile edit page text color

- resources/authgear/templates/en/web/__use_recovery_code.html
- resources/authgear/templates/en/web/enter_totp.html
- resources/authgear/templates/en/web/settings_profile.html
> Fix text color in various places

- resources/authgear/static/authgear-dark-theme.css
> Work around date input picker icon visibility in dark mode on Chrome

- pkg/auth/handler/webapp/viewmodels/settings_profile.go
- pkg/util/tzutil/list.go
- pkg/util/tzutil/timezone.go
- resources/authgear/templates/en/web/settings_profile.html
- resources/authgear/templates/en/web/settings_profile_edit.html
> Show consistent timezone label

- resources/authgear/templates/en/web/settings_profile.html
> Show locale display label consistently

- authui/tailwind.config.js
- resources/authgear/templates/en/web/__page_frame.html
- resources/authgear/templates/en/web/__wide_page_frame.html
> Set max-width on Auth UI

- resources/authgear/templates/en/translation.json
- resources/authgear/templates/en/web/__error.html
- resources/authgear/templates/zh-HK/translation.json
- resources/authgear/templates/zh-TW/translation.json
> Fix error message for phone number required error

- portal/src/ErrorRenderer.tsx
- portal/src/FieldList.tsx
- portal/src/FormErrorMessageBar.tsx
- portal/src/FormTextFieldList.tsx
- portal/src/error/ErrorDialog.tsx
- portal/src/error/error.ts
- portal/src/error/parse.ts
- portal/src/error/webhook.ts
- portal/src/formbinding.tsx
- portal/src/graphql/portal/CustomDomainListScreen.tsx
- portal/src/graphql/portal/WebhookConfigurationScreen.tsx
- portal/src/locale-data/en.json
> Show webhook error on portal

- pkg/admin/graphql/user_mutation.go
> Fix incorrect role being used in Admin API

- portal/src/LabelWithTooltip.tsx
- portal/src/Tooltip.tsx
- portal/src/useTextFieldTooltip.tsx
> Expand TooltipHost area

- portal/src/graphql/adminapi/AddIdentityForm.tsx
- portal/src/graphql/adminapi/AddUserScreen.tsx
- portal/src/graphql/adminapi/ResetPasswordScreen.tsx
- portal/src/graphql/adminapi/UserDetailsScreen.tsx
- portal/src/graphql/portal/CreateAppScreen.tsx
- portal/src/graphql/portal/InviteAdminScreen.tsx
- portal/src/hook/useSimpleForm.ts
> Allow useSimpleForm to update initialState

- docs/specs/event.md
> Amend webhook spec

- portal/src/graphql/portal/LocalizationConfigurationScreen.tsx
- portal/src/graphql/portal/LoginIDConfigurationScreen.tsx
- portal/src/graphql/portal/UISettingsScreen.tsx
- portal/src/graphql/portal/mutations/updateAppTemplatesMutation.ts
- portal/src/graphql/portal/query/appTemplatesQuery.ts
- portal/src/resources.ts
- portal/src/util/resource.test.ts
- portal/src/util/resource.ts
> Make ResourceSpecifier extension-aware

- portal/src/CommandBarContainer.tsx
- portal/src/FormContainer.tsx
- portal/src/graphql/adminapi/AuditLogScreen.tsx
- portal/src/graphql/adminapi/UserDetailsScreen.tsx
- portal/src/graphql/adminapi/UsersScreen.tsx
- portal/src/graphql/portal/ApplicationsConfigurationScreen.tsx
- portal/src/graphql/portal/PortalAdminsSettings.tsx
- portal/src/locale-data/en.json
> Reorganize button positions in command bar

- resources/authgear/static/authgear.css
- resources/authgear/templates/en/translation.json
- resources/authgear/templates/en/web/setup_totp.html
- resources/authgear/templates/en/web/wechat_auth.html
- resources/authgear/templates/zh-HK/translation.json
- resources/authgear/templates/zh-TW/translation.json
> Fix setup TOTP page layout

- portal/src/error/parse.ts
- portal/src/error/webhook.ts
- portal/src/locale-data/en.json
> Show the raw info of WebHookDisallowed error

- go.mod
- go.sum
- pkg/lib/config/http.go
- pkg/util/validation/formats.go
- pkg/util/validation/formats_test.go
- portal/src/locale-data/en.json
> Validate HTTP origin spec

- .make-lint-expect
- Makefile
- pkg/lib/config/configsource/resources.go
- pkg/lib/web/css.go
- pkg/lib/web/image.go
- pkg/lib/web/javascript.go
- pkg/portal/appresource/manager.go
- pkg/portal/model/system_config.go
- pkg/portal/service/system_config.go
- pkg/util/resource/descriptor.go
- pkg/util/template/resource.go
- pkg/util/template/translation.go
- pkg/util/template/translation_test.go
- portal/src/graphql/portal/LocalizationConfigurationScreen.tsx
- portal/src/graphql/portal/query/appTemplatesQuery.ts
- portal/src/locale-data/en.json
- portal/src/resources.ts
- portal/src/system-config.ts
- portal/src/util/resource.test.ts
- portal/src/util/resource.ts
> Avoid saving identical translation key

- portal/src/graphql/adminapi/AddIdentityForm.tsx
- portal/src/graphql/adminapi/AddUserScreen.tsx
- portal/src/graphql/adminapi/ResetPasswordScreen.tsx
- portal/src/graphql/adminapi/UserDetailsScreen.tsx
- portal/src/graphql/adminapi/mutations/updateUserMutation.ts
- portal/src/graphql/portal/CreateAppScreen.tsx
- portal/src/graphql/portal/InviteAdminScreen.tsx
- portal/src/hook/useSimpleForm.ts
> Fix incorrect state in user profile form 

- portal/src/graphql/adminapi/AddIdentityForm.module.scss
- portal/src/graphql/adminapi/AddIdentityForm.tsx
> Fix broken layout in AddIdentityForm

- pkg/auth/handler/webapp/viewmodels/settings_profile.go
- pkg/lib/config/testdata/custom_attributes_tests.yaml
- pkg/lib/config/user_profile.go
- pkg/util/labelutil/label.go
- pkg/util/labelutil/label_test.go
- resources/authgear/templates/en/web/settings_profile.html
> Show custom attributes in /settings/profile

- pkg/auth/handler/webapp/settings_profile.go
- pkg/auth/handler/webapp/viewmodels/settings_profile.go
- pkg/lib/config/testdata/config_tests.yaml
- pkg/lib/config/testdata/default_config.yaml
- pkg/lib/config/user_profile.go
- portal/src/graphql/portal/UserProfileConfigurationScreen.tsx
- resources/authgear/templates/en/web/settings.html
- resources/authgear/templates/en/web/settings_profile.html
- resources/authgear/templates/en/web/settings_profile_edit.html
> Respect identity aware standard attributes access control

- migrations/authgear/20211220162815-remove_identity_anonymous_key_not_null.sql
- pkg/auth/deps.go
- pkg/auth/handler/api/anonymous_user_signup.go
- pkg/auth/handler/api/deps.go
- pkg/auth/routes.go
- pkg/auth/webapp/login_hint.go
- pkg/auth/wire_gen.go
- pkg/auth/wire_handler.go
- pkg/lib/authn/identity/anonymous/store.go
- pkg/lib/deps/deps_common.go
- pkg/lib/interaction/nodes/use_identity_anonymous.go
- pkg/lib/oauth/handler/deps.go
- pkg/lib/oauth/handler/handler_anonymous_user.go
- pkg/lib/oauth/handler/handler_token.go
- pkg/lib/oauth/handler/service.go
- pkg/lib/oauth/handler/web_session_type.go
> Signup anonymous user without key api

- pkg/auth/handler/api/anonymous_user_signup.go
- pkg/auth/handler/api/deps.go
- pkg/auth/wire_gen.go
- pkg/lib/oauth/handler/handler_anonymous_user.go
refs #1685 
- Correct the result object schema
- Block normal user when calling signup anonymous user with refresh token
> Fix anonymous user web signup api

- pkg/api/apierrors/error.go
- pkg/auth/deps.go
- pkg/auth/handler/api/anonymous_user_promotion_code.go
- pkg/auth/handler/api/anonymous_user_signup.go
- pkg/auth/handler/api/deps.go
- pkg/auth/routes.go
- pkg/auth/wire_gen.go
- pkg/auth/wire_handler.go
- pkg/lib/authn/identity/anonymous/deps.go
- pkg/lib/authn/identity/anonymous/promotion_code.go
- pkg/lib/authn/identity/anonymous/store_redis.go
- pkg/lib/deps/deps_common.go
- pkg/lib/oauth/handler/handler_anonymous_user.go
- pkg/lib/oauth/handler/web_session_type.go
> Request anonymous promotion code api for web 

- pkg/auth/handler/api/anonymous_user_signup.go
- pkg/lib/oauth/handler/handler_anonymous_user.go
> Make client id optional when session type is cookie for signup anonymous user

- pkg/api/apierrors/error.go
- pkg/auth/deps.go
- pkg/auth/handler/api/anonymous_user_promotion_code.go
- pkg/auth/handler/api/anonymous_user_signup.go
- pkg/auth/handler/api/deps.go
- pkg/auth/routes.go
- pkg/auth/webapp/login_hint.go
- pkg/auth/wire_gen.go
- pkg/auth/wire_handler.go
- pkg/lib/authn/identity/anonymous/deps.go
- pkg/lib/authn/identity/anonymous/promotion_code.go
- pkg/lib/authn/identity/anonymous/store.go
- pkg/lib/authn/identity/anonymous/store_redis.go
- pkg/lib/authn/identity/claim_key.go
- pkg/lib/authn/identity/service/conversion.go
- pkg/lib/authn/identity/service/service.go
- pkg/lib/deps/deps_common.go
- pkg/lib/interaction/context.go
- pkg/lib/interaction/nodes/use_identity_anonymous.go
- pkg/lib/oauth/handler/handler_anonymous_user.go
- pkg/lib/oauth/handler/handler_token.go
- pkg/lib/oauth/handler/web_session_type.go
> Support using the promotion code to promote anonymous user in the authz endpoint

- pkg/lib/interaction/nodes/do_create_user.go
- pkg/lib/interaction/ratelimit.go
- pkg/util/duration/duration.go
> Add signup anonymous user rate limit

- docs/specs/user-profile/design.md
@carmenlau Could you take a look on this if you have time?
> Simplify the specification of custom attributes

- pkg/auth/deps.go
- pkg/auth/handler/webapp/settings.go
- pkg/auth/routes.go
- pkg/auth/webapp/deps.go
- pkg/auth/webapp/settings_sub_routes_middleware.go
- pkg/auth/wire_gen.go
- pkg/auth/wire_middleware.go
- resources/authgear/templates/en/translation.json
- resources/authgear/templates/en/web/settings_anonymous_user.html
- resources/authgear/templates/zh-HK/translation.json
- resources/authgear/templates/zh-TW/translation.json
refs #1685 
Show placeholder settings page to anonymous user in /settings, and redirect all settings sub-routes to /settings
> Anonymous user settings page

- docs/specs/anonymous-user.md
- docs/specs/api.md
- docs/specs/oidc.md
- docs/specs/user-model.md
> Update anonymous user specification to add web support

- pkg/lib/config/testdata/custom_attributes_tests.yaml
- pkg/lib/config/user_profile.go
- pkg/util/validation/formats.go
- pkg/util/validation/formats_test.go
- portal/src/EditCustomAttributeForm.tsx
- portal/src/hook/useAppConfigForm.ts
- portal/src/hook/useAppSecretConfigForm.ts
- portal/src/hook/useResourceForm.ts
- portal/src/hook/useSimpleForm.ts
- portal/src/locale-data/en.json
> Fix custom attribute pointer validation

- pkg/auth/webapp/auth_entry_point_middleware.go
- pkg/auth/wire_gen.go
> Respect default_redirect_uri in entrypoints

- portal/src/CommandBarContainer.tsx
- portal/src/graphql/adminapi/UserDetailsScreen.tsx
- portal/src/locale-data/en.json
> Warn about scheduled deletion

- pkg/portal/graphql/query.go
> Don't allow user to access the analytics data if they are not the collaborators

- portal/package-lock.json
- portal/package.json
- portal/src/graphql/portal/AnalyticsSignupConversionWidget.tsx
- portal/src/graphql/portal/AnalyticsSignupMethodsWidget.module.scss
- portal/src/graphql/portal/AnalyticsSignupMethodsWidget.tsx
> Show percentage label on signup conversion chart

- portal/src/graphql/portal/PortalAdminList.tsx
- portal/src/graphql/portal/__generated__/globalTypes.ts
- portal/src/graphql/portal/query/__generated__/CollaboratorsAndInvitationsQuery.ts
- portal/src/graphql/portal/query/collaboratorsAndInvitationsQuery.ts
- portal/src/locale-data/en.json
> Update ui to disallow removing owner from the portal admin list

- pkg/lib/config/config.go
- pkg/lib/config/testdata/config_tests.yaml
> Add custom attribute min max config validation

- pkg/auth/handler/webapp/viewmodels/settings_profile.go
- pkg/util/template/func.go
- pkg/util/template/func_test.go
- portal/src/graphql/portal/EditCustomAttributeScreen.tsx
- resources/authgear/templates/en/web/settings_profile.html
- resources/authgear/templates/en/web/settings_profile_edit.html
> Fix displaying custom attribute zero value in the settings page

- portal/src/graphql/portal/AnalyticsSignupConversionWidget.tsx
- portal/src/graphql/portal/AnalyticsSignupMethodsWidget.tsx
> Update label style of signup conversion chart

- portal/src/EditCustomAttributeForm.tsx
- portal/src/error/parse.ts
- portal/src/graphql/adminapi/AddEmailScreen.tsx
- portal/src/graphql/adminapi/AddPhoneScreen.tsx
- portal/src/graphql/adminapi/AddUserScreen.tsx
- portal/src/graphql/adminapi/AddUsernameScreen.tsx
- portal/src/graphql/adminapi/UserDetailsConnectedIdentities.tsx
- portal/src/graphql/portal/AcceptAdminInvitationScreen.tsx
- portal/src/graphql/portal/CreateAppScreen.tsx
- portal/src/graphql/portal/CustomDomainListScreen.tsx
- portal/src/graphql/portal/InviteAdminScreen.tsx
- portal/src/graphql/portal/PortalAdminsSettings.tsx
- portal/src/graphql/portal/VerifyDomainScreen.tsx
- portal/src/locale-data/en.json
> Fix custom attribute name conflicts with standard attribute error message

- pkg/lib/config/config.go
- pkg/lib/config/testdata/config_tests.yaml
- portal/src/EditCustomAttributeForm.tsx
- portal/src/error/parse.ts
- portal/src/locale-data/en.json
> Show duplicate attribute name error for custom attributes

- portal/src/locale-data/en.json
> Update cancel user removal confirmation dialog copywriting

- pkg/auth/handler/webapp/settings.go
- pkg/auth/wire_gen.go
- resources/authgear/templates/en/web/settings.html
> Always show more button in the settings page when account deletion is enabled

- portal/src/graphql/adminapi/AuditLogEntryScreen.tsx
> Display raw user id in the audit log entry page

- pkg/admin/graphql/user.go
- portal/src/graphql/adminapi/UserDetailSummary.module.scss
- portal/src/graphql/adminapi/UserDetailSummary.tsx
- portal/src/graphql/adminapi/UserDetailsScreen.tsx
- portal/src/graphql/adminapi/query/__generated__/UserQuery.ts
- portal/src/graphql/adminapi/query/userQuery.ts
- portal/src/graphql/adminapi/schema.graphql
> Show user formatted name in the user profile detail page

- pkg/lib/config/localization.go
- pkg/portal/deps/deps.go
- pkg/portal/wire_gen.go
- pkg/util/intl/language.go
- pkg/util/intl/language_constant.go
- pkg/util/intl/language_test.go
- pkg/util/intlresource/prepare.go
- pkg/util/intlresource/prepare_test.go
- pkg/util/template/translation.go
- pkg/util/template/translation_test.go
> Introduce app-specific and app-agnostic keys in translation.json

- pkg/auth/handler/webapp/settings_delete_account.go
- pkg/auth/routes.go
- pkg/auth/webapp/deps.go
- pkg/auth/webapp/success_page_middleware.go
- pkg/auth/wire_gen.go
- pkg/auth/wire_middleware.go
- pkg/lib/interaction/nodes/forgot_password.go
- pkg/lib/interaction/nodes/reset_password.go
- pkg/lib/successpage/cookie.go
> Allow access successful pages once only

- cmd/authgear/images/server/config.go
- cmd/authgear/images/server/server.go
- pkg/images/config/object_store.go
- pkg/images/deps/deps.go
- pkg/images/deps/provider.go
- pkg/images/handler/deps.go
- pkg/images/handler/get.go
- pkg/images/wire.go
- pkg/images/wire_gen.go
- pkg/util/imageproxy/imageproxy.go
- pkg/util/imageproxy/imageproxy_test.go
- pkg/util/log/panic.go
> Proxy image request to object store

- cmd/authgear/images/server/config.go
- go.mod
- go.sum
- pkg/images/config/object_store.go
- pkg/images/deps/deps.go
- pkg/images/handler/deps.go
- pkg/images/handler/post.go
- pkg/images/routes.go
- pkg/images/wire.go
- pkg/images/wire_gen.go
- pkg/lib/cloudstorage/azure.go
- pkg/lib/cloudstorage/cloudstorage.go
- pkg/lib/cloudstorage/deps.go
- pkg/lib/cloudstorage/gcs.go
- pkg/lib/cloudstorage/presgin_upload_response.go
- pkg/lib/cloudstorage/presgin_upload_response_test.go
- pkg/lib/cloudstorage/presign_upload_request.go
- pkg/lib/cloudstorage/provider.go
- pkg/lib/cloudstorage/s3.go
> Upload images to object store

- pkg/auth/api/deps.go
- pkg/auth/api/require_authenticated_middleware.go
- pkg/auth/deps.go
- pkg/auth/handler/api/deps.go
- pkg/auth/handler/api/presign_images_upload.go
- pkg/auth/handler/api/ratelimit.go
- pkg/auth/routes.go
- pkg/auth/wire_gen.go
- pkg/auth/wire_handler.go
- pkg/auth/wire_middleware.go
- pkg/lib/config/environment.go
- pkg/lib/deps/deps_provider.go
refs #1868 
TODO: pre-sign the url
> Get upload image url api

- pkg/auth/deps.go
- pkg/auth/handler/api/presign_images_upload.go
- pkg/auth/wire_gen.go
- pkg/images/deps/deps.go
- pkg/images/handler/deps.go
- pkg/images/handler/post.go
- pkg/images/wire.go
- pkg/images/wire_gen.go
- pkg/lib/config/generate.go
- pkg/lib/config/secret.go
- pkg/lib/config/secret_data.go
- pkg/lib/config/testdata/parse_secret_tests.yaml
- pkg/lib/deps/deps_common.go
- pkg/lib/deps/deps_config.go
- pkg/lib/presign/deps.go
- pkg/lib/presign/presign.go
- pkg/util/httpsigning/httpsigning.go
- pkg/util/httpsigning/httpsigning_test.go
refs #1863 
WIP:
- Migrate script to re-generate the images secret for existing apps
> Protect post images endpoint with signature

- cmd/portal/migrate_resources_migrate_images_secret.go
- pkg/lib/presign/presign.go
> Add migrate images secret script

- authui/package-lock.json
- authui/package.json
- authui/src/authgear.ts
- authui/src/form.ts
- authui/src/imagepicker.ts
- authui/src/loading.ts
- resources/authgear/static/authgear.css
- resources/authgear/templates/en/web/__html_head.html
- resources/authgear/templates/en/web/__page_frame.html
- resources/authgear/templates/en/web/__wide_page_frame.html
> Improve form submission UX

- migrations/images/20220315123333-add_images_file.sql
- pkg/auth/handler/api/deps.go
- pkg/auth/handler/api/presign_images_upload.go
- pkg/auth/wire_gen.go
- pkg/images/deps/deps.go
- pkg/images/handler/post.go
- pkg/images/wire.go
- pkg/images/wire_gen.go
- pkg/lib/images/deps.go
- pkg/lib/images/model.go
- pkg/lib/images/model_test.go
- pkg/lib/images/store.go
> Save image file record when uploading

- resources/authgear/templates/en/translation.json
- resources/authgear/templates/en/web/settings_profile_edit.html
- resources/authgear/templates/zh-HK/translation.json
- resources/authgear/templates/zh-TW/translation.json
> Add confirmation dialog for removing profile image in auth ui

- .env.example
- pkg/auth/wire_gen.go
- pkg/images/config/environment.go
- pkg/images/deps/deps.go
- pkg/images/wire_gen.go
- pkg/lib/config/environment.go
- pkg/lib/deps/deps_provider.go
- pkg/lib/infra/middleware/cors.go
- pkg/lib/infra/middleware/cors_test.go
> Support providing allowed origins to CORSMiddleware through environment variable

- portal/src/graphql/adminapi/EditPictureScreen.tsx
> Show the navigation blocker when image is selected in the edit picture

- portal/src/graphql/adminapi/UserProfileForm.tsx
> Fix email, phone_number, preferred_username not editable

- portal/src/graphql/adminapi/AuditLogEntryScreen.tsx
- portal/src/graphql/adminapi/AuditLogList.tsx
- portal/src/graphql/adminapi/AuditLogScreen.tsx
- portal/src/graphql/adminapi/__generated__/AuditLogListQuery.ts
- portal/src/locale-data/en.json
> Show deleted user ID in audit log

- README.md
- cmd/authgear/Dockerfile
- cmd/portal/Dockerfile
- go.mod
- go.sum
- pkg/lib/web/error.go
- pkg/lib/web/image.go
- portal/src/error/error.ts
- portal/src/error/parse.ts
- portal/src/error/resources.ts
- portal/src/locale-data/en.json
> Validate image file type

- pkg/auth/handler/webapp/viewmodels/base.go
- resources/authgear/templates/en/web/settings_profile_edit.html
> Specify action in asynchronous form

- pkg/admin/graphql/user.go
- pkg/admin/loader/user.go
- pkg/lib/authn/user/queries.go
- portal/src/graphql/adminapi/UserDetailSummary.module.scss
- portal/src/graphql/adminapi/UserDetailSummary.tsx
- portal/src/graphql/adminapi/UserDetailsScreen.tsx
- portal/src/graphql/adminapi/UsersList.module.scss
- portal/src/graphql/adminapi/UsersList.tsx
- portal/src/graphql/adminapi/UsersScreen.tsx
- portal/src/graphql/adminapi/__generated__/UsersListQuery.ts
- portal/src/graphql/adminapi/query/__generated__/UserQuery.ts
- portal/src/graphql/adminapi/query/userQuery.ts
- portal/src/graphql/adminapi/schema.graphql
- portal/src/locale-data/en.json
- portal/src/util/user.ts
> Show formattedName and picture in UsersList

- pkg/lib/elasticsearch/index.go
- pkg/lib/elasticsearch/index_test.go
> Work around crashes on search keyword with mix of chinese characters

- portal/src/graphql/adminapi/UsersScreen.tsx
> Work around an issue related to frequent re-render of command bar item

- portal/src/graphql/adminapi/EditPictureScreen.tsx
> Prevent access to EditPictureScreen when picture is not editable

- authui/src/imagepicker.ts
- portal/src/ReactCropperjs.tsx
- portal/src/error/error.ts
- portal/src/error/parse.ts
- portal/src/graphql/adminapi/EditPictureScreen.tsx
- portal/src/locale-data/en.json
- resources/authgear/templates/en/translation.json
- resources/authgear/templates/en/web/__error.html
- resources/authgear/templates/zh-HK/translation.json
- resources/authgear/templates/zh-TW/translation.json
> Handle invalid selected image error

- portal/src/graphql/portal/UISettingsScreen.tsx
> Never save empty strings in UISettingsScreen

- portal/src/ReactCropperjs.module.scss
- portal/src/ReactCropperjs.tsx
- portal/src/graphql/adminapi/EditPictureScreen.module.scss
- portal/src/graphql/adminapi/EditPictureScreen.tsx
> Show placeholder when there is no picture

- authui/src/error.ts
- authui/src/form.ts
- authui/src/imagepicker.ts
- resources/authgear/templates/en/web/__error.html
> Handle ajax error more robustly

- cmd/authgear/elasticsearch/index.go
- cmd/authgear/elasticsearch/reindex.go
- pkg/api/model/user.go
- pkg/lib/elasticsearch/index.go
- pkg/lib/elasticsearch/index_test.go
- pkg/lib/elasticsearch/model.go
- pkg/lib/elasticsearch/model_test.go
- pkg/lib/elasticsearch/service.go
> Support searching user by oauth provider user id

- cmd/authgear/background/wire_gen.go
- cmd/authgear/elasticsearch/index.go
- cmd/authgear/elasticsearch/reindex.go
- pkg/admin/wire_gen.go
- pkg/api/model/user.go
- pkg/auth/wire_gen.go
- pkg/lib/deps/deps_common.go
- pkg/lib/elasticsearch/index.go
- pkg/lib/elasticsearch/index_test.go
- pkg/lib/elasticsearch/model.go
- pkg/lib/elasticsearch/model_test.go
- pkg/lib/elasticsearch/service.go
> User search standard attributes

- portal/src/locale-data/en.json
> Update billing page business plan info

- portal/src/graphql/portal/CreateProjectScreen.tsx
- portal/src/locale-data/en.json
> Use a slightly different copy for developers without any apps

- resources/authgear/static/authgear-dark-theme.css
- resources/authgear/static/authgear-light-theme.css
- resources/authgear/static/authgear.css
- resources/authgear/templates/en/web/login.html
- resources/authgear/templates/en/web/settings_identity.html
- resources/authgear/templates/en/web/settings_sessions.html
- resources/authgear/templates/en/web/signup.html
> Adjust dark theme colors

- pkg/lib/authn/sso/github.go
> Populate name and given_name with github username

- portal/src/error/parse.ts
- portal/src/graphql/portal/ApplicationsConfigurationScreen.tsx
- portal/src/graphql/portal/CreateOAuthClientScreen.tsx
- portal/src/graphql/portal/GetStartedScreen.tsx
- portal/src/locale-data/en.json
> Handle application quota exceeded error

- portal/src/graphql/portal/GetStartedScreen.module.scss
- portal/src/graphql/portal/GetStartedScreen.tsx
> Make get started screen width dynamic

- authui/src/authgear.ts
- authui/src/clickToSwitch.ts
- authui/src/tailwind.css
- resources/authgear/static/authgear.css
- resources/authgear/templates/en/web/wechat_auth.html
> Fix wechat page

- authui/src/form.ts
So when user clicks back, the buttons on the page are enabled
> Revert disabled buttons before turbolinks cache the page

- authui/src/form.ts
> Let GTM to handle form submission event

- pkg/auth/handler/webapp/alternatives.go
- pkg/auth/handler/webapp/deps.go
- pkg/auth/handler/webapp/interaction.go
- pkg/auth/handler/webapp/setup_whatsapp_otp.go
- pkg/auth/handler/webapp/viewmodels/alternatives.go
- pkg/auth/handler/webapp/whatsapp_otp.go
- pkg/auth/routes.go
- pkg/auth/webapp/service2.go
- pkg/auth/webapp/session_step.go
- pkg/auth/wire_gen.go
- pkg/auth/wire_handler.go
- pkg/lib/config/authenticator.go
- pkg/lib/config/testdata/default_config.yaml
- pkg/lib/interaction/nodes/create_authenticator_begin.go
- pkg/lib/interaction/nodes/create_authenticator_whatsapp_fallback_sms.go
- pkg/lib/interaction/nodes/create_authenticator_whatsapp_otp.go
- pkg/lib/interaction/nodes/create_authenticator_whatsapp_otp_setup.go
- resources/authgear/templates/en/translation.json
- resources/authgear/templates/en/web/__alternatives.html
- resources/authgear/templates/en/web/setup_whatsapp_otp.html
- resources/authgear/templates/en/web/whatsapp_otp.html
- resources/authgear/templates/zh-HK/translation.json
- resources/authgear/templates/zh-TW/translation.json
refs #1963 
The PR only updates the interaction with the whatsapp otp verification flow, the otp store is not implemented yet so when you click verify it will always succeed. The PR covers adding 1st and 2nd authenticators during signup, at settings page and portal.
> Update interaction to create oob otp sms authenticator by whatsapp otp

- pkg/auth/handler/webapp/alternatives.go
- pkg/auth/handler/webapp/deps.go
- pkg/auth/handler/webapp/interaction.go
- pkg/auth/handler/webapp/setup_whatsapp_otp.go
- pkg/auth/handler/webapp/verify_identity_via_whatsapp.go
- pkg/auth/handler/webapp/viewmodels/alternatives.go
- pkg/auth/handler/webapp/whatsapp_otp.go
- pkg/auth/routes.go
- pkg/auth/webapp/service2.go
- pkg/auth/webapp/session_step.go
- pkg/auth/wire_gen.go
- pkg/auth/wire_handler.go
- pkg/lib/config/authenticator.go
- pkg/lib/config/testdata/default_config.yaml
- pkg/lib/interaction/intents/verify_identity.go
- pkg/lib/interaction/nodes/create_authenticator_begin.go
- pkg/lib/interaction/nodes/create_authenticator_whatsapp_fallback_sms.go
- pkg/lib/interaction/nodes/create_authenticator_whatsapp_otp.go
- pkg/lib/interaction/nodes/create_authenticator_whatsapp_otp_setup.go
- pkg/lib/interaction/nodes/ensure_verification.go
- pkg/lib/interaction/nodes/verify_identity_via_whatsapp.go
- resources/authgear/templates/en/translation.json
- resources/authgear/templates/en/web/__alternatives.html
- resources/authgear/templates/en/web/settings.html
- resources/authgear/templates/en/web/settings_identity.html
- resources/authgear/templates/en/web/setup_whatsapp_otp.html
- resources/authgear/templates/en/web/verify_identity_via_whatsapp.html
- resources/authgear/templates/en/web/whatsapp_otp.html
- resources/authgear/templates/zh-HK/translation.json
- resources/authgear/templates/zh-TW/translation.json
refs #1963 
after #1982 
The PR only updates the interaction with the whatsapp otp verification flow, the otp store is not implemented yet so when you click verify it will always succeed. The PR covers verify phone via whatsapp.
> Update verification interaction to verify phone via whatsapp

- portal/src/graphql/portal/GetStartedScreen.tsx
> Fix get started screen counter

- pkg/admin/wire_gen.go
- pkg/auth/handler/webapp/interaction.go
- pkg/auth/handler/webapp/verify_identity_via_whatsapp.go
- pkg/auth/handler/webapp/whatsapp_otp.go
- pkg/auth/wire_gen.go
- pkg/lib/authn/authenticator/whatsapp/code.go
- pkg/lib/authn/authenticator/whatsapp/deps.go
- pkg/lib/authn/authenticator/whatsapp/errors.go
- pkg/lib/authn/authenticator/whatsapp/provider.go
- pkg/lib/authn/authenticator/whatsapp/store_redis.go
- pkg/lib/deps/deps_common.go
- pkg/lib/interaction/context.go
- pkg/lib/interaction/nodes/create_authenticator_whatsapp_otp.go
- pkg/lib/interaction/nodes/create_authenticator_whatsapp_otp_setup.go
- pkg/lib/interaction/nodes/verify_identity_via_whatsapp.go
refs #1963 
after #1987 
To test the otp store, we can use the dummy handler here to simulate the user input https://github.com/carmenlau/authgear-server/commit/b229f4fd8d7a6a8894b20baf83a4f65fdf738997
> Implement whatsapp otp store and provider

- .github/actions/libvips/action.yaml
- .github/workflows/ci.yaml
- .gitignore
- Makefile
> Build binary

- authui/src/authgear.ts
- authui/src/copy.ts
- resources/authgear/templates/en/web/settings_recovery_code.html
- resources/authgear/templates/en/web/setup_recovery_code.html
- resources/authgear/templates/en/web/setup_totp.html
> Convert copy button to Stimulus

- authui/src/accountdeletion.ts
- authui/src/authgear.ts
- authui/src/messageBar.ts
- authui/src/preventDoubleTap.ts
- authui/src/resendButton.ts
- resources/authgear/templates/en/web/__error.html
- resources/authgear/templates/en/web/__message_bar.html
- resources/authgear/templates/en/web/__page_frame.html
- resources/authgear/templates/en/web/enter_oob_otp.html
- resources/authgear/templates/en/web/settings_delete_account.html
- resources/authgear/templates/en/web/verify_identity.html
> Migrate to Stimulus part 2

- authui/src/authgear.ts
- authui/src/imagepicker.ts
- authui/src/intl-tel-input.d.ts
- authui/src/intlTelInput.ts
- authui/src/select.ts
- resources/authgear/templates/en/web/enter_login_id.html
- resources/authgear/templates/en/web/forgot_password.html
- resources/authgear/templates/en/web/login.html
- resources/authgear/templates/en/web/promote.html
- resources/authgear/templates/en/web/settings_profile_edit.html
- resources/authgear/templates/en/web/setup_oob_otp.html
- resources/authgear/templates/en/web/signup.html
> Migrate to Stimulus part 3

- authui/src/authgear.ts
- authui/src/date.ts
- authui/src/websocket.ts
- resources/authgear/templates/en/web/__page_frame.html
- resources/authgear/templates/en/web/__wide_page_frame.html
- resources/authgear/templates/en/web/settings_profile.html
> Migrate to Stimulus part 4

- pkg/admin/facade/authenticator.go
- pkg/admin/facade/identity.go
- pkg/admin/graphql/authenticator.go
- pkg/admin/graphql/authenticator_mutation.go
- pkg/admin/graphql/context.go
- pkg/admin/graphql/entity.go
- pkg/admin/graphql/identity.go
- pkg/admin/graphql/identity_mutation.go
- pkg/admin/graphql/session.go
- pkg/admin/graphql/user.go
- pkg/admin/loader/authenticator.go
- pkg/admin/loader/identity.go
- pkg/auth/handler/webapp/enter_login_id.go
- pkg/lib/authn/authenticator/service/service.go
- pkg/lib/authn/authenticator/service/store.go
- pkg/lib/authn/identity/service/service.go
- pkg/lib/authn/identity/service/store.go
- pkg/lib/facade/authenticator.go
- pkg/lib/facade/coordinator.go
- pkg/lib/facade/identity.go
- pkg/lib/interaction/context.go
- pkg/lib/interaction/intents/verify_identity.go
- pkg/lib/interaction/intents/verify_identity_resume.go
- pkg/lib/interaction/nodes/remove_authenticator.go
- pkg/lib/interaction/nodes/remove_identity.go
- pkg/lib/interaction/nodes/update_identity_end.go
> Align Node ID

- resources/authgear/templates/en/web/setup_whatsapp_otp.html
> Update using intl-tel-input controller in setup whatsapp otp page

- pkg/auth/handler/webapp/setup_totp.go
- pkg/lib/authn/authenticator/totp/provider.go
- pkg/lib/authn/otp/totp.go
- pkg/util/secretcode/oob_otp.go
- pkg/util/secretcode/oob_otp_test.go
- pkg/util/secretcode/totp.go
- pkg/util/secretcode/totp_test.go
> Remove leading and trailing whitespace in OTP code

- authui/src/authgear.ts
- authui/src/delayedAutoSubmit.ts
- authui/src/simpleModal.ts
- pkg/auth/handler/webapp/whatsapp.go
- pkg/auth/handler/webapp/whatsapp_otp.go
- resources/authgear/static/authgear.css
- resources/authgear/templates/en/translation.json
- resources/authgear/templates/en/web/__modal.html
- resources/authgear/templates/en/web/__page_frame.html
- resources/authgear/templates/en/web/__phone_otp_alternatives.html
- resources/authgear/templates/en/web/__wide_page_frame.html
- resources/authgear/templates/en/web/whatsapp_otp.html
- resources/authgear/templates/zh-HK/translation.json
- resources/authgear/templates/zh-TW/translation.json
> Update whatsapp OTP page ui

- pkg/auth/handler/webapp/change_password.go
- pkg/auth/handler/webapp/change_secondary_password.go
- pkg/auth/handler/webapp/create_password.go
- pkg/auth/handler/webapp/reset_password.go
- pkg/auth/handler/webapp/settings_change_password.go
- pkg/auth/handler/webapp/settings_change_secondary_password.go
- pkg/auth/handler/webapp/viewmodels/password_policy.go
- pkg/lib/authn/authenticator/password/checker.go
- pkg/lib/authn/authenticator/password/checker_test.go
- resources/authgear/templates/en/web/__password_input.html
- resources/authgear/templates/en/web/change_password.html
- resources/authgear/templates/en/web/change_secondary_password.html
- resources/authgear/templates/en/web/create_password.html
- resources/authgear/templates/en/web/reset_password.html
> Support PasswordRules for Apple

- portal/src/graphql/portal/AppsScreen.module.scss
> Fix screen broken layout

- authui/src/authgear.ts
- authui/src/delayedAutoSubmit.ts
- authui/src/simpleModal.ts
- pkg/auth/handler/webapp/interaction.go
- pkg/auth/handler/webapp/whatsapp.go
- pkg/auth/handler/webapp/whatsapp_otp.go
- resources/authgear/static/authgear.css
- resources/authgear/templates/en/translation.json
- resources/authgear/templates/en/web/__modal.html
- resources/authgear/templates/en/web/__page_frame.html
- resources/authgear/templates/en/web/__phone_otp_alternatives.html
- resources/authgear/templates/en/web/__wide_page_frame.html
- resources/authgear/templates/en/web/whatsapp_otp.html
- resources/authgear/templates/zh-HK/translation.json
- resources/authgear/templates/zh-TW/translation.json
> Support use device token and recovery code in whatsapp otp page

- pkg/lib/interaction/nodes/do_create_identity.go
> Fix incorrect error message in adding identity

- authui/src/colorscheme.ts
- resources/authgear/templates/en/web/__page_frame.html
- resources/authgear/templates/en/web/__wide_page_frame.html
So that we can use the tailwind class for dark theme
> Only add the dark theme class when dark theme is enabled

- resources/authgear/templates/en/web/__watermark.html
> Disable logo link for mobile

- portal/src/graphql/adminapi/DeleteUserDialog.tsx
- portal/src/graphql/adminapi/SetUserDisabledDialog.tsx
> Show the raw id in the confirmation dialog if there is no account identifier

- pkg/auth/handler/webapp/enter_recovery_code.go
- pkg/auth/handler/webapp/interaction.go
- resources/authgear/templates/en/web/enter_recovery_code.html
> Enable MFA device token for recovery code

- portal/src/graphql/portal/LoginIDConfigurationScreen.tsx
- portal/src/graphql/portal/PasswordPolicyConfigurationScreen.tsx
- portal/src/hook/useInput.ts
- portal/src/util/array.test.ts
- portal/src/util/array.ts
> Don't allow adding same items into the tag picker

- .gitignore
- Makefile
- authui/.parcelrc
- authui/package-lock.json
- authui/package.json
- authui/packages/parcel-namer-authgear/package.json
- authui/packages/parcel-namer-authgear/src/index.js
- authui/packages/parcel-reporter-authgear/package.json
- authui/packages/parcel-reporter-authgear/src/index.js
- authui/src/build.html
- authui/src/delayedAutoSubmit.ts
- authui/src/websocket.ts
- pkg/auth/handler/webapp/static_assets.go
- pkg/lib/web/parcel.go
- pkg/lib/web/source_map.go
- pkg/lib/web/source_map_test.go
- pkg/lib/web/static_asset_resolver.go
- pkg/lib/web/static_asset_resolver_test.go
- pkg/lib/web/static_assets.go
- pkg/lib/webparcel/parcel.go
- resources/authgear/templates/en/web/__html_head.html
> Fix Source Map

- authui/src/tailwind.css
- resources/authgear/static/authgear.css
- resources/authgear/templates/en/web/login.html
- resources/authgear/templates/en/web/promote.html
- resources/authgear/templates/en/web/signup.html
> Support multi-line buttons

- portal/src/graphql/portal/GetStartedScreen.module.scss
- portal/src/graphql/portal/GetStartedScreen.tsx
> Use ScreenTitle in GetStartedScreen

- resources/authgear/templates/en/web/login.html
- resources/authgear/templates/en/web/promote.html
- resources/authgear/templates/en/web/signup.html
> Update login / signup page button label

- pkg/auth/handler/webapp/whatsapp.go
- pkg/auth/handler/webapp/whatsapp_otp.go
- pkg/auth/handler/webapp/whatsapp_wati_callback.go
- resources/authgear/templates/en/translation.json
- resources/authgear/templates/zh-HK/translation.json
- resources/authgear/templates/zh-TW/translation.json
> Support more instruction in the per-filled message of whatsapp

- authui/src/authgear.ts
- authui/src/form.ts
- authui/src/intl-tel-input.d.ts
- authui/src/intlTelInput.ts
- authui/src/websocket.ts
- pkg/auth/handler/webapp/util.go
- portal/src/intl-tel-input.d.ts
- resources/authgear/templates/en/web/enter_login_id.html
- resources/authgear/templates/en/web/forgot_password.html
- resources/authgear/templates/en/web/login.html
- resources/authgear/templates/en/web/promote.html
- resources/authgear/templates/en/web/settings_profile_edit.html
- resources/authgear/templates/en/web/setup_oob_otp.html
- resources/authgear/templates/en/web/setup_whatsapp_otp.html
- resources/authgear/templates/en/web/signup.html
> Retain form values between login and signup page

- pkg/auth/handler/webapp/settings_recovery_code.go
- pkg/auth/handler/webapp/viewmodels/settings.go
- pkg/lib/config/authentication.go
- pkg/lib/config/testdata/default_config.yaml
- pkg/lib/interaction/nodes/authn_begin.go
- pkg/lib/interaction/nodes/generate_recovery_code_begin.go
- portal/src/graphql/portal/AuthenticatorConfigurationScreen.tsx
- portal/src/locale-data/en.json
- portal/src/types.ts
- resources/authgear/templates/en/translation.json
- resources/authgear/templates/en/web/settings_recovery_code.html
- resources/authgear/templates/zh-HK/translation.json
- resources/authgear/templates/zh-TW/translation.json
> Allow recovery code to be disabled

- pkg/images/config/environment.go
- pkg/images/deps/deps.go
- pkg/images/handler/get.go
- pkg/images/wire_gen.go
> Redirect to images CDN host

- resources/authgear/templates/en/web/__html_head.html
> Override tailwind.css with authgear.css

- resources/authgear/templates/en/web/login.html
- resources/authgear/templates/en/web/promote.html
- resources/authgear/templates/en/web/settings_identity.html
- resources/authgear/templates/en/web/signup.html
> Disable turbo link for oauth form

- pkg/admin/graphql/audit_log.go
- pkg/admin/wire_gen.go
- pkg/api/event/nonblocking/whatsapp_otp_verified.go
- pkg/auth/wire_gen.go
- pkg/lib/authn/authenticator/whatsapp/provider.go
- pkg/lib/deps/deps_common.go
- portal/src/graphql/adminapi/globalTypes.generated.ts
- portal/src/graphql/adminapi/schema.graphql
- portal/src/locale-data/en.json
> Track non-blocking event `whatsapp.otp.verified`

- pkg/admin/graphql/query.go
- pkg/lib/audit/read_store.go
- portal/src/graphql/adminapi/AuditLogList.module.scss
- portal/src/graphql/adminapi/AuditLogList.tsx
- portal/src/graphql/adminapi/AuditLogScreen.tsx
- portal/src/graphql/adminapi/globalTypes.generated.ts
- portal/src/graphql/adminapi/query/auditLogListQuery.generated.ts
- portal/src/graphql/adminapi/query/auditLogListQuery.graphql
- portal/src/graphql/adminapi/schema.graphql
- portal/src/locale-data/en.json
> Audit log sorting

- cmd/portal/analytic/deps.go
- cmd/portal/analytic/wire_gen.go
- cmd/portal/cmd/cmdusage/collect_count.go
- cmd/portal/usage/deps.go
- cmd/portal/usage/wire.go
- cmd/portal/usage/wire_gen.go
- pkg/lib/analytic/auditdb_read_store.go
- pkg/lib/analytic/count_collector.go
- pkg/lib/analytic/project_weekly_report.go
- pkg/lib/meter/auditdb_read_store.go
- pkg/lib/meter/deps.go
- pkg/lib/usage/count_collector.go
- pkg/lib/usage/usage_record.go
- pkg/util/phone/phone.go
- pkg/util/phone/phone_test.go
> Collect sms sent usage record

- cmd/portal/analytic/deps.go
- cmd/portal/analytic/wire_gen.go
- cmd/portal/cmd/cmdusage/collect_count.go
- cmd/portal/usage/deps.go
- cmd/portal/usage/wire.go
- cmd/portal/usage/wire_gen.go
- pkg/lib/analytic/auditdb_read_store.go
- pkg/lib/analytic/count_collector.go
- pkg/lib/analytic/project_weekly_report.go
- pkg/lib/meter/auditdb_read_store.go
- pkg/lib/meter/deps.go
- pkg/lib/usage/count_collector.go
- pkg/lib/usage/usage_record.go
- pkg/util/phone/phone.go
- pkg/util/phone/phone_test.go
> Collect email sent and whatsapp otp verified usage record

- authui/src/intlTelInput.ts
> Restore phone value without country code

- docs/specs/api-resolver.md
- nginx.conf
- pkg/api/model/session_info.go
- pkg/api/model/session_info_test.go
- pkg/lib/session/info.go
- pkg/portal/service/app.go
- pkg/resolver/deps.go
- pkg/resolver/handler/resolve.go
- pkg/resolver/handler/resolve_mock_test.go
- pkg/resolver/handler/resolve_test.go
- pkg/resolver/wire_gen.go
> Disable reauthentication if impossible

- pkg/portal/graphql/billing_mutation.go
- pkg/portal/graphql/context.go
- pkg/portal/libstripe/model.go
- pkg/portal/libstripe/service.go
- portal/src/graphql/portal/globalTypes.generated.ts
- portal/src/graphql/portal/schema.graphql
> Create strip checkout session link

- portal/src/ReactRouterLink.tsx
- portal/src/graphql/adminapi/AuditLogEntryScreen.tsx
- portal/src/graphql/adminapi/AuditLogList.tsx
- portal/src/graphql/adminapi/AuditLogScreen.tsx
> Support restore page by search params

- pkg/auth/handler/webapp/whatsapp.go
- pkg/util/phone/phone.go
- pkg/util/phone/phone_test.go
> Whatsapp OTP message formatting

- portal/src/ScreenNav.module.scss
- portal/src/ScreenNav.tsx
> Add chevron icon styles for ScreenNav

- portal/src/graphql/portal/SubscriptionCurrentPlanSummary.module.scss
- portal/src/graphql/portal/SubscriptionCurrentPlanSummary.tsx
- portal/src/graphql/portal/SubscriptionPlanCard.tsx
- portal/src/graphql/portal/SubscriptionScreen.tsx
- portal/src/locale-data/en.json
> More billing screen improvements

- pkg/lib/usage/globaldb_store.go
- pkg/lib/usage/usage_record.go
- pkg/portal/deps.go
- pkg/portal/graphql/app.go
- pkg/portal/graphql/billing.go
- pkg/portal/graphql/context.go
- pkg/portal/libstripe/model.go
- pkg/portal/libstripe/service.go
- pkg/portal/model/subscription.go
- pkg/portal/service/subscription.go
- pkg/portal/wire_gen.go
- portal/src/graphql/portal/SubscriptionScreen.tsx
- portal/src/graphql/portal/globalTypes.generated.ts
- portal/src/graphql/portal/query/subscriptionScreenQuery.generated.ts
- portal/src/graphql/portal/query/subscriptionScreenQuery.graphql
- portal/src/graphql/portal/schema.graphql
> Add subscriptionUsage to graphql

- portal/src/graphql/portal/SubscriptionCurrentPlanSummary.tsx
- portal/src/graphql/portal/SubscriptionScreen.tsx
- portal/src/graphql/portal/query/subscriptionScreenQuery.generated.ts
- portal/src/graphql/portal/query/subscriptionScreenQuery.graphql
- portal/src/locale-data/en.json
> Show subscription usage

- portal/src/graphql/portal/VerificationConfigurationScreen.tsx
- portal/src/locale-data/en.json
- portal/src/types.ts
> Whatsapp OTP config in portal

- migrations/portal/20220620152310-add_subscription.sql
- pkg/portal/model/subscription.go
- pkg/portal/service/subscription.go
> Add created_at and updated_at to subscription tables

- cmd/authgear/main.go
- cmd/portal/cmd/cmdpricing/deps.go
- cmd/portal/cmd/cmdpricing/pricing.go
- cmd/portal/cmd/cmdpricing/wire.go
- cmd/portal/cmd/cmdpricing/wire_gen.go
- cmd/portal/cmd/cmdusage/collect_count.go
- cmd/portal/main.go
- cmd/portal/usage/deps.go
- cmd/portal/usage/wire.go
- cmd/portal/usage/wire_gen.go
- pkg/util/cobrasentry/cobrasentry.go
- pkg/util/cobrasentry/context.go
- pkg/util/cobrasentry/deps.go
> Setup sentry for critical commands 

- portal/src/graphql/portal/LoginIDConfigurationScreen.tsx
- portal/src/locale-data/en.json
> Remove checking if length of phone checking list is 0

- pkg/auth/handler/webapp/whatsapp.go
- resources/authgear/templates/en/web/whatsapp_otp.html
> Use whatsapp custom url scheme for native mobile app

- authui/src/tailwind.css
- resources/authgear/static/authgear-dark-theme.css
- resources/authgear/static/authgear-light-theme.css
- resources/authgear/static/authgear.css
- resources/authgear/templates/en/web/__password_input.html
- resources/authgear/templates/en/web/enter_login_id.html
- resources/authgear/templates/en/web/enter_oob_otp.html
- resources/authgear/templates/en/web/enter_recovery_code.html
- resources/authgear/templates/en/web/enter_totp.html
- resources/authgear/templates/en/web/forgot_password.html
- resources/authgear/templates/en/web/login.html
- resources/authgear/templates/en/web/promote.html
- resources/authgear/templates/en/web/settings_delete_account.html
- resources/authgear/templates/en/web/settings_profile_edit.html
- resources/authgear/templates/en/web/setup_oob_otp.html
- resources/authgear/templates/en/web/setup_totp.html
- resources/authgear/templates/en/web/setup_whatsapp_otp.html
- resources/authgear/templates/en/web/signup.html
- resources/authgear/templates/en/web/verify_identity.html
> Fix the input field style in mobile safari

- .golangci.yml
- cmd/portal/cmd/cmdpricing/stripe_service.go
- pkg/portal/graphql/billing.go
- pkg/portal/graphql/billing_mutation.go
- pkg/portal/graphql/context.go
- pkg/portal/libstripe/model.go
- pkg/portal/libstripe/service.go
- pkg/portal/model/subscription.go
- pkg/portal/model/subscription_test.go
- pkg/portal/service/subscription.go
- pkg/portal/transport/stripe_webhook_handler.go
- pkg/util/setutil/set.go
- pkg/util/setutil/set_test.go
- portal/src/graphql/portal/SubscriptionPlanCard.tsx
- portal/src/graphql/portal/SubscriptionScreen.tsx
- portal/src/graphql/portal/globalTypes.generated.ts
- portal/src/graphql/portal/mutations/previewUpdateSubscriptionMutation.generated.ts
- portal/src/graphql/portal/mutations/previewUpdateSubscriptionMutation.graphql
- portal/src/graphql/portal/mutations/previewUpdateSubscriptionMutation.ts
- portal/src/graphql/portal/mutations/updateSubscriptionMutation.generated.ts
- portal/src/graphql/portal/mutations/updateSubscriptionMutation.graphql
- portal/src/graphql/portal/mutations/updateSubscriptionMutation.ts
- portal/src/graphql/portal/query/subscriptionScreenQuery.generated.ts
- portal/src/graphql/portal/query/subscriptionScreenQuery.graphql
- portal/src/graphql/portal/schema.graphql
- portal/src/locale-data/en.json
> Switch plan

- pkg/lib/config/feature.go
- pkg/lib/config/feature_collaborator.go
- pkg/lib/config/testdata/default_feature.yaml
- pkg/lib/deps/deps_config.go
- pkg/portal/service/collaborator.go
- pkg/portal/service/deps.go
- pkg/portal/wire_gen.go
- portal/src/graphql/portal/PortalAdminsSettings.tsx
- portal/src/types.ts
> Restrict the number of admins

- pkg/auth/wire_gen.go
- pkg/lib/config/configsource/resources.go
- pkg/lib/config/feature_identity.go
- pkg/lib/config/testdata/default_feature.yaml
- pkg/lib/config/testdata/parse_feature_tests.yaml
- pkg/lib/oauth/handler/handler_token.go
- portal/src/graphql/portal/BiometricConfigurationScreen.tsx
- portal/src/types.ts
> Disable biometric for free plan user

- portal/src/locale-data/en.json
> Clarify the estimated cost when changing plan

- portal/src/graphql/portal/PortalAdminsSettings.module.scss
- portal/src/graphql/portal/PortalAdminsSettings.tsx
- portal/src/locale-data/en.json
> Add message bar to tell the maximum number of collaborators

- pkg/lib/authn/authenticator/password/deps.go
- pkg/lib/config/configsource/resources.go
- pkg/lib/config/feature_authenticator.go
- pkg/lib/config/test/config.go
- pkg/lib/config/testdata/parse_feature_tests.yaml
- pkg/portal/appresource/manager_test.go
- portal/src/graphql/portal/PasswordPolicyConfigurationScreen.tsx
- portal/src/types.ts
> Remove basic password policy from the feature config

- cmd/authgear/elasticsearch/index.go
> Improve elasticsearch accuracy

- docs/specs/billing.md
> Document how we bill

- portal/src/graphql/portal/EditTemplatesWidget.module.css
- portal/src/graphql/portal/EditTemplatesWidget.tsx
- portal/src/graphql/portal/LocalizationConfigurationScreen.tsx
- portal/src/graphql/portal/query/appTemplatesQuery.ts
- portal/src/locale-data/en.json
- portal/src/resources.ts
- portal/src/util/resource.ts
ref #2087 
TODO:
- Support update email sender and reply-to in custom email provider page
> Support update email subject and refine localization screen 

- pkg/auth/deps.go
- pkg/auth/handler/webapp/login.go
- pkg/auth/handler/webapp/select_account.go
- pkg/auth/webapp/session.go
- pkg/auth/wire_gen.go
- pkg/lib/interaction/nodes/use_identity_oauth_provider.go
- pkg/lib/oauth/handler/handler_authz.go
- pkg/lib/oauth/protocol/authz.go
> Support x_oauth_provider_alias to redirect the user to the oauth provider

- pkg/auth/wire_gen.go
- pkg/images/wire_gen.go
- pkg/lib/config/oauth.go
- pkg/lib/config/oauth_test.go
- pkg/lib/infra/middleware/cors.go
- pkg/lib/infra/middleware/cors_test.go
- pkg/util/slice/strings.go
- pkg/util/slice/strings_test.go
- portal/src/graphql/portal/ApplicationsConfigurationScreen.tsx
- portal/src/locale-data/en.json
> Auto allow all client's redirect uris in CORS middleware

- pkg/lib/feature/forgotpassword/errors.go
- pkg/lib/feature/forgotpassword/provider.go
- pkg/lib/interaction/context.go
- pkg/lib/interaction/nodes/forgot_password.go
- pkg/lib/interaction/nodes/reset_password.go
- pkg/lib/interaction/nodes/utils_nodes.go
> Allow creating password with reset password

- portal/src/CommandBarContainer.module.css
- portal/src/CommandBarContainer.tsx
- portal/src/ScreenLayout.module.css
- portal/src/ScreenLayoutScrollView.module.css
- portal/src/ScreenLayoutScrollView.tsx
- portal/src/graphql/portal/AdminAPIConfigurationScreen.tsx
- portal/src/graphql/portal/CustomDomainListScreen.tsx
- portal/src/graphql/portal/GetStartedScreen.module.css
- portal/src/graphql/portal/GetStartedScreen.tsx
- portal/src/graphql/portal/LocalizationConfigurationScreen.module.css
- portal/src/graphql/portal/UISettingsScreen.module.css
> Fix horizontal overflow in Portal

- resources/authgear/templates/en/web/__password_input.html
> Password visibility toggle button style

- authui/package-lock.json
- authui/package.json
- authui/tailwind.config.js
> Migrate to Tailwind 3

- authui/src/colorscheme.ts
> Fix spinner box color in dark mode

- portal/.eslintignore
- portal/scripts/generateCodesplit.mjs
- portal/src/codesplit.ts
> Fix module not found error

- portal/src/graphql/portal/CreateOAuthClientScreen.tsx
- portal/src/graphql/portal/EditOAuthClientScreen.module.css
- portal/src/locale-data/en.json
> Application config UI optimization

- portal/src/locale-data/en.json
> Change biometric screen description copywritting

- portal/src/graphql/portal/SubscriptionScreen.tsx
> Fix billing page broken layout

- portal/src/BlockerDialog.tsx
- portal/src/FormContainer.tsx
- portal/src/NavigationBlockerDialog.tsx
- portal/src/locale-data/en.json
> Adjust discard confirm dialog button design

- pkg/lib/config/authenticator.go
- pkg/lib/config/testdata/default_config.yaml
- portal/src/graphql/portal/VerificationConfigurationScreen.tsx
> Set default phone_otp_mode to whatsapp or sms

- portal/src/graphql/portal/AccountDeletionConfigurationScreen.tsx
- portal/src/graphql/portal/AnonymousUsersConfigurationScreen.tsx
- portal/src/graphql/portal/ApplicationsConfigurationScreen.tsx
- portal/src/graphql/portal/AuthenticatorConfigurationScreen.module.css
- portal/src/graphql/portal/AuthenticatorConfigurationScreen.tsx
- portal/src/graphql/portal/BiometricConfigurationScreen.tsx
- portal/src/graphql/portal/CookieLifetimeConfigurationScreen.tsx
- portal/src/graphql/portal/CreateCustomAttributeScreen.tsx
- portal/src/graphql/portal/CreateOAuthClientScreen.tsx
- portal/src/graphql/portal/CustomAttributesConfigurationScreen.tsx
- portal/src/graphql/portal/CustomDomainListScreen.tsx
- portal/src/graphql/portal/EditCustomAttributeScreen.tsx
- portal/src/graphql/portal/EditOAuthClientScreen.tsx
- portal/src/graphql/portal/ForgotPasswordConfigurationScreen.tsx
- portal/src/graphql/portal/GoogleTagManagerConfigurationScreen.tsx
- portal/src/graphql/portal/IntegrationsConfigurationScreen.tsx
- portal/src/graphql/portal/LocalizationConfigurationScreen.tsx
- portal/src/graphql/portal/LoginIDConfigurationScreen.tsx
- portal/src/graphql/portal/PasswordPolicyConfigurationScreen.tsx
- portal/src/graphql/portal/ProjectWizardScreen.tsx
- portal/src/graphql/portal/StandardAttributesConfigurationScreen.tsx
- portal/src/graphql/portal/UISettingsScreen.tsx
- portal/src/graphql/portal/VerificationConfigurationScreen.tsx
- portal/src/hook/useAppConfigForm.ts
- portal/src/locale-data/en.json
> Prevent unreasonable setup in Authenticators screen

- portal/src/graphql/portal/CreateOAuthClientScreen.tsx
- portal/src/graphql/portal/EditOAuthClientScreen.module.css
- portal/src/graphql/portal/EditOAuthClientScreen.tsx
- portal/src/locale-data/en.json
> Show the quickstart list after creating new oauth client

- portal/src/graphql/portal/AnalyticsScreen.module.css
- portal/src/graphql/portal/AnalyticsScreen.tsx
- portal/src/locale-data/en.json
> Add description to analytics page

- portal/src/graphql/adminapi/AuditLogScreen.tsx
- portal/src/graphql/portal/ApplicationsConfigurationScreen.tsx
- portal/src/graphql/portal/AuthenticatorConfigurationScreen.tsx
- portal/src/graphql/portal/BiometricConfigurationScreen.tsx
- portal/src/graphql/portal/CustomDomainListScreen.tsx
- portal/src/graphql/portal/FeatureDisabledMessageBar.tsx
- portal/src/graphql/portal/LoginIDConfigurationScreen.tsx
- portal/src/graphql/portal/PasswordPolicyConfigurationScreen.tsx
- portal/src/graphql/portal/PortalAdminsSettings.tsx
- portal/src/graphql/portal/SingleSignOnConfigurationScreen.tsx
- portal/src/graphql/portal/SingleSignOnConfigurationWidget.tsx
- portal/src/graphql/portal/UISettingsScreen.tsx
- portal/src/graphql/portal/VerificationConfigurationScreen.tsx
- portal/src/graphql/portal/WebhookConfigurationScreen.tsx
> Update feature disabled message bar style

- portal/src/graphql/portal/CreateOAuthClientScreen.tsx
> Fix create oauth client page layout

- portal/src/locale-data/en.json
> Update error message for invalid username format in portal

- portal/src/graphql/portal/PasswordPolicyConfigurationScreen.tsx
> Fix password policy excluded keywords label style when it is disabled

- portal/src/graphql/portal/CreateOAuthClientScreen.tsx
ref https://github.com/authgear/authgear-server/issues/2103#issuecomment-1198986028
> Add default application name

- portal/src/locale-data/en.json
ref https://github.com/authgear/authgear-server/issues/2103#issuecomment-1203423762
> Correct typo in new application screen

- authui/src/passkey.ts
- pkg/auth/handler/webapp/alternatives.go
- pkg/auth/handler/webapp/create_passkey.go
- pkg/auth/handler/webapp/create_password.go
- pkg/auth/handler/webapp/deps.go
- pkg/auth/handler/webapp/enter_password.go
- pkg/auth/handler/webapp/use_passkey.go
- pkg/auth/handler/webapp/viewmodels/alternatives.go
- pkg/auth/routes.go
- pkg/auth/webapp/session_step.go
- pkg/auth/wire_gen.go
- pkg/auth/wire_handler.go
- pkg/lib/interaction/nodes/create_authenticator_begin.go
- pkg/lib/interaction/sort_authenticators.go
- pkg/lib/interaction/sort_authenticators_test.go
- pkg/util/sortutil/sortutil.go
- pkg/util/sortutil/sortutil_test.go
- resources/authgear/templates/en/translation.json
- resources/authgear/templates/en/web/__alternatives.html
- resources/authgear/templates/en/web/create_passkey.html
- resources/authgear/templates/en/web/use_passkey.html
- resources/authgear/templates/zh-HK/translation.json
- resources/authgear/templates/zh-TW/translation.json
> Support passkey with passwordless, and passkey standalone

- authui/src/authgear.ts
- authui/src/form.ts
- authui/src/passkey.ts
- authui/src/tailwind.css
- pkg/auth/handler/webapp/deps.go
- pkg/auth/handler/webapp/interaction.go
- pkg/auth/handler/webapp/prompt_create_passkey.go
- pkg/auth/routes.go
- pkg/auth/webapp/result.go
- pkg/auth/webapp/service2.go
- pkg/auth/webapp/session_step.go
- pkg/auth/wire_gen.go
- pkg/auth/wire_handler.go
- pkg/lib/interaction/intents/authenticate.go
- pkg/lib/interaction/nodes/prompt_create_passkey.go
- resources/authgear/templates/en/translation.json
- resources/authgear/templates/en/web/__page_frame.html
- resources/authgear/templates/en/web/__wide_page_frame.html
- resources/authgear/templates/en/web/login.html
- resources/authgear/templates/en/web/logout.html
- resources/authgear/templates/en/web/promote.html
- resources/authgear/templates/en/web/prompt_create_passkey.html
- resources/authgear/templates/en/web/select_account.html
- resources/authgear/templates/en/web/settings.html
- resources/authgear/templates/en/web/settings_identity.html
- resources/authgear/templates/en/web/settings_recovery_code.html
- resources/authgear/templates/en/web/setup_recovery_code.html
- resources/authgear/templates/en/web/signup.html
- resources/authgear/templates/zh-HK/translation.json
- resources/authgear/templates/zh-TW/translation.json
> Prompt to create passkey if the user does not have one

- .env.example
- README.md
> Update README file

- Makefile
- pkg/lib/web/embedded_resource.go
- pkg/lib/web/embedded_resource_test.go
> Fix too many open files error

- portal/src/CommandBarPrimaryButton.tsx
- portal/src/FormContainer.tsx
- portal/src/graphql/adminapi/UsersScreen.tsx
- portal/src/graphql/portal/ApplicationsConfigurationScreen.module.css
- portal/src/graphql/portal/ApplicationsConfigurationScreen.tsx
- portal/src/graphql/portal/CustomAttributesConfigurationScreen.tsx
- portal/src/graphql/portal/PortalAdminsSettings.tsx
> Change command bar button to primary button style

- portal/src/graphql/portal/FeatureDisabledMessageBar.tsx
> Force the color of link and text to be the same in the billing message bar

- portal/src/graphql/portal/AccountDeletionConfigurationScreen.tsx
- portal/src/graphql/portal/AuthenticatorConfigurationScreen.tsx
- portal/src/graphql/portal/CookieLifetimeConfigurationScreen.tsx
- portal/src/graphql/portal/CreateOAuthClientScreen.tsx
- portal/src/graphql/portal/CustomDomainListScreen.tsx
- portal/src/graphql/portal/ForgotPasswordConfigurationScreen.tsx
- portal/src/graphql/portal/GoogleTagManagerConfigurationScreen.tsx
- portal/src/graphql/portal/LocalizationConfigurationScreen.tsx
- portal/src/graphql/portal/LoginIDConfigurationScreen.tsx
- portal/src/graphql/portal/PasswordPolicyConfigurationScreen.tsx
- portal/src/graphql/portal/UISettingsScreen.tsx
- portal/src/graphql/portal/VerificationConfigurationScreen.tsx
> No remove defaults

- portal/src/graphql/portal/AuthenticatorConfigurationScreen.tsx
- portal/src/graphql/portal/LoginIDConfigurationScreen.tsx
- portal/src/locale-data/en.json
> Disable passkey toggle if login ID is disabled

- pkg/lib/feature/passkey/config_service.go
> Extend passkey support to Android

- .env.example
- cmd/portal/server/config.go
- cmd/portal/server/server.go
- docs/portal/gtm.md
- pkg/portal/config/google_tag_manager.go
- pkg/portal/deps/deps.go
- pkg/portal/deps/providers.go
- pkg/portal/model/system_config.go
- pkg/portal/service/system_config.go
- pkg/portal/wire_gen.go
- portal/package-lock.json
- portal/package.json
- portal/src/AppRoot.tsx
- portal/src/GTMProvider.tsx
- portal/src/ReactApp.tsx
- portal/src/WizardContentLayout.tsx
- portal/src/context/AppContext.ts
- portal/src/graphql/portal/CreateOAuthClientScreen.tsx
- portal/src/graphql/portal/CreateProjectScreen.tsx
- portal/src/graphql/portal/EditOAuthClientScreen.module.css
- portal/src/graphql/portal/EditOAuthClientScreen.tsx
- portal/src/graphql/portal/GetStartedScreen.tsx
- portal/src/graphql/portal/InviteAdminScreen.tsx
- portal/src/graphql/portal/ProjectWizardScreen.tsx
- portal/src/graphql/portal/SingleSignOnConfigurationScreen.tsx
- portal/src/locale-data/en.json
- portal/src/system-config.ts
ref #2206 
WIP:
Identity user in mixpanel will be handled in another PR
Setup:
https://github.com/carmenlau/authgear-server/blob/2206-portal-gtm/docs/portal/gtm.md
> Setup GTM in portal

- authui/src/passkey.ts
- pkg/auth/handler/webapp/viewmodels/base.go
- pkg/lib/interaction/nodes/authn_begin.go
- resources/authgear/templates/en/translation.json
- resources/authgear/templates/en/web/__error.html
- resources/authgear/templates/zh-HK/translation.json
- resources/authgear/templates/zh-TW/translation.json
This PR addresses the scenario 2 of https://github.com/authgear/authgear-server/issues/2320
ref #2320
> Handle passkey not found on Firefox

- pkg/portal/routes.go
> Allow Mixpanel and GTM in the csp script-src

- pkg/util/hexstring/hexstring.go
- pkg/util/hexstring/hexstring_test.go
- pkg/util/web3/eip681.go
- pkg/util/web3/eip681_test.go
reference https://eips.ethereum.org/EIPS/eip-681
an util used by indexer for parsing and creating EIP681 URIs
> Implement Web3 EIP681 util

- authui/src/passkey.ts
> Handle passkey not found error when using Android phone on iOS

- authui/src/authgear.ts
- authui/src/form.ts
- pkg/auth/webapp/result.go
- resources/authgear/templates/en/web/__page_frame.html
- resources/authgear/templates/en/web/__wide_page_frame.html
- resources/authgear/templates/en/web/settings_profile_edit.html
- resources/authgear/templates/en/web/settings_sessions.html
> Do not let Turbo to submit forms

- resources/authgear/templates/en/web/settings.html
> Truncate long text in security item

- portal/src/graphql/adminapi/AuditLogScreen.tsx
> Update last_updated_at if audit logs screen is refreshed

- portal/.eslintrc.json
- portal/src/BlockerDialog.tsx
- portal/src/ButtonWithLoading.tsx
- portal/src/CommandBarPrimaryButton.tsx
- portal/src/EditCustomAttributeForm.tsx
- portal/src/FormContainer.tsx
- portal/src/ImageFilePicker.tsx
- portal/src/ModifiedIndicator.tsx
- portal/src/PrimaryButton.tsx
- portal/src/TodoButtonWrapper.tsx
- portal/src/UserProfileAttributesList.tsx
- portal/src/error/ErrorDialog.tsx
- portal/src/graphql/adminapi/DeleteUserDialog.tsx
- portal/src/graphql/adminapi/EditPictureScreen.tsx
- portal/src/graphql/adminapi/SetUserDisabledDialog.tsx
- portal/src/graphql/adminapi/UserDetailsAccountSecurity.tsx
- portal/src/graphql/adminapi/UserDetailsConnectedIdentities.tsx
- portal/src/graphql/portal/AcceptAdminInvitationScreen.tsx
- portal/src/graphql/portal/AdminAPIConfigurationScreen.tsx
- portal/src/graphql/portal/AppsScreen.tsx
- portal/src/graphql/portal/CreateProjectScreen.tsx
- portal/src/graphql/portal/CustomAttributesConfigurationScreen.tsx
- portal/src/graphql/portal/DateRangeDialog.tsx
- portal/src/graphql/portal/EditOAuthClientScreen.tsx
- portal/src/graphql/portal/ManageLanguageWidget.tsx
- portal/src/graphql/portal/ProjectWizardScreen.tsx
- portal/src/graphql/portal/SMTPConfigurationScreen.tsx
- portal/src/graphql/portal/SubscriptionPlanCard.tsx
- portal/src/graphql/portal/SubscriptionScreen.tsx
- portal/src/graphql/portal/WebhookConfigurationScreen.tsx
> Customize disabled text color of primary button

- portal/src/graphql/portal/EditOAuthClientScreen.tsx
- portal/src/locale-data/en.json
> Update quickstart widget copywriting when the app type is unspecified

- portal/src/locale-data/en.json
> Fix typo in billing screen

- portal/src/graphql/portal/SingleSignOnConfigurationScreen.tsx
- portal/src/locale-data/en.json
> Add whatsapp otp doc link in Portal SSO page

- portal/src/graphql/portal/ApplicationsConfigurationScreen.tsx
- portal/src/graphql/portal/AppsScreen.tsx
- portal/src/graphql/portal/SMTPConfigurationScreen.module.css
> Portal minor ui tweak

- pkg/admin/facade/interaction.go
> Fix failed to create user on portal

- portal/src/CommandBarPrimaryButton.tsx
- portal/src/graphql/adminapi/UserDetailsScreen.tsx
- portal/src/graphql/portal/AnalyticsScreen.tsx
> Fix custom command bar items cause overflow menu miscalculation

- portal/src/ReactApp.module.css
> Fix mobile scrolling behavior

- portal/src/graphql/portal/AppsScreen.module.css
> Fix text overflow in AppsScreen

- portal/src/graphql/portal/EditOAuthClientScreen.tsx
> Add vue tutorial doc link

- portal/src/graphql/portal/EditOAuthClientScreen.tsx
> Add Angular tutorial doc link

- portal/src/ThemePreviewWidget.module.css
- portal/src/ThemePreviewWidget.tsx
> UI setting screen preview mode minor fix

- portal/src/graphql/adminapi/UsersList.module.css
- portal/src/graphql/adminapi/UsersList.tsx
> Truncate long text in the portal user list

- portal/src/graphql/adminapi/AddUserScreen.tsx
- portal/src/locale-data/en.json
> Disable add user screen if passkey is the only primary authenticator

- pkg/lib/facade/coordinator.go
- pkg/lib/interaction/nodes/prompt_create_passkey.go
ref #2391 
In this PR, it fixes:
- Fix failed to promote user as it failed to remove anonymous identity at `NodeDoRemoveIdentity`
- Should not ask the user to create passkey if they login with oauth
- Fix failed to authenticate anonymously when passkey is enabled. As there was an unexpected edge `EdgePromptCreatePasskey` and returned `interaction not completed for anonymous users` error.
> Fix failed to authenticate anonymously and promote anonymous user

- authui/tailwind.config.js
> Safelist OAuth provider type classnames

- pkg/lib/web/image.go
> Fix cast failure of web.languageImage

- portal/src/graphql/adminapi/AuditLogList.module.css
- portal/src/graphql/adminapi/AuditLogList.tsx
- portal/src/graphql/adminapi/UserDetailsSession.tsx
- portal/src/graphql/adminapi/UsersList.module.css
- portal/src/graphql/adminapi/UsersList.tsx
- portal/src/graphql/adminapi/UsersScreen.tsx
- portal/src/locale-data/en.json
> Add empty state to various lists

- portal/src/FormContainer.tsx
- portal/src/ReactApp.tsx
- portal/src/graphql/adminapi/UserDetailsAccountSecurity.tsx
- portal/src/graphql/adminapi/UserDetailsConnectedIdentities.tsx
- portal/src/graphql/adminapi/UserDetailsScreen.tsx
- portal/src/hook/error.tsx
- portal/src/locale-data/en.json
> Add ErrorContext

- portal/src/graphql/portal/EditOAuthClientForm.tsx
> Fix Cookie Session Settings link bug

- portal/src/ChoiceButton.tsx
> Add ChoiceButton

- authui/src/passkey.ts
- authui/src/tailwind-dark-theme.css
- authui/src/tailwind-light-theme.css
- authui/src/tailwind.css
- pkg/auth/handler/webapp/enter_login_id.go
- pkg/auth/handler/webapp/forgot_password.go
- pkg/auth/handler/webapp/login.go
- pkg/auth/handler/webapp/passkey_request_options.go
- pkg/auth/handler/webapp/promote.go
- pkg/auth/handler/webapp/settings.go
- pkg/auth/handler/webapp/settings_identity.go
- pkg/auth/handler/webapp/signup.go
- pkg/auth/handler/webapp/viewmodels/authentication.go
- pkg/auth/handler/webapp/viewmodels/deps.go
- pkg/auth/wire_gen.go
- pkg/lib/feature/passkey/request_options_service.go
- resources/authgear/templates/en/translation.json
- resources/authgear/templates/en/web/__alternatives.html
- resources/authgear/templates/en/web/login.html
- resources/authgear/templates/en/web/use_passkey.html
- resources/authgear/templates/zh-HK/translation.json
- resources/authgear/templates/zh-TW/translation.json
> Add sign in with passkey button

- portal/src/graphql/portal/EditOAuthClientForm.tsx
- portal/src/locale-data/en.json
> Update portal to change oauth client application type uneditable

- cmd/portal/cmd/cmdpricing/stripe_service.go
> Work around Stripe usage record upload problem

- authui/src/passkey.ts
- pkg/auth/handler/webapp/passkey_request_options.go
- resources/authgear/templates/en/web/__alternatives.html
- resources/authgear/templates/en/web/login.html
- resources/authgear/templates/en/web/use_passkey.html
> Specify allowCredentials as a hint to /passkey/request_options

- portal/src/Widget.module.css
- portal/src/Widget.tsx
> Make expand/collapse of Widget more robust

- portal/.eslintrc.json
- portal/src/ExternalLink.tsx
- portal/src/Link.tsx
- portal/src/LinkButton.tsx
- portal/src/OrderButtons.tsx
- portal/src/PriorityList.module.css
- portal/src/PriorityList.tsx
- portal/src/ReactApp.tsx
- portal/src/ScreenHeader.tsx
- portal/src/TextLink.tsx
- portal/src/WidgetWithOrdering.tsx
- portal/src/WizardContentLayout.tsx
- portal/src/graphql/adminapi/AuditLogList.tsx
- portal/src/graphql/portal/AuthenticatorConfigurationScreen.tsx
- portal/src/graphql/portal/EditOAuthClientScreen.tsx
- portal/src/graphql/portal/GetStartedScreen.tsx
- portal/src/graphql/portal/IntegrationsConfigurationScreen.tsx
- portal/src/graphql/portal/LoginIDConfigurationScreen.tsx
- portal/src/graphql/portal/ManageLanguageWidget.tsx
- portal/src/graphql/portal/PhoneInputListWidget.tsx
- portal/src/graphql/portal/SubscriptionCurrentPlanSummary.tsx
- portal/src/graphql/portal/SubscriptionScreen.tsx
- portal/src/locale-data/en.json
> Add PriorityList

- pkg/util/deviceinfo/deviceinfo.go
> Add new Apple devices to deviceinfo mapping list

- README.md
> Add workaround for handling portal timeout issue in development

- portal/src/graphql/adminapi/UserDetailsScreen.tsx
> Fix disable user dialog glitch

- authui/src/passkey.ts
- pkg/auth/handler/webapp/confirm_web3_account.go
- pkg/auth/handler/webapp/enter_login_id.go
- pkg/auth/handler/webapp/forgot_password.go
- pkg/auth/handler/webapp/login.go
- pkg/auth/handler/webapp/promote.go
- pkg/auth/handler/webapp/settings.go
- pkg/auth/handler/webapp/settings_identity.go
- pkg/auth/handler/webapp/signup.go
- pkg/auth/handler/webapp/util.go
- pkg/auth/handler/webapp/viewmodels/authentication.go
- pkg/auth/wire_gen.go
- resources/authgear/templates/en/translation.json
- resources/authgear/templates/en/web/__error.html
- resources/authgear/templates/en/web/login.html
- resources/authgear/templates/en/web/promote.html
- resources/authgear/templates/en/web/signup.html
- resources/authgear/templates/zh-HK/translation.json
- resources/authgear/templates/zh-TW/translation.json
> Handle unsupported empty allowCredentials error

- pkg/lib/interaction/nodes/utils_nodes.go
> Fix nil pointer exception

- portal/src/graphql/portal/EditOAuthClientForm.tsx
- portal/src/graphql/portal/SingleSignOnConfigurationScreen.tsx
> Avoid unstable component

- portal/src/AppRoot.tsx
- portal/src/ScreenNav.tsx
- portal/src/Toggle.tsx
- portal/src/graphql/portal/AuthenticatorConfigurationScreen.tsx
- portal/src/graphql/portal/MFAConfigurationScreen.module.css
- portal/src/graphql/portal/MFAConfigurationScreen.tsx
- portal/src/graphql/portal/PasskeyConfigurationScreen.module.css
- portal/src/graphql/portal/PasskeyConfigurationScreen.tsx
- portal/src/graphql/portal/Web3ConfigurationScreen.tsx
- portal/src/locale-data/en.json
> Add passkey screen and 2FA screen

- portal/src/TextField.tsx
> Fix read-only text field style

- portal/src/locale-data/en.json
> Fix inconsistent statement for symbol in password policy

- cmd/authgear/Dockerfile
- cmd/portal/Dockerfile
- docker-entrypoint.sh
ref #2496
This change needs to be cherry-picked into the hotfix branch.
> Support system-wide self-signed TLS certificate

- pkg/auth/handler/oauth/userinfo.go
- pkg/auth/wire_gen.go
- pkg/lib/config/oauth.go
- pkg/lib/oauth/client_like.go
- pkg/lib/oauth/handler/handler_anonymous_user.go
- pkg/lib/oauth/handler/handler_authz.go
- pkg/lib/oauth/handler/handler_token.go
- pkg/lib/oauth/oidc/id_token.go
- pkg/lib/oauth/oidc/scopes.go
- pkg/lib/oauth/scope.go
> Introduce full-userinfo scope for third party app

- resources/authgear/templates/en/translation.json
- resources/authgear/templates/en/web/confirm_web3_account.html
- resources/authgear/templates/zh-HK/translation.json
- resources/authgear/templates/zh-TW/translation.json
> Guide the user where to change the wallet account

- pkg/api/model/siwe.go
- pkg/lib/authn/identity/siwe/provider.go
- pkg/lib/feature/siwe/service.go
- portal/src/graphql/adminapi/UserDetailSummary.module.css
- portal/src/graphql/adminapi/UserDetailSummary.tsx
- portal/src/graphql/adminapi/UserDetailsConnectedIdentities.module.css
- portal/src/graphql/adminapi/UserDetailsConnectedIdentities.tsx
- portal/src/util/eip681.test.ts
- portal/src/util/eip681.ts
> Make wallet address on portal a link

- .make-lint-expect
- pkg/lib/config/configsource/resources.go
- pkg/lib/config/secret.go
- pkg/lib/config/secret_update_instruction.go
- pkg/lib/config/secret_update_instruction_test.go
- pkg/lib/config/test/config.go
- pkg/lib/config/testdata/secret_update_instruction.yaml
- pkg/portal/appresource/manager_test.go
- pkg/portal/graphql/app_mutation.go
- pkg/portal/model/app.go
- portal/src/graphql/portal/SMTPConfigurationScreen.tsx
- portal/src/graphql/portal/SingleSignOnConfigurationScreen.tsx
- portal/src/graphql/portal/globalTypes.generated.ts
- portal/src/graphql/portal/mutations/updateAppAndSecretMutation.generated.ts
- portal/src/graphql/portal/mutations/updateAppAndSecretMutation.graphql
- portal/src/graphql/portal/mutations/updateAppAndSecretMutation.ts
- portal/src/graphql/portal/schema.graphql
- portal/src/hook/useAppConfigForm.ts
- portal/src/hook/useAppSecretConfigForm.ts
- portal/src/types.ts
> Introduce SecretConfigUpdateInstruction for updating secret config

- cmd/portal/cmd/cmdinternal/migrate_resources_migrate_images_secret.go
- pkg/lib/config/configsource/resources.go
- pkg/lib/config/generate.go
- pkg/lib/config/secret_update_instruction.go
- pkg/lib/config/secret_update_instruction_context.go
- pkg/lib/config/secret_update_instruction_test.go
- pkg/lib/config/testdata/secret_update_instruction.yaml
- pkg/portal/appresource/factory/factory.go
- pkg/portal/appresource/manager.go
- pkg/portal/appresource/manager_test.go
- pkg/portal/graphql/app_mutation.go
- pkg/portal/wire_gen.go
- pkg/util/secrets/generate.go
- pkg/util/secrets/generate_test.go
- portal/src/graphql/portal/CreateOAuthClientScreen.tsx
- portal/src/graphql/portal/EditOAuthClientScreen.tsx
- portal/src/graphql/portal/SMTPConfigurationScreen.tsx
- portal/src/graphql/portal/SingleSignOnConfigurationScreen.tsx
- portal/src/graphql/portal/WebhookConfigurationScreen.tsx
- portal/src/graphql/portal/globalTypes.generated.ts
- portal/src/graphql/portal/schema.graphql
- portal/src/hook/useAppSecretConfigForm.ts
- portal/src/locale-data/en.json
- portal/src/types.ts
Create third party app client via Portal
refs #2485
> Configure third party app in the portal part 2

- pkg/auth/handler/oauth/from_webapp.go
- pkg/auth/webapp/login_hint.go
- pkg/auth/webapp/url_provider.go
- pkg/auth/wire_gen.go
- pkg/lib/deps/deps_common.go
- pkg/lib/oauth/handler/handler_authz.go
- pkg/lib/oauth/handler/handler_authz_test.go
- pkg/lib/oauth/handler/mock_test.go
- pkg/lib/oauth/oauthsession/cookie.go
- pkg/lib/oauth/oauthsession/deps.go
- pkg/lib/oauth/oauthsession/error.go
- pkg/lib/oauth/oauthsession/model.go
- pkg/lib/oauth/oauthsession/store_redis.go
- pkg/lib/oauth/url_provider.go
> Refactor to store authz request to OAuthSession instead of passing it through query parameters

- pkg/auth/handler/webapp/viewmodels/settings_profile.go
- pkg/lib/authn/authenticator/info.go
- pkg/lib/authn/identity/info.go
- pkg/lib/authn/identity/service/service.go
- pkg/lib/authn/stdattrs/model.go
- pkg/lib/elasticsearch/service.go
- pkg/lib/facade/coordinator.go
- pkg/lib/feature/forgotpassword/provider.go
- pkg/lib/feature/stdattrs/service.go
- pkg/lib/feature/stdattrs/service_noevent.go
- pkg/lib/feature/verification/service.go
- pkg/lib/feature/welcomemessage/provider.go
> Fix standard attributes not populated at sign up

- pkg/auth/handler/webapp/confirm_web3_account.go
- pkg/auth/handler/webapp/missing_web3_wallet.go
- pkg/auth/wire_gen.go
- resources/authgear/templates/en/web/missing_web3_wallet.html
> Safe-guard web3 pages when SIWE is not enabled

- pkg/api/model/web3.go
- portal/src/graphql/adminapi/NFTCollectionDetailDialog.tsx
- portal/src/graphql/adminapi/UserDetailSummary.module.css
- portal/src/graphql/adminapi/UserDetailSummary.tsx
- portal/src/graphql/adminapi/UserDetailsConnectedIdentities.tsx
- portal/src/graphql/portal/Web3ConfigurationConfirmationDialog.tsx
- portal/src/graphql/portal/Web3ConfigurationDetailDialog.tsx
- portal/src/locale-data/en.json
- portal/src/util/eip681.test.ts
- portal/src/util/eip681.ts
- portal/src/util/networkId.ts
~~TODO: Handle https://github.com/authgear/authgear-server/issues/2453~~
refs #2488  #2511  #2528
> Add support to Polygon networks

- authui/src/tailwind.css
- resources/authgear/templates/en/translation.json
- resources/authgear/templates/en/web/consent.html
> Fix consent screen style

- pkg/lib/oauth/handler/handler_authz.go
> Handle authentication info expired when visiting consent screen

- pkg/api/model/web3.go
- pkg/portal/graphql/web3.go
- portal/src/graphql/portal/Web3ConfigurationAddCollectionForm.tsx
- portal/src/graphql/portal/Web3ConfigurationDetailDialog.tsx
- portal/src/graphql/portal/globalTypes.generated.ts
- portal/src/graphql/portal/mutations/watchNFTCollectionsMutation.generated.ts
- portal/src/graphql/portal/query/nftCollectionsQuery.generated.ts
- portal/src/graphql/portal/query/nftContractMetadataQuery.generated.ts
- portal/src/graphql/portal/schema.graphql
wait for authgear/authgear-nft-indexer#27
refs #2512
> Make NFTCollection total supply nullable

- pkg/admin/deps.go
- pkg/admin/facade/authorization.go
- pkg/admin/facade/deps.go
- pkg/admin/graphql/authorization.go
- pkg/admin/graphql/authorization_mutation.go
- pkg/admin/graphql/context.go
- pkg/admin/graphql/user.go
- pkg/admin/wire_gen.go
- pkg/api/model/authorization.go
- pkg/auth/handler/webapp/settings_sessions.go
- pkg/lib/oauth/authz.go
- pkg/lib/oauth/authz_filters.go
- portal/src/graphql/adminapi/UserDetailsAuthorization.module.css
- portal/src/graphql/adminapi/UserDetailsAuthorization.tsx
- portal/src/graphql/adminapi/UserDetailsScreen.tsx
- portal/src/graphql/adminapi/UserDetailsSession.tsx
- portal/src/graphql/adminapi/globalTypes.generated.ts
- portal/src/graphql/adminapi/mutations/deleteAuthorization.generated.ts
- portal/src/graphql/adminapi/mutations/deleteAuthorization.graphql
- portal/src/graphql/adminapi/mutations/deleteAuthorizationMutation.ts
- portal/src/graphql/adminapi/query/auditLogEntryQuery.generated.ts
- portal/src/graphql/adminapi/query/userQuery.generated.ts
- portal/src/graphql/adminapi/query/userQuery.graphql
- portal/src/graphql/adminapi/schema.graphql
- portal/src/locale-data/en.json
- portal/src/types.ts
> Manage authorized app list via the portal and admin api

- pkg/lib/oauth/handler/handler_token.go
- pkg/lib/oauth/handler/service.go
> Issue access token if the client is 3rd party and no offline_access

- pkg/portal/model/app.go
- pkg/portal/service/app.go
- portal/src/TextFieldWithButton.module.css
- portal/src/TextFieldWithButton.tsx
- portal/src/graphql/portal/EditOAuthClientForm.tsx
> Show client secret only when it is newly created or after re-auth

- portal/src/graphql/portal/EditOAuthClientForm.tsx
- portal/src/graphql/portal/EditOAuthClientScreen.tsx
- portal/src/locale-data/en.json
ref #2410 
TBC: https://github.com/authgear/authgear-server/issues/2410#issuecomment-1270358082
> Show OIDC endpoints in portal oauth client page for 3rd party app

- resources/authgear/templates/en/web/fatal_error.html
> Add handling for empty error page

- cmd/portal/cmd/cmdinternal/migrate_resources_migrate_toc_pp_footer.go
- pkg/auth/handler/webapp/template.go
- pkg/portal/service/app.go
- resources/authgear/templates/en/translation.json
- resources/authgear/templates/en/web/__toc_pp_footer.html
- resources/authgear/templates/en/web/login.html
- resources/authgear/templates/en/web/promote.html
- resources/authgear/templates/en/web/signup.html
- resources/authgear/templates/zh-HK/translation.json
- resources/authgear/templates/zh-TW/translation.json
> [Breaking Change] Add default value to Privacy Policy Link and Terms of Service Link

- pkg/util/httputil/content_type.go
- pkg/util/httputil/content_type_test.go
> Allow content-type to have valid charset specified

- pkg/lib/authn/sso/azureadb2c.go
> Recognize signInNames.emailAddress

- portal/src/index.tsx
> Turn off auto freeze

- resources/authgear/templates/en/translation.json
- resources/authgear/templates/en/web/settings.html
- resources/authgear/templates/en/web/settings_identity.html
> Update settings page identity section description

- portal/src/graphql/portal/Web3ConfigurationScreen.tsx
> Switch back to email + password when SIWE is turned off

- cmd/authgear/cmd/cmdinit/init.go
- cmd/authgear/cmd/cobraviper.go
- cmd/authgear/config/errors.go
- cmd/authgear/config/marshal.go
- cmd/authgear/config/options.go
- pkg/lib/config/generate.go
> Update `authgear init` to make it deployment friendly

- .make-lint-expect
- pkg/api/model/siwe.go
- pkg/api/model/web3.go
- pkg/lib/authn/identity/info.go
- pkg/lib/authn/identity/service/service.go
- pkg/lib/authn/identity/siwe/provider.go
- pkg/lib/authn/identity/siwe/store.go
- pkg/lib/authn/identity/siwe_identity.go
- pkg/lib/feature/siwe/service.go
- pkg/lib/feature/web3/service.go
- pkg/util/web3/contractid.go
- pkg/util/web3/contractid_test.go
- pkg/util/web3/eip55.go
- pkg/util/web3/eip55_test.go
- pkg/util/web3/eip681.go
- pkg/util/web3/eip681_test.go
> Align ethereum address format to use EIP-55 in front end level

- portal/src/graphql/adminapi/UserDetailsConnectedIdentities.module.css
- portal/src/graphql/adminapi/UserDetailsConnectedIdentities.tsx
> Align remove button to the right in UserDetailsIdentities page

- portal/src/graphql/adminapi/UserDetailsConnectedIdentities.module.css
- portal/src/graphql/adminapi/UserDetailsConnectedIdentities.tsx
> Hide add identity for users with SIWE identity

- portal/src/error/error.ts
- portal/src/graphql/portal/Web3ConfigurationAddCollectionSection.tsx
- portal/src/graphql/portal/Web3ConfigurationScreen.tsx
- portal/src/locale-data/en.json
needs authgear/authgear-nft-indexer#36
solves #2584
> Display service unavailable error accordingly if returned from indexer

- pkg/lib/interaction/nodes/prompt_create_passkey.go
> Prompt create passkey only when the identity being used is compatible

- .env.example
- README.md
- go.mod
- pkg/lib/config/database_env.go
- pkg/util/log/factory.go
- pkg/util/log/writer_hook.go
fix #2553 
fix #1724 
fix #2092
> Increase default pool size

- pkg/lib/authn/identity/biometric_identity.go
- pkg/lib/authn/identity/service/service.go
- pkg/lib/facade/coordinator.go
- pkg/util/deviceinfo/deviceinfo.go
- pkg/util/deviceinfo/deviceinfo_test.go
> Remove biometric

- cmd/authgear/config/options.go
> Fix incorrect audit db schema data type in the init command

- pkg/portal/graphql/app.go
- pkg/portal/graphql/billing_mutation.go
- pkg/portal/graphql/context.go
- pkg/portal/graphql/scalars.go
- pkg/portal/libstripe/error.go
- pkg/portal/libstripe/event_model.go
- pkg/portal/libstripe/service.go
- pkg/portal/model/subscription.go
- pkg/portal/service/subscription.go
- pkg/portal/transport/stripe_webhook_handler.go
- portal/graphql.portal.codegen.yaml
- portal/package-lock.json
- portal/package.json
- portal/src/graphql.d.ts
- portal/src/graphql/portal/globalTypes.generated.ts
- portal/src/graphql/portal/schema.graphql
> Handle stuck incomplete subscription

- portal/src/graphql/portal/SubscriptionCurrentPlanSummary.module.css
- portal/src/graphql/portal/SubscriptionCurrentPlanSummary.tsx
> Fix portal billing page layout

- cmd/portal/cmd/cmdinternal/migrate_resources_remove_is_first_party.go
- pkg/lib/config/oauth.go
> Remove legacy is_first_party flag from the OAuth config

- pkg/admin/graphql/user.go
- portal/src/graphql/adminapi/globalTypes.generated.ts
- portal/src/graphql/adminapi/schema.graphql
> Add description to user's fields in admin api

- portal/src/error/error.ts
- portal/src/error/parse.ts
- portal/src/error/web3.ts
- portal/src/locale-data/en.json
> Handle AlchemyProtocol error
