authgear/authgear-server

.github/workflows/ci.yaml
This job requires credentials which are not available in forked repo.
=> Skip running image job in forked repo

pkg/auth/dependency/webapp/csrf_middleware.go, pkg/core/samesite/incompatible.go, pkg/core/samesite/incompatible_test.go
=> Do not send SameSite=None if Secure attribute is absent

cmd/authgear/server/server.go, cmd/authgear/server/wire.go, cmd/authgear/server/wire_gen.go, go.mod, go.sum, pkg/admin/routes.go, pkg/auth/routes.go, pkg/lib/config/config.go, pkg/lib/config/server.go, pkg/lib/config/source/constants.go, pkg/lib/config/source/deps.go, pkg/lib/config/source/local_file.go, pkg/lib/config/source/local_fs.go, pkg/lib/config/source/source.go, pkg/lib/deps/middleware_request.go, pkg/lib/deps/template.go, pkg/resolver/routes.go, pkg/util/template/file_loader.go, pkg/util/template/resolver.go, pkg/util/template/uri_loader.go
@louischan-oursky 
As discussed previously, we would like to refactor `ProvideConfig` into `ResolveAppIDByRequest` and `ResolveConfigByAppID` functions. However, I realized that resolving app ID depends on the host-appID mapping, which is strongly coupled with resolving config logic. Therefore I suppose we should keep it as-is for now.
ref #169
=> Hot-reload local configuration files

.gitignore, cmd/authgear/config/config.go, cmd/authgear/config/options.go, cmd/authgear/config/prompt.go, docker-compose.yaml, go.mod, go.sum, pkg/lib/config/secret_data.go, pkg/lib/config/testdata/parse_secret_tests.yaml, pkg/lib/infra/redis/pool.go
TLS can be used using `rediss://localhost`. (note the double s)
fix #193
=> Use URL for Redis connection credentials

portal/src/ExtendableWidget.module.scss
Closes #298 
as it rotates when the arrow rotate
=> Remove extenable widget hover hightlight

portal/src/graphql/adminapi/UserDetailsAccountSecurity.tsx, portal/src/graphql/adminapi/mutations/__generated__/DeleteAuthenticatorMutation.ts, portal/src/graphql/adminapi/mutations/deleteAuthenticatorMutation.ts, portal/src/locale-data/en.json, portal/src/util/error.ts, portal/src/util/validation.ts
Closes #370 
TODO: 
- handle error from backend
- get unknown error from backend
- can only add 1 secondary authenticator during setup, cannot test for error
get following error from backend
```json
{
"data": null,
"errors": [
{
"message": "reflect: call of reflect.Value.Type on zero Value",
"locations": [
{
"line": 2,
"column": 3
}
],
"path": [
"deleteAuthenticator"
]
}
]
}
```
=> [Portal] Integrate delete authenticator mutation

portal/src/graphql/adminapi/UserDetailsScreen.tsx, portal/src/graphql/portal/AuthenticationAuthenticatorSettings.tsx, portal/src/graphql/portal/AuthenticationConfigurationScreen.tsx, portal/src/graphql/portal/ForgotPasswordSettings.tsx, portal/src/graphql/portal/PasswordPolicySettings.tsx, portal/src/graphql/portal/PasswordsScreen.tsx, portal/src/hook/usePivot.ts
fix #333 
- use url fragment (hash) to control pivot
- change tab => navigation => can use NavigationBlockerDialog to block
- avoid unnecessary useRef, useEffect to handle warn user on change tab
- fix password screen not warning user when leaving page with dirty form
=> Warn user on change tab with dirty form

portal/src/graphql/portal/PasswordPolicySettings.tsx, portal/src/util/misc.ts
parseInt("", 10) = NaN, NaN is not valid number in authgear config, leads to unhandled error
=> Fix leaving min length field empty in password policy page unhandled error

portal/src/graphql/portal/CreateOAuthClientScreen.tsx, portal/src/graphql/portal/ModifyOAuthClientForm.tsx
Object without field post_logout_redirect_uris and having
post_logout_redirect_uris = undefined is not equal, null coalescing to
empty array to fix this
=> Fix edit client form dirty after save

migrations/portal/20201015122924-add-unique-to-collaborator-invitation-code.sql, pkg/portal/deps.go, pkg/portal/graphql/app.go, pkg/portal/graphql/app_mutation.go, pkg/portal/graphql/collaborator.go, pkg/portal/graphql/collaborator_mutation.go, pkg/portal/graphql/context.go, pkg/portal/graphql/domain_mutation.go, pkg/portal/loader/app.go, pkg/portal/loader/authz.go, pkg/portal/loader/collaborator.go, pkg/portal/loader/domain.go, pkg/portal/model/collaborator.go, pkg/portal/service/authz.go, pkg/portal/service/collaborator.go, pkg/portal/wire_gen.go, pkg/util/graphqlutil/lazy.go, portal/src/graphql/portal/schema.graphql
fix #433 
There are two remaining FIXMEs
- Send the invitation email. I am going to reuse the template mechanism from pkg/lib. The problem is where to store the default template. Storing it in templates/ seems a bit inappropriate because it is a place for authgear.
- Able to call Admin API of `accounts`.
=> Portal access control - Part 2

portal/src/graphql/portal/DNSConfigurationScreen.tsx, portal/src/graphql/portal/mutations/__generated__/DeleteDomainMutation.ts, portal/src/graphql/portal/mutations/deleteDomainMutation.ts
fix #538 
Cause:
If domain in config is not included in verified domains (domains in DB with
isVerified = true), it will trigger useEffect on mount, firing mutation. If default domain
(non-custom verified domain) is not found, mutation fails as public
origin is required field
Fix:
Move update config to screen, check if domain in config is included in
verified domain only after delete domain mutation instead of useEffect.
Public origin section only observe public origin in config, will reset
dropdown state if config is changed (after delete domain)
=> Fix DNS screen firing unexpected mutation

portal/src/ExtendableWidget.tsx, portal/src/graphql/portal/SingleSignOnConfigurationWidget.tsx
To avoid text field in enabled single sign on widget not mounted (hence cannot consume
validation error), force widget to be extended if enabled. extend on
enabled, collapse on disabled
=> Modify extendable widget behaviour

portal/src/hook/usePivot.ts
fix https://github.com/authgear/authgear-deploy/issues/28
Cause:
This is caused by redirection if the fragment (hash) is not valid (each tab has a key, selected tab specified by fragment), as this affects the history, for example:
`previous page` -> `/app/:appID/configuration/authentication` -> `/app/:appID/configuration/authentication#login-id`
So back button has no effect, including the confirm button in navigation blocker dialog.
Fix:
Use `replaceState` to avoid pushing to history stack
=> Fix back button no response in page with tab

pkg/util/blocklist/blocklist.go, pkg/util/blocklist/blocklist_test.go
=> Treat plaintext blocklist entry as anchored pattern

pkg/portal/graphql/app.go, portal/src/AppRoot.tsx
fix https://github.com/authgear/authgear-deploy/issues/32
Motivation:
- Avoid error like unhandled forbidden error
- App ID which has valid base64 encoding but not valid UTF8 encoding for Postgres
- App ID with incorrect encoding leads to empty response without error
=> Add error handling for invalid app ID

portal/src/graphql/portal/SingleSignOnConfigurationScreen.tsx
fix #663 
Cause:
In effective app config, an extra field "claims" is added to oauth provider in
/identity/oauth/providers. We use the app config directly as our screen
state.
When new provider is added, only the fields appear on portal sso screen is added to state,
so getting initial state after save from effective app config will get extra field.
Fix:
use raw app config for initial screen state.
=> Fix SSO screen modified indicator not cleared after save

pkg/auth/handler/webapp/verify_identity.go
fix #643 
Mask phone number for change phone number verification screen
such that it is consistent with screen for verify phone number for
adding secondary sms authenticator
=> Fix inconsistent masking of phone number

pkg/auth/handler/webapp/enter_login_id.go
fix https://github.com/authgear/authgear-deploy/issues/40
Add new rule to `enterLoginIDSchema` which requires `x_national_number` if
`login_id_key` is phone
=> Fix missing validation for login ID form

portal/src/graphql/portal/AuthenticationCountryCallingCodeList.module.scss, portal/src/graphql/portal/AuthenticationCountryCallingCodeList.tsx
fix #646
It seem to be fluent ui bug and not yet fixed (https://github.com/microsoft/fluentui/issues/3608).
The unnecessary horizontal scrollbar appears in DetailsList as it has `overflow-x: auto` style. So I simply added `overflow-x: hidden` to hide horizontal scrollbar. (I have tried setting `overflow-x: visible` to DetailsList, but the horizontal scrollbar would appears in scrollable pane.)
=> Fix horizontal scrollbar appears in country code list on windows browser

portal/src/ScreenHeader.tsx, portal/src/graphql/portal/AppsScreen.tsx, portal/src/types.ts
refs #780 
In the issue, the design shows the app id and name, but we don't have the concept of app name. So we showed the encoded app id and the origin. 
I updated to show the decoded app id and kept displaying the app origin, it doesn't look nice actually. Maybe we could consider to show the app id only in the app list?
=> Display decoded app id in app list and header

pkg/auth/deps.go, pkg/auth/handler/webapp/alternatives.go, pkg/auth/handler/webapp/controller.go, pkg/auth/handler/webapp/deps.go, pkg/auth/handler/webapp/return.go, pkg/auth/handler/webapp/verify_identity.go, pkg/auth/routes.go, pkg/auth/webapp/service2.go, pkg/auth/webapp/session_step.go, pkg/auth/wire_gen.go, pkg/auth/wire_handler.go, pkg/lib/feature/verification/code.go, pkg/lib/feature/verification/service.go, pkg/lib/interaction/context.go, pkg/lib/interaction/nodes/ensure_verification.go, pkg/lib/interaction/nodes/use_identity_oauth_provider.go, pkg/lib/interaction/nodes/use_identity_oauth_user_info.go, pkg/lib/interaction/nodes/verify_identity.go, pkg/lib/interaction/service.go, resources/authgear/templates/en/translation.json, resources/authgear/templates/en/web/return.html, resources/authgear/templates/en/web/verify_identity.html
This is the first part of #763. The user has to refresh the page manually to have the code filled in in the original user agent. The next PR will implement a websocket protocol between the server and the client to avoid manual refreshing.
=> Handle verification email being opened in another user agent

authui/src/authgear.css, pkg/admin/web_endpoints.go, pkg/auth/deps.go, pkg/auth/handler/webapp/publisher.go, pkg/auth/handler/webapp/viewmodels/base.go, pkg/auth/handler/webapp/websocket.go, pkg/auth/handler/webapp/wechat_auth.go, pkg/auth/handler/webapp/wechat_callback.go, pkg/auth/routes.go, pkg/auth/webapp/session.go, pkg/auth/webapp/session_step.go, pkg/auth/webapp/url_provider.go, pkg/auth/webapp/wechat_url_provider.go, pkg/auth/wire_gen.go, pkg/lib/authn/sso/wechat.go, pkg/lib/oauth/handler/handler_authz.go, pkg/lib/oauth/protocol/authz.go, resources/authgear/templates/en/translation.json, resources/authgear/templates/en/web/wechat_auth.html
refs #773 
Updates:
- Publish `WeChatLoginStart` evnt in wechat auth endpoint
- Change wechat endpoints to `/sso/wechat/auth/:alias` and `/sso/wechat/callback`
- Support `x_ws_channel_id` parameter in authorize endpoint, allow sdk specify websocket channel id
- Support `x_sdk` in authorize endpoint
- Updated `/sso/wechat/callback` to support api call from sdk
=> Publish WeChatLoginStart event for SDK integration

authui/src/authgear.css, authui/src/authgear.ts, pkg/admin/web_endpoints.go, pkg/auth/deps.go, pkg/auth/handler/webapp/viewmodels/base.go, pkg/auth/handler/webapp/wechat_auth.go, pkg/auth/handler/webapp/wechat_callback.go, pkg/auth/routes.go, pkg/auth/webapp/session.go, pkg/auth/webapp/session_step.go, pkg/auth/webapp/url_provider.go, pkg/auth/webapp/wechat_url_provider.go, pkg/auth/wire_gen.go, pkg/lib/authn/sso/wechat.go, pkg/lib/config/oauth.go, pkg/lib/oauth/handler/handler_authz.go, pkg/lib/oauth/handler/wechat.go, pkg/lib/oauth/protocol/authz.go, resources/authgear/templates/en/translation.json, resources/authgear/templates/en/web/wechat_auth.html
refs #773 
- Add `wechat_redirect_uris` in oauth client config and `wechat_redirect_uri` parameters in authorize endpoint
- Show "open wechat app" link which will go to `wechat_redirect_uri` for mobile integration, after clicking the link, the link will change to refresh page link
- Update wechat endpoints to `/sso/wechat/auth/:alias` and `/sso/wechat/callback`
=> Support open wechat redirect uri and wechat auth page for mobile integration

pkg/auth/handler/webapp/settings_mfa.go, pkg/lib/authn/mfa/service.go, pkg/lib/authn/mfa/store_device_token_redis.go, pkg/lib/interaction/nodes/authn_begin.go, resources/authgear/static/authgear-dark-theme.css, resources/authgear/static/authgear-light-theme.css, resources/authgear/templates/en/translation.json, resources/authgear/templates/en/web/enter_oob_otp.html, resources/authgear/templates/en/web/logout.html, resources/authgear/templates/en/web/settings.html, resources/authgear/templates/en/web/settings_mfa.html, resources/authgear/templates/en/web/settings_recovery_code.html, resources/authgear/templates/en/web/verify_identity.html
refs #914 
- At `/settings`
- Move "Click here to sign up" from the top to bottom with "Log out"
- At `/settings/mfa`
- "Forget all trusted devices" => "Forgot all trusted devices that could skip MFA", and give a feedback when this button is clicked.
- When there are no MFA configured, change "Details" to "Configure"
- At `enter_oob_otp `
- The "Didn't receive the code?" text size is abnormal (should be same or smaller then content font size)
- The "Resend" text countdown is grey and impossible to read.
=> Fix setting page ux issue

pkg/auth/handler/webapp/settings.go, pkg/auth/wire_gen.go, resources/authgear/templates/en/web/settings.html
refs #914 
The logout page is designed for linkable from outside Authgear, so we could
skip the logout page within the Authgear.
=> Logout from setting page directly

pkg/auth/handler/webapp/controller.go
=> Redirect X-Authgear-XHR request to same path to display invalid session error

pkg/auth/webapp/service2.go, resources/authgear/templates/en/translation.json, resources/authgear/templates/en/web/__error.html
fix authgear/authgear-sdk-js#64
The error will be shown in this way. Only `Operation is not allowed.` can be translated and `Webhook defined error` is the reason returned from the webhook.
=> Do not redirect if interaction is aborted by webhook 

pkg/auth/webapp/service2.go, pkg/lib/feature/forgotpassword/provider.go, pkg/lib/feature/forgotpassword/ratelimit.go, pkg/lib/feature/verification/ratelimit.go, pkg/lib/feature/verification/service.go, pkg/lib/interaction/context.go, pkg/lib/interaction/nodes/do_create_user.go, resources/authgear/templates/en/translation.json, resources/authgear/templates/en/web/__error.html
depends on #1027 
fix #1019 
- Fix incorrect timing for signup rate limit
- Remove `verification-generate-code` rate limit which is bounded by `verification-send-code` rate limit
- Rename and update `reset-password-send-code` rate limit
=> Rate limit issue

docs/specs/user-model.md, pkg/lib/config/testdata/default_config.yaml
ref #906 
Louis reminded me that we should avoid using the terms blacklist / whitelist, update the spec and config for that.
=> Rename email domain blocklist and allowlist in spec

portal/src/graphql/portal/CustomDomainListScreen.tsx, portal/src/graphql/portal/LocalizationConfigurationScreen.tsx, portal/src/graphql/portal/LoginIDConfigurationScreen.tsx, portal/src/graphql/portal/UISettingsScreen.tsx, portal/src/hook/useAppConfigForm.ts, portal/src/hook/useResourceForm.ts
Update saving config and templates one by one
Both api will update k8s secret, if we call them at the same time, the
second call may be failed, due to the secret version is updated in the
first call.
ref #1109
=> Fix failed to perform action that saves config and templates at the same time in portal

cmd/authgear/server/server.go, cmd/authgear/server/wire.go, cmd/authgear/server/wire_gen.go, cmd/portal/server/server.go, cmd/portal/server/wire.go, cmd/portal/server/wire_gen.go, migrations/portal/20210415115311-add_config_source.sql, migrations/portal/20210416193011-add_config_source_and_domain_trigger.sql, nginx.conf, pkg/lib/config/configsource/config.go, pkg/lib/config/configsource/database.go, pkg/lib/config/configsource/deps.go, pkg/lib/config/configsource/errors.go, pkg/lib/config/configsource/source.go, pkg/lib/config/configsource/store.go, pkg/lib/deps/deps_provider.go, pkg/lib/deps/providers.go, pkg/lib/infra/db/global/deps.go, pkg/lib/infra/db/listener.go, pkg/portal/service/config.go
ref #1127 
Initial draft for review only, not fully working
Done
- Basic ResolveAppID from db
- ResolveContext from db
- UpdateResources from db
- CreateResources from db
- Support cache
- Update portal nginx config to have correct host header when calling resolve endpoint
Todo
- TBD: Add `APP_HOST_SUFFIX` config and use it in ResolveAppID
- Command to setup first `accounts` app
=> Support database config source

README.md, cmd/authgear/init.go, cmd/authgear/main.go, cmd/authgear/migrate.go, cmd/portal/db.go, cmd/portal/internal.go, cmd/portal/internal/db.go, cmd/portal/internal/setup_portal.go, cmd/portal/main.go, cmd/portal/migrate.go
require #1140 
refs #1127 
To be discussed:
- I added the command to `./cmd/portal` instead of `./cmd/auth`, seems more appropriate. 
- After implementing it, I found the arguments `default-domain` and `custom-domain` looks like domains of portal, maybe rename to `default-auth-domain` and `custom-auth-domain` are better?
=> Add command to setup db config source for portal

cmd/authgear/elasticsearch/reindex.go, cmd/authgear/elasticsearch/wire_gen.go
I discovered this bug when I attempted to run the reindex command against staging deployment. After a few iterations, the connection limit reached and the command failed.
=> Fix reindex command create new connection for each app

pkg/lib/interaction/nodes/do_update_identity.go
=> Fix old_identity and new_identity payload are swapped in login id update event

pkg/auth/routes.go
To solve the problem of the inline script doesn't work in the authorization
endpoint response.
ref #1203
=> Update to apply Content Security Policy to web app pages only

pkg/auth/webapp/deps.go, pkg/auth/webapp/public_origin_middleware.go, pkg/auth/wire_gen.go, pkg/lib/deps/middleware_request.go, pkg/lib/infra/middleware/cors.go, pkg/lib/infra/middleware/cors_test.go, pkg/lib/infra/middleware/deps.go, pkg/lib/session/deps.go, pkg/lib/session/middleware.go, pkg/resolver/wire_gen.go
We encountered a problem in staging server that the server returns http 200 with empty body for all routes, so we suspect the middleware early exit without calling next for some cases. Adding more logs for diagnostic.
=> Add middleware logs for diagnostic

pkg/auth/deps.go, pkg/auth/handler/webapp/controller.go, pkg/auth/handler/webapp/deps.go, pkg/auth/handler/webapp/identity.go, pkg/auth/handler/webapp/identity_test.go, pkg/auth/handler/webapp/root.go, pkg/auth/handler/webapp/select_account.go, pkg/auth/routes.go, pkg/auth/webapp/auth_entry_point_middleware.go, pkg/auth/webapp/service2.go, pkg/auth/wire_gen.go, pkg/auth/wire_handler.go, pkg/lib/oauth/handler/handler_authz.go, pkg/lib/oauth/handler/handler_authz_test.go, resources/authgear/static/authgear.css, resources/authgear/templates/en/translation.json, resources/authgear/templates/en/web/select_account.html, resources/authgear/templates/zh-HK/translation.json, resources/authgear/templates/zh-TW/translation.json
=> Support continue or use another account when triggering authentication

cmd/portal/plan/service.go, cmd/portal/pricing.go
To avoid storing empty struct key to the yaml and json, we should store
the raw feature config rather than the result of ParseFeatureConfig.
Since the function will populate the struct to avoid nil pointer in the
feature config object.
=> Store raw feature config to the database

pkg/lib/config/authentication.go, pkg/lib/config/testdata/default_config.yaml, portal/src/graphql/portal/OnboardingConfigAppScreen.module.scss, portal/src/graphql/portal/OnboardingConfigAppScreen.tsx, portal/src/locale-data/en.json
Update onboarding to disable sms feature with upgrade button
To test this, you will need to add `./vars/authgear.features.yaml` with the following content.
```
identity:
login_id:
types:
phone:
disabled: true
authentication:
secondary_authenticators:
oob_otp_sms:
disabled: true
```
=> Update onboarding to disable sms feature with upgrade button

pkg/auth/webapp/session.go, pkg/auth/webapp/session_store.go
fix #1207 
We updated to accept prompt list in the authz endpoint and the legacy
prompt data migration is no longer needed after the prompt list update
is deployed.
=> Remove LegacyPrompt parameter

pkg/lib/ratelimit/storage_redis.go, pkg/util/httputil/cookie.go
=> Ensure time.Unix() calls are followed by UTC()

resources/authgear/templates/en/web/settings.html
Ref #1061
Not only should unset OAuth values be hidden, but also any unset identity.
=> Hide unset value instead of just unset oauth value

pkg/lib/analytic/store_redis.go
=> Correct analytic redis keys to have date in correct ISO 8601 format

pkg/lib/interaction/intents/add_identity.go, pkg/lib/interaction/nodes/do_create_identity.go, pkg/lib/interaction/nodes/ensure_remove_anonymous_identity.go, portal/src/graphql/adminapi/AddIdentityForm.tsx, portal/src/graphql/adminapi/UserDetailsConnectedIdentities.tsx, portal/src/locale-data/en.json
fix #1762 
- Remove anonymous identity when admin add identity to anonymous user 
- Trigger promote non-blocking event
- Fix not able to add email / phone through portal in the follow scenarios
- when OOB OTP is disabled 
- when OOB OTP is enabled but priority is lower than password
=> Fix admin adding identity to anonymous user

pkg/lib/config/authentication.go, pkg/lib/config/config.go, pkg/lib/config/testdata/config_tests.yaml, pkg/lib/interaction/nodes/authn_begin.go, portal/src/error/parse.ts, portal/src/error/validation.ts, portal/src/graphql/portal/AuthenticatorConfigurationScreen.tsx, portal/src/graphql/portal/OnboardingConfigAppScreen.tsx, portal/src/locale-data/en.json, portal/src/types.ts
ref #1705 
Should merge and deploy after #1751
When deploying this change, should re-run migration script in #1751 to ensure all configs don't have deprecated options
=> [Migration needed] Remove deprecate `if_requested` secondary authentication mode

portal/src/util/jsonpointer.test.ts, portal/src/util/jsonpointer.ts
To fix the portal crash when typing characters which need to be escaped in the custom attribute name
=> Fix parseJSONPointer with escape character

pkg/util/template/func.go, pkg/util/template/func_test.go, resources/authgear/templates/en/web/settings_profile.html, resources/authgear/templates/en/web/settings_profile_edit.html
=> Fix showing large number incorrectly in scientific notation for custom attribute

portal/src/graphql/adminapi/UserProfileForm.tsx
refs #1789 
Submit the current input even it is invalid for phone number input
So that the admin api server can validate the phone value and show the
error on portal, submitting empty value will cause removing the custom
attribute value.
=> Fix missing error message when inputting invalid phone number in portal

portal/src/error/error.ts, portal/src/error/parse.ts, portal/src/graphql/portal/UISettingsScreen.tsx, portal/src/locale-data/en.json
refs #1786 
When user uploads a large app icon, the request may be blocked by the load
balancer with 413 error code. Show "file is too large" error message
for this case.
=> Show generic error message when the request is too large

pkg/auth/handler/webapp/account_status.go, pkg/auth/handler/webapp/controller.go, resources/authgear/templates/en/web/__error.html
refs #1814 
- After user login an invalid account and see the account status page, complete the interaction so that user won't be able to click the browser back and resubmit again
- When there is an unexpected error in the interaction, redirect to `/error` if the original request is a `GET` request to avoid infinite redirect loop
- To test, delete the user in the middle of the authentication interaction
=> Complete the interaction when user login with an invalid account

authui/src/imagepicker.ts, nginx.conf
refs #1871 
I found that there are options `maxWidth` and `minWidth` for `getCroppedCanvas` which is suitable for our case, see the [doc](https://github.com/fengyuanchen/cropperjs#getcroppedcanvasoptions). When I tried using the placeholder images, it works as expected. But when I tried a very large image and crop an area which should be larger than 1024x1024, I expected I should be able to get an image with 1024x1024, but the result image is smaller. No idea yet :(
The placeholder images:
The large images:
=> Adjust the cropped image size to at most 1024x1024

pkg/auth/handler/webapp/whatsapp_wati_callback.go
It is common to have errors in the whatsapp callback, especially when
we reuse the same whatsapp number in different environment. Webhooks
will be sent to all environments, unexpected webhooks will be received.
=> Change whatsapp callback error log level to info

pkg/portal/libstripe/error.go, pkg/portal/libstripe/service.go, pkg/portal/transport/stripe_webhook_handler.go
It will happen only if 2 users subscribe plan for the same app at the same time.
Or the server failed to receive webhook event of the 1st checkout and the user
repeats the checkout flow again.
=> Avoid duplicate subscription more robustly

pkg/lib/oauth/handler/result_authz.go, pkg/lib/oauth/oidc/handler/handler_end_session.go, pkg/lib/oauth/response_mode.go, pkg/lib/oauth/response_mode_test.go
ref #1869 
To test:
1. Use updated JS SDK that will redirect to `end_session_endpoint` (https://github.com/authgear/authgear-sdk-js/pull/196)
2. Start the web app example and use different etld+1 domain, `sessionType` set to `refresh_token`
3. Add the post logout uri to the oauth client config
4. Login via the web app
5. Login via `/login` link
6. Logout from the web app
=> Fix failed to redirect to a custom URI after logout via end_session_endpoint

portal/src/graphql/portal/AnalyticsActivityWidget.tsx
ref #2182 
We should compare the string with the values of Periodical enum but not
the keys.
It was working since the keys and values of the enum were the same, and
it broke after the keys were changed from uppercase to capitalize string.
=> Fix weekly tab doesn't work in analytics page

pkg/portal/libstripe/service.go, portal/src/graphql/portal/SubscriptionPlanCard.module.css, portal/src/graphql/portal/SubscriptionPlanCard.tsx, portal/src/graphql/portal/SubscriptionScreen.tsx, portal/src/locale-data/en.json
ref #2268 
To support automatic tax we need to
1. Update the price items to become tax exclusive in Stripe portal 
2. Mark automatic tax enabled when creating the subscriptions
Finally I found that we can test the tax settings in the sandbox environment and I updated the dev env for testing.
=> Enable automatic tax for subscription

pkg/auth/handler/webapp/whatsapp_otp.go
fix #2305 
In whatsapp otp page, alternatives should be empty. Provide empty
AlternativeStepsViewModel for this case.
=> Fix failed to open whatsapp otp page when verifying phone via whatsapp

docs/portal/gtm.md, pkg/portal/loader/user.go, portal/src/GTMProvider.tsx, portal/src/ReactApp.tsx
ref #2206 
~~Per discussion, changed to another approach to compare the mixpanel distinct id and user id, only call `reset` and `identify` when the distinct id is changed. The checking will be done after `mixpanel.init` or `ag.lifecycle.identified` event.~~
After more testing, I found that it is better to call GTM in React instead of pasting the script in index.html. It is because:
1. To ensure the events are associated with the correct user, all the events should be tracked after `mixpanel.identify` including page view.
1. Even we pasting the code in index.html, the initial history change events only fire occasionally.
So I changed the implementation,
1. Keep the mixpanel installation script in the initialization phase, but move `mixpanel.init` to `ag.event.identify`. To ensure no events …
=> Identify portal user and track page view in mixpanel

docs/portal/gtm.md
ref #2206 
When `cookie_domain` is not provided, mixpanel doesn't write the cookie and the distinct_id will keep changing when refresh.
=> Fix mixpanel distinct_id keep changing when refresh

portal/src/Widget.tsx
ref #2417 
Some widgets failed to get the correct height and this fix is a workaround that doesn't set max height when it is not extensible.
=> Fix the widget layout when it is not extensible

portal/src/Widget.module.css, portal/src/Widget.tsx, portal/src/graphql/portal/SMTPConfigurationScreen.module.css, portal/src/graphql/portal/SMTPConfigurationScreen.tsx, portal/src/graphql/portal/UISettingsScreen.module.css, portal/src/graphql/portal/UISettingsScreen.tsx, portal/src/graphql/portal/WebhookConfigurationScreen.module.css, portal/src/graphql/portal/WebhookConfigurationScreen.tsx
ref #2417 
Some pages layout are broken after adding the content wrapper (74aca12bde3c615712fd1687540a3b3aa2d4f670)
=> Fix the grid layout in various pages

resources/authgear/templates/en/translation.json
Original:
Should be `Your device supports passkey...faster and safer logins...`
=> Fix setup passkey dialog copywriting grammar

pkg/lib/authn/identity/info.go
- Prevent yielding error after https://github.com/authgear/authgear-nft-indexer/pull/25#issuecomment-1267896019 due to no nft collection
- Added missing case check for SIWE identity in AllStandardClaims
=> Add back missing case check for SIWE identity type

authui/src/authgear.ts, authui/src/web3.ts, pkg/auth/handler/webapp/confirm_web3_account.go, pkg/auth/handler/webapp/deps.go, pkg/auth/routes.go, pkg/auth/webapp/dynamic_csp_middleware.go, pkg/auth/wire_gen.go, pkg/auth/wire_handler.go, pkg/auth/wire_middleware.go, pkg/lib/web/csp.go, pkg/lib/web/csp_test.go, resources/authgear/templates/en/translation.json, resources/authgear/templates/en/web/connect_web3_account.html, resources/authgear/templates/en/web/login.html, resources/authgear/templates/en/web/signup.html, resources/authgear/templates/zh-HK/translation.json, resources/authgear/templates/zh-TW/translation.json
- Show dash and dummy logo if no account has been connected yet 
- If account connection is rejected, prompt again for connection when Next button is clicked and will proceed directly to the SIWE flow
@fungc-io @louischan-oursky see if these changes make sense to you
refs #2507 #2539
=> Prevent CSP violation for MetaMask on SIWE pages

pkg/lib/feature/web3/service.go, pkg/util/hexstring/hexstring.go, pkg/util/hexstring/hexstring_test.go, pkg/util/web3/contractid.go, pkg/util/web3/contractid_test.go, pkg/util/web3/eip681.go, pkg/util/web3/eip681_test.go, portal/src/util/contractId.test.ts, portal/src/util/contractId.ts, portal/src/util/eip681.test.ts, portal/src/util/eip681.ts
- Apparently we have to keep the leading zeroes for the contract addresses
- Added query params for contractID to handle putting token id information into the url, this respects the `parameters` field for the eip681 [spec](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-681.md)
=> Separate trimmed zero hexstring parser and make ContractID support parameters

pkg/admin/facade/authenticator.go, pkg/admin/facade/identity.go, pkg/admin/graphql/context.go, pkg/admin/graphql/user.go, pkg/lib/authn/authenticator/service/service.go, pkg/lib/authn/authenticator/service/store.go, pkg/lib/authn/identity/service/service.go, pkg/lib/authn/identity/service/store.go, pkg/lib/interaction/nodes/do_remove_authenticator.go, portal/src/graphql/adminapi/globalTypes.generated.ts, portal/src/graphql/adminapi/schema.graphql
refs #2328 
Some notes and questions:
1. I think it is protected already?
> Deleting a primary OOB OTP authenticator DOES NOT delete the login ID identity. But deletion is possible only if the login ID identity still have a usable primary authenticator.
refs: https://github.com/authgear/authgear-server/blob/7f46b8e6422a33c0ed7db3a4ce841943e71d6317/pkg/lib/interaction/nodes/do_remove_authenticator.go#L55
1. I revised `primaryOOBOTPAuthenticators` and `secondaryOOBOTPAuthenticators` to have `Email` and `SMS`. Do you think `primaryOOBOTP(Email|SMS)Authenticators` should be a single item or a list? In the PR, they are lists but it seems using a single item is more accurate? thought?
=> Redesign Admin API to avoid identities and authenticators ambiguity

portal/src/graphql/portal/AnalyticsScreen.tsx
fix #2635 
The bug occurs only in countries that have daylight saving.
When we use setFullYear or setDate to the date object, it applies
changes to the local time and the 1 hour shift will be automatically
adjusted. When we convert the time back to UTC, the date will become
incorrect. To avoid this problem, we always create a new time instance
in UTC when doing the date calculation.
=> Fix incorrect date range in analytics page

pkg/auth/endpoints.go, pkg/auth/handler/webapp/controller.go, pkg/auth/handler/webapp/oauth_entrypoint.go, pkg/auth/handler/webapp/root.go, pkg/auth/handler/webapp/select_account.go, pkg/auth/webapp/auth_entry_point_middleware.go, pkg/auth/webapp/client_id.go, pkg/auth/webapp/redirect.go, pkg/auth/webapp/result.go, pkg/auth/webapp/service2.go, pkg/auth/webapp/session.go, pkg/auth/webapp/url.go, pkg/auth/webapp/url_provider.go, pkg/auth/wire_gen.go, pkg/lib/config/oauth.go, pkg/lib/oauth/handler/handler_authz.go
ref #2628 
----
**Some cases to test**
1. When the unauthenticated user visits an auth required path (e.g. "/settings/identity"),
they should be redirected back to the original path after login. (This was broken and it is fixed in this PR)
1. When the unauthenticated user visits "/", they should be redirected to "/settings" after login.
1. Start authentication via SDK, the enduser should be redirected back to the client app.
1. The enduser visits login link with `client_id` and `redirect_uri`, they should be redirected back to `redirect_uri`.
1. The enduser visits login link with `client_id` only, they should be redirected back to default redirect uri.
1. The enduser visits login link with `redirect_uri` only, they should be redirected back to "/settings".
More cases are welcome!!
=> Redirect the user based on query after authentication

pkg/admin/facade/session.go, pkg/admin/wire_gen.go, pkg/api/event/nonblocking/user_signed_out.go, pkg/auth/handler/webapp/settings.go, pkg/auth/handler/webapp/settings_sessions.go, pkg/auth/wire_gen.go, pkg/lib/deps/deps_common.go, pkg/lib/interaction/context.go, pkg/lib/interaction/nodes/do_ensure_session.go, pkg/lib/oauth/handler/handler_revoke.go, pkg/lib/session/manager.go, pkg/lib/session/session.go
refs #2639 
We had to logic to clean up the unreachable IDP session already. refs: https://github.com/authgear/authgear-server/blob/36b1da967a0b466ffc7e7b9a9877da2eb8d783aa/pkg/lib/interaction/nodes/do_ensure_session.go#L203
In this PR, I updated the cleanup to remove refresh tokens in the same SSO group
=> Cleanup whole SSO group when cleaning up unreachable IDP session

pkg/auth/routes.go, pkg/auth/wire_gen.go, pkg/auth/wire_middleware.go, pkg/lib/session/middleware.go, pkg/resolver/routes.go, pkg/resolver/wire.go, pkg/resolver/wire_gen.go
ref #2713 
The problem happened after commit fc8c1aee79c513894b99326b04179811ad13c405. Actually, some endpoints only accept IDP sessions. After we change the priority in the middleware, the app session is resolved when both the app session and IDP session exist. Those endpoints don't expect an app session is resolved and cause the problem.
In this PR, I updated the middleware to resolve the IDP session for those endpoints.
=> Accepts IDP session only for authz endpoint, continue and consent page

.gitignore, portal/src/CodeEditor.tsx
Demo: https://codesandbox.io/s/focused-kalam-8jxnfl
Currently Deno hook editor cannot resolve external dependencies, so user only know if types are correct on save.
This PR downloads imports and include them in monaco-editor, providing better type-hint for users.
1. Assumes downloaded file does not have relative imports, falls back to `any` otherwise
- Typescript ignores path alias if the imported path has `.ts` extension
- `"moduleResolution": "bundler"`([related pr](https://github.com/microsoft/TypeScript/pull/51669)) might help fix `.ts` extension handling, however monaco-editor's `monaco.languages.typescript.ModuleResolutionKind` does not support it yet
- monaco-editor cannot install vscode extension e.g. https://marketplace.visualstudio.com/items?itemName=denoland.vscode-deno so need …
=> Resolve authgear event type hints for deno hook editor

migrations/authgear/20230130154554-is_anonymized_default_false.sql
ref: #2731
Current production deployment may have significant delay between database schema and code deployment. 
Without default value for `is_anonymized`, user signup will fail until code is deployed also.
1. Apply migration up to before this PR
2. Checkout cb6d9f82ae9e
3. Try signup, should error after submit password
4. Apply migration of this PR
5. Try signup again, should create user successfully
=> Default is_anonymized to false

Makefile
Current average time for `golangci-lint` command is ~5min.
=> Increase golang-ci lint timeout

pkg/admin/wire_gen.go, pkg/auth/wire_gen.go, pkg/latte/intent_authenticate_email_login_link.go, pkg/latte/intent_authenticate_oob_otp_phone.go, pkg/latte/intent_verify_identity.go, pkg/latte/node_verify_email.go, pkg/latte/node_verify_phone_sms.go, pkg/latte/utils_authn.go, pkg/lib/authn/authenticator/oob/sender.go, pkg/lib/authn/otp/sender.go, pkg/lib/config/messaging.go, pkg/lib/config/testdata/default_config.yaml, pkg/lib/feature/forgotpassword/provider.go, pkg/lib/infra/sms/ratelimit.go, pkg/lib/interaction/ratelimit.go, pkg/lib/ratelimit/error.go, pkg/lib/workflow/dependencies.go, resources/authgear/templates/en/web/__error.html
ref #2986 
Remarks:
- Doesn't support updating via the portal yet
- Question: Currently in the workflow API. When a phone number is submitted and the rate limit is reached (including per phone, per IP, and resend cooldown), we skip sending and no error is returned. Should we show the error to the user if it is per phone or per IP limit?
=> Support per IP rate limit to send any SMS

pkg/lib/authn/identity/loginid/provider.go, pkg/lib/authn/identity/oauth/provider.go, pkg/lib/authn/identity/service/service.go, pkg/lib/authn/identity/service/service_mock_test.go
Steps to reproduce the bug:
1. Sign in as anonymous user.
2. Promote with a OAuth account that is already linked to an existing user.
ref #3234
=> Fix identity conflict is not checked for OAuth

pkg/lib/interaction/nodes/do_create_user.go
When rate limited, the nil err is always returned.
=> Fix signup rate limit

pkg/lib/authn/authenticator/info.go
ref #3334 
Conditions to reproduce the bug:
1. Email link login & sso login is enabled in the project.
2. Create an account using email link as primary authenticator.
3. In settings, link to google oauth. The google account must have the same email address as the registered login id in previous step.
4. Logout, and login again. Crash.
=> Fix login crashing if login id is having same email with oauth id

portal/package.json
ref #3543 
https://parceljs.org/features/scope-hoisting/
It might result in a larger bundle size and some performance impact, but I guess that is not very important for portal.
=> Disable parcel scope hoisting

pkg/lib/oauth/handler/handler_token.go
app2appGetDeviceKeyJWKVerified will consume the challenge so it cannot be called twice.
ref #3564
=> Avoid calling app2appGetDeviceKeyJWKVerified twice

.gitignore, authui/src/authflowv2/base.css, authui/src/authflowv2/components.css, authui/src/authflowv2/components/layout.css, authui/src/authflowv2/components/widget.css, authui/tailwind.config.js, pkg/lib/web/html.go, pkg/lib/web/static_asset_resolver.go, pkg/lib/web/static_assets.go, resources/authgear/templates/en/web/authflowv2/__html_head.html, resources/authgear/templates/en/web/authflowv2/__page_frame.html, resources/authgear/templates/en/web/authflowv2/enter_password.html, resources/authgear/templates/en/web/authflowv2/layout.html
ref #3567 
- The layout can be customized by creating a file in `var/templates/en/web/authflowv2/layout.html`
Customized border, border radius and box shadow:
=> Add basic layout & widget styles

pkg/auth/handler/webapp/authflow_change_password.go, pkg/auth/handler/webapp/authflow_controller.go, pkg/auth/handler/webapp/authflow_controller_test.go, pkg/auth/handler/webapp/authflow_create_password.go, pkg/auth/handler/webapp/authflow_enter_oob_otp.go, pkg/auth/handler/webapp/authflow_enter_password.go, pkg/auth/handler/webapp/authflow_enter_recovery_code.go, pkg/auth/handler/webapp/authflow_enter_totp.go, pkg/auth/handler/webapp/authflow_fallback.go, pkg/auth/handler/webapp/authflow_forgot_password.go, pkg/auth/handler/webapp/authflow_forgot_password_otp.go, pkg/auth/handler/webapp/authflow_login.go, pkg/auth/handler/webapp/authflow_oob_otp_link.go, pkg/auth/handler/webapp/authflow_promote.go, pkg/auth/handler/webapp/authflow_prompt_create_passkey.go, pkg/auth/handler/webapp/authflow_reset_password.go, pkg/auth/handler/webapp/authflow_setup_oob_otp.go, pkg/auth/handler/webapp/authflow_setup_totp.go, pkg/auth/handler/webapp/authflow_signup.go, pkg/auth/handler/webapp/authflow_terminate_other_sessions.go, pkg/auth/handler/webapp/authflow_use_passkey.go, pkg/auth/handler/webapp/authflow_view_recovery_code.go, pkg/auth/handler/webapp/authflow_wechat.go, pkg/auth/handler/webapp/authflow_whatsapp_otp.go, pkg/auth/webapp/session_authflow.go, resources/authgear/templates/en/translation.json, resources/authgear/templates/en/web/authflow_setup_oob_otp.html, resources/authgear/templates/zh-HK/translation.json, resources/authgear/templates/zh-TW/translation.json
ref #3549 
@fungc-io I removed the fallback to sms logic in this step, because the ux seems confusing. I guess displaying an error is better. Maybe you can test it out in staging later.
=> Fix setup secondary oob otp crashing in auth ui

pkg/auth/handler/webapp/authflow_login.go, pkg/auth/webapp/authflow.go, resources/authgear/templates/en/web/authflow_login.html
The cause is it passed "identification": "email" to authflow.
ref #3631
=> Fix if only username is enabled, user cannot login with username

pkg/util/template/engine.go, pkg/util/template/func.go, pkg/util/template/func_test.go, pkg/util/template/resource.go, pkg/util/template/translation_map.go
ref #3644 
Usage
```
{{ $errorMessage := include "authflowv2/__error.html" . }}
```
=> Add "include" for executing template as a string

authui/src/authflowv2/components/password-strength-meter.css, authui/src/authflowv2/password-policy.ts, authui/src/authflowv2/password-strength-meter.ts, resources/authgear/templates/en/web/authflowv2/__password_strength_meter.html
ref #3734
Seems safari won't display element inside `<meter>` element, so update to use `role="meter"` instead
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/meter_role
https://github.com/authgear/authgear-server/assets/63200569/bd06f367-b96c-4b98-a748-43ed20c6e39a
=> Update password strength meter to use role meter

authui/src/phoneInput.ts
ref #3765
Can not completely duplicate the behaviour of `intl-tel-input`.
----------------
`intl-tel-input` is referencing a custom dataset  and it will combine the country calling code and area code to determine the country before the complete phone number is entered
https://github.com/authgear/intl-tel-input/blob/master/src/js/data.js
https://github.com/authgear/intl-tel-input/blob/3e25f91f1ab5af622caf878b971d9e87b4d770d9/src/js/intlTelInput.js#L289
`libphonenumber.js`  has similar mechanism called `leading_digits` but only some of the countries are defined so it doesn't work for all phone number (e.g. US and Canada) and complete phone number is required to determine the country for these countries. It's using regex to do the matching for those case …
=> Determine the country selected before complete phone number is entered

authui/src/authflowv2/components/code-block.css
=> Use monospace font for code block

docs/specs/oidc.md, docs/specs/sdk.md
ref #3813
This spec is a reincarnation of #2886. 
Changes from previous spec:
- Use new response type similar to authorization_code wit new grant type instead of internal settings action code
- Treat settings action as part of the authorization flow instead of plain webview
=> Specify settings action

portal/src/graphql/portal/LocalizationConfigurationScreen.tsx, portal/src/graphql/portal/ManageLanguageWidget.tsx, portal/src/graphql/portal/UISettingsScreen.tsx, portal/src/hook/useDelayedSave.ts
=> Immediate apply on destructive language change

pkg/admin/wire_gen.go, pkg/auth/wire_gen.go, pkg/lib/infra/whatsapp/service.go, pkg/util/intl/match.go, pkg/util/intl/match_test.go, pkg/util/intl/oidc.go, pkg/util/intl/resolve.go, pkg/util/intlresource/match.go, pkg/util/template/translation_test.go, pkg/worker/wire_gen.go
ref #3718 #3454 
Benchmark result
```
goos: darwin
goarch: amd64
pkg: github.com/authgear/authgear-server/pkg/util/intl
cpu: VirtualApple @ 2.50GHz
BenchmarkMatch-8       	   56115	     21034 ns/op
BenchmarkBestMatch-8   	   48363	     24730 ns/op
```
=> Use a better matching algorithm to match languages

pkg/admin/graphql/user_mutation.go, pkg/auth/webapp/authflow.go, pkg/lib/authn/identity/loginid/normalizer.go, pkg/lib/authn/identity/loginid/normalizer_test.go, pkg/lib/authn/stdattrs/normalizer.go, pkg/lib/elasticsearch/model.go, pkg/lib/usage/count_collector.go, pkg/util/phone/deps.go, pkg/util/phone/legal_and_valid_parser.go, pkg/util/phone/legal_and_valid_parser_test.go, pkg/util/phone/legal_parser.go, pkg/util/phone/legal_parser_test.go, pkg/util/phone/parser.go, pkg/util/phone/phone.go, pkg/util/phone/phone_test.go, pkg/util/validation/formats.go
=> Add phone normalizer

docs/specs/account-linking.md
ref DEV-1246
The problem:
Starting at this example config:
```yaml
authentication_flow:
signup_flows:
- name: signup_flow_1
account_linking:
oauth:
- alias: adfs
oauth_claim:
pointer: "/preferred_username"
user_profile:
pointer: "/preferred_username"
action: login_and_link
login_flow: default
steps:
- name: identify
type: identify
one_of:
- identification: email
- identification: oauth
promote_flows:
- name: promote_flow_1
steps:
- name: identify
type: identify
one_of:
- identification: email
- identification: oauth
```
The linking logics, (like `oauth_claim.pointer`, `user_profile.pointer`, which are originally the link_by part), is defined in the signup flow. And in the above example, promote flow didn't define any "link by what". But this seems doesn’t make sense because this kind of …
=> Make account linking config global to all flows

authui/src/intlTelInput.ts
ref DEV-1386
It seems that it become case sensitive comparison.
The commit that changes the behavior:
https://github.com/jackocnr/intl-tel-input/commit/4bb581597c49e81626489c598dbe5a84916e0a51
=> Fix intl tel input isn't selecting initial country correctly

e2e/run.sh
Looks like per test timeout is not available yet
https://github.com/golang/go/issues/48157
=> Extend e2e test timeout

.dockerignore
=> Fix resources/portal/static/img/* were excluded from docker build

resources/authgear/templates/en/web/authflowv2/oob_otp_link.html
ref DEV-1443
ref #4373
@tung2744
=> Fix wrong footer background color in verficiation success page

pkg/lib/authenticationflow/declarative/generate_config_account_recovery_flow.go, pkg/lib/authenticationflow/declarative/generate_config_account_recovery_flow_test.go, pkg/lib/authenticationflow/declarative/generate_config_captcha.go, pkg/lib/authenticationflow/declarative/generate_config_login_flow.go, pkg/lib/authenticationflow/declarative/generate_config_login_flow_test.go, pkg/lib/authenticationflow/declarative/generate_config_reauth_flow.go, pkg/lib/authenticationflow/declarative/generate_config_reauth_flow_test.go, pkg/lib/authenticationflow/declarative/generate_config_signup_flow.go, pkg/lib/authenticationflow/declarative/generate_config_signup_flow_test.go, pkg/lib/authenticationflow/declarative/generate_config_signup_login_flow.go, pkg/lib/authenticationflow/declarative/generate_config_signup_login_flow_test.go, pkg/lib/config/authentication_flow.go, pkg/lib/config/authentication_flow_object_captcha.go, pkg/lib/config/testdata/login_flow_tests.yaml, pkg/lib/config/testdata/reauth_flow_tests.yaml, pkg/lib/config/testdata/signup_flow_tests.yaml, pkg/lib/config/testdata/signup_login_flow_tests.yaml
1. [Resolved - `No`] Should allow captcha for reauth's identify step too? (ongoing discussion [here](https://github.com/authgear/authgear-server/pull/4282#discussion_r1641979288)) 
2. [Resolved - `Yes, but specify when consuming`]Should specify cascading relationship of root captcha (enabled) & branch captcha (required)? (ongoing discussion [here](https://github.com/authgear/authgear-server/pull/4282#discussion_r1641965018))
- More test cases if necessary
3. Account recovery flow test case is missing - is it
1. intentional; OR
2. because JSON schema is dynamically generated? ref pkg/lib/config/authentication_flow.go:1438
4. Currently supports recursive definition of captcha; Assume only top layer is read
=> Make generated auth flows aware of captcha

pkg/auth/routes.go, pkg/auth/webapp/csrf.go, pkg/auth/webapp/csrf_debug_middleware.go, pkg/auth/webapp/csrf_middleware.go, pkg/auth/webapp/deps.go, pkg/auth/wire_gen.go, pkg/auth/wire_middleware.go, pkg/util/sentry/request.go
Ref DEV-1337
Sentry log from test project:
(sanity check by removing debug cookie manually in browser)
Note the referer field is auto masked by sentry, and seems override is not working (see linear discussion)
=> Add sentry tracking with debug info for csrf errors

cmd/authgear/Dockerfile, cmd/portal/Dockerfile, custombuild/cmd/authgearx/Dockerfile, custombuild/cmd/portalx/Dockerfile
Ref DEV-1379
--- 
quay.io report:
Base image (golang on noble): 31 mid, 37 low; https://quay.io/repository/elise-oursky/golang/manifest/sha256:2e97d55dc96a0bdd6031ca1e1f147cff9d33f69ff31706f3163bc8019ec9d841?tab=vulnerabilities
Authgear Server: 582 medium, 94 low; https://quay.io/repository/elise-oursky/authgear-server/manifest/sha256:c61f6437b88b1e251b6aab8347e05605ed3d493f3a5721126e26a611699052c6?tab=vulnerabilities
Authgear portal: same as above; https://quay.io/repository/elise-oursky/authgear-portal/manifest/sha256:ef218e503b7486096bbb855511b2318937c859e2ee433914f1e573d6380eab22?tab=vulnerabilities
=> Adopt ubuntu base for docker images

pkg/lib/authenticationflow/context.go, pkg/lib/authenticationflow/declarative/bot_protection.go, pkg/lib/authenticationflow/declarative/data_authenticate_option.go, pkg/lib/authenticationflow/declarative/data_create_authenticator_option.go, pkg/lib/authenticationflow/declarative/data_identification.go, pkg/lib/authenticationflow/declarative/intent_login_flow_step_identify.go, pkg/lib/authenticationflow/declarative/intent_lookup_identity_oauth.go, pkg/lib/authenticationflow/declarative/intent_oauth.go, pkg/lib/authenticationflow/declarative/intent_promote_flow_step_identify.go, pkg/lib/authenticationflow/declarative/intent_promote_identity_oauth.go, pkg/lib/authenticationflow/declarative/intent_reauth_flow_step_identify.go, pkg/lib/authenticationflow/declarative/intent_signup_flow_step_identify.go, pkg/lib/authenticationflow/declarative/intent_signup_login_flow_step_identify.go, pkg/lib/authenticationflow/declarative/utils_common.go, pkg/lib/authenticationflow/session.go, pkg/lib/authenticationflow/session_bot_protection.go, pkg/lib/config/authentication_flow.go
- #4382 
This PR only address 3 out of 4 items of DEV-1413
Why? - to prevent conflict of 4th point with another PR #4372
=> Implement bot protection in auth flow handlers

authui/src/authflowv2/components/otp-input.css
Demo video:
https://github.com/authgear/authgear-server/assets/79845066/356736ef-a9c8-44ee-b8e2-9bb4d0ca743a
Ignore the internal error, it is to stop submitting the code instantly for demo.
=> Fix ios autofill reveal input in otp

pkg/util/phone/legal_and_valid_parser.go, pkg/util/phone/legal_and_valid_parser_test.go, pkg/util/phone/legal_parser.go, pkg/util/phone/legal_parser_test.go
"the string supplied is too short to be a phone number" from here https://github.com/nyaruka/phonenumbers/blob/v1.3.6/phonenumbers.go#L2873
But I did not find an example of invalid phone number that can trigger this case.
ref DEV-1528
=> Do not accidentally leak errors from phonenumbers

pkg/auth/handler/webapp/authflowv2/forgot_password.go
OTPForm information (email link vs phone otp) was rich in authUI v1
Since we simplified UI & information load to user in authUI v2, this `legacy` field is obsolete and not used. Unused code rot, so removed.
=> Remove unused `OTPForm` in forgot_password handler

pkg/auth/handler/webapp/authflowv2/select_account.go, pkg/auth/handler/webapp/select_account.go, pkg/auth/handler/webapp/settings_delete_account.go, pkg/latte/intent_ensure_session.go, pkg/lib/authenticationflow/declarative/node_did_reauthenticate.go, pkg/lib/authenticationflow/declarative/node_do_create_session.go, pkg/lib/authn/authenticationinfo/model.go, pkg/lib/interaction/nodes/do_ensure_session.go, pkg/lib/oauth/grant_code.go, pkg/lib/oauth/grant_offline.go, pkg/lib/oauth/handler/handler_authz.go, pkg/lib/oauth/handler/handler_authz_test.go, pkg/lib/oauth/handler/handler_token.go, pkg/lib/oauth/handler/service_code_grant.go, pkg/lib/oauth/handler/service_settings_action_grant.go, pkg/lib/oauth/settings_action_code.go, pkg/lib/session/idpsession/session.go, pkg/lib/session/session.go, pkg/lib/session/test/context.go
The bug occurs when:
1. You have an access token session of user A
2. You try to authenticate as user B
3. You got an access token of user B (sub=user-b-id), but internally the session id was the session in 1. As a result the server will think you are user A.
ref DEV-1589
=> Fix access token issued can be resolved to a wrong user id

authui/src/authflowv2.ts, authui/src/authflowv2/turboForm.ts, resources/authgear/templates/en/web/authflowv2/__authflow_branch.html, resources/authgear/templates/en/web/authflowv2/__forgot_password_alternatives.html, resources/authgear/templates/en/web/authflowv2/__otp_input.html, resources/authgear/templates/en/web/authflowv2/__page_frame.html, resources/authgear/templates/en/web/authflowv2/account_linking.html, resources/authgear/templates/en/web/authflowv2/change_password.html, resources/authgear/templates/en/web/authflowv2/change_password_success.html, resources/authgear/templates/en/web/authflowv2/create_password.html, resources/authgear/templates/en/web/authflowv2/enter_oob_otp.html, resources/authgear/templates/en/web/authflowv2/enter_password.html, resources/authgear/templates/en/web/authflowv2/enter_recovery_code.html, resources/authgear/templates/en/web/authflowv2/enter_totp.html, resources/authgear/templates/en/web/authflowv2/forgot_password.html, resources/authgear/templates/en/web/authflowv2/forgot_password_link_sent.html, resources/authgear/templates/en/web/authflowv2/forgot_password_otp.html, resources/authgear/templates/en/web/authflowv2/login.html, resources/authgear/templates/en/web/authflowv2/oob_otp_link.html, resources/authgear/templates/en/web/authflowv2/prompt_create_passkey.html, resources/authgear/templates/en/web/authflowv2/reset_password.html, resources/authgear/templates/en/web/authflowv2/select_account.html, resources/authgear/templates/en/web/authflowv2/setup_oob_otp.html, resources/authgear/templates/en/web/authflowv2/setup_totp_verify.html, resources/authgear/templates/en/web/authflowv2/signup.html, resources/authgear/templates/en/web/authflowv2/terminate_other_sessions.html, resources/authgear/templates/en/web/authflowv2/use_passkey.html, resources/authgear/templates/en/web/authflowv2/verify_login_link.html, resources/authgear/templates/en/web/authflowv2/view_recovery_code.html, resources/authgear/templates/en/web/authflowv2/wechat.html
<details>
<summary>Outdated</summary>
As per offline discussion, it was found that `<form>` `submit` events using stimulius syntax like below did not stop other methods the form from submitting
```html
<form
...
data-action="submit->someController#someMethod"
>
...
```
```ts
// someController.ts
class SomeController extends Controller {
someMethod(e: Event) {
e.preventDefault()
e.stopImmediatePropagation() // This did not stop other actions
}
}
```
This PR exists to make `e.stopImmediatePropagation` in `someMethod` works as expected
</details>
Tested turbo-enabled forms submission, still behaves like SPA
Total 36 forms
```bash
rg '<form' ./resources/authgear/templates/en/web/authflowv2 | rg '<form' -c
```
30 forms have `data-controller="turbo-form"` added
```bash
rg '<form' …
```
=> Replace XHRSubmitFormController with TurboFormController for declarative form submission hijack

pkg/auth/deps.go, pkg/auth/handler/webapp/authflowv2/enter_password.go, pkg/auth/handler/webapp/authflowv2/enter_recovery_code.go, pkg/auth/handler/webapp/authflowv2/enter_totp.go, pkg/auth/handler/webapp/authflowv2/forgot_password.go, pkg/auth/handler/webapp/authflowv2/internal_signup_login.go, pkg/auth/handler/webapp/authflowv2/login.go, pkg/auth/handler/webapp/authflowv2/promote.go, pkg/auth/handler/webapp/authflowv2/use_passkey.go, pkg/auth/handler/webapp/bot_protection.go, pkg/auth/handler/webapp/viewmodels/authflow.go, pkg/auth/handler/webapp/viewmodels/base.go, pkg/auth/webapp/authflow.go, pkg/auth/webapp/bot_protection.go, pkg/lib/authenticationflow/declarative/data_bot_protection.go, pkg/lib/config/bot_protection.go
- guard captcha if required in below http handlers in AuthUI
- signup identify, all branches
- signup-login identify, all branches
- promote identify, all branches
- login identify, all branches
- login primary authentication, password, passkey (non-oob-otp branches)
- login secondary authentication, additional password, totp, recovery code (non-oob-otp branches)
- reauth primary authentication, password, passkey (non-oob-otp branches)
- reauth secondary authentication, additional password, totp, recovery code (non-oob-otp branches)
This PR only implements server-side guarding (server as in SSR, not api serever)
- special handling on `oob-otp-email` and `oob-otp-sms` which requires an extra screen
=> Add bot protection handling in http handlers

pkg/lib/botprotection/provider.go
Fix e2e tests failing on `authgear/main` after #4493 is merged
The problem - `err == nil` case not handled. 
e2e tests pass locally now
```
ok  	github.com/authgear/authgear-server/e2e/pkg/testrunner	16.735s
```
Sorry for all inconvenience caused 🙏
=> Fix missing nil err return in bot protection verification logic

pkg/latte/node_authenticate_oob_otp_phone.go, pkg/lib/interaction/nodes/authn_oob.go, pkg/lib/interaction/nodes/authn_whatsapp.go, pkg/lib/interaction/nodes/create_authenticator_whatsapp_otp.go
In #4487, we require VerifyOptions to have Form if verifying OOB OTP. But we only updated VerifyOneWithSpec.
ref DEV-1680
=> Fix VerifyWithSpec is not updated to include Form

authui/src/authflowv2.ts, authui/src/authflowv2/botprotection/botProtection.ts, authui/src/authflowv2/botprotection/botProtectionDialog.ts, authui/src/authflowv2/botprotection/botProtectionStandalonePage.ts, authui/src/authflowv2/botprotection/botProtectionTokenInput.ts, authui/src/authflowv2/botprotection/botProtectionWidget.ts, authui/src/authflowv2/botprotection/cloudflareTurnstile.ts, authui/src/authflowv2/botprotection/recaptchav2.ts, pkg/lib/web/html.go, resources/authgear/templates/en/web/authflowv2/__bot_protection_dialog.html, resources/authgear/templates/en/web/authflowv2/__bot_protection_form_input.html, resources/authgear/templates/en/web/authflowv2/__page_frame.html, resources/authgear/templates/en/web/authflowv2/enter_password.html, resources/authgear/templates/en/web/authflowv2/forgot_password.html, resources/authgear/templates/en/web/authflowv2/login.html, resources/authgear/templates/en/web/authflowv2/signup.html, resources/authgear/templates/en/web/authflowv2/verify_bot_protection.html
Implement captcha guard in
https://github.com/user-attachments/assets/b4568a15-abf4-47b5-9dd2-6348f641c0a6
If you noticed a 502 gate error in preview, it's because of header too large (>4kb) again.
1. grecaptcha has an embedded `<textarea />` input, which store the very long grecaptcha token
2. I also have an input field `x_bot_protection_provider_token`, store the very long grecaptcha token _again_
3. Empty phone input will return an error, **with entire form input returned**
4. Each token cost ~ 500b - 1kb, so the response headers with `web_err` in set cookie exceeded 4kb easily.
<details>
<summary> Sample repsonse Header (4372 bytes) </summary>
```
Cache-Control: no-store
Content-Security-Policy: default-src 'self'; script-src 'strict-dynamic' 'nonce-SASWCQCQ9NNC3NZRB68QDMXM7CTZHKDQ' …
```
=> Implement captcha modal in AuthUI v2

e2e/tests/bot_protection/signup/create_authenticator/primary_oob_otp_email/error_missing_required_field.test.yaml, e2e/tests/bot_protection/signup/create_authenticator/primary_oob_otp_email/fail.test.yaml, e2e/tests/bot_protection/signup/create_authenticator/primary_oob_otp_email/sucess.test.yaml, e2e/tests/bot_protection/signup/create_authenticator/primary_oob_otp_sms/error_missing_required_field.test.yaml, e2e/tests/bot_protection/signup/create_authenticator/primary_oob_otp_sms/fail.test.yaml, e2e/tests/bot_protection/signup/create_authenticator/primary_oob_otp_sms/sucess.test.yaml, e2e/tests/bot_protection/signup/create_authenticator/secondary_oob_otp_email/error_missing_required_field.test.yaml, e2e/tests/bot_protection/signup/create_authenticator/secondary_oob_otp_email/fail.test.yaml, e2e/tests/bot_protection/signup/create_authenticator/secondary_oob_otp_email/sucess.test.yaml, e2e/tests/bot_protection/signup/create_authenticator/secondary_oob_otp_sms/error_missing_required_field.test.yaml, e2e/tests/bot_protection/signup/create_authenticator/secondary_oob_otp_sms/fail.test.yaml, e2e/tests/bot_protection/signup/create_authenticator/secondary_oob_otp_sms/sucess.test.yaml, pkg/lib/authenticationflow/declarative/data_create_authenticator_option.go, pkg/lib/authenticationflow/declarative/input_signup_flow_step_create_authenticator.go, pkg/lib/authenticationflow/declarative/input_signup_flow_step_create_authenticator_test.go, pkg/lib/authenticationflow/declarative/input_take_oob_otp_target.go, pkg/lib/authenticationflow/declarative/intent_create_authenticator_oob_otp.go, pkg/lib/authenticationflow/declarative/intent_signup_flow_step_create_authenticator.go, pkg/lib/authenticationflow/declarative/utils_bot_protection.go
- #4512 
DEV-1608 requires captcha in `signup > create_authenticator`, which is not supported yet. It is added in this PR
1. Only supports `create_authenticator_oob_otp` ? -  asked in https://github.com/authgear/authgear-server/pull/4282#discussion_r1695145534
- yes
2. Only supports `secondary_oob_otp`? Both in authflow/authUI, I cannot observe when will `create_authenticator > primary_oob_otp` take place
- no, also need `primary_oob_otp` & `verify`, will also implement in this PR
=> Allow captcha configuration in signup create_authenticator oob_otp

authui/package-lock.json, authui/package.json, authui/src/authflowv2/icons/material-symbols.css, authui/src/authflowv2/icons/twemoji-countries.css, authui/src/base64.ts, authui/src/build-authflowv2.html, authui/src/build-dummy.html, authui/src/build.html, authui/src/icons/authgear-icons.css, authui/src/tailwind.css, portal/package-lock.json, portal/package.json, portal/src/graphql/adminapi/UserDetailsConnectedIdentities.tsx, portal/src/graphql/portal/PhoneInputListWidget.tsx, portal/src/model/themeAuthFlowV2.ts, portal/src/types.ts
It fixes below problem. Now at step 3, the mal-formatted files will be formatted
1. run `npm run prettier`
2. mal-formatted files are cached in `./node_modules/.cache/prettier/.prettier-cache` 
ref https://prettier.io/docs/en/cli.html#--cache
3. run `npm run prettier:format`
At 3, the mal-formatted files will NOT be formatted, which is unexpected
=> Do not cache `prettier:format` in portal

e2e/pkg/testrunner/testcase.go, e2e/tests/login/totp_recovery/totp_user.sql, e2e/tests/reauth/reauth_user.sql
I found the issue was not
> error not thrown
Instead, it is
> database did not throw error when inserting duplicate primary key records
Which is caused by `ON CONFLICT DO NOTHING` clause in custom sql.
I will remove all `ON CONFLICT DO NOTHING` clauses as a fix 🙏 Since UUID() will be introduced in [DEV-1765](https://linear.app/authgear/issue/DEV-1765/add-generateuuid-to-e2e-template)
=> Remove `ON CONFLICT DO NOTHING` clause in e2e custom sqls

portal/src/graphql/adminapi/UsersScreen.tsx, portal/src/locale-data/en.json
- Seems previously the page size is intentionally set to 10 due to performance problem in [Issue #3176](https://github.com/authgear/authgear-server/issues/3176) 
- Then, the performance problem is fixed in [Issue #3233](https://github.com/authgear/authgear-server/issues/3233)
I tried increasing page size, seems no significant load speed difference (locally)
Maybe need to test on staging before/after, see if 50-page-size cause performance issue
=> Make user screen page size as 50

e2e/tests/login/totp_recovery/totp_user.sql, e2e/tests/reauth/reauth_user.sql, e2e/tests/reauth/test.yaml
- #4522 
- #4568 
~I realized we need to reuse the generated uuidv4 in db in reauth e2e tests.~
~Thus, this PR depends on https://linear.app/authgear/issue/DEV-1766/add-a-new-step-to-run-a-database-query-and-assert-the-result too.~
~Will mark this as draft first~
EDIT: updated
=> Use `uuidv4` and `action: query` in existing e2e tests

e2e/tests/issue_DEV_1458_import_uppercase/case_insensitive/email/test.yaml, e2e/tests/issue_DEV_1458_import_uppercase/case_insensitive/email/user.json, e2e/tests/issue_DEV_1458_import_uppercase/case_insensitive/username/test.yaml, e2e/tests/issue_DEV_1458_import_uppercase/case_insensitive/username/user.json, e2e/tests/issue_DEV_1458_import_uppercase/case_sensitive/email/test.yaml, e2e/tests/issue_DEV_1458_import_uppercase/case_sensitive/email/user.json, e2e/tests/issue_DEV_1458_import_uppercase/case_sensitive/username/test.yaml, e2e/tests/issue_DEV_1458_import_uppercase/case_sensitive/username/user.json, pkg/lib/userimport/model.go, pkg/lib/userimport/model_test.go, pkg/lib/userimport/service.go
- #4522 
- #4568 
Fix a bug where 
if
- `authgear.yaml` has `username/email.case_sensitive=false`
then
- import username/email with uppercase with fail
On 2nd thought, maybe the expected behavior is to skip these `invalid uppercase` imports and show error message?
=> Fix import api failed to handle email username with upper cases

.github/workflows/ci.yaml
Usually I test ci by creating a `test-ci-<ISSUE_NUMBER>` branch in main repo (`authgear/authgear-server` here).
But since I am not allowed to do that, maybe @louischan-oursky can help create `test-ci-DEV-1791` for me? 🙏 Then we
1. make this PR target `test-ci-DEV-1791`, merge it
2. confirm `NPM_AUDIT_LEVEL` works
3. make another PR from `test-ci-DEV-1791` to `main`?
Please advise if otherwise~
P.S. or maybe the script is simple enough that we are confident to merge to main directly 👍
=> Allow variable NPM_AUDIT_LEVEL in authui-test & portal-test

authui/src/authflowv2/components/layout.css
=> Fix partial background image is shown in authui mobile layout

portal/src/OnboardingSurveyScreen.tsx, portal/src/PhoneTextField.tsx
ref DEV-1647
Note below previews are achieved by hard-coding `ip-address` server side
| UK          | Japan                                   |
|---------------------|------------------------------------------|
| <img width="512" alt="image" src="https://github.com/user-attachments/assets/1dcc7253-2228-4696-b4f6-6efb8eb4ae2c">                | <img width="501" alt="image" src="https://github.com/user-attachments/assets/0ab74d11-9546-4c7a-abf7-84951d906733">                           |
=> Use geo-ip for country code in onboarding survey

portal/src/graphql/adminapi/UsersList.tsx
ref dev-1788
I also try fixing this by changing `IListProps.renderedWindowsAhead = 3`, which _does_ fix the problem. But passing a correct page size seems a more proper fix.
ref https://github.com/microsoft/fluentui/blob/07f70bdc0c1d0718ff35b3aef8f7ac87635520e3/packages/react/src/components/List/List.tsx#L37
https://github.com/user-attachments/assets/cd0ab173-43bf-496a-8471-7e5bb409103a
=> Fix users list page size not equal to search result size

pkg/auth/webapp/session_authflow.go
My refactoring in #4602 did not update with @IniZio changes in #4555 
- the input type is `interface{}`
- there is no merge conflict 
Thanks @louischan-oursky for helping me fix this
=> Fix regression due to TakeBranchResultInput variable wrong reference

pkg/util/template/validation.go, pkg/util/template/validation_test.go
cc @kiootic or was it intentional not to traverse into `TemplateNode.Pipe`?
=> Fix pipes nested in templates not traversed in validateHTMLTemplate

cmd/authgear/background/wire_gen.go, e2e/cmd/e2e/pkg/wire_gen.go, pkg/admin/wire_gen.go, pkg/lib/authn/authenticator/password/deps.go, pkg/lib/authn/authenticator/password/generator.go, pkg/lib/authn/authenticator/password/generator_test.go, pkg/redisqueue/wire_gen.go, pkg/resolver/wire_gen.go, portal/src/util/passwordGenerator.test.ts, portal/src/util/passwordGenerator.ts
- https://github.com/authgear/authgear-server/actions/runs/10572893051/job/29291367108
- https://github.com/authgear/authgear-server/actions/runs/10465349585/job/28980452492?pr=4619
Think it happened at least 3 times since it got merged. Was curious why so I did some math.
```
all combinations of `[1-9]{8}` = 9^8
all combinations of `[0-9]{8}` = 10^8
P(1st trial fail) = 1
because `if (!ranOnce) return 0`
P(2nd trial fail) = [1 - (9^8 / 10^8)] = 0.5695
P(3nd trial fail) = [1 - (9^8 / 10^8)]^2 = 0.5695^2 = 0.3243
...
P(10th trial fail) = [1 - (9^8 / 10^8)]^9 = 0.5695^9 = 0.00630
```
`0.00630` = `test will fail 6 times out of 1000 CI runs`, which is not that unlikely, so it failing 3 times is kind of expected.
Say we aim for `only fail once in 100,000 CI runs`
```
[1 - (9^8 / 10^8)]^n <= …
```
=> Fix portal & server generate password test sometimes fail

portal/src/components/design/AppLogoPicker.tsx
=> Fix app logo background when there is a uploaded logo

Makefile, devtools/gotemplatelinter/args_flags.go, devtools/gotemplatelinter/final_newline_rule.go, devtools/gotemplatelinter/final_newline_rule_test.go, devtools/gotemplatelinter/flags.go, devtools/gotemplatelinter/indent_rule.go, devtools/gotemplatelinter/main.go, devtools/gotemplatelinter/transation_key_rule_check_include.go, devtools/gotemplatelinter/transation_key_rule_check_template.go, devtools/gotemplatelinter/transation_key_rule_check_translate.go, devtools/gotemplatelinter/transation_key_rule_check_translations_render_text.go, devtools/gotemplatelinter/translation_key_rule.go, devtools/gotemplatelinter/translation_key_rule_check_translation_key.go, devtools/gotemplatelinter/translation_key_rule_traverse_tree.go
@louischan-oursky Seems unable to reuse code in `pkg/util/template/validation.go` inside `devtools/`.
I plan to duplicate the template validation into `devtools/gotemplatetranslationlinter/validation.go`. Any thoughts?
=> Add translation key rule to gotemplate linter

docs/specs/bot-protection.md, pkg/lib/authenticationflow/declarative/generate_config_signup_login_flow.go, pkg/lib/authenticationflow/declarative/generate_config_signup_login_flow_test.go
ref DEV-1972
Previously we missed that signup_login identify should also requires bot_protection according to `requirements.___`
- `oob_otp_email` -> `signup_login > identify > email`
- `oob_otp_sms` -> `signup_login > identify > phone`
This PR added that back. Note the changes in `spec/bot-protection.md`
https://github.com/user-attachments/assets/f9be9358-ffa6-4cc4-a36a-ec7042994f3d
=> Fix captcha authflow signup login flow identify doesnt require captcha correctly

pkg/auth/webapp/session_authflow.go
ref DEV-1904
The problem was `channel` defaulted as `options[0].Channel` in `takeBranchLoginAuthenticate`, but this default channel is not inherited in the captcha redirect screen
Thought about adding test for this, but currently we don't have UI testing
https://github.com/user-attachments/assets/13faf110-48ab-4475-a089-b5f65efa8cac
https://github.com/user-attachments/assets/f0f9ddab-12ed-4484-8941-4c5077e4028a
=> Fix bot protection input channel not inherited from previous screen

pkg/lib/authn/stdattrs/validate.go, pkg/lib/authn/stdattrs/validate_test.go, pkg/lib/userimport/model.go, pkg/lib/userimport/model_test.go, pkg/lib/userimport/reuseschema.go, pkg/util/validation/schema_builder.go, pkg/util/validation/schema_builder_test.go
ref DEV-1482
Some directions I thought of, but only implemented the checked ones
ref https://docs.authgear.com/how-to-guide/user-management/import-users-using-user-import-api#input-format
@louischan-oursky see if you expected more strict rules? thanks 🙏
=> Stricten user import schema

pkg/auth/handler/saml/login.go, pkg/lib/config/config.go, pkg/lib/config/saml.go, pkg/lib/config/testdata/config_tests.yaml, pkg/lib/saml/service.go, pkg/lib/saml/service_test.go
ref DEV-2002
Steps to update existing configs:
1. Deploy the code in this pr
2. Add `client_id` in existing config. Old endpoints should still work, but metadata will be updated.
3. Switch to new endpoints.
4. Remove `id` from configs.
5. Remove `id` from code.
=> SAML: Add client_id to service provider

portal/src/util/formatDatetime.ts
As https://tc39.es/ecma402/#table-datetimeformat-components
doesnt have options to control whether display `GMT` or `UTC`, added a replace for this purpose
Preview:
=> Replace GMT string in datetime string to UTC

portal/src/locale-data/en.json
@louischan-oursky fixed combine sign up, login text wording
Preview:
=> Fix sign up or login option wording

portal/src/components/audit-log/ActivityTypeFilterDropdown.tsx, portal/src/components/audit-log/AuditLogFilterBar.module.css, portal/src/components/audit-log/AuditLogFilterBar.tsx, portal/src/components/audit-log/ClearAllButton.tsx, portal/src/components/audit-log/DateRangeFilterDropdown.tsx, portal/src/components/audit-log/RefreshButton.tsx, portal/src/graphql/adminapi/AuditLogScreen.module.css, portal/src/graphql/adminapi/AuditLogScreen.tsx, portal/src/hook/useScreenBreakpoint.ts, portal/src/hook/useWindowSize.ts
ref DEV-1462
- Replace existing command bar as custom filter bar
- In mobile, render dropdown instead of command bar button with submenu items
- searchable dropdown for activity type
https://github.com/user-attachments/assets/e003481e-dbce-4668-beb4-511958ed92b1
~Pending because xcode have problem on my machine :(~
https://github.com/user-attachments/assets/c72688a8-c5e1-47f2-8c7c-eac243fc254b
https://github.com/user-attachments/assets/64d970c8-1847-40a5-9a97-bc0de5de6c2b
=> Implement new mobile layout for audit log filters

devtools/gotemplatelinter/translation_key_rule_check_translation_key.go
Use set over list. `find` time complexity became O(1)
=> Slightly optimize performance of translation key linter `is defined` logic

pkg/lib/userimport/service.go
As `err` is always `nil` when executing this code, effectively it is having the same logic before the fix. But this looks like a mistake.
=> Fix incorrect error checking in user import

resources/authgear/templates/en/web/authflowv2/wechat.html
Found this weird behavior when working on PR #4705 
- `wechat.html` is referencing `$.HasUnknownError`
- If you do a global search `HasUnknownError`, it is only returned by SSR in password pages and ldap_login
- [`wechat.go`](https://github.com/authgear/authgear-server/blob/main/pkg/auth/handler/webapp/authflowv2/wechat.go#L54-L55) only use [base view model, which does not have HasUnknownError](https://github.com/authgear/authgear-server/blob/main/pkg/auth/handler/webapp/viewmodels/base.go)
- i.e. `$.HasUnknownError` is always nil in`wechat.html`
Not sure if expected, maybe need to introduce back the wechat unknown error somehow?
=> Remove non-existing $.HasUnknownError in wechat.html

portal/src/graphql/portal/SingleSignOnConfigurationWidget.tsx, portal/src/hook/useOAuthProviderForm.ts
ref DEV-1911
The `isEnabled` form state is used from the legacy design and it is not longer being used in the current design.
https://github.com/user-attachments/assets/ff3cea5b-9dd8-49d9-a10a-6b62d705f593
https://github.com/user-attachments/assets/54917e25-0e2c-4745-918a-5f25b6ed6d3b
=> Fix disabled save button in sso screen

devtools/gotemplatelinter/transation_key_rule_check_template.go, resources/authgear/templates/en/web/authflowv2/__html_head.html
cont'd PR #4733
Just realized not even special cases should be allowed in template, so removed it. 🙏 
(Ran `make lint-translation-keys`, expected no change)
=> Change missing template into include in translation linter

docs/specs/roles-groups.md, pkg/lib/rolesgroups/key.go, pkg/lib/rolesgroups/key_test.go
@louischan-oursky fixed validation pattern and added few more tests to it🙏
Preview:
```
=== RUN   TestValidateKey
.........
10 total assertions
--- PASS: TestValidateKey (0.00s)
PASS
ok      github.com/authgear/authgear-server/pkg/lib/rolesgroups (cached)
```
=> Fix key input validation pattern and test

portal/src/graphql/portal/ApplicationsConfigurationScreen.tsx, portal/src/graphql/portal/CreateOAuthClientScreen.tsx, portal/src/hook/useOAuthClientForm.ts
ref DEV-2075
The underlying reason of this issue is because we are using the raw read-only `currentState.clients` to construct our config. When we call `clearEmptyObject()`, it will try to delete empty objects and error will occured as the objects of `currentState.clients` are read-only.
https://github.com/user-attachments/assets/ce2c0e4c-5231-481c-9a34-ff6d80fbbd4b
=> Fix Application Screen cannot be displayed

portal/src/graphql/portal/CustomAttributesConfigurationScreen.tsx, portal/src/graphql/portal/StandardAttributesConfigurationScreen.tsx
ref DEV-2086
Also quickly skimmed through all screens, seems all other non-sticky-footer save buttons are intentional. IOW, only this screen need changes
EDIT: just observed another problem, the table width did not grow. Lemme fix fix
EDIT2: fixed in [12ed2e8](https://github.com/authgear/authgear-server/pull/4758/commits/12ed2e8c322a343d96bd0509c8fec356a373f857)
| standard | custom |
| ------  | ----- |
| <img width="1640" alt="image" src="https://github.com/user-attachments/assets/65bd464f-50d9-43bb-a475-b6a8edfcc038">        | <img width="1621" alt="image" src="https://github.com/user-attachments/assets/e9b3c5e9-db0d-479c-aeed-9a623500093a">    |
=> Make custom attribute save button bottom bar sticky

pkg/images/wire_gen.go, pkg/lib/infra/middleware/cors_matcher.go, pkg/lib/infra/middleware/cors_test.go
ref DEV-2001
I do it based on the slo feature branch because we also want to whitelist the slo endpoint
=> Whitelist more origins in CORS middleware

.github/workflows/ci.yaml, CONTRIBUTING.md, authui/.browserslistrc, authui/package-lock.json, authui/package.json, portal/.browserslistrc, portal/package.json, scripts/sh/ensure-browserslist-coverage.sh
ref DEV-2108
[New authUI coverage: 85.6%](https://browsersl.ist/#q=iOS+%3E%3D+14%0Alast+5+Chrome+versions%0Alast+5+ChromeAndroid+versions%0Alast+5+Edge+versions%0Alast+5+Safari+versions+%23+non-iOS+Safari%0Alast+5+Firefox+versions%0Alast+5+FirefoxAndroid+versions%0Alast+2+Samsung+versions+%23+Samsung+default+browser+-+Samsung+Internet%0Anot+dead+%23+no+browsers+without+security+updates%0A)
Fixed
- `Android` referred to Android webview instead of all browsers on Android (ref https://github.com/browserslist/browserslist/blob/ee095bd1934a43f6a591acff7e8a3e05be86cf61/README.md?plain=1#L333)
- included more versions, some browsers like Chrome 127 is still the most popular (current 129, that makes Chrome 127 not included in `last 2 Chrome versions`
=> Specify browserslistrc more accurately

portal/src/ReactApp.tsx
ref DEV-1767
Actually not sure how to reproduce [this](https://authgear.sentry.io/issues/5897586517/?alert_rule_id=15285121&alert_timestamp=1727150257207&alert_type=email&environment=production&notification_uuid=904c3b4b-2df3-4f8d-912c-49c1e67af8d3&project=4507492100014080&referrer=alert_email)
Decided to use a substring match to also catch error like this.
Question - maybe I should just filter all errors with `posthog` in it? 🤔 Since we plan to handle it properly in [this issue](https://linear.app/authgear/issue/DEV-2131/integrate-gtm-posthog-osano-properly) anyway.
cc @tung2744
=> Use substring match to filter posthog type error

pkg/admin/graphql/user_mutation.go, pkg/auth/deps.go, pkg/auth/handler/webapp/authflowv2/reset_password.go, pkg/lib/authn/otp/sender.go, pkg/lib/deps/deps_common.go, pkg/lib/feature/forgotpassword/service.go
ref DEV-2048
This PR
- generates `admin_reset_password` flow as an account_recovery flow by default
- uses said flow when the account_recovery_code has `FlowReference.Name == "admin_reset_password"`
https://github.com/user-attachments/assets/c50df1e8-1456-4506-a3cb-0180aae3f569
=> Handle admin_api reset password in authflow v2

authui/src/authflowv2/components/brand-logo.css
To prevent object-contain-ed width out grow max-width
https://github.com/user-attachments/assets/a97e1d95-a6d3-4006-ac5f-0fc6011aafac
=> Use max-height for brand-logo customisation

postgres/Dockerfile
This can be built with `docker compose build db --no-cache` successfully.
=> Fix postgres/Dockerfile is too old

Makefile, pkg/lib/oauth/handler/handler_token_test.go, pkg/lib/oauth/store_grant.go, pkg/lib/oauth/store_grant_mock_test.go
`make fmt` is programmed to ignore `_mock_test.go`. So this generated file should be named `store_grant_mock_test.go`.
=> Rename store_grant_mock.go to store_grant_mock_test.go

.github/workflows/ci.yaml
Previously, the image were duplicated in the GitHub Actions YAML. Now we read from docker-compose.yaml and caches all found images in it.
The build log when the cache is empty: https://github.com/louischan-oursky/authgear-server/actions/runs/11361490536/job/31601304202
The build log when the cache is hit: https://github.com/louischan-oursky/authgear-server/actions/runs/11361682829/job/31601915874
=> Improve the cache logic of e2e docker images

authui/src/authflowv2/components/input.css
ref DEV-2207
[![CI](https://github.com/IniZio/authgear-server/actions/workflows/ci.yaml/badge.svg?branch=DEV-2207-update-input-disabled-style)](https://github.com/IniZio/authgear-server/tree/DEV-2207-update-input-disabled-style)
Dark|Light
-|-
=> [Settings v2] Update input disabled background color

pkg/admin/facade/identity.go, pkg/admin/facade/user.go, pkg/latte/intent_authenticate.go, pkg/latte/intent_change_email.go, pkg/latte/intent_create_login_id.go, pkg/latte/intent_forgot_password_v2.go, pkg/latte/node_change_email.go, pkg/lib/accountmanagement/service_identity.go, pkg/lib/authenticationflow/declarative/intent_account_recovery_flow_step_select_destination.go, pkg/lib/authenticationflow/declarative/intent_create_identity_login_id.go, pkg/lib/authenticationflow/declarative/intent_lookup_identity_login_id.go, pkg/lib/authenticationflow/declarative/intent_promote_identity_login_id.go, pkg/lib/authenticationflow/declarative/intent_use_account_recovery_identity.go, pkg/lib/authenticationflow/declarative/intent_use_identity_login_id.go, pkg/lib/authn/identity/info.go, pkg/lib/authn/identity/loginid/checker.go, pkg/lib/authn/identity/loginid/checker_test.go, pkg/lib/authn/identity/loginid/provider.go, pkg/lib/authn/identity/loginid/store.go, pkg/lib/authn/identity/loginid_spec.go, pkg/lib/authn/identity/migrate_spec.go, pkg/lib/authn/identity/service/service.go, pkg/lib/interaction/nodes/select_identity_end.go, pkg/lib/interaction/nodes/use_identity_login_id.go, pkg/lib/userimport/service.go, pkg/util/stringutil/userinputstring.go, pkg/util/stringutil/userinputstring_test.go
ref DEV-2253
- We did validate emails, but mail.ParseAddress is success when the email containing a space.
=> Trim whitespaces in email and username checker

portal/src/ReactApp.tsx, portal/src/util/error.ts
=> Ignore network error in portal

k6/go.mod, k6/go.sum
To include this commit https://github.com/grafana/k6/commit/dde8e55d817df99f7d6fec2b3ee1c8fc63bea269 which upgrade x/net to v0.33.0
To fix https://github.com/authgear/authgear-server/security/dependabot/164
=> Update k6 to v0.56.0

.vettedpositions, authui/src/authflowv2/components/otp-input.css, authui/src/authflowv2/components/widget.css, pkg/auth/deps.go, pkg/auth/handler/webapp/authflowv2/settings_delete_account.go, pkg/auth/handler/webapp/authflowv2/settings_delete_account_success.go, pkg/auth/handler/webapp/authflowv2/settings_identity_add_email.go, pkg/auth/handler/webapp/authflowv2/settings_identity_add_phone.go, pkg/auth/handler/webapp/authflowv2/settings_identity_new_username.go, pkg/auth/handler/webapp/authflowv2/settings_identity_verify_email.go, pkg/auth/handler/webapp/authflowv2/settings_identity_verify_phone.go, pkg/auth/handler/webapp/controller.go, pkg/lib/endpoints/endpoints.go, pkg/lib/oauth/handler/handler_authz.go, pkg/lib/oauth/oidc/errors.go, pkg/lib/oauth/oidc/ui.go, pkg/lib/oauth/protocol/authz.go, pkg/lib/oauth/protocol/setting_action.go
ref DEV-2411
Can test with https://github.com/authgear/authgear-sdk-flutter/pull/72
=> Support add login id setting actions

authui/vite.config.ts, portal/vite.config.ts
When using vite development server, there are always some http requests load indefinitely. It seems that the default port of hmr of vite development server is `3100` which collides with the port we used for authgear server.
=> Use another port for vite hmr

pkg/admin/facade/oauth.go, pkg/admin/graphql/context.go, pkg/admin/graphql/session_mutation.go, portal/src/graphql/adminapi/globalTypes.generated.ts, portal/src/graphql/adminapi/schema.graphql
ref DEV-2490
Accepts URL-safe base64-encoded deviceInfo in `createSession` mutation, similar to OAuth's `x_device_info`
=> Add deviceInfo param to createSession mutation

.vettedpositions, experiments/DEV-2544/main.go, k6/authflow.js, pkg/auth/handler/oauth/redirect.go, pkg/lib/config/oauth.go, pkg/lib/oauth/handler/handler_authz.go, pkg/lib/oauth/handler/handler_authz_test.go, pkg/lib/oauth/handler/handler_proxy_redirect.go, pkg/lib/oauth/handler/handler_proxy_redirect_test.go, pkg/lib/oauth/handler/result_authz.go, pkg/lib/oauth/oidc/handler/handler_end_session.go, pkg/lib/oauth/response_mode.go, pkg/lib/oauth/response_mode_test.go
ref DEV-2544
Tested with the following
1. iOS ASWebAuthenticationSession
2. iOS WebView
3. Chrome CustomTabs on Pixel (Emulator)
4. Chrome WebView on Pixel (Emulator)
5. Xiaomi CustomTabs on Redmi (Device)
6. A custom UI that uses iframe to load the redirect URI.
=> Use 303 / 200 to perform OAuth redirect

.github/actions/build-custom-image/action.yaml, .github/actions/build-image/action.yaml, .github/workflows/custom-build.yaml, .github/workflows/oursky.yaml, .github/workflows/run-builds.yaml, cmd/authgear/cmd/cmdinit/init.go, makefiles/common.mk, makefiles/guideline.mk, once/docker-entrypoint.sh, pkg/portal/model/system_config.go, pkg/portal/service/system_config.go, portal/src/graphql/portal/AppsScreen.tsx, portal/src/system-config.ts
ref DEV-2412
(Note that the accounts project is hidden and the create project button is hidden)
It can be tested with `./once/docker-compose.yaml`
```
services:
once:
build:
context: ../
dockerfile: ./once/Dockerfile
volumes:
- postgres_data:/var/lib/postgresql/data
- redis_data:/var/lib/redis/data
- certbot_data:/etc/letsencrypt
- minio_data:/var/lib/minio/data
environment:
POSTGRES_PASSWORD: "1234"
REDIS_PASSWORD: "1234"
MINIO_ROOT_PASSWORD: "12345678"
AUTHGEAR_HTTP_ORIGIN_PORTAL: "http://portal.localhost"
AUTHGEAR_HTTP_ORIGIN_ACCOUNTS: "http://accounts.localhost"
AUTHGEAR_HTTP_ORIGIN_PROJECT: "http://project.localhost"
AUTHGEAR_CERTBOT_RUN_INTERVAL: "86400"
AUTHGEAR_ONCE_ADMIN_USER_EMAIL: "louischan@oursky.com"
AUTHGEAR_ONCE_ADMIN_USER_PASSWORD: "12345678" …
```
=> Build ONCE docker image - Part 4

.vettedpositions, pkg/util/otelutil/oteldatabasesql/instrumentation.go, pkg/util/otelutil/oteldatabasesql/instrumentation_test.go
ref DEV-2729
To use it, set this to sensible value, like 3000.
=> Support AUTHGEARDEBUG_DATABASE_CONNECTION_WAIT_TIME_TIMEOUT_MILLISECONDS

cmd/portal/internal/check.go, e2e/tests/oauth/demo_credential_provider.test.yaml, e2e/var/authgear.secrets.yaml, pkg/admin/wire_gen.go, pkg/lib/authenticationflow/declarative/data_identification.go, pkg/lib/authenticationflow/declarative/data_oauth.go, pkg/lib/authenticationflow/declarative/intent_login_flow_step_identify.go, pkg/lib/authenticationflow/declarative/intent_lookup_identity_oauth.go, pkg/lib/authenticationflow/declarative/intent_oauth.go, pkg/lib/authenticationflow/declarative/intent_promote_flow_step_identify.go, pkg/lib/authenticationflow/declarative/intent_promote_identity_oauth.go, pkg/lib/authenticationflow/declarative/intent_signup_flow_step_identify.go, pkg/lib/authenticationflow/declarative/intent_signup_login_flow_step_identify.go, pkg/lib/authenticationflow/declarative/utils_common.go, pkg/lib/authenticationflow/dependencies.go, pkg/lib/authn/sso/oauth_provider.go, pkg/lib/config/configsource/loader.go, pkg/lib/config/identity.go, pkg/lib/config/secret.go, pkg/lib/config/secret_sso_oauth_demo_credentials.go, pkg/lib/config/secret_test.go, pkg/lib/config/testdata/parse_secret_tests.yaml, pkg/lib/config/testdata/secret_config_validate_tests.yaml, pkg/lib/deps/deps_config.go
ref DEV-2719
requires https://github.com/authgear/authgear-server/pull/5191
1. Add demo credentials to `authgear.secrets.yaml`.
```yaml
- data:
items:
- provider_config:
claims:
email:
assume_verified: true
required: true
client_id: {CLIENT_ID}
type: google
client_secret:  {CLIENT_SECRET}
key: sso.oauth.demo_credentials
```
2. Set `missing_credential_allowed` in the corresponding provider:
```yaml
- alias: google
create_disabled: false
delete_disabled: false
type: google
missing_credential_allowed: true
```
3. Use authflow api to test oauth.
=> Support oauth demo credentials in authflow

flake.nix
Otherwise the effective bash is the minimal one, lacking features like vi-mode and completion.
=> Explicitly install bashInteractive in flake

.vettedpositions, pkg/admin/deps.go, pkg/admin/facade/oauth.go, pkg/admin/wire_gen.go, pkg/auth/deps.go, pkg/auth/handler/api/anonymous_user_signup.go, pkg/auth/handler/oauth/authorize.go, pkg/auth/handler/webapp/tester.go, pkg/lib/deps/deps_common.go, pkg/lib/oauth/grant_access_service.go, pkg/lib/oauth/grant_offline_service.go, pkg/lib/oauth/handler/handler_anonymous_user.go, pkg/lib/oauth/handler/handler_authz.go, pkg/lib/oauth/handler/handler_authz_mock_test.go, pkg/lib/oauth/handler/handler_authz_test.go, pkg/lib/oauth/handler/handler_token.go, pkg/lib/oauth/handler/handler_token_mock_test.go, pkg/lib/oauth/handler/handler_token_test.go, pkg/lib/oauth/handler/service_preauthenticated_url.go, pkg/lib/oauth/handler/service_token.go, pkg/lib/oauth/handler/service_token_mock_test.go, pkg/lib/oauth/handler/service_token_test.go, pkg/lib/oauth/pre_authenticated_url_token.go, pkg/lib/oauth/token_encoding.go, pkg/lib/oauth/token_encoding_mock_test.go, pkg/lib/oauth/token_encoding_test.go
ref DEV-3061
Manually tested the following cases:
- Sign in with mobile SDK
- Anonymous user sign in with mobile SDK
- Biometric login with mobile SDK
- Sign in with web SDK
- Anonymous user sign in with web SDK
- Pre-authenticated URL with mobile SDK
- Refresh access token
- The /tester endpoint
=> Move access token hook outside transaction
